use super::super::row::{Contract, SpecTool};
use crate::browser::tool_proficiency::Proficiency;
use crate::tool_chest::core::intent_bus::ActionType;
use crate::tool_chest::core::tool::ToolKind;

const T: &str = "portals";
const TL: &str = "Portals";

pub(super) static ROWS: &[SpecTool] = &[
    SpecTool::new(
        T,
        TL,
        "physics",
        "Physics",
        "portals:add-collider",
        "Add collider",
        "Give an object a collision shape.",
        "portal",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Intermediate,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "physics",
        "Physics",
        "portals:add-rigidbody",
        "Add rigid body",
        "Let an object fall and collide.",
        "portal",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Intermediate,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "physics",
        "Physics",
        "portals:add-trigger",
        "Add trigger",
        "Fire an event when something enters.",
        "portal",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Intermediate,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "physics",
        "Physics",
        "portals:physics-material",
        "Physics material",
        "Set friction and bounce.",
        "portal",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Intermediate,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "physics",
        "Physics",
        "portals:physics-bake",
        "Bake physics",
        "Bake the physics scene for a smoother run.",
        "portal",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Expert,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "inspect",
        "Inspect",
        "portals:world-statistics",
        "World stats",
        "Show object, polygon, and portal counts.",
        "inspect",
        ToolKind::Query,
        ActionType::Query,
        Proficiency::Novice,
        Contract::Live("Render.scene"),
    ),
    SpecTool::new(
        T,
        TL,
        "inspect",
        "Inspect",
        "portals:physics-inspector",
        "Physics inspector",
        "List bodies, colliders, and triggers.",
        "inspect",
        ToolKind::Query,
        ActionType::Query,
        Proficiency::Intermediate,
        Contract::Live("Render.scene"),
    ),
    SpecTool::new(
        T,
        TL,
        "inspect",
        "Inspect",
        "portals:portal-graph",
        "Portal graph",
        "Show how worlds link through portals.",
        "inspect",
        ToolKind::Query,
        ActionType::Query,
        Proficiency::Intermediate,
        Contract::Live("Render.scene"),
    ),
    SpecTool::new(
        T,
        TL,
        "inspect",
        "Inspect",
        "portals:player-list",
        "Who is here",
        "List people currently in this world.",
        "inspect",
        ToolKind::Query,
        ActionType::Query,
        Proficiency::Intermediate,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "inspect",
        "Inspect",
        "portals:metadata-view",
        "World details",
        "Show portal and world metadata.",
        "inspect",
        ToolKind::Query,
        ActionType::Query,
        Proficiency::Novice,
        Contract::Live("Render.scene"),
    ),
];
