use super::super::row::{Contract, SpecTool};
use crate::browser::tool_proficiency::Proficiency;
use crate::tool_chest::core::intent_bus::ActionType;
use crate::tool_chest::core::tool::ToolKind;

const T: &str = "portals";
const TL: &str = "Portals";

pub(super) static ROWS: &[SpecTool] = &[
    SpecTool::new(
        T,
        TL,
        "portals",
        "Portal links",
        "portals:create-portal",
        "New portal",
        "Make a named link to another world.",
        "portal",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Intermediate,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "portals",
        "Portal links",
        "portals:portal-link",
        "Link portal",
        "Point this portal at a destination world.",
        "portal",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Intermediate,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "portals",
        "Portal links",
        "portals:portal-destination",
        "Portal destination",
        "Show where this portal leads.",
        "portal",
        ToolKind::Query,
        ActionType::Query,
        Proficiency::Novice,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "portals",
        "Portal links",
        "portals:portal-preview",
        "Preview portal",
        "Look through to the destination world.",
        "portal",
        ToolKind::Query,
        ActionType::Query,
        Proficiency::Intermediate,
        Contract::Live("Render.scene"),
    ),
    SpecTool::new(
        T,
        TL,
        "portals",
        "Portal links",
        "portals:portal-list",
        "List portals",
        "List every portal in this world.",
        "portal",
        ToolKind::Query,
        ActionType::Query,
        Proficiency::Novice,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "portals",
        "Portal links",
        "portals:portal-test",
        "Test portal",
        "Walk through this portal to check it.",
        "portal",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Intermediate,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "avatars",
        "Avatars",
        "portals:avatar-select",
        "Default avatar",
        "Choose the default body for this world.",
        "portal",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Novice,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "avatars",
        "Avatars",
        "portals:avatar-customise",
        "Customise avatar",
        "Change how this avatar looks.",
        "portal",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Intermediate,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "avatars",
        "Avatars",
        "portals:controller-map",
        "Map controllers",
        "Map hands and sticks to actions.",
        "portal",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Expert,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "avatars",
        "Avatars",
        "portals:avatar-preview",
        "Preview avatar",
        "Look at this avatar.",
        "portal",
        ToolKind::Query,
        ActionType::Query,
        Proficiency::Novice,
        Contract::Live("Render.scene"),
    ),
    SpecTool::new(
        T,
        TL,
        "avatars",
        "Avatars",
        "portals:avatar-spawn",
        "Spawn avatar",
        "Place an avatar at a point in the world.",
        "portal",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Intermediate,
        Contract::Local,
    ),
];
