use super::super::row::{Contract, SpecTool};
use crate::browser::tool_proficiency::Proficiency;
use crate::tool_chest::core::intent_bus::ActionType;
use crate::tool_chest::core::tool::ToolKind;

const T: &str = "portals";
const TL: &str = "Portals";

pub(super) static ROWS: &[SpecTool] = &[
    SpecTool::new(
        T,
        TL,
        "world-building",
        "World building",
        "portals:create-world",
        "New world",
        "Start a named world with an environment.",
        "portal",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Novice,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "world-building",
        "World building",
        "portals:terrain-edit",
        "Sculpt terrain",
        "Raise and lower the world's ground.",
        "portal",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Intermediate,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "world-building",
        "World building",
        "portals:skybox-set",
        "Set skybox",
        "Choose the sky around this world.",
        "portal",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Novice,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "world-building",
        "World building",
        "portals:environment-light",
        "World light",
        "Set the world's ambient lighting.",
        "portal",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Intermediate,
        Contract::Live("Render.scene"),
    ),
    SpecTool::new(
        T,
        TL,
        "world-building",
        "World building",
        "portals:spawn-point",
        "Spawn point",
        "Mark where people arrive.",
        "portal",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Novice,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "world-building",
        "World building",
        "portals:boundary-set",
        "World boundary",
        "Set how far the world extends.",
        "portal",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Intermediate,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "world-building",
        "World building",
        "portals:world-save",
        "Save world",
        "Save the current world state.",
        "portal",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Novice,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "world-building",
        "World building",
        "portals:world-publish",
        "Publish world",
        "Publish this world to a portal host.",
        "portal",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Expert,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "objects",
        "World objects",
        "portals:place-prop",
        "Place a prop",
        "Put a prop in the world.",
        "portal",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Novice,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "objects",
        "World objects",
        "portals:place-furniture",
        "Place furniture",
        "Put furniture in the world.",
        "portal",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Novice,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "objects",
        "World objects",
        "portals:interactive-object",
        "Interactive object",
        "Place an object people can use.",
        "portal",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Intermediate,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "objects",
        "World objects",
        "portals:portal-anchor",
        "Portal anchor",
        "Place an entrance to another world.",
        "portal",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Intermediate,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "objects",
        "World objects",
        "portals:object-transform",
        "Transform object",
        "Move, rotate, or scale a placed object.",
        "portal",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Novice,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "objects",
        "World objects",
        "portals:object-duplicate",
        "Duplicate object",
        "Copy a placed object.",
        "portal",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Novice,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "objects",
        "World objects",
        "portals:object-delete",
        "Delete object",
        "Remove a placed object.",
        "portal",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Novice,
        Contract::Local,
    ),
];
