#[cfg(not(target_arch = "wasm32"))]
pub mod mesh_datagram;
#[cfg(not(target_arch = "wasm32"))]
pub mod mesh_service;
pub mod protocol;
pub mod routing;
#[cfg(not(target_arch = "wasm32"))]
pub mod social_webnet;
pub mod swarm;
#[cfg(not(target_arch = "wasm32"))]
pub mod sync_node;
#[cfg(not(target_arch = "wasm32"))]
pub mod sync_ops;
#[cfg(not(target_arch = "wasm32"))]
pub mod wireguard_runtime;
#[cfg(not(target_arch = "wasm32"))]
pub mod wireguard_userspace;
