//! Forge-native causal-attention schedule and WGSL emission.
//!
//! This is intentionally a separate kernel from the legacy bridge shader: it
//! has a declared schedule, deterministic source hash, and can therefore be
//! validated and certified by the Forge pipeline.  It operates on dequantized
//! f32 Q/K/V views; quantized projection and KV packing remain outside this
//! kernel's ABI.

use super::{validate_wgsl, ForgeError, Schedule, ValidationReport};

/// The attention workload bound into one Forge kernel.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct AttentionShape {
    pub head_dim: u32,
    pub head_count: u32,
    pub context_tokens: u32,
    pub batch_tokens: u32,
}

/// A hardware-safe attention schedule.  The generated kernel uses one
/// workgroup per attention head and an online tiled reduction over context.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct AttentionSchedule {
    pub workgroup_size: u32,
    pub context_tile: u32,
    pub vector_width: u32,
}

impl AttentionSchedule {
    /// Ampere/A2000 schedule for batch-one decode: four warps, one context
    /// score per lane, and scalar value accumulation to keep register pressure
    /// bounded under the 64-register kill criterion.
    pub const fn a2000_decode() -> Self {
        Self {
            workgroup_size: 128,
            context_tile: 128,
            vector_width: 1,
        }
    }

    /// Ampere/A2000 prefill schedule: eight warps, with a 256-token score tile.
    pub const fn a2000_prefill() -> Self {
        Self {
            workgroup_size: 256,
            context_tile: 256,
            vector_width: 1,
        }
    }

    pub fn validate(self, shape: AttentionShape) -> Result<(), ForgeError> {
        if shape.head_dim == 0 || shape.head_count == 0 || shape.context_tokens == 0 {
            return Err(ForgeError::InvalidSchedule(
                "attention shape must have non-zero head dimension, head count, and context".into(),
            ));
        }
        if !matches!(self.workgroup_size, 32 | 64 | 128 | 256)
            || self.context_tile != self.workgroup_size
            || self.vector_width != 1
        {
            return Err(ForgeError::InvalidSchedule(
                "attention schedule requires a warp-aligned workgroup and one score per lane"
                    .into(),
            ));
        }
        Ok(())
    }

    /// Compatibility view for generic Forge scheduling/reporting APIs.
    pub const fn forge_schedule(self) -> Schedule {
        Schedule {
            workgroup_size: self.workgroup_size,
            items_per_invocation: 1,
            vector_width: self.vector_width,
        }
    }
}

/// Generated attention kernel plus its Naga validation report.
#[derive(Debug, Clone)]
pub struct AttentionShader {
    pub schedule: AttentionSchedule,
    pub shape: AttentionShape,
    pub source_hash: String,
    pub source: String,
    pub validation: ValidationReport,
}

/// Emit and Naga-validate a causal scaled-dot-product attention kernel.
///
/// The kernel makes three tiled context passes: global score maximum, softmax
/// denominator, then value accumulation.  This avoids an unbounded shared
/// memory allocation for long contexts and retains deterministic reduction
/// order.  `output` is `[head_count, head_dim]`; `keys` and `values` are
/// `[head_count, context_tokens, head_dim]`.
pub fn synthesize_causal_attention(
    shape: AttentionShape,
    schedule: AttentionSchedule,
) -> Result<AttentionShader, ForgeError> {
    schedule.validate(shape)?;
    let wg = schedule.workgroup_size;
    let source = format!(
        r#"// Generated by Qualia WGSL Forge attention schedule.
// A2000-compatible: four/eight warp workgroup, scalar accumulation, tiled context.
struct AttentionParams {{
    context_tokens: u32,
    head_dim: u32,
    head_count: u32,
    _pad0: u32,
    scale: f32,
    _pad1: vec3<u32>,
}}

@group(0) @binding(0) var<storage, read> query: array<f32>;
@group(0) @binding(1) var<storage, read> keys: array<f32>;
@group(0) @binding(2) var<storage, read> values: array<f32>;
@group(0) @binding(3) var<storage, read_write> output: array<f32>;
@group(0) @binding(4) var<uniform> params: AttentionParams;

var<workgroup> reduce: array<f32, {wg}>;

fn score(head: u32, token: u32) -> f32 {{
    let q_base = head * params.head_dim;
    let kv_base = (head * params.context_tokens + token) * params.head_dim;
    var dot: f32 = 0.0;
    for (var d: u32 = 0u; d < params.head_dim; d = d + 1u) {{
        dot = dot + query[q_base + d] * keys[kv_base + d];
    }}
    return dot * params.scale;
}}

@compute @workgroup_size({wg})
fn causal_attention(
    @builtin(workgroup_id) workgroup: vec3<u32>,
    @builtin(local_invocation_id) local: vec3<u32>,
) {{
    let head = workgroup.x;
    let lane = local.x;
    if (head >= params.head_count) {{ return; }}

    var max_score = -3.402823466e+38;
    for (var base: u32 = 0u; base < params.context_tokens; base = base + {wg}u) {{
        let token = base + lane;
        reduce[lane] = select(-3.402823466e+38, score(head, token), token < params.context_tokens);
        workgroupBarrier();
        for (var stride: u32 = {wg}u / 2u; stride > 0u; stride = stride / 2u) {{
            if (lane < stride) {{ reduce[lane] = max(reduce[lane], reduce[lane + stride]); }}
            workgroupBarrier();
        }}
        if (lane == 0u) {{ reduce[0] = max(max_score, reduce[0]); }}
        workgroupBarrier();
        max_score = reduce[0];
        workgroupBarrier();
    }}

    var denominator = 0.0;
    for (var base: u32 = 0u; base < params.context_tokens; base = base + {wg}u) {{
        let token = base + lane;
        reduce[lane] = select(0.0, exp(score(head, token) - max_score), token < params.context_tokens);
        workgroupBarrier();
        for (var stride: u32 = {wg}u / 2u; stride > 0u; stride = stride / 2u) {{
            if (lane < stride) {{ reduce[lane] = reduce[lane] + reduce[lane + stride]; }}
            workgroupBarrier();
        }}
        if (lane == 0u) {{ reduce[0] = denominator + reduce[0]; }}
        workgroupBarrier();
        denominator = reduce[0];
        workgroupBarrier();
    }}

    for (var d: u32 = lane; d < params.head_dim; d = d + {wg}u) {{
        var acc = 0.0;
        for (var token: u32 = 0u; token < params.context_tokens; token = token + 1u) {{
            let p = exp(score(head, token) - max_score) / denominator;
            let value_index = (head * params.context_tokens + token) * params.head_dim + d;
            acc = acc + p * values[value_index];
        }}
        output[head * params.head_dim + d] = acc;
    }}
}}
"#
    );
    let validation = validate_wgsl(&source)?;
    let source_hash = validation.source_hash.clone();
    Ok(AttentionShader {
        schedule,
        shape,
        source_hash,
        source,
        validation,
    })
}

/// Caller-buffered stable scaled-dot-product attention oracle.
///
/// This is the certification reference for the generated shader: it uses the same fixed traversal
/// order and no heap allocation.  The caller supplies a single query per head, contiguous
/// `[head, token, dim]` key/value tensors, and `[head, dim]` output storage.
pub fn causal_attention_oracle(
    shape: AttentionShape,
    query: &[f32],
    keys: &[f32],
    values: &[f32],
    scale: f32,
    out: &mut [f32],
) -> Result<(), ForgeError> {
    if shape.head_dim == 0 || shape.head_count == 0 || shape.context_tokens == 0 {
        return Err(ForgeError::InvalidKernel(
            "attention oracle requires non-zero head dimension, head count, and context".into(),
        ));
    }
    if !scale.is_finite() {
        return Err(ForgeError::InvalidKernel(
            "attention scale must be finite".into(),
        ));
    }
    let heads = shape.head_count as usize;
    let dim = shape.head_dim as usize;
    let context = shape.context_tokens as usize;
    let q_len = heads
        .checked_mul(dim)
        .ok_or_else(|| ForgeError::InvalidKernel("attention query length overflow".into()))?;
    let kv_len = q_len
        .checked_mul(context)
        .ok_or_else(|| ForgeError::InvalidKernel("attention KV length overflow".into()))?;
    if query.len() < q_len || keys.len() < kv_len || values.len() < kv_len || out.len() < q_len {
        return Err(ForgeError::InvalidKernel(
            "attention oracle input or output buffer is too small".into(),
        ));
    }

    for head in 0..heads {
        let q_base = head * dim;
        let kv_head_base = head * context * dim;
        let mut max_score = f32::NEG_INFINITY;
        for token in 0..context {
            let base = kv_head_base + token * dim;
            let mut dot = 0.0f32;
            for d in 0..dim {
                dot += query[q_base + d] * keys[base + d];
            }
            max_score = max_score.max(dot * scale);
        }
        let mut denominator = 0.0f32;
        for token in 0..context {
            let base = kv_head_base + token * dim;
            let mut dot = 0.0f32;
            for d in 0..dim {
                dot += query[q_base + d] * keys[base + d];
            }
            denominator += (dot * scale - max_score).exp();
        }
        if !denominator.is_finite() || denominator <= 0.0 {
            return Err(ForgeError::OracleMismatch(
                "attention oracle produced an invalid softmax denominator".into(),
            ));
        }
        for d in 0..dim {
            let mut accumulated = 0.0f32;
            for token in 0..context {
                let base = kv_head_base + token * dim;
                let mut dot = 0.0f32;
                for qd in 0..dim {
                    dot += query[q_base + qd] * keys[base + qd];
                }
                accumulated += ((dot * scale - max_score).exp() / denominator) * values[base + d];
            }
            out[q_base + d] = accumulated;
        }
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn a2000_decode_schedule_emits_valid_tiled_attention() {
        let shader = synthesize_causal_attention(
            AttentionShape {
                head_dim: 128,
                head_count: 8,
                context_tokens: 513,
                batch_tokens: 1,
            },
            AttentionSchedule::a2000_decode(),
        )
        .expect("attention shader");
        assert!(shader.source.contains("@compute @workgroup_size(128)"));
        assert!(shader
            .source
            .contains("var<workgroup> reduce: array<f32, 128>"));
        assert_eq!(shader.validation.entry_points, vec!["causal_attention"]);
    }

    #[test]
    fn attention_oracle_uses_stable_softmax_and_caller_buffer() {
        let shape = AttentionShape {
            head_dim: 2,
            head_count: 1,
            context_tokens: 2,
            batch_tokens: 1,
        };
        let query = [1.0, 0.0];
        let keys = [1.0, 0.0, 0.0, 1.0];
        let values = [4.0, 2.0, 8.0, 6.0];
        let mut out = [0.0; 2];
        causal_attention_oracle(shape, &query, &keys, &values, 1.0, &mut out)
            .expect("oracle evaluation");
        let p = core::f32::consts::E / (core::f32::consts::E + 1.0);
        assert!((out[0] - (p * 4.0 + (1.0 - p) * 8.0)).abs() < 1e-5);
        assert!((out[1] - (p * 2.0 + (1.0 - p) * 6.0)).abs() < 1e-5);
    }
}
