use super::super::row::{Contract, SpecTool};
use crate::browser::tool_proficiency::Proficiency;
use crate::tool_chest::core::intent_bus::ActionType;
use crate::tool_chest::core::tool::ToolKind;

const T: &str = "video";
const TL: &str = "Moving pictures";

pub(super) static ROWS: &[SpecTool] = &[
    SpecTool::new(
        T,
        TL,
        "effects",
        "Picture effects",
        "video:stabilise",
        "Steady",
        "Steady shaky pictures on this clip.",
        "video",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Intermediate,
        Contract::Gated("Needs the clip's motion analysed."),
    ),
    SpecTool::new(
        T,
        TL,
        "effects",
        "Picture effects",
        "video:speed-change",
        "Speed",
        "Change how fast the selected clip plays.",
        "video",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Intermediate,
        Contract::Live("Animation.easing"),
    ),
    SpecTool::new(
        T,
        TL,
        "effects",
        "Picture effects",
        "video:transform",
        "Place and size",
        "Move, scale, or turn the picture.",
        "video",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Novice,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "effects",
        "Picture effects",
        "video:chroma-key",
        "Green screen",
        "Cut out a key colour from the picture.",
        "video",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Intermediate,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "effects",
        "Picture effects",
        "video:mask",
        "Mask",
        "Hide part of the selected frame.",
        "video",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Intermediate,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "effects",
        "Picture effects",
        "video:motion-track",
        "Follow motion",
        "Follow a point in the picture.",
        "video",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Expert,
        Contract::Gated("Needs a track point and a range of frames."),
    ),
    SpecTool::new(
        T,
        TL,
        "effects",
        "Picture effects",
        "video:add-blur",
        "Blur",
        "Soften the selected picture.",
        "video",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Novice,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "generators",
        "Make a picture",
        "video:title-generator",
        "Title",
        "Make a title clip on this timeline.",
        "video",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Novice,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "generators",
        "Make a picture",
        "video:lower-third",
        "Lower third",
        "Make a name plate along the bottom.",
        "video",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Intermediate,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "generators",
        "Make a picture",
        "video:shape-generator",
        "Shape",
        "Make a shape clip on this timeline.",
        "video",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Novice,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "generators",
        "Make a picture",
        "video:colour-matte",
        "Colour fill",
        "Make a solid colour clip.",
        "video",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Novice,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "generators",
        "Make a picture",
        "video:noise-generator",
        "Noise",
        "Make a noise clip on this timeline.",
        "video",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Intermediate,
        Contract::Local,
    ),
];
