use super::super::row::{Contract, SpecTool};
use crate::browser::tool_proficiency::Proficiency;
use crate::tool_chest::core::intent_bus::ActionType;
use crate::tool_chest::core::tool::ToolKind;

const T: &str = "video";
const TL: &str = "Moving pictures";

pub(super) static ROWS: &[SpecTool] = &[
    SpecTool::new(
        T,
        TL,
        "audio-sync",
        "Picture and sound",
        "video:sync-from-audio",
        "Sync to sound",
        "Line the picture up with the sound.",
        "video",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Intermediate,
        Contract::Gated("Needs a picture clip and a sound clip to match."),
    ),
    SpecTool::new(
        T,
        TL,
        "audio-sync",
        "Picture and sound",
        "video:auto-align",
        "Auto-align",
        "Line several clips up by their sound.",
        "video",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Expert,
        Contract::Gated("Needs clips with matching sound."),
    ),
    SpecTool::new(
        T,
        TL,
        "audio-sync",
        "Picture and sound",
        "video:scrub-audio",
        "Scrub sound",
        "Hear the sound at this frame.",
        "video",
        ToolKind::Query,
        ActionType::Query,
        Proficiency::Novice,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "audio-sync",
        "Picture and sound",
        "video:extract-audio",
        "Lift the sound",
        "Take the sound out of the picture clip.",
        "video",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Intermediate,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "audio-sync",
        "Picture and sound",
        "video:link-clips",
        "Link clips",
        "Keep picture and sound clips together.",
        "video",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Novice,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "inspect",
        "Inspect",
        "video:waveform-monitor",
        "Waveform",
        "Show brightness across the selected frame.",
        "video",
        ToolKind::Query,
        ActionType::Query,
        Proficiency::Intermediate,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "inspect",
        "Inspect",
        "video:vectorscope",
        "Vectorscope",
        "Show colour on a round scope for this frame.",
        "video",
        ToolKind::Query,
        ActionType::Query,
        Proficiency::Intermediate,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "inspect",
        "Inspect",
        "video:histogram",
        "Histogram",
        "Show how much of each colour is in the frame.",
        "video",
        ToolKind::Query,
        ActionType::Query,
        Proficiency::Novice,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "inspect",
        "Inspect",
        "video:frame-info",
        "Frame details",
        "Show time, size, and format for this frame.",
        "video",
        ToolKind::Query,
        ActionType::Query,
        Proficiency::Novice,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "inspect",
        "Inspect",
        "video:metadata-view",
        "Picture details",
        "Show format, size, frame rate, and colour space.",
        "video",
        ToolKind::Query,
        ActionType::Query,
        Proficiency::Novice,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "render",
        "Finish",
        "video:render-queue",
        "Queue a finish",
        "Queue this piece to be finished.",
        "video",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Intermediate,
        Contract::Gated("Needs an output place and finish settings."),
    ),
    SpecTool::new(
        T,
        TL,
        "render",
        "Finish",
        "video:render-settings",
        "Finish settings",
        "Set format, quality, and size for the finish.",
        "video",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Intermediate,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "render",
        "Finish",
        "video:render-preview",
        "Preview frame",
        "Draw this frame of the scene.",
        "video",
        ToolKind::Query,
        ActionType::Query,
        Proficiency::Novice,
        Contract::Live("Render.scene"),
    ),
    SpecTool::new(
        T,
        TL,
        "render",
        "Finish",
        "video:export-preset",
        "Save a finish preset",
        "Save these finish settings on the selected surface.",
        "video",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Intermediate,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "render",
        "Finish",
        "video:batch-render",
        "Finish several",
        "Finish several queued jobs.",
        "video",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Expert,
        Contract::Gated("Needs queued finish jobs."),
    ),
];
