use super::super::row::{Contract, SpecTool};
use crate::browser::tool_proficiency::Proficiency;
use crate::tool_chest::core::intent_bus::ActionType;
use crate::tool_chest::core::tool::ToolKind;

const T: &str = "video";
const TL: &str = "Moving pictures";

pub(super) static ROWS: &[SpecTool] = &[
    SpecTool::new(
        T,
        TL,
        "transitions",
        "Joins",
        "video:crossfade",
        "Crossfade",
        "Dissolve from one clip to the next.",
        "video",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Novice,
        Contract::Live("Animation.easing"),
    ),
    SpecTool::new(
        T,
        TL,
        "transitions",
        "Joins",
        "video:wipe",
        "Wipe",
        "Wipe from one clip to the next.",
        "video",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Intermediate,
        Contract::Live("Animation.easing"),
    ),
    SpecTool::new(
        T,
        TL,
        "transitions",
        "Joins",
        "video:dissolve",
        "Dissolve",
        "Softly blend from one clip to the next.",
        "video",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Novice,
        Contract::Live("Animation.easing"),
    ),
    SpecTool::new(
        T,
        TL,
        "transitions",
        "Joins",
        "video:push",
        "Push",
        "Push one clip in with the next.",
        "video",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Intermediate,
        Contract::Live("Animation.easing"),
    ),
    SpecTool::new(
        T,
        TL,
        "transitions",
        "Joins",
        "video:slide",
        "Slide",
        "Slide the next clip over this one.",
        "video",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Intermediate,
        Contract::Live("Animation.easing"),
    ),
    SpecTool::new(
        T,
        TL,
        "transitions",
        "Joins",
        "video:dip-to-black",
        "Dip to black",
        "Fade through black between clips.",
        "video",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Novice,
        Contract::Live("Animation.easing"),
    ),
    SpecTool::new(
        T,
        TL,
        "transitions",
        "Joins",
        "video:custom-transition",
        "Custom join",
        "Use a saved join between clips.",
        "video",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Expert,
        Contract::Live("Animation.evaluate_preset"),
    ),
    SpecTool::new(
        T,
        TL,
        "colour",
        "Colour",
        "video:lift-gamma-gain",
        "Lift, gamma, gain",
        "Grade shadows, midtones, and highlights.",
        "video",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Intermediate,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "colour",
        "Colour",
        "video:saturation",
        "Saturation",
        "Make the colours stronger or quieter.",
        "video",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Novice,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "colour",
        "Colour",
        "video:colour-wheels",
        "Colour wheels",
        "Grade shadows, midtones, and highlights with wheels.",
        "video",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Intermediate,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "colour",
        "Colour",
        "video:curves",
        "Curves",
        "Shape brightness with a curve.",
        "video",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Intermediate,
        Contract::Live("Animation.bezier_eval"),
    ),
    SpecTool::new(
        T,
        TL,
        "colour",
        "Colour",
        "video:hue-vs-hue",
        "Hue versus hue",
        "Shift one colour towards another.",
        "video",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Expert,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "colour",
        "Colour",
        "video:hue-vs-sat",
        "Hue versus saturation",
        "Change how strong one colour is.",
        "video",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Expert,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "colour",
        "Colour",
        "video:lut-apply",
        "Apply a look",
        "Apply a look-up table to this clip.",
        "video",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Intermediate,
        Contract::Gated("Needs a look-up table file."),
    ),
    SpecTool::new(
        T,
        TL,
        "colour",
        "Colour",
        "video:lut-export",
        "Export a look",
        "Save this grade as a look-up table.",
        "video",
        ToolKind::Query,
        ActionType::Query,
        Proficiency::Expert,
        Contract::Gated("Needs a place to save the look-up table."),
    ),
];
