use super::super::row::{Contract, SpecTool};
use crate::browser::tool_proficiency::Proficiency;
use crate::tool_chest::core::intent_bus::ActionType;
use crate::tool_chest::core::tool::ToolKind;

const T: &str = "video";
const TL: &str = "Moving pictures";

pub(super) static ROWS: &[SpecTool] = &[
    SpecTool::new(
        T,
        TL,
        "transport",
        "Play and stop",
        "video:play",
        "Play",
        "Start playing from this frame.",
        "video",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Novice,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "transport",
        "Play and stop",
        "video:stop",
        "Stop",
        "Stop playing on the selected surface.",
        "video",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Novice,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "transport",
        "Play and stop",
        "video:mark-in",
        "Mark in",
        "Mark where this shot starts.",
        "video",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Novice,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "transport",
        "Play and stop",
        "video:mark-out",
        "Mark out",
        "Mark where this shot ends.",
        "video",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Novice,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "transport",
        "Play and stop",
        "video:shuttle",
        "Shuttle",
        "Play faster or slower, forwards or back.",
        "video",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Intermediate,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "transport",
        "Play and stop",
        "video:jog",
        "Jog",
        "Step one frame at a time.",
        "video",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Novice,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "editing",
        "Cut and join",
        "video:razor",
        "Razor",
        "Cut the selected clip at this frame.",
        "video",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Novice,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "editing",
        "Cut and join",
        "video:splice",
        "Splice",
        "Join selected clips together.",
        "video",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Novice,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "editing",
        "Cut and join",
        "video:overwrite",
        "Overwrite",
        "Put this clip over what is already there.",
        "video",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Intermediate,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "editing",
        "Cut and join",
        "video:insert",
        "Insert",
        "Put this clip in and push the rest along.",
        "video",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Intermediate,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "editing",
        "Cut and join",
        "video:ripple-delete",
        "Ripple delete",
        "Remove the clip and close the gap.",
        "video",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Intermediate,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "editing",
        "Cut and join",
        "video:lift",
        "Lift",
        "Take the clip out and leave a gap.",
        "video",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Intermediate,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "editing",
        "Cut and join",
        "video:append",
        "Append",
        "Put this clip at the end of the track.",
        "video",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Novice,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "editing",
        "Cut and join",
        "video:split-clip",
        "Split",
        "Split the clip into two at this frame.",
        "video",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Novice,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "editing",
        "Cut and join",
        "video:match-frame",
        "Match frame",
        "Find this frame in the source bin.",
        "video",
        ToolKind::Query,
        ActionType::Query,
        Proficiency::Intermediate,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "editing",
        "Cut and join",
        "video:replace",
        "Replace",
        "Swap this clip for another.",
        "video",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Intermediate,
        Contract::Local,
    ),
];
