use super::super::row::{Contract, SpecTool};
use crate::browser::tool_proficiency::Proficiency;
use crate::tool_chest::core::intent_bus::ActionType;
use crate::tool_chest::core::tool::ToolKind;

const T: &str = "hypermedia";
const TL: &str = "Interactive";

pub(super) static ROWS: &[SpecTool] = &[
    SpecTool::new(
        T,
        TL,
        "interactive",
        "Overlays",
        "hypermedia:add-trigger",
        "Add a trigger",
        "Put a cue on the timeline that starts something.",
        "timeline",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Novice,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "interactive",
        "Overlays",
        "hypermedia:trigger-condition",
        "Set when it fires",
        "Say what must be true before this trigger runs.",
        "timeline",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Intermediate,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "interactive",
        "Overlays",
        "hypermedia:trigger-action",
        "Set what it does",
        "Choose what happens when this trigger fires.",
        "timeline",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Intermediate,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "interactive",
        "Overlays",
        "hypermedia:overlay-create",
        "Make an overlay",
        "Create a graphic that sits on the picture.",
        "timeline",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Novice,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "interactive",
        "Overlays",
        "hypermedia:overlay-edit",
        "Edit overlay",
        "Change the writing or picture in this overlay.",
        "timeline",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Intermediate,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "interactive",
        "Overlays",
        "hypermedia:overlay-timeline",
        "Place overlay",
        "Set when this overlay appears and how long it stays.",
        "timeline",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Intermediate,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "interactive",
        "Overlays",
        "hypermedia:interactive-preview",
        "Preview the show",
        "Watch the picture with overlays as the audience would.",
        "timeline",
        ToolKind::Query,
        ActionType::Query,
        Proficiency::Novice,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "interactive",
        "Overlays",
        "hypermedia:interactive-test",
        "Run a test",
        "Walk through a test path of the interactive show.",
        "timeline",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Expert,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "second-screen",
        "Second screen",
        "hypermedia:companion-app-config",
        "Companion app",
        "Set up the phone or tablet that rides along with the show.",
        "screen",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Intermediate,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "second-screen",
        "Second screen",
        "hypermedia:sync-stream-setup",
        "Sync the stream",
        "Keep the second screen in time with the broadcast.",
        "screen",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Expert,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "second-screen",
        "Second screen",
        "hypermedia:remote-control-map",
        "Map the remote",
        "Tie remote keys to actions on the overlay.",
        "screen",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Intermediate,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "second-screen",
        "Second screen",
        "hypermedia:second-screen-preview",
        "Preview second screen",
        "See what the companion screen will show.",
        "screen",
        ToolKind::Query,
        ActionType::Query,
        Proficiency::Novice,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "second-screen",
        "Second screen",
        "hypermedia:push-notification",
        "Push a notice",
        "Send a short notice to paired screens at a cue.",
        "screen",
        ToolKind::RunAction,
        ActionType::Publish,
        Proficiency::Intermediate,
        Contract::Live("Pulse.publish"),
    ),
    SpecTool::new(
        T,
        TL,
        "second-screen",
        "Second screen",
        "hypermedia:screen-pairing",
        "Pair a screen",
        "Join a second screen to this show.",
        "screen",
        ToolKind::RunAction,
        ActionType::Publish,
        Proficiency::Intermediate,
        Contract::Live("Pulse.publish_presence"),
    ),
];
