use super::super::row::{Contract, SpecTool};
use crate::browser::tool_proficiency::Proficiency;
use crate::tool_chest::core::intent_bus::ActionType;
use crate::tool_chest::core::tool::ToolKind;

const T: &str = "hypermedia";
const TL: &str = "Interactive";

pub(super) static ROWS: &[SpecTool] = &[
    SpecTool::new(
        T,
        TL,
        "social",
        "Audience",
        "hypermedia:chat-overlay",
        "Show chat",
        "Put live chat on the picture.",
        "social",
        ToolKind::RunAction,
        ActionType::Publish,
        Proficiency::Novice,
        Contract::Live("Pulse.publish"),
    ),
    SpecTool::new(
        T,
        TL,
        "social",
        "Audience",
        "hypermedia:poll-create",
        "Start a poll",
        "Ask the audience a question with timed choices.",
        "social",
        ToolKind::RunAction,
        ActionType::Publish,
        Proficiency::Novice,
        Contract::Live("Pulse.publish"),
    ),
    SpecTool::new(
        T,
        TL,
        "social",
        "Audience",
        "hypermedia:reaction-overlay",
        "Show reactions",
        "Put audience reactions on the picture.",
        "social",
        ToolKind::RunAction,
        ActionType::Publish,
        Proficiency::Intermediate,
        Contract::Live("Pulse.publish"),
    ),
    SpecTool::new(
        T,
        TL,
        "social",
        "Audience",
        "hypermedia:share-button",
        "Share button",
        "Add a share control to the overlay.",
        "social",
        ToolKind::RunAction,
        ActionType::Publish,
        Proficiency::Novice,
        Contract::Live("Pulse.publish"),
    ),
    SpecTool::new(
        T,
        TL,
        "social",
        "Audience",
        "hypermedia:co-view-sync",
        "Watch together",
        "Keep everyone in the room on the same moment.",
        "social",
        ToolKind::RunAction,
        ActionType::Publish,
        Proficiency::Intermediate,
        Contract::Live("Pulse.publish_presence"),
    ),
    SpecTool::new(
        T,
        TL,
        "social",
        "Audience",
        "hypermedia:social-moderation",
        "Moderation rules",
        "Set what chat and reactions are allowed.",
        "social",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Expert,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "packaging",
        "Packaging",
        "hypermedia:hbbtv-package",
        "Pack the app",
        "Build the broadcast app package.",
        "package",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Expert,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "packaging",
        "Packaging",
        "hypermedia:ait-config",
        "App table",
        "Fill the application information table for the package.",
        "package",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Expert,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "packaging",
        "Packaging",
        "hypermedia:dvb-stream-bind",
        "Bind the stream",
        "Tie this package to a broadcast stream.",
        "package",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Expert,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "packaging",
        "Packaging",
        "hypermedia:drm-config",
        "Rights lock",
        "Set the lock that protects the stream.",
        "package",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Expert,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "packaging",
        "Packaging",
        "hypermedia:app-data-bundle",
        "Bundle app data",
        "Pack extra app files with the package.",
        "package",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Expert,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "packaging",
        "Packaging",
        "hypermedia:package-validate",
        "Check the package",
        "Check the package against the broadcast rules.",
        "package",
        ToolKind::Query,
        ActionType::Query,
        Proficiency::Expert,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "packaging",
        "Packaging",
        "hypermedia:package-export",
        "Export package",
        "Write the package out for the broadcaster.",
        "package",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Expert,
        Contract::Local,
    ),
];
