use super::super::row::{Contract, SpecTool};
use crate::browser::tool_proficiency::Proficiency;
use crate::tool_chest::core::intent_bus::ActionType;
use crate::tool_chest::core::tool::ToolKind;

const T: &str = "hypermedia";
const TL: &str = "Interactive";

pub(super) static ROWS: &[SpecTool] = &[
    SpecTool::new(
        T,
        TL,
        "sync",
        "Timing",
        "hypermedia:timeline-sync",
        "Sync the timeline",
        "Choose what the timeline keeps time with.",
        "timeline",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Intermediate,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "sync",
        "Timing",
        "hypermedia:event-sync",
        "Sync on an event",
        "Fire a sync when a named event happens.",
        "timeline",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Intermediate,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "sync",
        "Timing",
        "hypermedia:wall-clock-sync",
        "Wall-clock sync",
        "Keep time with the real-world clock.",
        "timeline",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Expert,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "sync",
        "Timing",
        "hypermedia:scte35-marker",
        "Ad-break marker",
        "Put an ad-break marker on the timeline.",
        "timeline",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Expert,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "sync",
        "Timing",
        "hypermedia:sync-test",
        "Test the sync",
        "Measure how tightly the screens stay together.",
        "timeline",
        ToolKind::Query,
        ActionType::Query,
        Proficiency::Expert,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "inspect",
        "Inspect",
        "hypermedia:package-inspector",
        "Inspect package",
        "Open the package and list what is inside.",
        "inspect",
        ToolKind::Query,
        ActionType::Query,
        Proficiency::Intermediate,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "inspect",
        "Inspect",
        "hypermedia:stream-analyser",
        "Analyse the stream",
        "Check bitrate, codec, and continuity.",
        "inspect",
        ToolKind::Query,
        ActionType::Query,
        Proficiency::Intermediate,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "inspect",
        "Inspect",
        "hypermedia:device-emulator",
        "Emulate a device",
        "See the show as a chosen TV or box would.",
        "inspect",
        ToolKind::Query,
        ActionType::Query,
        Proficiency::Intermediate,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "inspect",
        "Inspect",
        "hypermedia:bandwidth-simulator",
        "Simulate bandwidth",
        "See the show under a slower connection.",
        "inspect",
        ToolKind::Query,
        ActionType::Query,
        Proficiency::Expert,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "inspect",
        "Inspect",
        "hypermedia:metadata-view",
        "Show metadata",
        "Read the facts stored on this interactive asset.",
        "inspect",
        ToolKind::Query,
        ActionType::Query,
        Proficiency::Intermediate,
        Contract::Local,
    ),
];
