//! Health manifold seed — health & wellbeing containers (Workstream B).
//!
//! Copyright (c) 2026 Timothy Charles Holborn. All rights reserved.

use super::super::core::registry::{
    DockPosition, ManifoldSeed, SeedConnection, SeedContainer, SeedPanel,
};

pub fn health_manifold_seed() -> ManifoldSeed {
    ManifoldSeed {
        id: "health".into(),
        label: "Health".into(),
        icon: "health".into(),
        ontology_prefix: "med".into(),
        description: "Health & wellbeing: conditions, lab results, medications, mental wellbeing, \
             biometrics, welfare support, safeguards. Consent-gated. Sanctuary-respecting."
            .into(),
        containers: vec![
            SeedContainer {
                container_type: "health_overview".into(),
                title: "Health Overview".into(),
                x: 30.0,
                y: 30.0,
                width: 1340.0,
                height: 280.0,
                z: 1.0,
                honesty: "present".into(),
                ..Default::default()
            },
            SeedContainer {
                container_type: "conditions".into(),
                title: "Conditions".into(),
                x: 30.0,
                y: 330.0,
                width: 660.0,
                height: 260.0,
                z: 1.0,
                honesty: "present".into(),
                ..Default::default()
            },
            SeedContainer {
                container_type: "clinical_reports".into(),
                title: "Clinical Reports".into(),
                x: 710.0,
                y: 330.0,
                width: 660.0,
                height: 260.0,
                z: 1.0,
                honesty: "present".into(),
                ..Default::default()
            },
            SeedContainer {
                container_type: "lab_results".into(),
                title: "Lab Results".into(),
                x: 30.0,
                y: 610.0,
                width: 660.0,
                height: 280.0,
                z: 1.0,
                honesty: "present".into(),
                ..Default::default()
            },
            SeedContainer {
                container_type: "medications".into(),
                title: "Medications".into(),
                x: 710.0,
                y: 610.0,
                width: 660.0,
                height: 280.0,
                z: 1.0,
                honesty: "present".into(),
                ..Default::default()
            },
            SeedContainer {
                container_type: "vitals".into(),
                title: "Vitals".into(),
                x: 30.0,
                y: 910.0,
                width: 660.0,
                height: 240.0,
                z: 1.0,
                honesty: "present".into(),
                ..Default::default()
            },
            SeedContainer {
                container_type: "mental_wellbeing".into(),
                title: "Mental Wellbeing".into(),
                x: 710.0,
                y: 910.0,
                width: 660.0,
                height: 280.0,
                z: 1.0,
                honesty: "present".into(),
                ..Default::default()
            },
            SeedContainer {
                container_type: "therapy_notes".into(),
                title: "Therapy Notes".into(),
                x: 30.0,
                y: 1210.0,
                width: 660.0,
                height: 240.0,
                z: 1.0,
                honesty: "present".into(),
                ..Default::default()
            },
            SeedContainer {
                container_type: "sleep".into(),
                title: "Sleep".into(),
                x: 710.0,
                y: 1210.0,
                width: 660.0,
                height: 240.0,
                z: 1.0,
                honesty: "present".into(),
                ..Default::default()
            },
            SeedContainer {
                container_type: "diet".into(),
                title: "Diet".into(),
                x: 30.0,
                y: 1470.0,
                width: 660.0,
                height: 240.0,
                z: 1.0,
                honesty: "present".into(),
                ..Default::default()
            },
            SeedContainer {
                container_type: "physical_activity".into(),
                title: "Physical Activity".into(),
                x: 710.0,
                y: 1470.0,
                width: 660.0,
                height: 240.0,
                z: 1.0,
                honesty: "present".into(),
                ..Default::default()
            },
            SeedContainer {
                container_type: "immunizations".into(),
                title: "Immunizations".into(),
                x: 30.0,
                y: 1730.0,
                width: 660.0,
                height: 240.0,
                z: 1.0,
                honesty: "present".into(),
                ..Default::default()
            },
            SeedContainer {
                container_type: "procedures".into(),
                title: "Procedures".into(),
                x: 710.0,
                y: 1730.0,
                width: 660.0,
                height: 240.0,
                z: 1.0,
                honesty: "present".into(),
                ..Default::default()
            },
            SeedContainer {
                container_type: "family_history".into(),
                title: "Family History".into(),
                x: 30.0,
                y: 1990.0,
                width: 660.0,
                height: 240.0,
                z: 1.0,
                honesty: "present".into(),
                ..Default::default()
            },
            SeedContainer {
                container_type: "hypotheses".into(),
                title: "Hypotheses".into(),
                x: 710.0,
                y: 1990.0,
                width: 660.0,
                height: 280.0,
                z: 1.0,
                honesty: "present".into(),
                ..Default::default()
            },
            SeedContainer {
                container_type: "biometrics".into(),
                title: "Biometrics".into(),
                x: 30.0,
                y: 2250.0,
                width: 660.0,
                height: 240.0,
                z: 1.0,
                honesty: "present".into(),
                ..Default::default()
            },
            SeedContainer {
                container_type: "health_documents".into(),
                title: "Health Documents".into(),
                x: 710.0,
                y: 2250.0,
                width: 660.0,
                height: 260.0,
                z: 1.0,
                honesty: "present".into(),
                ..Default::default()
            },
            SeedContainer {
                container_type: "welfare_support".into(),
                title: "Welfare Support".into(),
                x: 30.0,
                y: 2510.0,
                width: 660.0,
                height: 240.0,
                z: 1.0,
                honesty: "present".into(),
                ..Default::default()
            },
            SeedContainer {
                container_type: "life_records".into(),
                title: "Life Records".into(),
                x: 710.0,
                y: 2510.0,
                width: 660.0,
                height: 240.0,
                z: 1.0,
                honesty: "present".into(),
                ..Default::default()
            },
            SeedContainer {
                container_type: "authority_attestations".into(),
                title: "Authority Attestations".into(),
                x: 30.0,
                y: 2770.0,
                width: 660.0,
                height: 240.0,
                z: 1.0,
                honesty: "present".into(),
                ..Default::default()
            },
            SeedContainer {
                container_type: "safeguards".into(),
                title: "Safeguards".into(),
                x: 710.0,
                y: 2770.0,
                width: 660.0,
                height: 240.0,
                z: 1.0,
                honesty: "present".into(),
                ..Default::default()
            },
            SeedContainer {
                container_type: "disclosure_log".into(),
                title: "Disclosure Log".into(),
                x: 30.0,
                y: 3030.0,
                width: 1340.0,
                height: 240.0,
                z: 1.0,
                honesty: "present".into(),
                ..Default::default()
            },
        ],
        connections: vec![
            SeedConnection {
                id: "wire-h1".into(),
                from: 0,
                to: 1,
                wire_type: "active".into(),
                label: "med:hasConditions".into(),
            },
            SeedConnection {
                id: "wire-h2".into(),
                from: 0,
                to: 2,
                wire_type: "active".into(),
                label: "med:hasClinicalReports".into(),
            },
            SeedConnection {
                id: "wire-h3".into(),
                from: 0,
                to: 3,
                wire_type: "active".into(),
                label: "med:hasLabResults".into(),
            },
            SeedConnection {
                id: "wire-h4".into(),
                from: 0,
                to: 4,
                wire_type: "active".into(),
                label: "med:hasMedications".into(),
            },
            SeedConnection {
                id: "wire-h5".into(),
                from: 0,
                to: 5,
                wire_type: "active".into(),
                label: "med:hasVitals".into(),
            },
            SeedConnection {
                id: "wire-h6".into(),
                from: 0,
                to: 6,
                wire_type: "active".into(),
                label: "med:hasMentalWellbeing".into(),
            },
            SeedConnection {
                id: "wire-h7".into(),
                from: 6,
                to: 7,
                wire_type: "active".into(),
                label: "med:hasTherapyNotes".into(),
            },
            SeedConnection {
                id: "wire-h8".into(),
                from: 0,
                to: 8,
                wire_type: "active".into(),
                label: "med:hasSleep".into(),
            },
            SeedConnection {
                id: "wire-h9".into(),
                from: 0,
                to: 9,
                wire_type: "active".into(),
                label: "med:hasDiet".into(),
            },
            SeedConnection {
                id: "wire-h10".into(),
                from: 0,
                to: 10,
                wire_type: "active".into(),
                label: "med:hasPhysicalActivity".into(),
            },
            SeedConnection {
                id: "wire-h11".into(),
                from: 0,
                to: 11,
                wire_type: "active".into(),
                label: "med:hasImmunizations".into(),
            },
            SeedConnection {
                id: "wire-h12".into(),
                from: 0,
                to: 12,
                wire_type: "active".into(),
                label: "med:hasProcedures".into(),
            },
            SeedConnection {
                id: "wire-h13".into(),
                from: 0,
                to: 13,
                wire_type: "active".into(),
                label: "med:hasFamilyHistory".into(),
            },
            SeedConnection {
                id: "wire-h14".into(),
                from: 3,
                to: 14,
                wire_type: "active".into(),
                label: "med:hasHypotheses".into(),
            },
            SeedConnection {
                id: "wire-h15".into(),
                from: 0,
                to: 15,
                wire_type: "active".into(),
                label: "med:hasBiometrics".into(),
            },
            SeedConnection {
                id: "wire-h16".into(),
                from: 2,
                to: 16,
                wire_type: "active".into(),
                label: "med:hasDocuments".into(),
            },
            SeedConnection {
                id: "wire-h17".into(),
                from: 0,
                to: 17,
                wire_type: "active".into(),
                label: "med:hasWelfareSupport".into(),
            },
            SeedConnection {
                id: "wire-h18".into(),
                from: 17,
                to: 18,
                wire_type: "active".into(),
                label: "med:hasLifeRecords".into(),
            },
            SeedConnection {
                id: "wire-h19".into(),
                from: 17,
                to: 19,
                wire_type: "active".into(),
                label: "med:hasAttestations".into(),
            },
            SeedConnection {
                id: "wire-h20".into(),
                from: 0,
                to: 20,
                wire_type: "active".into(),
                label: "med:hasSafeguards".into(),
            },
            SeedConnection {
                id: "wire-h21".into(),
                from: 0,
                to: 21,
                wire_type: "active".into(),
                label: "med:hasDisclosureLog".into(),
            },
        ],
        panels: vec![SeedPanel {
            panel_type: "aura".into(),
            dock: DockPosition::Right,
        }],
    }
}
