//! Projects manifold seed — sheet, graph, pulse for collaborative projects.
//!
//! Copyright (c) 2026 Timothy Charles Holborn. All rights reserved.

use super::super::core::registry::{
    DockPosition, ManifoldSeed, SeedConnection, SeedContainer, SeedPanel,
};
use super::super::core::ManifoldSociality;

pub fn projects_manifold_seed() -> ManifoldSeed {
    ManifoldSeed {
        id: "projects".into(),
        label: "Projects".into(),
        icon: "projects".into(),
        ontology_prefix: "coop".into(),
        description: "Collaborative projects \u{2014} a social manifold: many people, members, presence, sheet, kanban, budget, discussion, commons."
            .into(),
        containers: vec![
            SeedContainer {
                container_type: "project_sheet".into(),
                title: "Project Sheet".into(),
                x: 30.0,
                y: 30.0,
                width: 420.0,
                height: 340.0,
                z: 1.0,
                honesty: "present".into(),
                ..Default::default()
            },
            SeedContainer {
                container_type: "kanban".into(),
                title: "Work Items Kanban".into(),
                x: 470.0,
                y: 30.0,
                width: 500.0,
                height: 340.0,
                z: 1.0,
                honesty: "present".into(),
                ..Default::default()
            },
            SeedContainer {
                container_type: "graph".into(),
                title: "Project Graph".into(),
                x: 990.0,
                y: 30.0,
                width: 380.0,
                height: 340.0,
                z: 1.0,
                honesty: "present".into(),
                ..Default::default()
            },
            SeedContainer {
                container_type: "budget".into(),
                title: "Budget & Finance".into(),
                x: 30.0,
                y: 390.0,
                width: 420.0,
                height: 280.0,
                z: 1.0,
                honesty: "present".into(),
                ..Default::default()
            },
            SeedContainer {
                container_type: "cost_base".into(),
                title: "Cost Base & Obligation".into(),
                x: 470.0,
                y: 390.0,
                width: 420.0,
                height: 280.0,
                z: 1.0,
                honesty: "present".into(),
                ..Default::default()
            },
            SeedContainer {
                container_type: "deliverable".into(),
                title: "Deliverables & Artifacts".into(),
                x: 910.0,
                y: 390.0,
                width: 460.0,
                height: 280.0,
                z: 1.0,
                honesty: "present".into(),
                ..Default::default()
            },
            SeedContainer {
                container_type: "review".into(),
                title: "Reviews & Decisions".into(),
                x: 30.0,
                y: 690.0,
                width: 420.0,
                height: 240.0,
                z: 1.0,
                honesty: "present".into(),
                ..Default::default()
            },
            SeedContainer {
                container_type: "discussion".into(),
                title: "Discussion".into(),
                x: 470.0,
                y: 690.0,
                width: 420.0,
                height: 240.0,
                z: 1.0,
                honesty: "present".into(),
                ..Default::default()
            },
            SeedContainer {
                container_type: "roadmap".into(),
                title: "Roadmap & Phases".into(),
                x: 910.0,
                y: 690.0,
                width: 460.0,
                height: 240.0,
                z: 1.0,
                honesty: "present".into(),
                ..Default::default()
            },
            SeedContainer {
                container_type: "commons".into(),
                title: "Commons Publication".into(),
                x: 30.0,
                y: 950.0,
                width: 620.0,
                height: 200.0,
                z: 1.0,
                honesty: "present".into(),
                ..Default::default()
            },
            SeedContainer {
                container_type: "pulse".into(),
                title: "Activity Pulse".into(),
                x: 670.0,
                y: 950.0,
                width: 700.0,
                height: 200.0,
                z: 1.0,
                honesty: "present".into(),
                ..Default::default()
            },
            SeedContainer {
                container_type: "agreement_builder".into(),
                title: "Agreement Builder".into(),
                x: 30.0,
                y: 1180.0,
                width: 620.0,
                height: 320.0,
                z: 1.0,
                honesty: "present".into(),
                ..Default::default()
            },
            SeedContainer {
                container_type: "compensation_model".into(),
                title: "Compensation Model".into(),
                x: 670.0,
                y: 1180.0,
                width: 700.0,
                height: 320.0,
                z: 1.0,
                honesty: "present".into(),
                ..Default::default()
            },
            SeedContainer {
                container_type: "contribution_ledger".into(),
                title: "Contribution Ledger".into(),
                x: 30.0,
                y: 1530.0,
                width: 620.0,
                height: 280.0,
                z: 1.0,
                honesty: "present".into(),
                ..Default::default()
            },
            SeedContainer {
                container_type: "license_builder".into(),
                title: "License Builder".into(),
                x: 670.0,
                y: 1530.0,
                width: 700.0,
                height: 280.0,
                z: 1.0,
                honesty: "present".into(),
                ..Default::default()
            },
            SeedContainer {
                container_type: "obligation_tracker".into(),
                title: "Obligation Tracker".into(),
                x: 30.0,
                y: 1840.0,
                width: 1340.0,
                height: 240.0,
                z: 1.0,
                honesty: "present".into(),
                ..Default::default()
            },
            SeedContainer {
                container_type: "ip_registry".into(),
                title: "IP Registry".into(),
                x: 30.0,
                y: 2120.0,
                width: 620.0,
                height: 280.0,
                z: 1.0,
                honesty: "present".into(),
                ..Default::default()
            },
            SeedContainer {
                container_type: "data_sources".into(),
                title: "Data Sources".into(),
                x: 670.0,
                y: 2120.0,
                width: 700.0,
                height: 280.0,
                z: 1.0,
                honesty: "present".into(),
                ..Default::default()
            },
            SeedContainer {
                container_type: "disputes".into(),
                title: "Disputes".into(),
                x: 30.0,
                y: 2450.0,
                width: 620.0,
                height: 280.0,
                z: 1.0,
                honesty: "present".into(),
                ..Default::default()
            },
            SeedContainer {
                container_type: "complaints".into(),
                title: "Complaints".into(),
                x: 670.0,
                y: 2450.0,
                width: 700.0,
                height: 280.0,
                z: 1.0,
                honesty: "present".into(),
                ..Default::default()
            },
            SeedContainer {
                container_type: "corrections".into(),
                title: "Corrections".into(),
                x: 30.0,
                y: 2770.0,
                width: 620.0,
                height: 240.0,
                z: 1.0,
                honesty: "present".into(),
                ..Default::default()
            },
            SeedContainer {
                container_type: "governance_meetings".into(),
                title: "Governance Meetings".into(),
                x: 670.0,
                y: 2770.0,
                width: 700.0,
                height: 240.0,
                z: 1.0,
                honesty: "present".into(),
                ..Default::default()
            },
            SeedContainer {
                container_type: "conflict_of_interest".into(),
                title: "Conflict of Interest".into(),
                x: 30.0,
                y: 3060.0,
                width: 1340.0,
                height: 240.0,
                z: 1.0,
                honesty: "present".into(),
                ..Default::default()
            },
            SeedContainer {
                container_type: "onboarding".into(),
                title: "Onboarding".into(),
                x: 30.0,
                y: 3350.0,
                width: 620.0,
                height: 320.0,
                z: 1.0,
                honesty: "present".into(),
                ..Default::default()
            },
            SeedContainer {
                container_type: "bulk_import".into(),
                title: "Bulk Import".into(),
                x: 670.0,
                y: 3350.0,
                width: 700.0,
                height: 320.0,
                z: 1.0,
                honesty: "present".into(),
                ..Default::default()
            },
            SeedContainer {
                container_type: "knowledge_base".into(),
                title: "Knowledge Base".into(),
                x: 30.0,
                y: 3720.0,
                width: 620.0,
                height: 300.0,
                z: 1.0,
                honesty: "present".into(),
                ..Default::default()
            },
            SeedContainer {
                container_type: "agent_console".into(),
                title: "Agent Console".into(),
                x: 670.0,
                y: 3720.0,
                width: 700.0,
                height: 300.0,
                z: 1.0,
                honesty: "present".into(),
                ..Default::default()
            },
            SeedContainer {
                container_type: "dashboard".into(),
                title: "Dashboard".into(),
                x: 30.0,
                y: 4090.0,
                width: 1340.0,
                height: 280.0,
                z: 1.0,
                honesty: "present".into(),
                ..Default::default()
            },
            SeedContainer {
                container_type: "wiki".into(),
                title: "Wiki".into(),
                x: 30.0,
                y: 4410.0,
                width: 620.0,
                height: 280.0,
                z: 1.0,
                honesty: "present".into(),
                ..Default::default()
            },
            SeedContainer {
                container_type: "governance".into(),
                title: "Governance".into(),
                x: 670.0,
                y: 4410.0,
                width: 700.0,
                height: 280.0,
                z: 1.0,
                honesty: "present".into(),
                ..Default::default()
            },
            SeedContainer {
                container_type: "credentials".into(),
                title: "Credentials".into(),
                x: 30.0,
                y: 4730.0,
                width: 620.0,
                height: 260.0,
                z: 1.0,
                honesty: "present".into(),
                ..Default::default()
            },
            SeedContainer {
                container_type: "token_mgr".into(),
                title: "Token Manager".into(),
                x: 670.0,
                y: 4730.0,
                width: 700.0,
                height: 260.0,
                z: 1.0,
                honesty: "present".into(),
                ..Default::default()
            },
            SeedContainer {
                container_type: "awards".into(),
                title: "Awards".into(),
                x: 30.0,
                y: 5050.0,
                width: 1340.0,
                height: 240.0,
                z: 1.0,
                honesty: "present".into(),
                ..Default::default()
            },
            SeedContainer {
                container_type: "gantt".into(),
                title: "Gantt Chart".into(),
                x: 30.0,
                y: 5330.0,
                width: 1340.0,
                height: 300.0,
                z: 1.0,
                honesty: "present".into(),
                ..Default::default()
            },
            SeedContainer {
                container_type: "timeline".into(),
                title: "Timeline".into(),
                x: 30.0,
                y: 5670.0,
                width: 1340.0,
                height: 280.0,
                z: 1.0,
                honesty: "present".into(),
                ..Default::default()
            },
            SeedContainer {
                container_type: "calendar".into(),
                title: "Calendar".into(),
                x: 30.0,
                y: 5990.0,
                width: 1340.0,
                height: 300.0,
                z: 1.0,
                honesty: "present".into(),
                ..Default::default()
            },
            SeedContainer {
                container_type: "doc_mgmt".into(),
                title: "Document Management".into(),
                x: 30.0,
                y: 6330.0,
                width: 1340.0,
                height: 260.0,
                z: 1.0,
                honesty: "present".into(),
                ..Default::default()
            },
            SeedContainer {
                container_type: "resource_report".into(),
                title: "Resource Report".into(),
                x: 30.0,
                y: 6650.0,
                width: 660.0,
                height: 280.0,
                z: 1.0,
                honesty: "present".into(),
                ..Default::default()
            },
            SeedContainer {
                container_type: "time_tracking".into(),
                title: "Time Tracking".into(),
                x: 710.0,
                y: 6650.0,
                width: 660.0,
                height: 280.0,
                z: 1.0,
                honesty: "present".into(),
                ..Default::default()
            },
            SeedContainer {
                container_type: "voting".into(),
                title: "Voting".into(),
                x: 30.0,
                y: 6970.0,
                width: 660.0,
                height: 280.0,
                z: 1.0,
                honesty: "present".into(),
                ..Default::default()
            },
            SeedContainer {
                container_type: "risk".into(),
                title: "Risk Register".into(),
                x: 710.0,
                y: 6970.0,
                width: 660.0,
                height: 280.0,
                z: 1.0,
                honesty: "present".into(),
                ..Default::default()
            },
            SeedContainer {
                container_type: "task_list".into(),
                title: "Task List".into(),
                x: 30.0,
                y: 7290.0,
                width: 660.0,
                height: 260.0,
                z: 1.0,
                honesty: "present".into(),
                ..Default::default()
            },
            SeedContainer {
                container_type: "issues".into(),
                title: "Issues".into(),
                x: 710.0,
                y: 7290.0,
                width: 660.0,
                height: 260.0,
                z: 1.0,
                honesty: "present".into(),
                ..Default::default()
            },
            SeedContainer {
                container_type: "asset_mgr".into(),
                title: "Asset Manager".into(),
                x: 30.0,
                y: 7590.0,
                width: 660.0,
                height: 280.0,
                z: 1.0,
                honesty: "present".into(),
                ..Default::default()
            },
            SeedContainer {
                container_type: "bounties".into(),
                title: "Bounties".into(),
                x: 710.0,
                y: 7590.0,
                width: 660.0,
                height: 280.0,
                z: 1.0,
                honesty: "present".into(),
                ..Default::default()
            },
            SeedContainer {
                container_type: "automation".into(),
                title: "Automation".into(),
                x: 30.0,
                y: 7890.0,
                width: 660.0,
                height: 280.0,
                z: 1.0,
                honesty: "present".into(),
                ..Default::default()
            },
            SeedContainer {
                container_type: "analytics".into(),
                title: "Analytics".into(),
                x: 710.0,
                y: 7890.0,
                width: 660.0,
                height: 280.0,
                z: 1.0,
                honesty: "present".into(),
                ..Default::default()
            },
            SeedContainer {
                container_type: "events".into(),
                title: "Events".into(),
                x: 30.0,
                y: 8210.0,
                width: 660.0,
                height: 280.0,
                z: 1.0,
                honesty: "present".into(),
                ..Default::default()
            },
            SeedContainer {
                container_type: "news".into(),
                title: "News".into(),
                x: 710.0,
                y: 8210.0,
                width: 660.0,
                height: 280.0,
                z: 1.0,
                honesty: "present".into(),
                ..Default::default()
            },
            SeedContainer {
                container_type: "portfolio".into(),
                title: "Portfolio".into(),
                x: 30.0,
                y: 8510.0,
                width: 1340.0,
                height: 260.0,
                z: 1.0,
                honesty: "present".into(),
                ..Default::default()
            },
            SeedContainer {
                container_type: "integrations".into(),
                title: "Integrations".into(),
                x: 30.0,
                y: 8810.0,
                width: 660.0,
                height: 260.0,
                z: 1.0,
                honesty: "present".into(),
                ..Default::default()
            },
            SeedContainer {
                container_type: "retrospective".into(),
                title: "Retrospective".into(),
                x: 710.0,
                y: 8810.0,
                width: 660.0,
                height: 260.0,
                z: 1.0,
                honesty: "present".into(),
                ..Default::default()
            },
            SeedContainer {
                container_type: "participants".into(),
                title: "People on this project".into(),
                x: 30.0,
                y: 9110.0,
                width: 660.0,
                height: 240.0,
                z: 1.0,
                honesty: "live".into(),
                ..Default::default()
            },
            SeedContainer {
                container_type: "presence".into(),
                title: "Who is here".into(),
                x: 710.0,
                y: 9110.0,
                width: 660.0,
                height: 240.0,
                z: 1.0,
                honesty: "live".into(),
                ..Default::default()
            },
        ],
        connections: vec![
            SeedConnection {
                id: "wire-p1".into(),
                from: 0,
                to: 1,
                wire_type: "active".into(),
                label: "coop:hasWorkItems".into(),
            },
            SeedConnection {
                id: "wire-p2".into(),
                from: 0,
                to: 2,
                wire_type: "active".into(),
                label: "coop:hasGraph".into(),
            },
            SeedConnection {
                id: "wire-p3".into(),
                from: 0,
                to: 3,
                wire_type: "active".into(),
                label: "coop:hasBudget".into(),
            },
            SeedConnection {
                id: "wire-p4".into(),
                from: 3,
                to: 4,
                wire_type: "active".into(),
                label: "coop:hasCostBase".into(),
            },
            SeedConnection {
                id: "wire-p5".into(),
                from: 1,
                to: 5,
                wire_type: "active".into(),
                label: "coop:hasDeliverables".into(),
            },
            SeedConnection {
                id: "wire-p6".into(),
                from: 5,
                to: 6,
                wire_type: "active".into(),
                label: "coop:hasReviews".into(),
            },
            SeedConnection {
                id: "wire-p7".into(),
                from: 0,
                to: 8,
                wire_type: "active".into(),
                label: "coop:hasRoadmap".into(),
            },
            SeedConnection {
                id: "wire-p8".into(),
                from: 4,
                to: 9,
                wire_type: "active".into(),
                label: "coop:publishesTo".into(),
            },
            SeedConnection {
                id: "wire-p9".into(),
                from: 1,
                to: 10,
                wire_type: "event".into(),
                label: "coop:emitsPulse".into(),
            },
            SeedConnection {
                id: "wire-p10".into(),
                from: 0,
                to: 11,
                wire_type: "active".into(),
                label: "coop:hasAgreement".into(),
            },
            SeedConnection {
                id: "wire-p11".into(),
                from: 11,
                to: 12,
                wire_type: "active".into(),
                label: "coop:hasCompensationModel".into(),
            },
            SeedConnection {
                id: "wire-p12".into(),
                from: 12,
                to: 13,
                wire_type: "active".into(),
                label: "coop:hasContributionLedger".into(),
            },
            SeedConnection {
                id: "wire-p13".into(),
                from: 11,
                to: 14,
                wire_type: "active".into(),
                label: "coop:hasLicense".into(),
            },
            SeedConnection {
                id: "wire-p14".into(),
                from: 14,
                to: 15,
                wire_type: "active".into(),
                label: "coop:tracksObligation".into(),
            },
            SeedConnection {
                id: "wire-p15".into(),
                from: 13,
                to: 15,
                wire_type: "active".into(),
                label: "coop:contributesToObligation".into(),
            },
            SeedConnection {
                id: "wire-p16".into(),
                from: 0,
                to: 16,
                wire_type: "active".into(),
                label: "coop:hasIP".into(),
            },
            SeedConnection {
                id: "wire-p17".into(),
                from: 12,
                to: 17,
                wire_type: "active".into(),
                label: "coop:usesDataSource".into(),
            },
            SeedConnection {
                id: "wire-p18".into(),
                from: 0,
                to: 18,
                wire_type: "active".into(),
                label: "coop:hasDisputes".into(),
            },
            SeedConnection {
                id: "wire-p19".into(),
                from: 18,
                to: 19,
                wire_type: "active".into(),
                label: "coop:disputeToComplaint".into(),
            },
            SeedConnection {
                id: "wire-p20".into(),
                from: 18,
                to: 20,
                wire_type: "active".into(),
                label: "coop:disputeToCorrection".into(),
            },
            SeedConnection {
                id: "wire-p21".into(),
                from: 0,
                to: 21,
                wire_type: "active".into(),
                label: "coop:hasMeetings".into(),
            },
            SeedConnection {
                id: "wire-p22".into(),
                from: 21,
                to: 22,
                wire_type: "active".into(),
                label: "coop:hasCOI".into(),
            },
            SeedConnection {
                id: "wire-p23".into(),
                from: 0,
                to: 23,
                wire_type: "active".into(),
                label: "coop:hasOnboarding".into(),
            },
            SeedConnection {
                id: "wire-p24".into(),
                from: 23,
                to: 24,
                wire_type: "active".into(),
                label: "coop:hasBulkImport".into(),
            },
            SeedConnection {
                id: "wire-p25".into(),
                from: 0,
                to: 25,
                wire_type: "active".into(),
                label: "coop:hasKnowledgeBase".into(),
            },
            SeedConnection {
                id: "wire-p26".into(),
                from: 25,
                to: 26,
                wire_type: "active".into(),
                label: "coop:hasAgentConsole".into(),
            },
            SeedConnection {
                id: "wire-p27".into(),
                from: 0,
                to: 29,
                wire_type: "active".into(),
                label: "coop:hasDashboard".into(),
            },
            SeedConnection {
                id: "wire-p28".into(),
                from: 0,
                to: 30,
                wire_type: "active".into(),
                label: "coop:hasWiki".into(),
            },
            SeedConnection {
                id: "wire-p29".into(),
                from: 0,
                to: 31,
                wire_type: "active".into(),
                label: "coop:hasGovernance".into(),
            },
            SeedConnection {
                id: "wire-p30".into(),
                from: 31,
                to: 32,
                wire_type: "active".into(),
                label: "coop:hasCredentials".into(),
            },
            SeedConnection {
                id: "wire-p31".into(),
                from: 31,
                to: 33,
                wire_type: "active".into(),
                label: "coop:hasTokens".into(),
            },
            SeedConnection {
                id: "wire-p32".into(),
                from: 33,
                to: 34,
                wire_type: "active".into(),
                label: "coop:hasAwards".into(),
            },
            SeedConnection {
                id: "wire-p33".into(),
                from: 0,
                to: 35,
                wire_type: "active".into(),
                label: "coop:hasGantt".into(),
            },
            SeedConnection {
                id: "wire-p34".into(),
                from: 35,
                to: 36,
                wire_type: "active".into(),
                label: "coop:hasTimeline".into(),
            },
            SeedConnection {
                id: "wire-p35".into(),
                from: 36,
                to: 37,
                wire_type: "active".into(),
                label: "coop:hasCalendar".into(),
            },
            SeedConnection {
                id: "wire-p36".into(),
                from: 0,
                to: 38,
                wire_type: "active".into(),
                label: "coop:hasDocMgmt".into(),
            },
            SeedConnection {
                id: "wire-p37".into(),
                from: 0,
                to: 39,
                wire_type: "active".into(),
                label: "coop:hasResourceReport".into(),
            },
            SeedConnection {
                id: "wire-p38".into(),
                from: 39,
                to: 40,
                wire_type: "active".into(),
                label: "coop:hasTimeTracking".into(),
            },
            SeedConnection {
                id: "wire-p39".into(),
                from: 31,
                to: 41,
                wire_type: "active".into(),
                label: "coop:hasVoting".into(),
            },
            SeedConnection {
                id: "wire-p40".into(),
                from: 0,
                to: 42,
                wire_type: "active".into(),
                label: "coop:hasRiskRegister".into(),
            },
            SeedConnection {
                id: "wire-p41".into(),
                from: 1,
                to: 43,
                wire_type: "active".into(),
                label: "coop:hasTaskList".into(),
            },
            SeedConnection {
                id: "wire-p42".into(),
                from: 43,
                to: 44,
                wire_type: "active".into(),
                label: "coop:hasIssues".into(),
            },
            SeedConnection {
                id: "wire-p43".into(),
                from: 0,
                to: 45,
                wire_type: "active".into(),
                label: "coop:hasAssetMgr".into(),
            },
            SeedConnection {
                id: "wire-p44".into(),
                from: 33,
                to: 46,
                wire_type: "active".into(),
                label: "coop:hasBounties".into(),
            },
            SeedConnection {
                id: "wire-p45".into(),
                from: 0,
                to: 47,
                wire_type: "active".into(),
                label: "coop:hasAutomation".into(),
            },
            SeedConnection {
                id: "wire-p46".into(),
                from: 29,
                to: 48,
                wire_type: "active".into(),
                label: "coop:hasAnalytics".into(),
            },
            SeedConnection {
                id: "wire-p47".into(),
                from: 37,
                to: 49,
                wire_type: "active".into(),
                label: "coop:hasEvents".into(),
            },
            SeedConnection {
                id: "wire-p48".into(),
                from: 49,
                to: 50,
                wire_type: "active".into(),
                label: "coop:hasNews".into(),
            },
            SeedConnection {
                id: "wire-p49".into(),
                from: 0,
                to: 51,
                wire_type: "active".into(),
                label: "coop:hasPortfolio".into(),
            },
            SeedConnection {
                id: "wire-p50".into(),
                from: 0,
                to: 52,
                wire_type: "active".into(),
                label: "coop:hasIntegrations".into(),
            },
            SeedConnection {
                id: "wire-p51".into(),
                from: 48,
                to: 53,
                wire_type: "active".into(),
                label: "coop:hasRetrospective".into(),
            },
        ],
        panels: vec![SeedPanel {
            panel_type: "aura".into(),
            dock: DockPosition::Right,
        }],
        sociality: ManifoldSociality::Social,
        ..Default::default()
    }
}
