// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/chat_session.dart';
import 'api/qapp_api.dart';
import 'api/qualia_api.dart';
import 'api/resource_catalog.dart';
import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustApiApiImplPlatform extends BaseApiImpl<RustApiWire> {
  RustApiApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
      get rust_arc_decrement_strong_count_QappManifestPtr => wire
          ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQappManifestPtr;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  QappManifest
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQappManifest(
          dynamic raw);

  @protected
  QappManifest
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQappManifest(
          dynamic raw);

  @protected
  RustStreamSink<String> dco_decode_StreamSink_String_Sse(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  ActorBridge dco_decode_actor_bridge(dynamic raw);

  @protected
  AgentConfig dco_decode_agent_config(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  ActorBridge dco_decode_box_autoadd_actor_bridge(dynamic raw);

  @protected
  AgentConfig dco_decode_box_autoadd_agent_config(dynamic raw);

  @protected
  DelegationRuleBridge dco_decode_box_autoadd_delegation_rule_bridge(
      dynamic raw);

  @protected
  QpuOracleSettingsInput dco_decode_box_autoadd_qpu_oracle_settings_input(
      dynamic raw);

  @protected
  TaxRecipientSuite dco_decode_box_autoadd_tax_recipient_suite(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  CatalogItem dco_decode_catalog_item(dynamic raw);

  @protected
  ChatMessage dco_decode_chat_message(dynamic raw);

  @protected
  ChatSessionSummary dco_decode_chat_session_summary(dynamic raw);

  @protected
  CoinBalance dco_decode_coin_balance(dynamic raw);

  @protected
  DelegationRuleBridge dco_decode_delegation_rule_bridge(dynamic raw);

  @protected
  DispatchResult dco_decode_dispatch_result(dynamic raw);

  @protected
  double dco_decode_f_32(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  FrontDoorBridge dco_decode_front_door_bridge(dynamic raw);

  @protected
  HardwareStatus dco_decode_hardware_status(dynamic raw);

  @protected
  HardwareTelemetry dco_decode_hardware_telemetry(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<ActorBridge> dco_decode_list_actor_bridge(dynamic raw);

  @protected
  List<CatalogItem> dco_decode_list_catalog_item(dynamic raw);

  @protected
  List<ChatMessage> dco_decode_list_chat_message(dynamic raw);

  @protected
  List<ChatSessionSummary> dco_decode_list_chat_session_summary(dynamic raw);

  @protected
  List<CoinBalance> dco_decode_list_coin_balance(dynamic raw);

  @protected
  List<DelegationRuleBridge> dco_decode_list_delegation_rule_bridge(
      dynamic raw);

  @protected
  List<FrontDoorBridge> dco_decode_list_front_door_bridge(dynamic raw);

  @protected
  List<LLMResource> dco_decode_list_llm_resource(dynamic raw);

  @protected
  List<ModelInfo> dco_decode_list_model_info(dynamic raw);

  @protected
  List<OntologyResource> dco_decode_list_ontology_resource(dynamic raw);

  @protected
  Float32List dco_decode_list_prim_f_32_strict(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<ProgressPayload> dco_decode_list_progress_payload(dynamic raw);

  @protected
  List<TaxRecipient> dco_decode_list_tax_recipient(dynamic raw);

  @protected
  List<TokenEntry> dco_decode_list_token_entry(dynamic raw);

  @protected
  List<TxRecord> dco_decode_list_tx_record(dynamic raw);

  @protected
  LLMResource dco_decode_llm_resource(dynamic raw);

  @protected
  ModelInfo dco_decode_model_info(dynamic raw);

  @protected
  OntologyResource dco_decode_ontology_resource(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  List<String>? dco_decode_opt_list_String(dynamic raw);

  @protected
  PrerequisiteStatus dco_decode_prerequisite_status(dynamic raw);

  @protected
  ProgressPayload dco_decode_progress_payload(dynamic raw);

  @protected
  QpuChatCommandResult dco_decode_qpu_chat_command_result(dynamic raw);

  @protected
  QpuOracleSettings dco_decode_qpu_oracle_settings(dynamic raw);

  @protected
  QpuOracleSettingsInput dco_decode_qpu_oracle_settings_input(dynamic raw);

  @protected
  SpatialPhysicsState dco_decode_spatial_physics_state(dynamic raw);

  @protected
  TaxRecipient dco_decode_tax_recipient(dynamic raw);

  @protected
  TaxRecipientSuite dco_decode_tax_recipient_suite(dynamic raw);

  @protected
  TokenEntry dco_decode_token_entry(dynamic raw);

  @protected
  TxRecord dco_decode_tx_record(dynamic raw);

  @protected
  int dco_decode_u_16(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  WalletStatus dco_decode_wallet_status(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  QappManifest
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQappManifest(
          SseDeserializer deserializer);

  @protected
  QappManifest
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQappManifest(
          SseDeserializer deserializer);

  @protected
  RustStreamSink<String> sse_decode_StreamSink_String_Sse(
      SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  ActorBridge sse_decode_actor_bridge(SseDeserializer deserializer);

  @protected
  AgentConfig sse_decode_agent_config(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  ActorBridge sse_decode_box_autoadd_actor_bridge(SseDeserializer deserializer);

  @protected
  AgentConfig sse_decode_box_autoadd_agent_config(SseDeserializer deserializer);

  @protected
  DelegationRuleBridge sse_decode_box_autoadd_delegation_rule_bridge(
      SseDeserializer deserializer);

  @protected
  QpuOracleSettingsInput sse_decode_box_autoadd_qpu_oracle_settings_input(
      SseDeserializer deserializer);

  @protected
  TaxRecipientSuite sse_decode_box_autoadd_tax_recipient_suite(
      SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  CatalogItem sse_decode_catalog_item(SseDeserializer deserializer);

  @protected
  ChatMessage sse_decode_chat_message(SseDeserializer deserializer);

  @protected
  ChatSessionSummary sse_decode_chat_session_summary(
      SseDeserializer deserializer);

  @protected
  CoinBalance sse_decode_coin_balance(SseDeserializer deserializer);

  @protected
  DelegationRuleBridge sse_decode_delegation_rule_bridge(
      SseDeserializer deserializer);

  @protected
  DispatchResult sse_decode_dispatch_result(SseDeserializer deserializer);

  @protected
  double sse_decode_f_32(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  FrontDoorBridge sse_decode_front_door_bridge(SseDeserializer deserializer);

  @protected
  HardwareStatus sse_decode_hardware_status(SseDeserializer deserializer);

  @protected
  HardwareTelemetry sse_decode_hardware_telemetry(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<ActorBridge> sse_decode_list_actor_bridge(SseDeserializer deserializer);

  @protected
  List<CatalogItem> sse_decode_list_catalog_item(SseDeserializer deserializer);

  @protected
  List<ChatMessage> sse_decode_list_chat_message(SseDeserializer deserializer);

  @protected
  List<ChatSessionSummary> sse_decode_list_chat_session_summary(
      SseDeserializer deserializer);

  @protected
  List<CoinBalance> sse_decode_list_coin_balance(SseDeserializer deserializer);

  @protected
  List<DelegationRuleBridge> sse_decode_list_delegation_rule_bridge(
      SseDeserializer deserializer);

  @protected
  List<FrontDoorBridge> sse_decode_list_front_door_bridge(
      SseDeserializer deserializer);

  @protected
  List<LLMResource> sse_decode_list_llm_resource(SseDeserializer deserializer);

  @protected
  List<ModelInfo> sse_decode_list_model_info(SseDeserializer deserializer);

  @protected
  List<OntologyResource> sse_decode_list_ontology_resource(
      SseDeserializer deserializer);

  @protected
  Float32List sse_decode_list_prim_f_32_strict(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<ProgressPayload> sse_decode_list_progress_payload(
      SseDeserializer deserializer);

  @protected
  List<TaxRecipient> sse_decode_list_tax_recipient(
      SseDeserializer deserializer);

  @protected
  List<TokenEntry> sse_decode_list_token_entry(SseDeserializer deserializer);

  @protected
  List<TxRecord> sse_decode_list_tx_record(SseDeserializer deserializer);

  @protected
  LLMResource sse_decode_llm_resource(SseDeserializer deserializer);

  @protected
  ModelInfo sse_decode_model_info(SseDeserializer deserializer);

  @protected
  OntologyResource sse_decode_ontology_resource(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  List<String>? sse_decode_opt_list_String(SseDeserializer deserializer);

  @protected
  PrerequisiteStatus sse_decode_prerequisite_status(
      SseDeserializer deserializer);

  @protected
  ProgressPayload sse_decode_progress_payload(SseDeserializer deserializer);

  @protected
  QpuChatCommandResult sse_decode_qpu_chat_command_result(
      SseDeserializer deserializer);

  @protected
  QpuOracleSettings sse_decode_qpu_oracle_settings(
      SseDeserializer deserializer);

  @protected
  QpuOracleSettingsInput sse_decode_qpu_oracle_settings_input(
      SseDeserializer deserializer);

  @protected
  SpatialPhysicsState sse_decode_spatial_physics_state(
      SseDeserializer deserializer);

  @protected
  TaxRecipient sse_decode_tax_recipient(SseDeserializer deserializer);

  @protected
  TaxRecipientSuite sse_decode_tax_recipient_suite(
      SseDeserializer deserializer);

  @protected
  TokenEntry sse_decode_token_entry(SseDeserializer deserializer);

  @protected
  TxRecord sse_decode_tx_record(SseDeserializer deserializer);

  @protected
  int sse_decode_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  WalletStatus sse_decode_wallet_status(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
      AnyhowException self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQappManifest(
          QappManifest self, SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQappManifest(
          QappManifest self, SseSerializer serializer);

  @protected
  void sse_encode_StreamSink_String_Sse(
      RustStreamSink<String> self, SseSerializer serializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_actor_bridge(ActorBridge self, SseSerializer serializer);

  @protected
  void sse_encode_agent_config(AgentConfig self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_actor_bridge(
      ActorBridge self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_agent_config(
      AgentConfig self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_delegation_rule_bridge(
      DelegationRuleBridge self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_qpu_oracle_settings_input(
      QpuOracleSettingsInput self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_tax_recipient_suite(
      TaxRecipientSuite self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_catalog_item(CatalogItem self, SseSerializer serializer);

  @protected
  void sse_encode_chat_message(ChatMessage self, SseSerializer serializer);

  @protected
  void sse_encode_chat_session_summary(
      ChatSessionSummary self, SseSerializer serializer);

  @protected
  void sse_encode_coin_balance(CoinBalance self, SseSerializer serializer);

  @protected
  void sse_encode_delegation_rule_bridge(
      DelegationRuleBridge self, SseSerializer serializer);

  @protected
  void sse_encode_dispatch_result(
      DispatchResult self, SseSerializer serializer);

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_front_door_bridge(
      FrontDoorBridge self, SseSerializer serializer);

  @protected
  void sse_encode_hardware_status(
      HardwareStatus self, SseSerializer serializer);

  @protected
  void sse_encode_hardware_telemetry(
      HardwareTelemetry self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_actor_bridge(
      List<ActorBridge> self, SseSerializer serializer);

  @protected
  void sse_encode_list_catalog_item(
      List<CatalogItem> self, SseSerializer serializer);

  @protected
  void sse_encode_list_chat_message(
      List<ChatMessage> self, SseSerializer serializer);

  @protected
  void sse_encode_list_chat_session_summary(
      List<ChatSessionSummary> self, SseSerializer serializer);

  @protected
  void sse_encode_list_coin_balance(
      List<CoinBalance> self, SseSerializer serializer);

  @protected
  void sse_encode_list_delegation_rule_bridge(
      List<DelegationRuleBridge> self, SseSerializer serializer);

  @protected
  void sse_encode_list_front_door_bridge(
      List<FrontDoorBridge> self, SseSerializer serializer);

  @protected
  void sse_encode_list_llm_resource(
      List<LLMResource> self, SseSerializer serializer);

  @protected
  void sse_encode_list_model_info(
      List<ModelInfo> self, SseSerializer serializer);

  @protected
  void sse_encode_list_ontology_resource(
      List<OntologyResource> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_f_32_strict(
      Float32List self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer);

  @protected
  void sse_encode_list_progress_payload(
      List<ProgressPayload> self, SseSerializer serializer);

  @protected
  void sse_encode_list_tax_recipient(
      List<TaxRecipient> self, SseSerializer serializer);

  @protected
  void sse_encode_list_token_entry(
      List<TokenEntry> self, SseSerializer serializer);

  @protected
  void sse_encode_list_tx_record(List<TxRecord> self, SseSerializer serializer);

  @protected
  void sse_encode_llm_resource(LLMResource self, SseSerializer serializer);

  @protected
  void sse_encode_model_info(ModelInfo self, SseSerializer serializer);

  @protected
  void sse_encode_ontology_resource(
      OntologyResource self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_String(List<String>? self, SseSerializer serializer);

  @protected
  void sse_encode_prerequisite_status(
      PrerequisiteStatus self, SseSerializer serializer);

  @protected
  void sse_encode_progress_payload(
      ProgressPayload self, SseSerializer serializer);

  @protected
  void sse_encode_qpu_chat_command_result(
      QpuChatCommandResult self, SseSerializer serializer);

  @protected
  void sse_encode_qpu_oracle_settings(
      QpuOracleSettings self, SseSerializer serializer);

  @protected
  void sse_encode_qpu_oracle_settings_input(
      QpuOracleSettingsInput self, SseSerializer serializer);

  @protected
  void sse_encode_spatial_physics_state(
      SpatialPhysicsState self, SseSerializer serializer);

  @protected
  void sse_encode_tax_recipient(TaxRecipient self, SseSerializer serializer);

  @protected
  void sse_encode_tax_recipient_suite(
      TaxRecipientSuite self, SseSerializer serializer);

  @protected
  void sse_encode_token_entry(TokenEntry self, SseSerializer serializer);

  @protected
  void sse_encode_tx_record(TxRecord self, SseSerializer serializer);

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_wallet_status(WalletStatus self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);
}

// Section: wire_class

class RustApiWire implements BaseWire {
  factory RustApiWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustApiWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustApiWire(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQappManifest(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQappManifest(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQappManifestPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_qualia_flutter_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQappManifest');
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQappManifest =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQappManifestPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQappManifest(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQappManifest(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQappManifestPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_qualia_flutter_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQappManifest');
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQappManifest =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerQappManifestPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();
}
