// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/qualia_api.dart';
import 'api/resource_catalog.dart';
import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustApi extends BaseEntrypoint<RustApiApi, RustApiApiImpl, RustApiWire> {
  @internal
  static final instance = RustApi._();

  RustApi._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustApiApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({
    required RustApiApi api,
  }) {
    instance.initMockImpl(
      api: api,
    );
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustApiApiImpl, RustApiWire> get apiImplConstructor =>
      RustApiApiImpl.new;

  @override
  WireConstructor<RustApiWire> get wireConstructor =>
      RustApiWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => 581647352;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
    stem: 'qualia_flutter_rust',
    ioDirectory: 'rust/target/release/',
    webPrefix: 'pkg/',
    wasmBindgenName: 'wasm_bindgen',
  );
}

abstract class RustApiApi extends BaseApi {
  Future<void> crateApiQualiaApiCancelDownload({required String id});

  Future<bool> crateApiQualiaApiCheckOllamaStatus();

  Future<String> crateApiQualiaApiDaemonStatus();

  Future<String> crateApiQualiaApiDeriveWalletsFromSeed({required String seed});

  Future<List<ModelInfo>> crateApiQualiaApiDiscoverModels();

  Future<String> crateApiResourceCatalogDownloadLlm({required String id});

  Future<String> crateApiQualiaApiDownloadModel(
      {required String url, required String filename, required String modelId});

  Future<List<CatalogItem>> crateApiQualiaApiFetchModelCatalog();

  Future<List<CatalogItem>> crateApiQualiaApiFetchModelCatalogReal();

  Future<List<CatalogItem>> crateApiQualiaApiFetchOntologyCatalog();

  Future<List<CatalogItem>> crateApiQualiaApiFetchOntologyCatalogReal();

  Future<String> crateApiQualiaApiGenerateAppCredential(
      {required String appName});

  Future<String> crateApiQualiaApiGenerateBip39Seed();

  Future<List<ProgressPayload>> crateApiQualiaApiGetActiveDownloads();

  Future<String?> crateApiQualiaApiGetActiveModel();

  Future<List<CoinBalance>> crateApiQualiaApiGetCoinBalances();

  Future<AgentConfig> crateApiQualiaApiGetConfig();

  Future<HardwareStatus> crateApiQualiaApiGetHardwareStatus();

  Future<SpatialPhysicsState> crateApiQualiaApiGetPhysicsState();

  Future<double> crateApiQualiaApiGetPhysicsStatePressure();

  Future<double> crateApiQualiaApiGetPhysicsStateTemperature();

  Future<double> crateApiQualiaApiGetPhysicsStateTimeDilation();

  Future<double> crateApiQualiaApiGetSpatialPressure();

  Future<double> crateApiQualiaApiGetSpatialTemperature();

  Future<double> crateApiQualiaApiGetSpatialTimeDilation();

  Future<TaxRecipientSuite> crateApiQualiaApiGetTaxSuite();

  Future<String> crateApiQualiaApiGreet({required String name});

  String crateApiSimpleGreet({required String name});

  Future<String> crateApiQualiaApiImportExternalSeed(
      {required String network, required String seed, required String label});

  Future<String> crateApiResourceCatalogImportOntology({required String id});

  Future<String> crateApiQualiaApiIngestLiterature({required String filePath});

  Future<void> crateApiSimpleInitApp();

  Future<void> crateApiQualiaApiInitCore();

  Future<String> crateApiQualiaApiLaunchInstalledApp({required String appName});

  Future<List<String>> crateApiQualiaApiListInstalledApps();

  Future<String?> crateApiQualiaApiLoadIdentity();

  Future<String> crateApiQualiaApiLoadImportedAccounts();

  Future<List<LLMResource>> crateApiResourceCatalogLoadLlmResources();

  Future<List<OntologyResource>> crateApiResourceCatalogLoadOntologyResources();

  Future<void> crateApiQualiaApiSaveConfig({required AgentConfig newConfig});

  Future<void> crateApiQualiaApiSaveIdentity({required String walletsJson});

  Future<void> crateApiQualiaApiSaveImportedAccounts(
      {required String accountsJson});

  Future<void> crateApiQualiaApiSetActiveModel({required String modelName});

  Future<String> crateApiQualiaApiStartDaemon();

  Future<void> crateApiQualiaApiUpdatePhysicsState(
      {required double temperature,
      required double pressure,
      required double timeDilation});

  Future<String> crateApiQualiaApiUpsertCmldDefinition(
      {required String term, required String contextDid});

  Future<String> crateApiQualiaApiVerifyAndInstallApp(
      {required String zipPath, required String credentialSig});
}

class RustApiApiImpl extends RustApiApiImplPlatform implements RustApiApi {
  RustApiApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<void> crateApiQualiaApiCancelDownload({required String id}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(id, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 1, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiQualiaApiCancelDownloadConstMeta,
      argValues: [id],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiQualiaApiCancelDownloadConstMeta =>
      const TaskConstMeta(
        debugName: "cancel_download",
        argNames: ["id"],
      );

  @override
  Future<bool> crateApiQualiaApiCheckOllamaStatus() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 2, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_bool,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiQualiaApiCheckOllamaStatusConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiQualiaApiCheckOllamaStatusConstMeta =>
      const TaskConstMeta(
        debugName: "check_ollama_status",
        argNames: [],
      );

  @override
  Future<String> crateApiQualiaApiDaemonStatus() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 3, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiQualiaApiDaemonStatusConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiQualiaApiDaemonStatusConstMeta =>
      const TaskConstMeta(
        debugName: "daemon_status",
        argNames: [],
      );

  @override
  Future<String> crateApiQualiaApiDeriveWalletsFromSeed(
      {required String seed}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(seed, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 4, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiQualiaApiDeriveWalletsFromSeedConstMeta,
      argValues: [seed],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiQualiaApiDeriveWalletsFromSeedConstMeta =>
      const TaskConstMeta(
        debugName: "derive_wallets_from_seed",
        argNames: ["seed"],
      );

  @override
  Future<List<ModelInfo>> crateApiQualiaApiDiscoverModels() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 5, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_model_info,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiQualiaApiDiscoverModelsConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiQualiaApiDiscoverModelsConstMeta =>
      const TaskConstMeta(
        debugName: "discover_models",
        argNames: [],
      );

  @override
  Future<String> crateApiResourceCatalogDownloadLlm({required String id}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(id, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 6, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiResourceCatalogDownloadLlmConstMeta,
      argValues: [id],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiResourceCatalogDownloadLlmConstMeta =>
      const TaskConstMeta(
        debugName: "download_llm",
        argNames: ["id"],
      );

  @override
  Future<String> crateApiQualiaApiDownloadModel(
      {required String url,
      required String filename,
      required String modelId}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(url, serializer);
        sse_encode_String(filename, serializer);
        sse_encode_String(modelId, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 7, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiQualiaApiDownloadModelConstMeta,
      argValues: [url, filename, modelId],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiQualiaApiDownloadModelConstMeta =>
      const TaskConstMeta(
        debugName: "download_model",
        argNames: ["url", "filename", "modelId"],
      );

  @override
  Future<List<CatalogItem>> crateApiQualiaApiFetchModelCatalog() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 8, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_catalog_item,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiQualiaApiFetchModelCatalogConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiQualiaApiFetchModelCatalogConstMeta =>
      const TaskConstMeta(
        debugName: "fetch_model_catalog",
        argNames: [],
      );

  @override
  Future<List<CatalogItem>> crateApiQualiaApiFetchModelCatalogReal() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 9, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_catalog_item,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiQualiaApiFetchModelCatalogRealConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiQualiaApiFetchModelCatalogRealConstMeta =>
      const TaskConstMeta(
        debugName: "fetch_model_catalog_real",
        argNames: [],
      );

  @override
  Future<List<CatalogItem>> crateApiQualiaApiFetchOntologyCatalog() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 10, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_catalog_item,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiQualiaApiFetchOntologyCatalogConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiQualiaApiFetchOntologyCatalogConstMeta =>
      const TaskConstMeta(
        debugName: "fetch_ontology_catalog",
        argNames: [],
      );

  @override
  Future<List<CatalogItem>> crateApiQualiaApiFetchOntologyCatalogReal() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 11, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_catalog_item,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiQualiaApiFetchOntologyCatalogRealConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiQualiaApiFetchOntologyCatalogRealConstMeta =>
      const TaskConstMeta(
        debugName: "fetch_ontology_catalog_real",
        argNames: [],
      );

  @override
  Future<String> crateApiQualiaApiGenerateAppCredential(
      {required String appName}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(appName, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 12, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiQualiaApiGenerateAppCredentialConstMeta,
      argValues: [appName],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiQualiaApiGenerateAppCredentialConstMeta =>
      const TaskConstMeta(
        debugName: "generate_app_credential",
        argNames: ["appName"],
      );

  @override
  Future<String> crateApiQualiaApiGenerateBip39Seed() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 13, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiQualiaApiGenerateBip39SeedConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiQualiaApiGenerateBip39SeedConstMeta =>
      const TaskConstMeta(
        debugName: "generate_bip39_seed",
        argNames: [],
      );

  @override
  Future<List<ProgressPayload>> crateApiQualiaApiGetActiveDownloads() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 14, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_progress_payload,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiQualiaApiGetActiveDownloadsConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiQualiaApiGetActiveDownloadsConstMeta =>
      const TaskConstMeta(
        debugName: "get_active_downloads",
        argNames: [],
      );

  @override
  Future<String?> crateApiQualiaApiGetActiveModel() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 15, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_opt_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiQualiaApiGetActiveModelConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiQualiaApiGetActiveModelConstMeta =>
      const TaskConstMeta(
        debugName: "get_active_model",
        argNames: [],
      );

  @override
  Future<List<CoinBalance>> crateApiQualiaApiGetCoinBalances() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 16, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_coin_balance,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiQualiaApiGetCoinBalancesConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiQualiaApiGetCoinBalancesConstMeta =>
      const TaskConstMeta(
        debugName: "get_coin_balances",
        argNames: [],
      );

  @override
  Future<AgentConfig> crateApiQualiaApiGetConfig() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 17, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_agent_config,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiQualiaApiGetConfigConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiQualiaApiGetConfigConstMeta => const TaskConstMeta(
        debugName: "get_config",
        argNames: [],
      );

  @override
  Future<HardwareStatus> crateApiQualiaApiGetHardwareStatus() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 18, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_hardware_status,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiQualiaApiGetHardwareStatusConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiQualiaApiGetHardwareStatusConstMeta =>
      const TaskConstMeta(
        debugName: "get_hardware_status",
        argNames: [],
      );

  @override
  Future<SpatialPhysicsState> crateApiQualiaApiGetPhysicsState() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 19, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_spatial_physics_state,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiQualiaApiGetPhysicsStateConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiQualiaApiGetPhysicsStateConstMeta =>
      const TaskConstMeta(
        debugName: "get_physics_state",
        argNames: [],
      );

  @override
  Future<double> crateApiQualiaApiGetPhysicsStatePressure() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 20, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_f_64,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiQualiaApiGetPhysicsStatePressureConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiQualiaApiGetPhysicsStatePressureConstMeta =>
      const TaskConstMeta(
        debugName: "get_physics_state_pressure",
        argNames: [],
      );

  @override
  Future<double> crateApiQualiaApiGetPhysicsStateTemperature() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 21, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_f_64,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiQualiaApiGetPhysicsStateTemperatureConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiQualiaApiGetPhysicsStateTemperatureConstMeta =>
      const TaskConstMeta(
        debugName: "get_physics_state_temperature",
        argNames: [],
      );

  @override
  Future<double> crateApiQualiaApiGetPhysicsStateTimeDilation() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 22, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_f_64,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiQualiaApiGetPhysicsStateTimeDilationConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiQualiaApiGetPhysicsStateTimeDilationConstMeta =>
      const TaskConstMeta(
        debugName: "get_physics_state_time_dilation",
        argNames: [],
      );

  @override
  Future<double> crateApiQualiaApiGetSpatialPressure() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 23, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_f_64,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiQualiaApiGetSpatialPressureConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiQualiaApiGetSpatialPressureConstMeta =>
      const TaskConstMeta(
        debugName: "get_spatial_pressure",
        argNames: [],
      );

  @override
  Future<double> crateApiQualiaApiGetSpatialTemperature() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 24, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_f_64,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiQualiaApiGetSpatialTemperatureConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiQualiaApiGetSpatialTemperatureConstMeta =>
      const TaskConstMeta(
        debugName: "get_spatial_temperature",
        argNames: [],
      );

  @override
  Future<double> crateApiQualiaApiGetSpatialTimeDilation() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 25, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_f_64,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiQualiaApiGetSpatialTimeDilationConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiQualiaApiGetSpatialTimeDilationConstMeta =>
      const TaskConstMeta(
        debugName: "get_spatial_time_dilation",
        argNames: [],
      );

  @override
  Future<TaxRecipientSuite> crateApiQualiaApiGetTaxSuite() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 26, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_tax_recipient_suite,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiQualiaApiGetTaxSuiteConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiQualiaApiGetTaxSuiteConstMeta =>
      const TaskConstMeta(
        debugName: "get_tax_suite",
        argNames: [],
      );

  @override
  Future<String> crateApiQualiaApiGreet({required String name}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(name, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 27, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiQualiaApiGreetConstMeta,
      argValues: [name],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiQualiaApiGreetConstMeta => const TaskConstMeta(
        debugName: "greet",
        argNames: ["name"],
      );

  @override
  String crateApiSimpleGreet({required String name}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(name, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 28)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiSimpleGreetConstMeta,
      argValues: [name],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSimpleGreetConstMeta => const TaskConstMeta(
        debugName: "greet",
        argNames: ["name"],
      );

  @override
  Future<String> crateApiQualiaApiImportExternalSeed(
      {required String network, required String seed, required String label}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(network, serializer);
        sse_encode_String(seed, serializer);
        sse_encode_String(label, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 29, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiQualiaApiImportExternalSeedConstMeta,
      argValues: [network, seed, label],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiQualiaApiImportExternalSeedConstMeta =>
      const TaskConstMeta(
        debugName: "import_external_seed",
        argNames: ["network", "seed", "label"],
      );

  @override
  Future<String> crateApiResourceCatalogImportOntology({required String id}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(id, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 30, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiResourceCatalogImportOntologyConstMeta,
      argValues: [id],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiResourceCatalogImportOntologyConstMeta =>
      const TaskConstMeta(
        debugName: "import_ontology",
        argNames: ["id"],
      );

  @override
  Future<String> crateApiQualiaApiIngestLiterature({required String filePath}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(filePath, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 31, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiQualiaApiIngestLiteratureConstMeta,
      argValues: [filePath],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiQualiaApiIngestLiteratureConstMeta =>
      const TaskConstMeta(
        debugName: "ingest_literature",
        argNames: ["filePath"],
      );

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 32, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiSimpleInitAppConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta => const TaskConstMeta(
        debugName: "init_app",
        argNames: [],
      );

  @override
  Future<void> crateApiQualiaApiInitCore() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 33, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiQualiaApiInitCoreConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiQualiaApiInitCoreConstMeta => const TaskConstMeta(
        debugName: "init_core",
        argNames: [],
      );

  @override
  Future<String> crateApiQualiaApiLaunchInstalledApp(
      {required String appName}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(appName, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 34, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiQualiaApiLaunchInstalledAppConstMeta,
      argValues: [appName],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiQualiaApiLaunchInstalledAppConstMeta =>
      const TaskConstMeta(
        debugName: "launch_installed_app",
        argNames: ["appName"],
      );

  @override
  Future<List<String>> crateApiQualiaApiListInstalledApps() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 35, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiQualiaApiListInstalledAppsConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiQualiaApiListInstalledAppsConstMeta =>
      const TaskConstMeta(
        debugName: "list_installed_apps",
        argNames: [],
      );

  @override
  Future<String?> crateApiQualiaApiLoadIdentity() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 36, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_opt_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiQualiaApiLoadIdentityConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiQualiaApiLoadIdentityConstMeta =>
      const TaskConstMeta(
        debugName: "load_identity",
        argNames: [],
      );

  @override
  Future<String> crateApiQualiaApiLoadImportedAccounts() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 37, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiQualiaApiLoadImportedAccountsConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiQualiaApiLoadImportedAccountsConstMeta =>
      const TaskConstMeta(
        debugName: "load_imported_accounts",
        argNames: [],
      );

  @override
  Future<List<LLMResource>> crateApiResourceCatalogLoadLlmResources() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 38, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_llm_resource,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiResourceCatalogLoadLlmResourcesConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiResourceCatalogLoadLlmResourcesConstMeta =>
      const TaskConstMeta(
        debugName: "load_llm_resources",
        argNames: [],
      );

  @override
  Future<List<OntologyResource>>
      crateApiResourceCatalogLoadOntologyResources() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 39, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_ontology_resource,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiResourceCatalogLoadOntologyResourcesConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiResourceCatalogLoadOntologyResourcesConstMeta =>
      const TaskConstMeta(
        debugName: "load_ontology_resources",
        argNames: [],
      );

  @override
  Future<void> crateApiQualiaApiSaveConfig({required AgentConfig newConfig}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_box_autoadd_agent_config(newConfig, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 40, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiQualiaApiSaveConfigConstMeta,
      argValues: [newConfig],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiQualiaApiSaveConfigConstMeta =>
      const TaskConstMeta(
        debugName: "save_config",
        argNames: ["newConfig"],
      );

  @override
  Future<void> crateApiQualiaApiSaveIdentity({required String walletsJson}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(walletsJson, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 41, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiQualiaApiSaveIdentityConstMeta,
      argValues: [walletsJson],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiQualiaApiSaveIdentityConstMeta =>
      const TaskConstMeta(
        debugName: "save_identity",
        argNames: ["walletsJson"],
      );

  @override
  Future<void> crateApiQualiaApiSaveImportedAccounts(
      {required String accountsJson}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(accountsJson, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 42, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiQualiaApiSaveImportedAccountsConstMeta,
      argValues: [accountsJson],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiQualiaApiSaveImportedAccountsConstMeta =>
      const TaskConstMeta(
        debugName: "save_imported_accounts",
        argNames: ["accountsJson"],
      );

  @override
  Future<void> crateApiQualiaApiSetActiveModel({required String modelName}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(modelName, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 43, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiQualiaApiSetActiveModelConstMeta,
      argValues: [modelName],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiQualiaApiSetActiveModelConstMeta =>
      const TaskConstMeta(
        debugName: "set_active_model",
        argNames: ["modelName"],
      );

  @override
  Future<String> crateApiQualiaApiStartDaemon() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 44, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiQualiaApiStartDaemonConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiQualiaApiStartDaemonConstMeta =>
      const TaskConstMeta(
        debugName: "start_daemon",
        argNames: [],
      );

  @override
  Future<void> crateApiQualiaApiUpdatePhysicsState(
      {required double temperature,
      required double pressure,
      required double timeDilation}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_f_64(temperature, serializer);
        sse_encode_f_64(pressure, serializer);
        sse_encode_f_64(timeDilation, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 45, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiQualiaApiUpdatePhysicsStateConstMeta,
      argValues: [temperature, pressure, timeDilation],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiQualiaApiUpdatePhysicsStateConstMeta =>
      const TaskConstMeta(
        debugName: "update_physics_state",
        argNames: ["temperature", "pressure", "timeDilation"],
      );

  @override
  Future<String> crateApiQualiaApiUpsertCmldDefinition(
      {required String term, required String contextDid}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(term, serializer);
        sse_encode_String(contextDid, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 46, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiQualiaApiUpsertCmldDefinitionConstMeta,
      argValues: [term, contextDid],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiQualiaApiUpsertCmldDefinitionConstMeta =>
      const TaskConstMeta(
        debugName: "upsert_cmld_definition",
        argNames: ["term", "contextDid"],
      );

  @override
  Future<String> crateApiQualiaApiVerifyAndInstallApp(
      {required String zipPath, required String credentialSig}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(zipPath, serializer);
        sse_encode_String(credentialSig, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 47, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiQualiaApiVerifyAndInstallAppConstMeta,
      argValues: [zipPath, credentialSig],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiQualiaApiVerifyAndInstallAppConstMeta =>
      const TaskConstMeta(
        debugName: "verify_and_install_app",
        argNames: ["zipPath", "credentialSig"],
      );

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  AgentConfig dco_decode_agent_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return AgentConfig(
      storagePath: dco_decode_String(arr[0]),
      storageQuotaGb: dco_decode_u_64(arr[1]),
      baseConnectivityCostIlp: dco_decode_u_64(arr[2]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  AgentConfig dco_decode_box_autoadd_agent_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_agent_config(raw);
  }

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  CatalogItem dco_decode_catalog_item(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return CatalogItem(
      id: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      tag: dco_decode_String(arr[2]),
      params: dco_decode_opt_String(arr[3]),
      format: dco_decode_String(arr[4]),
      size: dco_decode_String(arr[5]),
      vram: dco_decode_opt_String(arr[6]),
    );
  }

  @protected
  CoinBalance dco_decode_coin_balance(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 10)
      throw Exception('unexpected arr length: expect 10 but see ${arr.length}');
    return CoinBalance(
      coin: dco_decode_String(arr[0]),
      ticker: dco_decode_String(arr[1]),
      address: dco_decode_String(arr[2]),
      balance: dco_decode_f_64(arr[3]),
      balanceDisplay: dco_decode_String(arr[4]),
      fiatUsd: dco_decode_f_64(arr[5]),
      priceUsd: dco_decode_f_64(arr[6]),
      change24H: dco_decode_f_64(arr[7]),
      network: dco_decode_String(arr[8]),
      status: dco_decode_String(arr[9]),
    );
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  HardwareStatus dco_decode_hardware_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return HardwareStatus(
      ramTotalGb: dco_decode_f_64(arr[0]),
      ramUsedGb: dco_decode_f_64(arr[1]),
      vramEstimatedGb: dco_decode_f_64(arr[2]),
    );
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<CatalogItem> dco_decode_list_catalog_item(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_catalog_item).toList();
  }

  @protected
  List<CoinBalance> dco_decode_list_coin_balance(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_coin_balance).toList();
  }

  @protected
  List<LLMResource> dco_decode_list_llm_resource(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_llm_resource).toList();
  }

  @protected
  List<ModelInfo> dco_decode_list_model_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_model_info).toList();
  }

  @protected
  List<OntologyResource> dco_decode_list_ontology_resource(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_ontology_resource).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<ProgressPayload> dco_decode_list_progress_payload(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_progress_payload).toList();
  }

  @protected
  List<TaxRecipient> dco_decode_list_tax_recipient(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_tax_recipient).toList();
  }

  @protected
  LLMResource dco_decode_llm_resource(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 12)
      throw Exception('unexpected arr length: expect 12 but see ${arr.length}');
    return LLMResource(
      id: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      provider: dco_decode_opt_String(arr[2]),
      format: dco_decode_String(arr[3]),
      quantization: dco_decode_opt_String(arr[4]),
      sizeMb: dco_decode_opt_box_autoadd_u_32(arr[5]),
      ramEstimateMb: dco_decode_opt_box_autoadd_u_32(arr[6]),
      license: dco_decode_opt_String(arr[7]),
      tags: dco_decode_opt_list_String(arr[8]),
      recommendedFor: dco_decode_opt_list_String(arr[9]),
      downloadUrl: dco_decode_opt_String(arr[10]),
      notes: dco_decode_opt_String(arr[11]),
    );
  }

  @protected
  ModelInfo dco_decode_model_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return ModelInfo(
      name: dco_decode_String(arr[0]),
      isActive: dco_decode_bool(arr[1]),
      avatarType: dco_decode_String(arr[2]),
    );
  }

  @protected
  OntologyResource dco_decode_ontology_resource(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 9)
      throw Exception('unexpected arr length: expect 9 but see ${arr.length}');
    return OntologyResource(
      id: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      acronym: dco_decode_opt_String(arr[2]),
      domain: dco_decode_opt_String(arr[3]),
      format: dco_decode_String(arr[4]),
      sizeEstimateMb: dco_decode_opt_box_autoadd_u_32(arr[5]),
      license: dco_decode_opt_String(arr[6]),
      downloadUrl: dco_decode_opt_String(arr[7]),
      notes: dco_decode_opt_String(arr[8]),
    );
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_32(raw);
  }

  @protected
  List<String>? dco_decode_opt_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_list_String(raw);
  }

  @protected
  ProgressPayload dco_decode_progress_payload(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return ProgressPayload(
      id: dco_decode_String(arr[0]),
      progress: dco_decode_f_64(arr[1]),
      downloadedBytes: dco_decode_u_64(arr[2]),
      totalBytes: dco_decode_u_64(arr[3]),
      speedKbps: dco_decode_f_64(arr[4]),
      status: dco_decode_String(arr[5]),
    );
  }

  @protected
  SpatialPhysicsState dco_decode_spatial_physics_state(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return SpatialPhysicsState(
      temperature: dco_decode_f_64(arr[0]),
      pressure: dco_decode_f_64(arr[1]),
      timeDilation: dco_decode_f_64(arr[2]),
    );
  }

  @protected
  TaxRecipient dco_decode_tax_recipient(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return TaxRecipient(
      label: dco_decode_String(arr[0]),
      ilpAddress: dco_decode_String(arr[1]),
      sharePercent: dco_decode_f_64(arr[2]),
      useNym: dco_decode_bool(arr[3]),
    );
  }

  @protected
  TaxRecipientSuite dco_decode_tax_recipient_suite(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return TaxRecipientSuite(
      jurisdictionDid: dco_decode_String(arr[0]),
      recipients: dco_decode_list_tax_recipient(arr[1]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  AgentConfig sse_decode_agent_config(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_storagePath = sse_decode_String(deserializer);
    var var_storageQuotaGb = sse_decode_u_64(deserializer);
    var var_baseConnectivityCostIlp = sse_decode_u_64(deserializer);
    return AgentConfig(
        storagePath: var_storagePath,
        storageQuotaGb: var_storageQuotaGb,
        baseConnectivityCostIlp: var_baseConnectivityCostIlp);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  AgentConfig sse_decode_box_autoadd_agent_config(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_agent_config(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_32(deserializer));
  }

  @protected
  CatalogItem sse_decode_catalog_item(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_tag = sse_decode_String(deserializer);
    var var_params = sse_decode_opt_String(deserializer);
    var var_format = sse_decode_String(deserializer);
    var var_size = sse_decode_String(deserializer);
    var var_vram = sse_decode_opt_String(deserializer);
    return CatalogItem(
        id: var_id,
        name: var_name,
        tag: var_tag,
        params: var_params,
        format: var_format,
        size: var_size,
        vram: var_vram);
  }

  @protected
  CoinBalance sse_decode_coin_balance(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_coin = sse_decode_String(deserializer);
    var var_ticker = sse_decode_String(deserializer);
    var var_address = sse_decode_String(deserializer);
    var var_balance = sse_decode_f_64(deserializer);
    var var_balanceDisplay = sse_decode_String(deserializer);
    var var_fiatUsd = sse_decode_f_64(deserializer);
    var var_priceUsd = sse_decode_f_64(deserializer);
    var var_change24H = sse_decode_f_64(deserializer);
    var var_network = sse_decode_String(deserializer);
    var var_status = sse_decode_String(deserializer);
    return CoinBalance(
        coin: var_coin,
        ticker: var_ticker,
        address: var_address,
        balance: var_balance,
        balanceDisplay: var_balanceDisplay,
        fiatUsd: var_fiatUsd,
        priceUsd: var_priceUsd,
        change24H: var_change24H,
        network: var_network,
        status: var_status);
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  HardwareStatus sse_decode_hardware_status(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_ramTotalGb = sse_decode_f_64(deserializer);
    var var_ramUsedGb = sse_decode_f_64(deserializer);
    var var_vramEstimatedGb = sse_decode_f_64(deserializer);
    return HardwareStatus(
        ramTotalGb: var_ramTotalGb,
        ramUsedGb: var_ramUsedGb,
        vramEstimatedGb: var_vramEstimatedGb);
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<CatalogItem> sse_decode_list_catalog_item(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <CatalogItem>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_catalog_item(deserializer));
    }
    return ans_;
  }

  @protected
  List<CoinBalance> sse_decode_list_coin_balance(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <CoinBalance>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_coin_balance(deserializer));
    }
    return ans_;
  }

  @protected
  List<LLMResource> sse_decode_list_llm_resource(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <LLMResource>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_llm_resource(deserializer));
    }
    return ans_;
  }

  @protected
  List<ModelInfo> sse_decode_list_model_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ModelInfo>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_model_info(deserializer));
    }
    return ans_;
  }

  @protected
  List<OntologyResource> sse_decode_list_ontology_resource(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <OntologyResource>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_ontology_resource(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<ProgressPayload> sse_decode_list_progress_payload(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ProgressPayload>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_progress_payload(deserializer));
    }
    return ans_;
  }

  @protected
  List<TaxRecipient> sse_decode_list_tax_recipient(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <TaxRecipient>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_tax_recipient(deserializer));
    }
    return ans_;
  }

  @protected
  LLMResource sse_decode_llm_resource(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_provider = sse_decode_opt_String(deserializer);
    var var_format = sse_decode_String(deserializer);
    var var_quantization = sse_decode_opt_String(deserializer);
    var var_sizeMb = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_ramEstimateMb = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_license = sse_decode_opt_String(deserializer);
    var var_tags = sse_decode_opt_list_String(deserializer);
    var var_recommendedFor = sse_decode_opt_list_String(deserializer);
    var var_downloadUrl = sse_decode_opt_String(deserializer);
    var var_notes = sse_decode_opt_String(deserializer);
    return LLMResource(
        id: var_id,
        name: var_name,
        provider: var_provider,
        format: var_format,
        quantization: var_quantization,
        sizeMb: var_sizeMb,
        ramEstimateMb: var_ramEstimateMb,
        license: var_license,
        tags: var_tags,
        recommendedFor: var_recommendedFor,
        downloadUrl: var_downloadUrl,
        notes: var_notes);
  }

  @protected
  ModelInfo sse_decode_model_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_isActive = sse_decode_bool(deserializer);
    var var_avatarType = sse_decode_String(deserializer);
    return ModelInfo(
        name: var_name, isActive: var_isActive, avatarType: var_avatarType);
  }

  @protected
  OntologyResource sse_decode_ontology_resource(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_acronym = sse_decode_opt_String(deserializer);
    var var_domain = sse_decode_opt_String(deserializer);
    var var_format = sse_decode_String(deserializer);
    var var_sizeEstimateMb = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_license = sse_decode_opt_String(deserializer);
    var var_downloadUrl = sse_decode_opt_String(deserializer);
    var var_notes = sse_decode_opt_String(deserializer);
    return OntologyResource(
        id: var_id,
        name: var_name,
        acronym: var_acronym,
        domain: var_domain,
        format: var_format,
        sizeEstimateMb: var_sizeEstimateMb,
        license: var_license,
        downloadUrl: var_downloadUrl,
        notes: var_notes);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  List<String>? sse_decode_opt_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_list_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  ProgressPayload sse_decode_progress_payload(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_progress = sse_decode_f_64(deserializer);
    var var_downloadedBytes = sse_decode_u_64(deserializer);
    var var_totalBytes = sse_decode_u_64(deserializer);
    var var_speedKbps = sse_decode_f_64(deserializer);
    var var_status = sse_decode_String(deserializer);
    return ProgressPayload(
        id: var_id,
        progress: var_progress,
        downloadedBytes: var_downloadedBytes,
        totalBytes: var_totalBytes,
        speedKbps: var_speedKbps,
        status: var_status);
  }

  @protected
  SpatialPhysicsState sse_decode_spatial_physics_state(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_temperature = sse_decode_f_64(deserializer);
    var var_pressure = sse_decode_f_64(deserializer);
    var var_timeDilation = sse_decode_f_64(deserializer);
    return SpatialPhysicsState(
        temperature: var_temperature,
        pressure: var_pressure,
        timeDilation: var_timeDilation);
  }

  @protected
  TaxRecipient sse_decode_tax_recipient(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_label = sse_decode_String(deserializer);
    var var_ilpAddress = sse_decode_String(deserializer);
    var var_sharePercent = sse_decode_f_64(deserializer);
    var var_useNym = sse_decode_bool(deserializer);
    return TaxRecipient(
        label: var_label,
        ilpAddress: var_ilpAddress,
        sharePercent: var_sharePercent,
        useNym: var_useNym);
  }

  @protected
  TaxRecipientSuite sse_decode_tax_recipient_suite(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_jurisdictionDid = sse_decode_String(deserializer);
    var var_recipients = sse_decode_list_tax_recipient(deserializer);
    return TaxRecipientSuite(
        jurisdictionDid: var_jurisdictionDid, recipients: var_recipients);
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_agent_config(AgentConfig self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.storagePath, serializer);
    sse_encode_u_64(self.storageQuotaGb, serializer);
    sse_encode_u_64(self.baseConnectivityCostIlp, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_agent_config(
      AgentConfig self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_agent_config(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self, serializer);
  }

  @protected
  void sse_encode_catalog_item(CatalogItem self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.tag, serializer);
    sse_encode_opt_String(self.params, serializer);
    sse_encode_String(self.format, serializer);
    sse_encode_String(self.size, serializer);
    sse_encode_opt_String(self.vram, serializer);
  }

  @protected
  void sse_encode_coin_balance(CoinBalance self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.coin, serializer);
    sse_encode_String(self.ticker, serializer);
    sse_encode_String(self.address, serializer);
    sse_encode_f_64(self.balance, serializer);
    sse_encode_String(self.balanceDisplay, serializer);
    sse_encode_f_64(self.fiatUsd, serializer);
    sse_encode_f_64(self.priceUsd, serializer);
    sse_encode_f_64(self.change24H, serializer);
    sse_encode_String(self.network, serializer);
    sse_encode_String(self.status, serializer);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_hardware_status(
      HardwareStatus self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self.ramTotalGb, serializer);
    sse_encode_f_64(self.ramUsedGb, serializer);
    sse_encode_f_64(self.vramEstimatedGb, serializer);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_catalog_item(
      List<CatalogItem> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_catalog_item(item, serializer);
    }
  }

  @protected
  void sse_encode_list_coin_balance(
      List<CoinBalance> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_coin_balance(item, serializer);
    }
  }

  @protected
  void sse_encode_list_llm_resource(
      List<LLMResource> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_llm_resource(item, serializer);
    }
  }

  @protected
  void sse_encode_list_model_info(
      List<ModelInfo> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_model_info(item, serializer);
    }
  }

  @protected
  void sse_encode_list_ontology_resource(
      List<OntologyResource> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_ontology_resource(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_progress_payload(
      List<ProgressPayload> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_progress_payload(item, serializer);
    }
  }

  @protected
  void sse_encode_list_tax_recipient(
      List<TaxRecipient> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_tax_recipient(item, serializer);
    }
  }

  @protected
  void sse_encode_llm_resource(LLMResource self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_opt_String(self.provider, serializer);
    sse_encode_String(self.format, serializer);
    sse_encode_opt_String(self.quantization, serializer);
    sse_encode_opt_box_autoadd_u_32(self.sizeMb, serializer);
    sse_encode_opt_box_autoadd_u_32(self.ramEstimateMb, serializer);
    sse_encode_opt_String(self.license, serializer);
    sse_encode_opt_list_String(self.tags, serializer);
    sse_encode_opt_list_String(self.recommendedFor, serializer);
    sse_encode_opt_String(self.downloadUrl, serializer);
    sse_encode_opt_String(self.notes, serializer);
  }

  @protected
  void sse_encode_model_info(ModelInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_bool(self.isActive, serializer);
    sse_encode_String(self.avatarType, serializer);
  }

  @protected
  void sse_encode_ontology_resource(
      OntologyResource self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_opt_String(self.acronym, serializer);
    sse_encode_opt_String(self.domain, serializer);
    sse_encode_String(self.format, serializer);
    sse_encode_opt_box_autoadd_u_32(self.sizeEstimateMb, serializer);
    sse_encode_opt_String(self.license, serializer);
    sse_encode_opt_String(self.downloadUrl, serializer);
    sse_encode_opt_String(self.notes, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_32(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_list_String(
      List<String>? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_list_String(self, serializer);
    }
  }

  @protected
  void sse_encode_progress_payload(
      ProgressPayload self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_f_64(self.progress, serializer);
    sse_encode_u_64(self.downloadedBytes, serializer);
    sse_encode_u_64(self.totalBytes, serializer);
    sse_encode_f_64(self.speedKbps, serializer);
    sse_encode_String(self.status, serializer);
  }

  @protected
  void sse_encode_spatial_physics_state(
      SpatialPhysicsState self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self.temperature, serializer);
    sse_encode_f_64(self.pressure, serializer);
    sse_encode_f_64(self.timeDilation, serializer);
  }

  @protected
  void sse_encode_tax_recipient(TaxRecipient self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.label, serializer);
    sse_encode_String(self.ilpAddress, serializer);
    sse_encode_f_64(self.sharePercent, serializer);
    sse_encode_bool(self.useNym, serializer);
  }

  @protected
  void sse_encode_tax_recipient_suite(
      TaxRecipientSuite self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.jurisdictionDid, serializer);
    sse_encode_list_tax_recipient(self.recipients, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
