use super::super::row::{Contract, SpecTool};
use crate::browser::tool_proficiency::Proficiency;
use crate::tool_chest::core::intent_bus::ActionType;
use crate::tool_chest::core::tool::ToolKind;

const T: &str = "spatial3d";
const TL: &str = "3D editing";

pub(super) static ROWS: &[SpecTool] = &[
    SpecTool::new(
        T,
        TL,
        "materials",
        "Materials",
        "spatial3d:create-material",
        "New material",
        "Make a PBR, unlit, or custom-shader material.",
        "3d",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Novice,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "materials",
        "Materials",
        "spatial3d:assign-material",
        "Assign material",
        "Put a material on the selected object.",
        "3d",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Novice,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "materials",
        "Materials",
        "spatial3d:texture-paint",
        "Paint texture",
        "Paint onto the mesh texture.",
        "3d",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Intermediate,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "materials",
        "Materials",
        "spatial3d:uv-edit",
        "Edit UVs",
        "Unwrap and edit the UV map.",
        "3d",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Expert,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "materials",
        "Materials",
        "spatial3d:material-node",
        "Material nodes",
        "Edit the material node graph.",
        "3d",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Expert,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "materials",
        "Materials",
        "spatial3d:pbr-preset",
        "PBR preset",
        "Apply metal, wood, stone, glass, or fabric.",
        "3d",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Intermediate,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "camera-light",
        "Cameras and lights",
        "spatial3d:add-camera",
        "Add camera",
        "Place a camera with lens and orientation.",
        "3d",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Novice,
        Contract::Live("Render.gpu_set_camera"),
    ),
    SpecTool::new(
        T,
        TL,
        "camera-light",
        "Cameras and lights",
        "spatial3d:camera-frame",
        "Frame camera",
        "Point the camera at a target.",
        "3d",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Novice,
        Contract::Live("Render.gpu_set_camera"),
    ),
    SpecTool::new(
        T,
        TL,
        "camera-light",
        "Cameras and lights",
        "spatial3d:add-light",
        "Add a light",
        "Place a point, sun, spot, or area light.",
        "3d",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Novice,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "camera-light",
        "Cameras and lights",
        "spatial3d:light-type",
        "Light type",
        "Change the selected light's kind.",
        "3d",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Intermediate,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "camera-light",
        "Cameras and lights",
        "spatial3d:hdri-setup",
        "HDRI sky",
        "Set the scene's environment image.",
        "3d",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Intermediate,
        Contract::Live("Render.scene"),
    ),
    SpecTool::new(
        T,
        TL,
        "camera-light",
        "Cameras and lights",
        "spatial3d:shadow-setup",
        "Shadows",
        "Set shadow type, resolution, and bias.",
        "3d",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Intermediate,
        Contract::Live("Render.scene"),
    ),
];
