use super::super::row::{Contract, SpecTool};
use crate::browser::tool_proficiency::Proficiency;
use crate::tool_chest::core::intent_bus::ActionType;
use crate::tool_chest::core::tool::ToolKind;

const T: &str = "spatial3d";
const TL: &str = "3D editing";

pub(super) static ROWS: &[SpecTool] = &[
    SpecTool::new(
        T,
        TL,
        "narrative",
        "Story",
        "spatial3d:add-scene",
        "Add a scene",
        "Add a named scene to the story.",
        "timeline",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Novice,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "narrative",
        "Story",
        "spatial3d:scene-sequence",
        "Scene order",
        "Order scenes in the story.",
        "timeline",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Intermediate,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "narrative",
        "Story",
        "spatial3d:camera-path",
        "Camera path",
        "Animate the camera along a path.",
        "timeline",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Intermediate,
        Contract::Live("Render.gpu_set_camera"),
    ),
    SpecTool::new(
        T,
        TL,
        "narrative",
        "Story",
        "spatial3d:storyboard-frame",
        "Storyboard frame",
        "Pin a still and a note to this scene.",
        "timeline",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Novice,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "narrative",
        "Story",
        "spatial3d:trigger-zone",
        "Trigger zone",
        "Fire an action when someone enters a zone.",
        "timeline",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Intermediate,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "narrative",
        "Story",
        "spatial3d:narrative-export",
        "Export story",
        "Export the story as a board or script.",
        "timeline",
        ToolKind::Query,
        ActionType::Query,
        Proficiency::Intermediate,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "inspect",
        "Inspect",
        "spatial3d:mesh-statistics",
        "Mesh stats",
        "Show vertex, face, and UV counts.",
        "inspect",
        ToolKind::Query,
        ActionType::Query,
        Proficiency::Novice,
        Contract::Live("Render.scene"),
    ),
    SpecTool::new(
        T,
        TL,
        "inspect",
        "Inspect",
        "spatial3d:material-inspector",
        "Material inspector",
        "Show material channels and textures.",
        "inspect",
        ToolKind::Query,
        ActionType::Query,
        Proficiency::Intermediate,
        Contract::Live("Render.scene"),
    ),
    SpecTool::new(
        T,
        TL,
        "inspect",
        "Inspect",
        "spatial3d:rig-inspector",
        "Rig inspector",
        "Show bones, constraints, and weights.",
        "inspect",
        ToolKind::Query,
        ActionType::Query,
        Proficiency::Intermediate,
        Contract::Live("Render.scene"),
    ),
    SpecTool::new(
        T,
        TL,
        "inspect",
        "Inspect",
        "spatial3d:scene-graph",
        "Scene graph",
        "Show the full object hierarchy.",
        "inspect",
        ToolKind::Query,
        ActionType::Query,
        Proficiency::Novice,
        Contract::Live("Render.scene"),
    ),
    SpecTool::new(
        T,
        TL,
        "inspect",
        "Inspect",
        "spatial3d:metadata-view",
        "Asset details",
        "Show format, vertex count, bones, and morphs.",
        "inspect",
        ToolKind::Query,
        ActionType::Query,
        Proficiency::Novice,
        Contract::Live("Render.scene"),
    ),
];
