use super::super::row::{Contract, SpecTool};
use crate::browser::tool_proficiency::Proficiency;
use crate::tool_chest::core::intent_bus::ActionType;
use crate::tool_chest::core::tool::ToolKind;

const T: &str = "spatial3d";
const TL: &str = "3D editing";

pub(super) static ROWS: &[SpecTool] = &[
    SpecTool::new(
        T,
        TL,
        "object",
        "Scene objects",
        "spatial3d:add-mesh",
        "Add a mesh",
        "Place a cube, sphere, cylinder, plane, cone, or torus.",
        "3d",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Novice,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "object",
        "Scene objects",
        "spatial3d:import-mesh",
        "Import a mesh",
        "Bring in a glTF, OBJ, FBX, or STL mesh.",
        "3d",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Intermediate,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "object",
        "Scene objects",
        "spatial3d:delete-object",
        "Delete object",
        "Remove the selected object from the scene.",
        "3d",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Novice,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "object",
        "Scene objects",
        "spatial3d:duplicate-object",
        "Duplicate object",
        "Copy the selected object, linked or independent.",
        "3d",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Novice,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "object",
        "Scene objects",
        "spatial3d:parent-object",
        "Parent object",
        "Attach one object to another in the hierarchy.",
        "3d",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Intermediate,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "object",
        "Scene objects",
        "spatial3d:group-objects",
        "Group objects",
        "Group the selected objects together.",
        "3d",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Novice,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "object",
        "Scene objects",
        "spatial3d:snap-to-grid",
        "Snap to grid",
        "Snap the selected object onto the grid.",
        "3d",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Novice,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "object",
        "Scene objects",
        "spatial3d:transform-object",
        "Move, rotate, scale",
        "Set position, rotation, and scale of the selected object.",
        "3d",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Novice,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "modelling",
        "Mesh editing",
        "spatial3d:extrude",
        "Extrude",
        "Push selected faces, edges, or vertices out.",
        "3d",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Intermediate,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "modelling",
        "Mesh editing",
        "spatial3d:inset",
        "Inset faces",
        "Shrink selected faces inward.",
        "3d",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Intermediate,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "modelling",
        "Mesh editing",
        "spatial3d:bevel",
        "Bevel",
        "Round or chamfer selected edges.",
        "3d",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Intermediate,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "modelling",
        "Mesh editing",
        "spatial3d:loop-cut",
        "Loop cut",
        "Cut a ring of new edges around the mesh.",
        "3d",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Intermediate,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "modelling",
        "Mesh editing",
        "spatial3d:subdivide",
        "Subdivide",
        "Split selected faces into finer faces.",
        "3d",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Intermediate,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "modelling",
        "Mesh editing",
        "spatial3d:merge-vertices",
        "Merge vertices",
        "Join vertices at centre, first, last, or collapse.",
        "3d",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Expert,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "modelling",
        "Mesh editing",
        "spatial3d:knife-tool",
        "Knife",
        "Cut faces along a drawn path.",
        "3d",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Expert,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "modelling",
        "Mesh editing",
        "spatial3d:boolean-op",
        "Boolean",
        "Union, difference, or intersect two meshes.",
        "3d",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Expert,
        Contract::Local,
    ),
];
