use super::super::row::{Contract, SpecTool};
use crate::browser::tool_proficiency::Proficiency;
use crate::tool_chest::core::intent_bus::ActionType;
use crate::tool_chest::core::tool::ToolKind;

const T: &str = "spatial3d";
const TL: &str = "3D editing";

pub(super) static ROWS: &[SpecTool] = &[
    SpecTool::new(
        T,
        TL,
        "rigging",
        "Rigging",
        "spatial3d:add-bone",
        "Add a bone",
        "Add a bone to the rig.",
        "3d",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Intermediate,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "rigging",
        "Rigging",
        "spatial3d:weight-paint",
        "Weight paint",
        "Paint how much a bone moves each vertex.",
        "3d",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Expert,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "rigging",
        "Rigging",
        "spatial3d:inverse-kinematics",
        "Inverse kinematics",
        "Set up an IK chain toward a target.",
        "3d",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Expert,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "rigging",
        "Rigging",
        "spatial3d:bone-constraint",
        "Bone constraint",
        "Constrain a bone to a target.",
        "3d",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Expert,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "rigging",
        "Rigging",
        "spatial3d:pose-mirror",
        "Mirror pose",
        "Mirror the pose across an axis.",
        "3d",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Intermediate,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "rigging",
        "Rigging",
        "spatial3d:rig-test",
        "Test the rig",
        "Check for weight gaps and bone conflicts.",
        "3d",
        ToolKind::Query,
        ActionType::Query,
        Proficiency::Expert,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "animation",
        "Animation",
        "spatial3d:keyframe-insert",
        "Insert keyframe",
        "Record a value on this frame.",
        "timeline",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Intermediate,
        Contract::Live("Animation.evaluate_preset"),
    ),
    SpecTool::new(
        T,
        TL,
        "animation",
        "Animation",
        "spatial3d:keyframe-edit",
        "Edit keyframe",
        "Change a keyframe value or interpolation.",
        "timeline",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Intermediate,
        Contract::Live("Animation.evaluate_preset"),
    ),
    SpecTool::new(
        T,
        TL,
        "animation",
        "Animation",
        "spatial3d:dope-sheet",
        "Dope sheet",
        "Show keyframes across objects.",
        "timeline",
        ToolKind::Query,
        ActionType::Query,
        Proficiency::Intermediate,
        Contract::Live("Animation.evaluate_preset"),
    ),
    SpecTool::new(
        T,
        TL,
        "animation",
        "Animation",
        "spatial3d:graph-editor",
        "Graph editor",
        "Show the animation curve for a property.",
        "timeline",
        ToolKind::Query,
        ActionType::Query,
        Proficiency::Expert,
        Contract::Live("Animation.evaluate_preset"),
    ),
    SpecTool::new(
        T,
        TL,
        "animation",
        "Animation",
        "spatial3d:action-clip",
        "Action clip",
        "Save a reusable clip from a frame range.",
        "timeline",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Intermediate,
        Contract::Live("Animation.evaluate_preset"),
    ),
    SpecTool::new(
        T,
        TL,
        "animation",
        "Animation",
        "spatial3d:animation-mixer",
        "Mix clips",
        "Blend action clips on the timeline.",
        "timeline",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Expert,
        Contract::Live("Animation.evaluate_preset"),
    ),
    SpecTool::new(
        T,
        TL,
        "animation",
        "Animation",
        "spatial3d:motion-path",
        "Motion path",
        "Show the path an object takes over time.",
        "timeline",
        ToolKind::Query,
        ActionType::Query,
        Proficiency::Intermediate,
        Contract::Live("Animation.evaluate_preset"),
    ),
];
