//! Extra AI-toolbox spec tools from TOOLBOX_CODE_SPEC.md.
//! Skips live `ai:extractor`, `ai:sentinel`, `ai:grounding`, `ai:co_author`, `ai:triad`.

use super::row::{Contract, SpecTool};
use crate::browser::tool_proficiency::Proficiency;
use crate::tool_chest::core::intent_bus::ActionType;
use crate::tool_chest::core::tool::ToolKind;

const T: &str = "ai";
const TL: &str = "AI";

pub fn rows() -> &'static [SpecTool] {
    #[rustfmt::skip]
    static ROWS: &[SpecTool] = &[
        SpecTool::new(T, TL, "symbolic", "Name finding", "ai:run-gazetteer",
            "Find known names", "Find known names in the writing, with where they start and end.",
            "ai", ToolKind::Query, ActionType::Query,
            Proficiency::Novice, Contract::Local),
        SpecTool::new(T, TL, "symbolic", "Name finding", "ai:run-fst",
            "Look up a word form", "Look up a word's stems and endings.",
            "ai", ToolKind::Query, ActionType::Query,
            Proficiency::Intermediate, Contract::Local),
        SpecTool::new(T, TL, "symbolic", "Name finding", "ai:run-coref-sieve",
            "Join name mentions", "Join mentions that refer to the same person or thing.",
            "ai", ToolKind::Query, ActionType::Query,
            Proficiency::Intermediate, Contract::Local),
        SpecTool::new(T, TL, "symbolic", "Name finding", "ai:run-frame-semantics",
            "Find roles", "Find the roles people and things play in this writing.",
            "ai", ToolKind::Query, ActionType::Query,
            Proficiency::Expert, Contract::Local),
        SpecTool::new(T, TL, "symbolic", "Name finding", "ai:run-temporal-parser",
            "Find times", "Find and normalise times and dates in this writing.",
            "ai", ToolKind::Query, ActionType::Query,
            Proficiency::Intermediate, Contract::Local),
        SpecTool::new(T, TL, "symbolic", "Name finding", "ai:run-geo-parser",
            "Find places", "Find and normalise place names in this writing.",
            "ai", ToolKind::Query, ActionType::Query,
            Proficiency::Intermediate, Contract::Local),
        SpecTool::new(T, TL, "symbolic", "Name finding", "ai:run-quantity-normalizer",
            "Find amounts", "Find and convert amounts and units in this writing.",
            "ai", ToolKind::Query, ActionType::Query,
            Proficiency::Intermediate, Contract::Local),
        SpecTool::new(T, TL, "symbolic", "Name finding", "ai:run-relation-extractor",
            "Find links", "Turn parsed writing into who-relates-to-what links.",
            "ai", ToolKind::Query, ActionType::Query,
            Proficiency::Expert, Contract::Local),
        SpecTool::new(T, TL, "symbolic", "Name finding", "ai:build-gazetteer",
            "Build a name list", "Build a fast name-finder from a list of terms.",
            "ai", ToolKind::RunAction, ActionType::Mutate,
            Proficiency::Expert, Contract::Local),
        SpecTool::new(T, TL, "symbolic", "Name finding", "ai:build-fst",
            "Build word forms", "Build a word-form lookup from a list of stems and endings.",
            "ai", ToolKind::RunAction, ActionType::Mutate,
            Proficiency::Expert, Contract::Local),
        SpecTool::new(T, TL, "neural", "Local models", "ai:run-embedder",
            "Make a fingerprint", "Make a number fingerprint for this writing.",
            "ai", ToolKind::Query, ActionType::Query,
            Proficiency::Intermediate, Contract::Local),
        SpecTool::new(T, TL, "neural", "Local models", "ai:run-transformer",
            "Run the model", "Run the local writing model on this prompt.",
            "ai", ToolKind::Query, ActionType::Query,
            Proficiency::Expert, Contract::Gated("Needs a loaded local model.")),
        SpecTool::new(T, TL, "neural", "Local models", "ai:run-classifier",
            "Classify writing", "Sort this writing into the named labels.",
            "ai", ToolKind::Query, ActionType::Query,
            Proficiency::Intermediate, Contract::Gated("Needs a loaded local model.")),
        SpecTool::new(T, TL, "neural", "Local models", "ai:run-reranker",
            "Rerank results", "Reorder candidate passages by how well they match the question.",
            "ai", ToolKind::Query, ActionType::Query,
            Proficiency::Expert, Contract::Gated("Needs a loaded local model.")),
        SpecTool::new(T, TL, "neural", "Local models", "ai:run-constrained-decode",
            "Guided writing", "Write with grammar or meaning constraints.",
            "ai", ToolKind::Query, ActionType::Query,
            Proficiency::Expert, Contract::Gated("Needs a loaded local model.")),
        SpecTool::new(T, TL, "neural", "Local models", "ai:load-model",
            "Load a model", "Load a local writing model.",
            "ai", ToolKind::RunAction, ActionType::Mutate,
            Proficiency::Expert, Contract::Gated("Needs a local model file.")),
        SpecTool::new(T, TL, "neural", "Local models", "ai:unload-model",
            "Unload a model", "Unload a local writing model to free memory.",
            "ai", ToolKind::RunAction, ActionType::Mutate,
            Proficiency::Expert, Contract::Local),
        SpecTool::new(T, TL, "bridge", "Checked facts", "ai:extract-substrate",
            "Make a fact sheet", "Turn writing into a checked set of names and links.",
            "graph", ToolKind::Query, ActionType::Query,
            Proficiency::Intermediate, Contract::Local),
        SpecTool::new(T, TL, "bridge", "Checked facts", "ai:build-graph-index",
            "Index the links", "Build a lookup index from names and links.",
            "graph", ToolKind::RunAction, ActionType::Mutate,
            Proficiency::Expert, Contract::Local),
        SpecTool::new(T, TL, "bridge", "Checked facts", "ai:graphrag-query",
            "Ask the graph", "Fetch the most relevant links for this question.",
            "graph", ToolKind::Query, ActionType::Query,
            Proficiency::Intermediate, Contract::Local),
        SpecTool::new(T, TL, "bridge", "Checked facts", "ai:verify-grounding",
            "Check the sources", "Check that this writing is tied to records you already have.",
            "graph", ToolKind::Query, ActionType::Query,
            Proficiency::Intermediate, Contract::Local),
        SpecTool::new(T, TL, "bridge", "Checked facts", "ai:feedback-loop",
            "Feed it back", "Feed model writing back into the link store for a check.",
            "graph", ToolKind::RunAction, ActionType::Mutate,
            Proficiency::Expert, Contract::Local),
        SpecTool::new(T, TL, "bridge", "Checked facts", "ai:inspect-substrate",
            "Inspect the facts", "Show the names, links, and notes in this fact sheet.",
            "graph", ToolKind::Query, ActionType::Query,
            Proficiency::Intermediate, Contract::Local),
        SpecTool::new(T, TL, "agent", "Task helpers", "ai:agent-plan",
            "Plan a task", "Plan the steps and tools for this task.",
            "ai", ToolKind::Query, ActionType::Query,
            Proficiency::Intermediate, Contract::Local),
        SpecTool::new(T, TL, "agent", "Task helpers", "ai:agent-execute",
            "Run the plan", "Run the planned steps.",
            "ai", ToolKind::RunAction, ActionType::Mutate,
            Proficiency::Expert, Contract::Gated("Needs a planned task to run.")),
        SpecTool::new(T, TL, "agent", "Task helpers", "ai:agent-verify",
            "Check the run", "Check that the run stayed grounded and within its powers.",
            "ai", ToolKind::Query, ActionType::Query,
            Proficiency::Expert, Contract::Local),
        SpecTool::new(T, TL, "agent", "Task helpers", "ai:agent-trace",
            "Show the trace", "Show every step, result, and error from this run.",
            "ai", ToolKind::Query, ActionType::Query,
            Proficiency::Intermediate, Contract::Local),
        SpecTool::new(T, TL, "agent", "Task helpers", "ai:load-golden-corpus",
            "Load examples", "Load a set of checked examples for scoring.",
            "ai", ToolKind::RunAction, ActionType::Mutate,
            Proficiency::Expert, Contract::Gated("Needs a set of checked examples.")),
        SpecTool::new(T, TL, "agent", "Task helpers", "ai:evaluate-agent",
            "Score the run", "Score this run against the checked examples.",
            "ai", ToolKind::Query, ActionType::Query,
            Proficiency::Expert, Contract::Gated("Needs a set of checked examples.")),
        SpecTool::new(T, TL, "agent", "Task helpers", "ai:sentinel-inspect",
            "Safety on this helper", "Show how the safety layer sees this helper's powers.",
            "shield", ToolKind::Query, ActionType::Query,
            Proficiency::Expert, Contract::Local),
        SpecTool::new(T, TL, "agent", "Task helpers", "ai:sentinel-gate",
            "Gate an action", "Ask the safety layer whether this helper may take an action.",
            "shield", ToolKind::RunAction, ActionType::Mutate,
            Proficiency::Expert, Contract::Gated("Needs a safety claim to check.")),
    ];
    ROWS
}
