//! Audio production spec tools from TOOLBOX_HYPERMEDIA_SPEC.md §2
//! (transport, tracks, editing, synthesis, midi, effects, mixing, inspect).

use super::row::{Contract, SpecTool};
use crate::browser::tool_proficiency::Proficiency;
use crate::tool_chest::core::intent_bus::ActionType;
use crate::tool_chest::core::tool::ToolKind;

const T: &str = "audio";
const TL: &str = "Sound";

pub fn rows() -> &'static [SpecTool] {
    static ROWS: &[SpecTool] = &[
        SpecTool::new(
            T,
            TL,
            "transport",
            "Play and stop",
            "audio:play",
            "Play",
            "Start playing from this place on the timeline.",
            "audio",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Novice,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "transport",
            "Play and stop",
            "audio:stop",
            "Stop",
            "Stop playing and return to the start.",
            "audio",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Novice,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "transport",
            "Play and stop",
            "audio:record",
            "Record",
            "Record into the armed track on this surface.",
            "audio",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Intermediate,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "transport",
            "Play and stop",
            "audio:loop-region",
            "Loop",
            "Loop a stretch of the selected timeline.",
            "audio",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Novice,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "transport",
            "Play and stop",
            "audio:metronome",
            "Click",
            "Turn the click on or off, and set the beat.",
            "audio",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Novice,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "transport",
            "Play and stop",
            "audio:tempo-set",
            "Tempo",
            "Set how fast this piece plays.",
            "audio",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Novice,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "tracks",
            "Tracks",
            "audio:add-audio-track",
            "Add a sound track",
            "Add a sound track to this piece.",
            "audio",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Novice,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "tracks",
            "Tracks",
            "audio:add-midi-track",
            "Add a notes track",
            "Add a notes track with an instrument.",
            "audio",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Novice,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "tracks",
            "Tracks",
            "audio:add-bus",
            "Add a bus",
            "Add a bus so several tracks can share a path.",
            "audio",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Intermediate,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "tracks",
            "Tracks",
            "audio:delete-track",
            "Remove track",
            "Remove the selected track.",
            "audio",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Novice,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "tracks",
            "Tracks",
            "audio:rename-track",
            "Rename track",
            "Give the selected track a new name.",
            "audio",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Novice,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "tracks",
            "Tracks",
            "audio:track-volume",
            "Volume",
            "Set how loud the selected track is.",
            "audio",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Novice,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "tracks",
            "Tracks",
            "audio:track-pan",
            "Pan",
            "Sit the selected track left, centre, or right.",
            "audio",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Novice,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "tracks",
            "Tracks",
            "audio:track-routing",
            "Route track",
            "Send the selected track to a bus or the master.",
            "audio",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Intermediate,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "editing",
            "Clip cuts",
            "audio:split-clip",
            "Split",
            "Cut the selected clip in two at this place.",
            "audio",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Novice,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "editing",
            "Clip cuts",
            "audio:join-clips",
            "Join",
            "Join neighbouring clips into one.",
            "audio",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Novice,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "editing",
            "Clip cuts",
            "audio:trim-clip",
            "Trim",
            "Shorten the selected clip at the ends.",
            "audio",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Novice,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "editing",
            "Clip cuts",
            "audio:fade-in",
            "Fade in",
            "Soften the start of the selected clip.",
            "audio",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Novice,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "editing",
            "Clip cuts",
            "audio:fade-out",
            "Fade out",
            "Soften the end of the selected clip.",
            "audio",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Novice,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "editing",
            "Clip cuts",
            "audio:crossfade",
            "Crossfade",
            "Blend two clips where they meet.",
            "audio",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Intermediate,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "editing",
            "Clip cuts",
            "audio:time-stretch",
            "Stretch time",
            "Stretch the clip without changing pitch.",
            "audio",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Intermediate,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "editing",
            "Clip cuts",
            "audio:pitch-shift",
            "Shift pitch",
            "Change pitch without changing length.",
            "audio",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Intermediate,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "editing",
            "Clip cuts",
            "audio:reverse",
            "Reverse",
            "Play the selected clip backwards.",
            "audio",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Novice,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "editing",
            "Clip cuts",
            "audio:normalise",
            "Even the loudness",
            "Bring the clip's peak to a chosen level.",
            "audio",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Intermediate,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "synthesis",
            "Sound makers",
            "audio:osc-config",
            "Oscillator",
            "Set the oscillator wave, pitch, and detune.",
            "audio",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Intermediate,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "synthesis",
            "Sound makers",
            "audio:filter-config",
            "Filter",
            "Set the filter type, cutoff, and resonance.",
            "audio",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Intermediate,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "synthesis",
            "Sound makers",
            "audio:envelope-config",
            "Envelope",
            "Set attack, decay, sustain, and release.",
            "audio",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Intermediate,
            Contract::Live("Animation.bezier_eval"),
        ),
        SpecTool::new(
            T,
            TL,
            "synthesis",
            "Sound makers",
            "audio:lfo-config",
            "Slow wobble",
            "Set the slow wobble and what it moves.",
            "audio",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Intermediate,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "synthesis",
            "Sound makers",
            "audio:mod-routing",
            "Modulation",
            "Route a source to a target with an amount.",
            "audio",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Expert,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "synthesis",
            "Sound makers",
            "audio:preset-save",
            "Save sound",
            "Save this synthesiser sound on the selected rack.",
            "audio",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Intermediate,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "synthesis",
            "Sound makers",
            "audio:preset-load",
            "Load sound",
            "Load a saved synthesiser sound.",
            "audio",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Intermediate,
            Contract::Gated("Needs a saved sound to load onto this rack."),
        ),
        SpecTool::new(
            T,
            TL,
            "synthesis",
            "Sound makers",
            "audio:wavetable-import",
            "Bring in a wavetable",
            "Load a wavetable into this synthesiser.",
            "audio",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Expert,
            Contract::Gated("Needs a wavetable file to bring in."),
        ),
        SpecTool::new(
            T,
            TL,
            "midi",
            "Notes",
            "audio:note-draw",
            "Draw a note",
            "Draw a note on the selected piano roll.",
            "audio",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Novice,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "midi",
            "Notes",
            "audio:note-edit",
            "Edit a note",
            "Change a note's pitch, start, or length.",
            "audio",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Novice,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "midi",
            "Notes",
            "audio:velocity-edit",
            "How hard",
            "Change how hard the selected note is struck.",
            "audio",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Intermediate,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "midi",
            "Notes",
            "audio:cc-edit",
            "Control curve",
            "Draw a control curve over time on this track.",
            "audio",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Intermediate,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "midi",
            "Notes",
            "audio:quantise",
            "Snap to the beat",
            "Snap notes on this track to the beat.",
            "audio",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Intermediate,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "midi",
            "Notes",
            "audio:transpose",
            "Transpose",
            "Move all notes on this track up or down.",
            "audio",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Intermediate,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "midi",
            "Notes",
            "audio:midi-import",
            "Bring in notes",
            "Load notes from a MIDI file onto this track.",
            "audio",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Intermediate,
            Contract::Gated("Needs a MIDI file to bring in."),
        ),
        SpecTool::new(
            T,
            TL,
            "effects",
            "Effects",
            "audio:add-effect",
            "Add an effect",
            "Put an effect on the selected track.",
            "audio",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Novice,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "effects",
            "Effects",
            "audio:reorder-effect",
            "Reorder effects",
            "Change the order of effects on this track.",
            "audio",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Intermediate,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "effects",
            "Effects",
            "audio:remove-effect",
            "Remove effect",
            "Take an effect off this track.",
            "audio",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Novice,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "effects",
            "Effects",
            "audio:reverb-config",
            "Room",
            "Set room size, damping, and wet or dry mix.",
            "audio",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Intermediate,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "effects",
            "Effects",
            "audio:delay-config",
            "Echo",
            "Set echo time, feedback, and mix.",
            "audio",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Intermediate,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "effects",
            "Effects",
            "audio:compressor-config",
            "Compressor",
            "Set threshold, ratio, attack, and release.",
            "audio",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Intermediate,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "effects",
            "Effects",
            "audio:eq-config",
            "Equaliser",
            "Set the bands of the equaliser on this track.",
            "audio",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Intermediate,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "effects",
            "Effects",
            "audio:saturation-config",
            "Warmth",
            "Set drive, mix, and character on this track.",
            "audio",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Intermediate,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "mixing",
            "Mix",
            "audio:set-send",
            "Send",
            "Set how much this track sends to a bus.",
            "audio",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Intermediate,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "mixing",
            "Mix",
            "audio:set-bus",
            "Bus output",
            "Route this track out through a bus.",
            "audio",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Intermediate,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "mixing",
            "Mix",
            "audio:automation-draw",
            "Draw automation",
            "Draw how a control moves over time.",
            "audio",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Intermediate,
            Contract::Live("Animation.bezier_eval"),
        ),
        SpecTool::new(
            T,
            TL,
            "mixing",
            "Mix",
            "audio:automation-edit",
            "Edit automation",
            "Move a point on an automation curve.",
            "audio",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Intermediate,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "mixing",
            "Mix",
            "audio:bounce-track",
            "Bounce track",
            "Mix this track down to a sound file.",
            "audio",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Expert,
            Contract::Gated("Needs a place to save the bounced sound."),
        ),
        SpecTool::new(
            T,
            TL,
            "mixing",
            "Mix",
            "audio:bounce-mix",
            "Bounce mix",
            "Mix the whole piece down to a sound file.",
            "audio",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Expert,
            Contract::Gated("Needs a place to save the mixed sound."),
        ),
        SpecTool::new(
            T,
            TL,
            "inspect",
            "Inspect",
            "audio:spectrum-analyser",
            "Spectrum",
            "Show the frequencies of the selected track.",
            "audio",
            ToolKind::Query,
            ActionType::Query,
            Proficiency::Intermediate,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "inspect",
            "Inspect",
            "audio:waveform-view",
            "Waveform",
            "Show the shape of the selected clip.",
            "audio",
            ToolKind::Query,
            ActionType::Query,
            Proficiency::Novice,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "inspect",
            "Inspect",
            "audio:phase-meter",
            "Phase",
            "Show how left and right line up on this track.",
            "audio",
            ToolKind::Query,
            ActionType::Query,
            Proficiency::Intermediate,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "inspect",
            "Inspect",
            "audio:loudness-meter",
            "Loudness",
            "Show how loud this track is over time.",
            "audio",
            ToolKind::Query,
            ActionType::Query,
            Proficiency::Intermediate,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "inspect",
            "Inspect",
            "audio:metadata-view",
            "Sound details",
            "Show sample rate, bit depth, channels, and length.",
            "audio",
            ToolKind::Query,
            ActionType::Query,
            Proficiency::Novice,
            Contract::Local,
        ),
    ];
    ROWS
}
