//! Extra code-toolbox spec tools from TOOLBOX_CODE_SPEC.md.
//! Skips live `code:vibe_diagnose`, `code:quin_statement`, `code:place_vibe`.

use super::row::{Contract, SpecTool};
use crate::browser::tool_proficiency::Proficiency;
use crate::tool_chest::core::intent_bus::ActionType;
use crate::tool_chest::core::tool::ToolKind;

const T: &str = "code";
const TL: &str = "Scripts";

pub fn rows() -> &'static [SpecTool] {
    #[rustfmt::skip]
    static ROWS: &[SpecTool] = &[
        SpecTool::new(T, TL, "vibe", "Script language", "code:vibe-console",
            "Script console", "Open a console for trying script lines.",
            "code", ToolKind::PlaceContainer, ActionType::Mutate,
            Proficiency::Novice, Contract::Place("code")),
        SpecTool::new(T, TL, "vibe", "Script language", "code:vibe-eval",
            "Run a line", "Run the selected script line with the powers it names.",
            "code", ToolKind::Query, ActionType::Query,
            Proficiency::Intermediate, Contract::Local),
        SpecTool::new(T, TL, "vibe", "Script language", "code:vibe-syntax-check",
            "Check spelling", "Check the script for grammar mistakes without running it.",
            "code", ToolKind::Query, ActionType::Query,
            Proficiency::Novice, Contract::Local),
        SpecTool::new(T, TL, "vibe", "Script language", "code:vibe-format",
            "Tidy script", "Neaten the selected script's spacing and line breaks.",
            "code", ToolKind::RunAction, ActionType::Mutate,
            Proficiency::Novice, Contract::Local),
        SpecTool::new(T, TL, "vibe", "Script language", "code:vibe-outline",
            "Script outline", "List the functions and types in this script.",
            "code", ToolKind::Query, ActionType::Query,
            Proficiency::Intermediate, Contract::Local),
        SpecTool::new(T, TL, "quin", "Named links", "code:quin-inspect",
            "Look up a link", "Show the notes attached to this who-relates-to-what link.",
            "graph", ToolKind::Query, ActionType::Query,
            Proficiency::Intermediate, Contract::Local),
        SpecTool::new(T, TL, "quin", "Named links", "code:quin-ref",
            "Find mentions", "Find every link that names this thing.",
            "graph", ToolKind::Query, ActionType::Query,
            Proficiency::Intermediate, Contract::Local),
        SpecTool::new(T, TL, "quin", "Named links", "code:quin-reify",
            "Add a note", "Attach extra notes to this link.",
            "graph", ToolKind::RunAction, ActionType::Annotate,
            Proficiency::Expert, Contract::Local),
        SpecTool::new(T, TL, "quin", "Named links", "code:quin-validate",
            "Check a link", "Check this link against a meaning shape.",
            "graph", ToolKind::Query, ActionType::Validate,
            Proficiency::Expert, Contract::Live("SHACL.validate")),
        SpecTool::new(T, TL, "project", "App project", "code:new-project",
            "New project", "Start a new app project.",
            "code", ToolKind::PlaceContainer, ActionType::Mutate,
            Proficiency::Novice, Contract::Place("code")),
        SpecTool::new(T, TL, "project", "App project", "code:add-module",
            "Add a module", "Add a script, meaning file, or native piece to this project.",
            "code", ToolKind::RunAction, ActionType::Mutate,
            Proficiency::Intermediate, Contract::Local),
        SpecTool::new(T, TL, "project", "App project", "code:remove-module",
            "Remove a module", "Take a module out of this project.",
            "code", ToolKind::RunAction, ActionType::Mutate,
            Proficiency::Intermediate, Contract::Local),
        SpecTool::new(T, TL, "project", "App project", "code:build-project",
            "Build", "Build this project for the chosen target.",
            "code", ToolKind::RunAction, ActionType::Mutate,
            Proficiency::Intermediate, Contract::Local),
        SpecTool::new(T, TL, "project", "App project", "code:test-project",
            "Run tests", "Run this project's tests.",
            "code", ToolKind::Query, ActionType::Query,
            Proficiency::Intermediate, Contract::Local),
        SpecTool::new(T, TL, "project", "App project", "code:package-project",
            "Package", "Pack the built project for sharing.",
            "code", ToolKind::RunAction, ActionType::Mutate,
            Proficiency::Expert, Contract::Local),
        SpecTool::new(T, TL, "project", "App project", "code:deploy-project",
            "Deploy", "Send the packed project to a chosen place.",
            "code", ToolKind::RunAction, ActionType::Mutate,
            Proficiency::Expert, Contract::Gated("Needs a chosen place to send the packed project.")),
        SpecTool::new(T, TL, "project", "App project", "code:inspect-manifest",
            "Show manifest", "Show the project's modules, powers, and build targets.",
            "code", ToolKind::Query, ActionType::Query,
            Proficiency::Intermediate, Contract::Local),
        SpecTool::new(T, TL, "hcf", "Packed pages", "code:hcf-author",
            "Write a bundle", "Write a hypermedia bundle from a source file.",
            "doc", ToolKind::RunAction, ActionType::Mutate,
            Proficiency::Intermediate, Contract::Local),
        SpecTool::new(T, TL, "hcf", "Packed pages", "code:hcf-compile",
            "Compile a bundle", "Compile the source bundle into the compact form.",
            "doc", ToolKind::RunAction, ActionType::Mutate,
            Proficiency::Expert, Contract::Local),
        SpecTool::new(T, TL, "hcf", "Packed pages", "code:hcf-validate",
            "Check a bundle", "Check a packed bundle against its schema.",
            "doc", ToolKind::Query, ActionType::Validate,
            Proficiency::Expert, Contract::Live("SHACL.validate")),
        SpecTool::new(T, TL, "hcf", "Packed pages", "code:hcf-inspect",
            "Inspect a bundle", "Show what pictures, meanings, and lists sit in this bundle.",
            "doc", ToolKind::Query, ActionType::Query,
            Proficiency::Intermediate, Contract::Local),
        SpecTool::new(T, TL, "hcf", "Packed pages", "code:hcf-extract",
            "Take an asset", "Pull one asset out of a packed bundle.",
            "doc", ToolKind::Query, ActionType::Query,
            Proficiency::Intermediate, Contract::Local),
        SpecTool::new(T, TL, "n3-ontology", "Meaning files", "code:n3-author",
            "Write meanings", "Write or edit a meaning file.",
            "ontology", ToolKind::PlaceContainer, ActionType::Mutate,
            Proficiency::Intermediate, Contract::Place("ontology")),
        SpecTool::new(T, TL, "n3-ontology", "Meaning files", "code:n3-compile",
            "Compile meanings", "Compile the meaning file into the compact form.",
            "ontology", ToolKind::RunAction, ActionType::Mutate,
            Proficiency::Expert, Contract::Local),
        SpecTool::new(T, TL, "n3-ontology", "Meaning files", "code:n3-validate",
            "Check meanings", "Check this meaning file against the tool-chest schema.",
            "ontology", ToolKind::Query, ActionType::Validate,
            Proficiency::Expert, Contract::Live("N3Logic.evaluate")),
        SpecTool::new(T, TL, "n3-ontology", "Meaning files", "code:n3-import",
            "List imports", "List the meaning files this one depends on.",
            "ontology", ToolKind::Query, ActionType::Query,
            Proficiency::Intermediate, Contract::Local),
        SpecTool::new(T, TL, "n3-ontology", "Meaning files", "code:n3-prefix-check",
            "Check prefixes", "Check short names in this meaning file.",
            "ontology", ToolKind::Query, ActionType::Query,
            Proficiency::Intermediate, Contract::Local),
        SpecTool::new(T, TL, "n3-ontology", "Meaning files", "code:ontology-load",
            "Load meanings", "Load a compiled meaning file into the registry.",
            "ontology", ToolKind::RunAction, ActionType::Mutate,
            Proficiency::Expert, Contract::Local),
        SpecTool::new(T, TL, "n3-ontology", "Meaning files", "code:ontology-query",
            "Look up a term", "Look up a term, class, or property in the registry.",
            "ontology", ToolKind::Query, ActionType::Query,
            Proficiency::Intermediate, Contract::Local),
        SpecTool::new(T, TL, "capability", "Named powers", "code:declare-capability",
            "Name a power", "Name a power this module needs, and why.",
            "shield", ToolKind::RunAction, ActionType::Mutate,
            Proficiency::Expert, Contract::Local),
        SpecTool::new(T, TL, "capability", "Named powers", "code:inspect-sentinel",
            "Safety view", "Show how the safety layer sees this module's powers.",
            "shield", ToolKind::Query, ActionType::Query,
            Proficiency::Expert, Contract::Local),
        SpecTool::new(T, TL, "capability", "Named powers", "code:test-capability-gating",
            "Test a power", "Test whether this module is allowed a named power.",
            "shield", ToolKind::Query, ActionType::Query,
            Proficiency::Expert, Contract::Local),
        SpecTool::new(T, TL, "capability", "Named powers", "code:grant-capability",
            "Grant a power", "Grant a named power to this module.",
            "shield", ToolKind::RunAction, ActionType::Mutate,
            Proficiency::Expert, Contract::Gated("Needs a signed yes from the safety layer.")),
        SpecTool::new(T, TL, "capability", "Named powers", "code:revoke-capability",
            "Revoke a power", "Take a named power away from this module.",
            "shield", ToolKind::RunAction, ActionType::Mutate,
            Proficiency::Expert, Contract::Gated("Needs a signed yes from the safety layer.")),
        SpecTool::new(T, TL, "capability", "Named powers", "code:audit-capabilities",
            "Audit powers", "List every named power and grant for this app.",
            "shield", ToolKind::Query, ActionType::Query,
            Proficiency::Expert, Contract::Local),
    ];
    ROWS
}
