//! Extra epistemics chains from TOOLBOX_EPISTEMICS_SPEC.md.
//! Merge into toolbox `epistemic`. Skip tag_objective/subjective/intersubjective/normative.

use super::row::{Contract, SpecTool};
use crate::browser::tool_proficiency::Proficiency;
use crate::tool_chest::core::intent_bus::ActionType;
use crate::tool_chest::core::tool::ToolKind;
use ActionType::{Mutate, Query};
use Contract::{Live, Local};
use Proficiency::{Expert, Intermediate, Novice};
use ToolKind::{Query as Look, RunAction};

const T: &str = "epistemic";
const TL: &str = "Epistemic Toolbox";

pub fn rows() -> &'static [SpecTool] {
    #[rustfmt::skip]
    static ROWS: &[SpecTool] = &[
        // evaluate (12)
        SpecTool::new(T, TL, "evaluate", "Assess claims", "epistemic:create-assessment", "Assess a claim",
            "Start an assessment of the selected claim, act, or writing.",
            "doc", RunAction, Mutate, Novice, Local),
        SpecTool::new(T, TL, "evaluate", "Assess claims", "epistemic:set-epistemic-mode", "Set how we know",
            "Say whether this is a shared fact, a point of view, agreed together, contested, unclear, or made up.",
            "doc", RunAction, Mutate, Novice, Local),
        SpecTool::new(T, TL, "evaluate", "Assess claims", "epistemic:set-reality-category", "Set fact or fiction",
            "Say whether this is non-fiction, fiction, or a blend, and which kind.",
            "doc", RunAction, Mutate, Intermediate, Local),
        SpecTool::new(T, TL, "evaluate", "Assess claims", "epistemic:mark-disputed", "Mark as disputed",
            "Note that another observer disagrees with this classification.",
            "doc", RunAction, Mutate, Intermediate, Local),
        SpecTool::new(T, TL, "evaluate", "Assess claims", "epistemic:set-spatio-temporal-context", "Set place and time",
            "Record where and when this was seen, and how the observer reached it.",
            "doc", RunAction, Mutate, Intermediate, Local),
        SpecTool::new(T, TL, "evaluate", "Assess claims", "epistemic:set-social-context", "Set social setting",
            "Record power, trust, group agreement, incentives, and pressure around this claim.",
            "doc", RunAction, Mutate, Intermediate, Local),
        SpecTool::new(T, TL, "evaluate", "Assess claims", "epistemic:query-assessments", "Find assessments",
            "Look up assessments by mode, category, confidence, observer, or target.",
            "doc", Look, Query, Intermediate, Local),
        SpecTool::new(T, TL, "evaluate", "Assess claims", "epistemic:compare-assessments", "Compare assessments",
            "Set two assessments of the same thing side by side.",
            "doc", Look, Query, Intermediate, Local),
        SpecTool::new(T, TL, "evaluate", "Assess claims", "epistemic:assess-recursive", "Assess an assessment",
            "Judge someone else's assessment, including why they might disagree.",
            "doc", RunAction, Mutate, Expert, Local),
        SpecTool::new(T, TL, "evaluate", "Assess claims", "epistemic:export-assessment", "Save the assessment",
            "Write this assessment out as a file.",
            "doc", RunAction, Mutate, Intermediate, Local),
        SpecTool::new(T, TL, "evaluate", "Assess claims", "epistemic:link-to-investigation", "Link to a case",
            "Connect this assessment to a case hypothesis.",
            "doc", RunAction, Mutate, Intermediate, Local),
        SpecTool::new(T, TL, "evaluate", "Assess claims", "epistemic:link-to-research", "Link to a finding",
            "Connect this assessment to a research finding.",
            "doc", RunAction, Mutate, Intermediate, Local),
        // perspective (7)
        SpecTool::new(T, TL, "perspective", "Points of view", "epistemic:register-perspective", "Register a viewpoint",
            "Record who is looking, what kind of observer they are, and how much they can see.",
            "doc", RunAction, Mutate, Novice, Local),
        SpecTool::new(T, TL, "perspective", "Points of view", "epistemic:add-bias", "Note a bias",
            "Record a known slant in this observer's viewpoint.",
            "doc", RunAction, Mutate, Intermediate, Local),
        SpecTool::new(T, TL, "perspective", "Points of view", "epistemic:query-perspectives", "Find viewpoints",
            "List every recorded viewpoint on the selected target.",
            "doc", Look, Query, Intermediate, Local),
        SpecTool::new(T, TL, "perspective", "Points of view", "epistemic:compare-perspectives", "Compare viewpoints",
            "Show where observers agree, disagree, and why.",
            "doc", Look, Query, Intermediate, Local),
        SpecTool::new(T, TL, "perspective", "Points of view", "epistemic:detect-perspective-conflict", "Find viewpoint clashes",
            "Flag observers who classify the same thing differently.",
            "doc", Look, Query, Expert, Local),
        SpecTool::new(T, TL, "perspective", "Points of view", "epistemic:assess-perspective-coverage", "Who has not spoken",
            "See which kinds of observer have not yet weighed in.",
            "doc", Look, Query, Expert, Local),
        SpecTool::new(T, TL, "perspective", "Points of view", "epistemic:reconcile-perspectives", "Reconcile viewpoints",
            "Try to settle a clash, or keep the disagreement on the record.",
            "doc", RunAction, Mutate, Expert, Local),
        // intentionality (6)
        SpecTool::new(T, TL, "intentionality", "Intent and mistakes", "epistemic:assess-intentionality", "Judge intent",
            "Say whether this act was meant, careless, accidental, forced, or habitual.",
            "doc", RunAction, Mutate, Intermediate, Local),
        SpecTool::new(T, TL, "intentionality", "Intent and mistakes", "epistemic:classify-mistake", "Classify a mistake",
            "Name the kind of mistake, how serious it is, and whether it can be fixed.",
            "doc", RunAction, Mutate, Intermediate, Local),
        SpecTool::new(T, TL, "intentionality", "Intent and mistakes", "epistemic:query-intentionality", "Find intent notes",
            "Look up intent judgements by kind, confidence, or actor.",
            "doc", Look, Query, Intermediate, Local),
        SpecTool::new(T, TL, "intentionality", "Intent and mistakes", "epistemic:query-mistakes", "Find mistakes",
            "Look up mistake notes by kind, seriousness, or how often they repeat.",
            "doc", Look, Query, Intermediate, Local),
        SpecTool::new(T, TL, "intentionality", "Intent and mistakes", "epistemic:detect-mistake-patterns", "Find repeating mistakes",
            "Spot repeating mistake types, slants, or skill gaps for this actor.",
            "doc", Look, Query, Expert, Local),
        SpecTool::new(T, TL, "intentionality", "Intent and mistakes", "epistemic:compare-intentionality", "Compare intent notes",
            "Set different intent judgements of the same act side by side.",
            "doc", Look, Query, Intermediate, Local),
        // grounding (5)
        SpecTool::new(T, TL, "grounding", "What it rests on", "epistemic:assess-grounding", "Say what it rests on",
            "Record whether this act rests on seeing, guessing, instruction, feeling, habit, or fiction.",
            "doc", RunAction, Mutate, Intermediate, Live("Inference.grounding")),
        SpecTool::new(T, TL, "grounding", "What it rests on", "epistemic:query-grounding", "Find grounding notes",
            "Look up what acts rest on, and whether others can check it.",
            "doc", Look, Query, Intermediate, Local),
        SpecTool::new(T, TL, "grounding", "What it rests on", "epistemic:detect-ungrounded-behaviour", "Find ungrounded acts",
            "Flag acts that have no stated basis.",
            "doc", Look, Query, Intermediate, Live("Inference.detect_ungrounded")),
        SpecTool::new(T, TL, "grounding", "What it rests on", "epistemic:verify-grounding", "Check the basis",
            "See whether other observers can confirm what this act rests on.",
            "doc", Look, Query, Intermediate, Live("Inference.grounding")),
        SpecTool::new(T, TL, "grounding", "What it rests on", "epistemic:compare-grounding", "Compare the basis",
            "Set different grounding notes for the same act side by side.",
            "doc", Look, Query, Intermediate, Local),
        // fiction (6)
        SpecTool::new(T, TL, "fiction", "Fact or fiction", "epistemic:classify-reality", "Classify fact or fiction",
            "Say whether this writing is non-fiction, fiction, or a blend.",
            "doc", RunAction, Mutate, Novice, Local),
        SpecTool::new(T, TL, "fiction", "Fact or fiction", "epistemic:query-classifications", "Find classifications",
            "Look up fact-or-fiction labels by kind, confidence, or dispute.",
            "doc", Look, Query, Intermediate, Local),
        SpecTool::new(T, TL, "fiction", "Fact or fiction", "epistemic:detect-deceptive-fiction", "Find fiction sold as fact",
            "Flag fiction presented as non-fiction as if it were true.",
            "doc", Look, Query, Expert, Local),
        SpecTool::new(T, TL, "fiction", "Fact or fiction", "epistemic:detect-blended-content", "Find mixed content",
            "Flag writing that mixes fiction and non-fiction, such as myth, legend, or marketing.",
            "doc", Look, Query, Intermediate, Local),
        SpecTool::new(T, TL, "fiction", "Fact or fiction", "epistemic:compare-classifications", "Compare fact/fiction labels",
            "Set different fact-or-fiction labels for the same writing side by side.",
            "doc", Look, Query, Intermediate, Local),
        SpecTool::new(T, TL, "fiction", "Fact or fiction", "epistemic:trace-fiction-to-reality", "Trace fiction to the real",
            "Follow how this fiction points at real people, places, or events.",
            "doc", Look, Query, Expert, Local),
        // sentiment (10)
        SpecTool::new(T, TL, "sentiment", "Feeling", "epistemic:assess-sentiment", "Note the feeling",
            "Record how someone feels toward this, how strongly, and whether it seems genuine.",
            "doc", RunAction, Mutate, Novice, Local),
        SpecTool::new(T, TL, "sentiment", "Feeling", "epistemic:set-sentiment-dimension", "Score the feeling",
            "Set a score for warmth, energy, control, certainty, moral tone, beauty, irony, or sarcasm.",
            "doc", RunAction, Mutate, Intermediate, Local),
        SpecTool::new(T, TL, "sentiment", "Feeling", "epistemic:link-sentiment-to-reality", "Link feeling to fact/fiction",
            "Note whether this feeling is aimed at something real or something made up.",
            "doc", RunAction, Mutate, Intermediate, Local),
        SpecTool::new(T, TL, "sentiment", "Feeling", "epistemic:query-sentiment", "Find feelings",
            "Look up recorded feelings by kind, strength, genuineness, person, or target.",
            "doc", Look, Query, Intermediate, Local),
        SpecTool::new(T, TL, "sentiment", "Feeling", "epistemic:analyse-sentiment-trends", "Feeling over time",
            "See how feeling toward this has changed over time.",
            "doc", Look, Query, Intermediate, Local),
        SpecTool::new(T, TL, "sentiment", "Feeling", "epistemic:detect-sentiment-manipulation", "Find pushed feeling",
            "Flag coordinated or amplified feeling that may be manufactured.",
            "doc", Look, Query, Expert, Local),
        SpecTool::new(T, TL, "sentiment", "Feeling", "epistemic:detect-performed-sentiment", "Find performed feeling",
            "Flag expressed feeling that likely differs from what is actually felt.",
            "doc", Look, Query, Expert, Local),
        SpecTool::new(T, TL, "sentiment", "Feeling", "epistemic:map-sentiment-network", "Map feeling flow",
            "Show who is shaping whose feeling in this group.",
            "doc", Look, Query, Expert, Local),
        SpecTool::new(T, TL, "sentiment", "Feeling", "epistemic:compare-sentiment", "Compare feelings",
            "Set different people's feelings toward the same thing side by side.",
            "doc", Look, Query, Intermediate, Local),
        SpecTool::new(T, TL, "sentiment", "Feeling", "epistemic:detect-sentiment-reality-mismatch", "Feeling out of scale",
            "Flag feeling far stronger than the reality of its target, such as rage at a fictional character.",
            "doc", Look, Query, Expert, Local),
        // ungrounded-generation (12)
        SpecTool::new(T, TL, "ungrounded-generation", "Ungrounded output", "epistemic:create-ug-instance", "Record ungrounded output",
            "Record a model output that is not grounded, including the model and how it was sampled.",
            "doc", RunAction, Mutate, Intermediate, Local),
        SpecTool::new(T, TL, "ungrounded-generation", "Ungrounded output", "epistemic:set-ug-cause", "Set the cause",
            "Name why this ungrounded output happened, such as a training gap or a retrieval miss.",
            "doc", RunAction, Mutate, Intermediate, Local),
        SpecTool::new(T, TL, "ungrounded-generation", "Ungrounded output", "epistemic:set-ug-consequence", "Set the consequence",
            "Name what went wrong in the output, such as a false fact or a false citation. No intent is implied.",
            "doc", RunAction, Mutate, Intermediate, Local),
        SpecTool::new(T, TL, "ungrounded-generation", "Ungrounded output", "epistemic:set-ug-detection", "Record how it was found",
            "Note how this ungrounded output was caught, and by whom.",
            "doc", RunAction, Mutate, Intermediate, Local),
        SpecTool::new(T, TL, "ungrounded-generation", "Ungrounded output", "epistemic:set-ug-mitigation", "Record the fix",
            "Note what was done or recommended to stop this kind of ungrounded output.",
            "doc", RunAction, Mutate, Intermediate, Local),
        SpecTool::new(T, TL, "ungrounded-generation", "Ungrounded output", "epistemic:set-ug-calibration", "Set confidence gap",
            "Record how far the model's stated confidence is from how well the output is grounded.",
            "doc", RunAction, Mutate, Expert, Local),
        SpecTool::new(T, TL, "ungrounded-generation", "Ungrounded output", "epistemic:query-ug-instances", "Find ungrounded output",
            "Look up ungrounded outputs by cause, consequence, model, or how they were found.",
            "doc", Look, Query, Intermediate, Local),
        SpecTool::new(T, TL, "ungrounded-generation", "Ungrounded output", "epistemic:query-ug-causes", "List the causes",
            "Show every cause recorded for this ungrounded output.",
            "doc", Look, Query, Intermediate, Local),
        SpecTool::new(T, TL, "ungrounded-generation", "Ungrounded output", "epistemic:query-ug-consequences", "List the consequences",
            "Show every consequence recorded for this ungrounded output.",
            "doc", Look, Query, Intermediate, Local),
        SpecTool::new(T, TL, "ungrounded-generation", "Ungrounded output", "epistemic:detect-ug-patterns", "Find repeating misses",
            "Spot repeating causes, consequences, and confidence gaps for this model.",
            "doc", Look, Query, Expert, Live("Inference.detect_ungrounded")),
        SpecTool::new(T, TL, "ungrounded-generation", "Ungrounded output", "epistemic:compare-ug-instances", "Compare ungrounded outputs",
            "Set two ungrounded outputs side by side.",
            "doc", Look, Query, Intermediate, Local),
        SpecTool::new(T, TL, "ungrounded-generation", "Ungrounded output", "epistemic:query-cause-consequence-matrix", "Cause and consequence pairs",
            "Show known pairings of cause and consequence, with likely fixes.",
            "doc", Look, Query, Expert, Local),
    ];
    ROWS
}
