//! Interactive hypermedia spec tools from TOOLBOX_HYPERMEDIA_SPEC_2.md §5
//! (interactive, second-screen, social, packaging, sync, inspect).

use super::row::{Contract, SpecTool};
use crate::browser::tool_proficiency::Proficiency;
use crate::tool_chest::core::intent_bus::ActionType;
use crate::tool_chest::core::tool::ToolKind;

const T: &str = "hypermedia";
const TL: &str = "Interactive";

pub fn rows() -> &'static [SpecTool] {
    static ROWS: &[SpecTool] = &[
        SpecTool::new(
            T,
            TL,
            "interactive",
            "Overlays",
            "hypermedia:add-trigger",
            "Add a trigger",
            "Put a cue on the timeline that starts something.",
            "timeline",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Novice,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "interactive",
            "Overlays",
            "hypermedia:trigger-condition",
            "Set when it fires",
            "Say what must be true before this trigger runs.",
            "timeline",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Intermediate,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "interactive",
            "Overlays",
            "hypermedia:trigger-action",
            "Set what it does",
            "Choose what happens when this trigger fires.",
            "timeline",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Intermediate,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "interactive",
            "Overlays",
            "hypermedia:overlay-create",
            "Make an overlay",
            "Create a graphic that sits on the picture.",
            "timeline",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Novice,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "interactive",
            "Overlays",
            "hypermedia:overlay-edit",
            "Edit overlay",
            "Change the writing or picture in this overlay.",
            "timeline",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Intermediate,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "interactive",
            "Overlays",
            "hypermedia:overlay-timeline",
            "Place overlay",
            "Set when this overlay appears and how long it stays.",
            "timeline",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Intermediate,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "interactive",
            "Overlays",
            "hypermedia:interactive-preview",
            "Preview the show",
            "Watch the picture with overlays as the audience would.",
            "timeline",
            ToolKind::Query,
            ActionType::Query,
            Proficiency::Novice,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "interactive",
            "Overlays",
            "hypermedia:interactive-test",
            "Run a test",
            "Walk through a test path of the interactive show.",
            "timeline",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Expert,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "second-screen",
            "Second screen",
            "hypermedia:companion-app-config",
            "Companion app",
            "Set up the phone or tablet that rides along with the show.",
            "screen",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Intermediate,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "second-screen",
            "Second screen",
            "hypermedia:sync-stream-setup",
            "Sync the stream",
            "Keep the second screen in time with the broadcast.",
            "screen",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Expert,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "second-screen",
            "Second screen",
            "hypermedia:remote-control-map",
            "Map the remote",
            "Tie remote keys to actions on the overlay.",
            "screen",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Intermediate,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "second-screen",
            "Second screen",
            "hypermedia:second-screen-preview",
            "Preview second screen",
            "See what the companion screen will show.",
            "screen",
            ToolKind::Query,
            ActionType::Query,
            Proficiency::Novice,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "second-screen",
            "Second screen",
            "hypermedia:push-notification",
            "Push a notice",
            "Send a short notice to paired screens at a cue.",
            "screen",
            ToolKind::RunAction,
            ActionType::Publish,
            Proficiency::Intermediate,
            Contract::Live("Pulse.publish"),
        ),
        SpecTool::new(
            T,
            TL,
            "second-screen",
            "Second screen",
            "hypermedia:screen-pairing",
            "Pair a screen",
            "Join a second screen to this show.",
            "screen",
            ToolKind::RunAction,
            ActionType::Publish,
            Proficiency::Intermediate,
            Contract::Live("Pulse.publish_presence"),
        ),
        SpecTool::new(
            T,
            TL,
            "social",
            "Audience",
            "hypermedia:chat-overlay",
            "Show chat",
            "Put live chat on the picture.",
            "social",
            ToolKind::RunAction,
            ActionType::Publish,
            Proficiency::Novice,
            Contract::Live("Pulse.publish"),
        ),
        SpecTool::new(
            T,
            TL,
            "social",
            "Audience",
            "hypermedia:poll-create",
            "Start a poll",
            "Ask the audience a question with timed choices.",
            "social",
            ToolKind::RunAction,
            ActionType::Publish,
            Proficiency::Novice,
            Contract::Live("Pulse.publish"),
        ),
        SpecTool::new(
            T,
            TL,
            "social",
            "Audience",
            "hypermedia:reaction-overlay",
            "Show reactions",
            "Put audience reactions on the picture.",
            "social",
            ToolKind::RunAction,
            ActionType::Publish,
            Proficiency::Intermediate,
            Contract::Live("Pulse.publish"),
        ),
        SpecTool::new(
            T,
            TL,
            "social",
            "Audience",
            "hypermedia:share-button",
            "Share button",
            "Add a share control to the overlay.",
            "social",
            ToolKind::RunAction,
            ActionType::Publish,
            Proficiency::Novice,
            Contract::Live("Pulse.publish"),
        ),
        SpecTool::new(
            T,
            TL,
            "social",
            "Audience",
            "hypermedia:co-view-sync",
            "Watch together",
            "Keep everyone in the room on the same moment.",
            "social",
            ToolKind::RunAction,
            ActionType::Publish,
            Proficiency::Intermediate,
            Contract::Live("Pulse.publish_presence"),
        ),
        SpecTool::new(
            T,
            TL,
            "social",
            "Audience",
            "hypermedia:social-moderation",
            "Moderation rules",
            "Set what chat and reactions are allowed.",
            "social",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Expert,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "packaging",
            "Packaging",
            "hypermedia:hbbtv-package",
            "Pack the app",
            "Build the broadcast app package.",
            "package",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Expert,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "packaging",
            "Packaging",
            "hypermedia:ait-config",
            "App table",
            "Fill the application information table for the package.",
            "package",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Expert,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "packaging",
            "Packaging",
            "hypermedia:dvb-stream-bind",
            "Bind the stream",
            "Tie this package to a broadcast stream.",
            "package",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Expert,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "packaging",
            "Packaging",
            "hypermedia:drm-config",
            "Rights lock",
            "Set the lock that protects the stream.",
            "package",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Expert,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "packaging",
            "Packaging",
            "hypermedia:app-data-bundle",
            "Bundle app data",
            "Pack extra app files with the package.",
            "package",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Expert,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "packaging",
            "Packaging",
            "hypermedia:package-validate",
            "Check the package",
            "Check the package against the broadcast rules.",
            "package",
            ToolKind::Query,
            ActionType::Query,
            Proficiency::Expert,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "packaging",
            "Packaging",
            "hypermedia:package-export",
            "Export package",
            "Write the package out for the broadcaster.",
            "package",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Expert,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "sync",
            "Timing",
            "hypermedia:timeline-sync",
            "Sync the timeline",
            "Choose what the timeline keeps time with.",
            "timeline",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Intermediate,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "sync",
            "Timing",
            "hypermedia:event-sync",
            "Sync on an event",
            "Fire a sync when a named event happens.",
            "timeline",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Intermediate,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "sync",
            "Timing",
            "hypermedia:wall-clock-sync",
            "Wall-clock sync",
            "Keep time with the real-world clock.",
            "timeline",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Expert,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "sync",
            "Timing",
            "hypermedia:scte35-marker",
            "Ad-break marker",
            "Put an ad-break marker on the timeline.",
            "timeline",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Expert,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "sync",
            "Timing",
            "hypermedia:sync-test",
            "Test the sync",
            "Measure how tightly the screens stay together.",
            "timeline",
            ToolKind::Query,
            ActionType::Query,
            Proficiency::Expert,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "inspect",
            "Inspect",
            "hypermedia:package-inspector",
            "Inspect package",
            "Open the package and list what is inside.",
            "inspect",
            ToolKind::Query,
            ActionType::Query,
            Proficiency::Intermediate,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "inspect",
            "Inspect",
            "hypermedia:stream-analyser",
            "Analyse the stream",
            "Check bitrate, codec, and continuity.",
            "inspect",
            ToolKind::Query,
            ActionType::Query,
            Proficiency::Intermediate,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "inspect",
            "Inspect",
            "hypermedia:device-emulator",
            "Emulate a device",
            "See the show as a chosen TV or box would.",
            "inspect",
            ToolKind::Query,
            ActionType::Query,
            Proficiency::Intermediate,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "inspect",
            "Inspect",
            "hypermedia:bandwidth-simulator",
            "Simulate bandwidth",
            "See the show under a slower connection.",
            "inspect",
            ToolKind::Query,
            ActionType::Query,
            Proficiency::Expert,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "inspect",
            "Inspect",
            "hypermedia:metadata-view",
            "Show metadata",
            "Read the facts stored on this interactive asset.",
            "inspect",
            ToolKind::Query,
            ActionType::Query,
            Proficiency::Intermediate,
            Contract::Local,
        ),
    ];
    ROWS
}
