//! Image-editing spec tools from TOOLBOX_HYPERMEDIA_SPEC.md §1.
use super::row::{Contract, SpecTool};
use crate::browser::tool_proficiency::Proficiency;
use crate::tool_chest::core::intent_bus::ActionType;
use crate::tool_chest::core::tool::ToolKind;

pub fn rows() -> &'static [SpecTool] {
    static ROWS: &[SpecTool] = &[
        SpecTool::new(
            "image",
            "Pictures",
            "layers",
            "Layers",
            "image:add-layer",
            "Add a layer",
            "Put a new layer on this picture.",
            "image",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Novice,
            Contract::Local,
        ),
        SpecTool::new(
            "image",
            "Pictures",
            "layers",
            "Layers",
            "image:delete-layer",
            "Remove a layer",
            "Take this layer off the picture.",
            "image",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Novice,
            Contract::Local,
        ),
        SpecTool::new(
            "image",
            "Pictures",
            "layers",
            "Layers",
            "image:reorder-layer",
            "Move a layer",
            "Change which layer sits in front.",
            "image",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Intermediate,
            Contract::Local,
        ),
        SpecTool::new(
            "image",
            "Pictures",
            "layers",
            "Layers",
            "image:merge-layers",
            "Merge layers",
            "Combine selected layers into one.",
            "image",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Intermediate,
            Contract::Local,
        ),
        SpecTool::new(
            "image",
            "Pictures",
            "layers",
            "Layers",
            "image:duplicate-layer",
            "Copy a layer",
            "Make a second copy of this layer.",
            "image",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Novice,
            Contract::Local,
        ),
        SpecTool::new(
            "image",
            "Pictures",
            "layers",
            "Layers",
            "image:group-layers",
            "Group layers",
            "Bundle selected layers together.",
            "image",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Intermediate,
            Contract::Local,
        ),
        SpecTool::new(
            "image",
            "Pictures",
            "layers",
            "Layers",
            "image:layer-opacity",
            "Layer fade",
            "Set how see-through this layer is.",
            "image",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Intermediate,
            Contract::Local,
        ),
        SpecTool::new(
            "image",
            "Pictures",
            "layers",
            "Layers",
            "image:layer-blend-mode",
            "Blend layers",
            "Choose how this layer mixes with the ones below.",
            "image",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Intermediate,
            Contract::Local,
        ),
        SpecTool::new(
            "image",
            "Pictures",
            "brushes",
            "Brushes",
            "image:brush-select",
            "Choose a brush",
            "Pick the brush shape for painting.",
            "image",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Novice,
            Contract::Local,
        ),
        SpecTool::new(
            "image",
            "Pictures",
            "brushes",
            "Brushes",
            "image:brush-size",
            "Brush size",
            "Set how wide the brush is.",
            "image",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Novice,
            Contract::Local,
        ),
        SpecTool::new(
            "image",
            "Pictures",
            "brushes",
            "Brushes",
            "image:brush-opacity",
            "Brush fade",
            "Set how strong each brush stroke is.",
            "image",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Intermediate,
            Contract::Local,
        ),
        SpecTool::new(
            "image",
            "Pictures",
            "brushes",
            "Brushes",
            "image:brush-hardness",
            "Brush edge",
            "Soften or harden the brush edge.",
            "image",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Intermediate,
            Contract::Local,
        ),
        SpecTool::new(
            "image",
            "Pictures",
            "brushes",
            "Brushes",
            "image:brush-flow",
            "Brush flow",
            "Set how quickly colour builds as you paint.",
            "image",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Intermediate,
            Contract::Local,
        ),
        SpecTool::new(
            "image",
            "Pictures",
            "brushes",
            "Brushes",
            "image:brush-colour",
            "Brush colour",
            "Set the colour this brush paints with.",
            "image",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Novice,
            Contract::Local,
        ),
        SpecTool::new(
            "image",
            "Pictures",
            "brushes",
            "Brushes",
            "image:eraser",
            "Eraser",
            "Rub pixels off the active layer.",
            "image",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Novice,
            Contract::Local,
        ),
        SpecTool::new(
            "image",
            "Pictures",
            "brushes",
            "Brushes",
            "image:clone-stamp",
            "Clone stamp",
            "Copy pixels from one spot to another.",
            "image",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Intermediate,
            Contract::Local,
        ),
        SpecTool::new(
            "image",
            "Pictures",
            "brushes",
            "Brushes",
            "image:heal-brush",
            "Heal brush",
            "Blend nearby texture over a blemish.",
            "image",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Expert,
            Contract::Local,
        ),
        SpecTool::new(
            "image",
            "Pictures",
            "brushes",
            "Brushes",
            "image:gradient-fill",
            "Gradient fill",
            "Fill an area with a colour fade.",
            "image",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Intermediate,
            Contract::Local,
        ),
        SpecTool::new(
            "image",
            "Pictures",
            "selection",
            "Selection",
            "image:rect-select",
            "Box select",
            "Draw a rectangle to select part of the picture.",
            "image",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Novice,
            Contract::Local,
        ),
        SpecTool::new(
            "image",
            "Pictures",
            "selection",
            "Selection",
            "image:lasso-select",
            "Lasso",
            "Draw a freehand outline to select.",
            "image",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Intermediate,
            Contract::Local,
        ),
        SpecTool::new(
            "image",
            "Pictures",
            "selection",
            "Selection",
            "image:magic-wand",
            "Magic wand",
            "Select nearby pixels of a similar colour.",
            "image",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Intermediate,
            Contract::Local,
        ),
        SpecTool::new(
            "image",
            "Pictures",
            "selection",
            "Selection",
            "image:vector-path-select",
            "Select along a path",
            "Select along a drawn path.",
            "image",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Expert,
            Contract::Local,
        ),
        SpecTool::new(
            "image",
            "Pictures",
            "selection",
            "Selection",
            "image:invert-selection",
            "Invert selection",
            "Select everything that is not selected.",
            "image",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Novice,
            Contract::Local,
        ),
        SpecTool::new(
            "image",
            "Pictures",
            "selection",
            "Selection",
            "image:feather-selection",
            "Soften selection",
            "Soften the edge of the selection.",
            "image",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Intermediate,
            Contract::Local,
        ),
        SpecTool::new(
            "image",
            "Pictures",
            "selection",
            "Selection",
            "image:refine-edge",
            "Refine edge",
            "Tighten the selection around hair or fine edges.",
            "image",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Expert,
            Contract::Local,
        ),
        SpecTool::new(
            "image",
            "Pictures",
            "filters",
            "Filters",
            "image:gaussian-blur",
            "Soften",
            "Soften this picture with a gentle blur.",
            "image",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Novice,
            Contract::Live("ComputerVision.gaussian_blur"),
        ),
        SpecTool::new(
            "image",
            "Pictures",
            "filters",
            "Filters",
            "image:sharpen",
            "Sharpen",
            "Make edges in this picture crisper.",
            "image",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Intermediate,
            Contract::Local,
        ),
        SpecTool::new(
            "image",
            "Pictures",
            "filters",
            "Filters",
            "image:colour-balance",
            "Colour balance",
            "Shift shadows, midtones, and highlights.",
            "image",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Intermediate,
            Contract::Local,
        ),
        SpecTool::new(
            "image",
            "Pictures",
            "filters",
            "Filters",
            "image:hue-saturation",
            "Hue and saturation",
            "Shift colour, richness, and lightness.",
            "image",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Intermediate,
            Contract::Local,
        ),
        SpecTool::new(
            "image",
            "Pictures",
            "filters",
            "Filters",
            "image:curves",
            "Tone curve",
            "Bend the light and dark of this picture.",
            "image",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Expert,
            Contract::Local,
        ),
        SpecTool::new(
            "image",
            "Pictures",
            "filters",
            "Filters",
            "image:levels",
            "Levels",
            "Set black, white, and mid-grey points.",
            "image",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Expert,
            Contract::Local,
        ),
        SpecTool::new(
            "image",
            "Pictures",
            "filters",
            "Filters",
            "image:distort",
            "Distort",
            "Warp this picture with a lens, ripple, wave, or twirl.",
            "image",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Expert,
            Contract::Local,
        ),
        SpecTool::new(
            "image",
            "Pictures",
            "filters",
            "Filters",
            "image:noise-reduction",
            "Reduce noise",
            "Smooth grain while keeping detail.",
            "image",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Expert,
            Contract::Local,
        ),
        SpecTool::new(
            "image",
            "Pictures",
            "masks",
            "Masks",
            "image:add-layer-mask",
            "Add a mask",
            "Hide parts of this layer without deleting them.",
            "image",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Novice,
            Contract::Local,
        ),
        SpecTool::new(
            "image",
            "Pictures",
            "masks",
            "Masks",
            "image:apply-mask",
            "Apply mask",
            "Bake the mask into the layer for good.",
            "image",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Intermediate,
            Contract::Local,
        ),
        SpecTool::new(
            "image",
            "Pictures",
            "masks",
            "Masks",
            "image:invert-mask",
            "Invert mask",
            "Swap what the mask shows and hides.",
            "image",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Intermediate,
            Contract::Local,
        ),
        SpecTool::new(
            "image",
            "Pictures",
            "masks",
            "Masks",
            "image:vector-mask",
            "Path mask",
            "Hide parts of this layer using a drawn path.",
            "image",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Expert,
            Contract::Local,
        ),
        SpecTool::new(
            "image",
            "Pictures",
            "masks",
            "Masks",
            "image:clipping-mask",
            "Clip to layer",
            "Show this layer only where the layer below has shape.",
            "image",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Expert,
            Contract::Local,
        ),
        SpecTool::new(
            "image",
            "Pictures",
            "colour",
            "Colour",
            "image:colour-picker",
            "Pick colour",
            "Sample a colour from the picture and make it active.",
            "image",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Novice,
            Contract::Local,
        ),
        SpecTool::new(
            "image",
            "Pictures",
            "colour",
            "Colour",
            "image:sample-colour",
            "Sample colour",
            "Read the colour at a point without changing the brush.",
            "image",
            ToolKind::Query,
            ActionType::Query,
            Proficiency::Intermediate,
            Contract::Local,
        ),
        SpecTool::new(
            "image",
            "Pictures",
            "colour",
            "Colour",
            "image:colour-profile",
            "Colour profile",
            "Assign a colour space to this picture.",
            "image",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Intermediate,
            Contract::Local,
        ),
        SpecTool::new(
            "image",
            "Pictures",
            "colour",
            "Colour",
            "image:convert-profile",
            "Convert colour space",
            "Convert this picture to another colour space.",
            "image",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Expert,
            Contract::Local,
        ),
        SpecTool::new(
            "image",
            "Pictures",
            "colour",
            "Colour",
            "image:gradient-map",
            "Gradient map",
            "Recolour the picture from dark to light along a gradient.",
            "image",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Expert,
            Contract::Local,
        ),
        SpecTool::new(
            "image",
            "Pictures",
            "colour",
            "Colour",
            "image:posterise",
            "Posterise",
            "Flatten the picture into fewer colour steps.",
            "image",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Intermediate,
            Contract::Local,
        ),
        SpecTool::new(
            "image",
            "Pictures",
            "vector",
            "Vector",
            "image:pen-tool",
            "Pen",
            "Draw a path with points and curves.",
            "image",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Intermediate,
            Contract::Local,
        ),
        SpecTool::new(
            "image",
            "Pictures",
            "vector",
            "Vector",
            "image:shape-tool",
            "Shape",
            "Draw a rectangle, ellipse, polygon, or star.",
            "image",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Novice,
            Contract::Local,
        ),
        SpecTool::new(
            "image",
            "Pictures",
            "vector",
            "Vector",
            "image:path-edit",
            "Edit path",
            "Move a point on a drawn path.",
            "image",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Intermediate,
            Contract::Local,
        ),
        SpecTool::new(
            "image",
            "Pictures",
            "vector",
            "Vector",
            "image:text-on-path",
            "Text on a path",
            "Place writing along a drawn path.",
            "image",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Expert,
            Contract::Local,
        ),
        SpecTool::new(
            "image",
            "Pictures",
            "vector",
            "Vector",
            "image:vector-export",
            "Export paths",
            "Save the drawn paths as a drawing file.",
            "image",
            ToolKind::Query,
            ActionType::Query,
            Proficiency::Expert,
            Contract::Local,
        ),
        SpecTool::new(
            "image",
            "Pictures",
            "vector",
            "Vector",
            "image:svg-import",
            "Import drawing",
            "Bring a drawing into a vector layer.",
            "image",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Expert,
            Contract::Local,
        ),
        SpecTool::new(
            "image",
            "Pictures",
            "inspect",
            "Inspect",
            "image:histogram",
            "Tones",
            "Show how light and dark this picture is.",
            "image",
            ToolKind::Query,
            ActionType::Query,
            Proficiency::Novice,
            Contract::Live("ComputerVision.histogram"),
        ),
        SpecTool::new(
            "image",
            "Pictures",
            "inspect",
            "Inspect",
            "image:colour-sampler",
            "Colour samples",
            "Read colour at several points on the picture.",
            "image",
            ToolKind::Query,
            ActionType::Query,
            Proficiency::Intermediate,
            Contract::Local,
        ),
        SpecTool::new(
            "image",
            "Pictures",
            "inspect",
            "Inspect",
            "image:info-probe",
            "Pixel info",
            "Show position, colour, and layer at this point.",
            "image",
            ToolKind::Query,
            ActionType::Query,
            Proficiency::Novice,
            Contract::Local,
        ),
        SpecTool::new(
            "image",
            "Pictures",
            "inspect",
            "Inspect",
            "image:metadata-view",
            "Picture facts",
            "Show size, colour space, bit depth, and print resolution.",
            "image",
            ToolKind::Query,
            ActionType::Query,
            Proficiency::Intermediate,
            Contract::Local,
        ),
        SpecTool::new(
            "image",
            "Pictures",
            "inspect",
            "Inspect",
            "image:profile-inspector",
            "Colour profile details",
            "Show the colour profile attached to this picture.",
            "image",
            ToolKind::Query,
            ActionType::Query,
            Proficiency::Expert,
            Contract::Local,
        ),
    ];
    ROWS
}
