//! Investigation and forecast chains from TOOLBOX_INVESTIGATION_SPEC.md.
//! New toolbox `investigation` (forensic + forecast chains).

use super::row::{Contract, SpecTool};
use crate::browser::tool_proficiency::Proficiency;
use crate::tool_chest::core::intent_bus::ActionType;
use crate::tool_chest::core::tool::ToolKind;
use ActionType::{Mutate, Query};
use Contract::{Live, Local};
use Proficiency::{Expert, Intermediate, Novice};
use ToolKind::{Query as Look, RunAction};

const T: &str = "investigation";
const TL: &str = "Investigation";

pub fn rows() -> &'static [SpecTool] {
    #[rustfmt::skip]
    static ROWS: &[SpecTool] = &[
        // case (11)
        SpecTool::new(T, TL, "case", "Case", "investigation:new-investigation", "Start a case",
            "Open a new investigation on this page.",
            "doc", RunAction, Mutate, Novice, Local),
        SpecTool::new(T, TL, "case", "Case", "investigation:set-mode", "Set case mode",
            "Say whether this case looks backward, forward, or both.",
            "doc", RunAction, Mutate, Intermediate, Local),
        SpecTool::new(T, TL, "case", "Case", "investigation:set-status", "Set case status",
            "Mark this case open, paused, closed, cold, reopened, or ongoing.",
            "doc", RunAction, Mutate, Novice, Local),
        SpecTool::new(T, TL, "case", "Case", "investigation:set-jurisdiction", "Set jurisdiction",
            "Record the legal or regulatory scope of this case.",
            "doc", RunAction, Mutate, Intermediate, Local),
        SpecTool::new(T, TL, "case", "Case", "investigation:add-subject", "Add a subject",
            "Add a person, organisation, system, event, or phenomenon to this case.",
            "doc", RunAction, Mutate, Novice, Local),
        SpecTool::new(T, TL, "case", "Case", "investigation:add-topic", "Add a topic",
            "Add a topic area this case covers.",
            "doc", RunAction, Mutate, Novice, Local),
        SpecTool::new(T, TL, "case", "Case", "investigation:add-event", "Add an event",
            "Add an event with time, place, and who was involved.",
            "doc", RunAction, Mutate, Novice, Local),
        SpecTool::new(T, TL, "case", "Case", "investigation:add-case", "Attach a case file",
            "Link a formal case file, number, and classification.",
            "doc", RunAction, Mutate, Intermediate, Local),
        SpecTool::new(T, TL, "case", "Case", "investigation:add-constituency", "Add a party",
            "Record a party with their role and how much they may see.",
            "doc", RunAction, Mutate, Intermediate, Local),
        SpecTool::new(T, TL, "case", "Case", "investigation:query-investigation", "Search the case",
            "Look up subjects, events, evidence, and hypotheses in this case.",
            "doc", Look, Query, Intermediate, Local),
        SpecTool::new(T, TL, "case", "Case", "investigation:export-findings", "Save the findings",
            "Write the case findings out as a report.",
            "doc", RunAction, Mutate, Intermediate, Local),
        // evidence (8)
        SpecTool::new(T, TL, "evidence", "Evidence", "investigation:collect-evidence", "Collect evidence",
            "Add a piece of evidence to the selected case.",
            "doc", RunAction, Mutate, Novice, Local),
        SpecTool::new(T, TL, "evidence", "Evidence", "investigation:set-reliability", "Set reliability",
            "Say how far this evidence can be trusted.",
            "doc", RunAction, Mutate, Intermediate, Local),
        SpecTool::new(T, TL, "evidence", "Evidence", "investigation:verify-evidence", "Check the evidence",
            "Check source, integrity, and cross-references for this evidence.",
            "doc", Look, Query, Intermediate, Local),
        SpecTool::new(T, TL, "evidence", "Evidence", "investigation:link-evidence-source", "Link the source",
            "Connect this evidence to the document, sensor, or testimony it came from.",
            "doc", RunAction, Mutate, Intermediate, Local),
        SpecTool::new(T, TL, "evidence", "Evidence", "investigation:tag-evidence", "Tag evidence",
            "Add labels so this evidence is easier to find later.",
            "doc", RunAction, Mutate, Novice, Local),
        SpecTool::new(T, TL, "evidence", "Evidence", "investigation:query-evidence", "Find evidence",
            "Look up evidence by kind, reliability, source, tags, or time.",
            "doc", Look, Query, Intermediate, Local),
        SpecTool::new(T, TL, "evidence", "Evidence", "investigation:redact-evidence", "Redact evidence",
            "Hide sensitive parts. Access rules still apply.",
            "doc", RunAction, Mutate, Expert, Local),
        SpecTool::new(T, TL, "evidence", "Evidence", "investigation:compare-evidence", "Compare evidence",
            "Set two pieces of evidence side by side for overlap or contradiction.",
            "doc", Look, Query, Intermediate, Local),
        // custody (5)
        SpecTool::new(T, TL, "custody", "Custody", "investigation:init-custody", "Start custody",
            "Begin a custody record for this evidence.",
            "doc", RunAction, Mutate, Intermediate, Local),
        SpecTool::new(T, TL, "custody", "Custody", "investigation:transfer-custody", "Hand over custody",
            "Record a custody transfer and why it happened.",
            "doc", RunAction, Mutate, Intermediate, Local),
        SpecTool::new(T, TL, "custody", "Custody", "investigation:record-transform", "Record a change",
            "Note a change made while in custody, such as a format conversion.",
            "doc", RunAction, Mutate, Intermediate, Local),
        SpecTool::new(T, TL, "custody", "Custody", "investigation:verify-custody", "Check custody",
            "See whether the custody chain has gaps.",
            "doc", Look, Query, Intermediate, Local),
        SpecTool::new(T, TL, "custody", "Custody", "investigation:custody-history", "Show custody history",
            "Show every holder and change for this evidence.",
            "doc", Look, Query, Intermediate, Local),
        // hypothesis (7)
        SpecTool::new(T, TL, "hypothesis", "Hypotheses", "investigation:propose-hypothesis", "Propose a hypothesis",
            "Add a hypothesis, optionally under another one.",
            "doc", RunAction, Mutate, Novice, Local),
        SpecTool::new(T, TL, "hypothesis", "Hypotheses", "investigation:set-hypothesis-status", "Set hypothesis status",
            "Mark this hypothesis proposed, testing, supported, confirmed, contradicted, disproven, or inconclusive.",
            "doc", RunAction, Mutate, Intermediate, Local),
        SpecTool::new(T, TL, "hypothesis", "Hypotheses", "investigation:evaluate-evidence", "Weigh evidence",
            "Say whether this evidence supports, contradicts, or is neutral to the hypothesis.",
            "doc", RunAction, Mutate, Intermediate, Local),
        SpecTool::new(T, TL, "hypothesis", "Hypotheses", "investigation:set-mutually-exclusive", "Mark as exclusive",
            "Say these two hypotheses cannot both be true.",
            "doc", RunAction, Mutate, Intermediate, Local),
        SpecTool::new(T, TL, "hypothesis", "Hypotheses", "investigation:query-hypotheses", "Find hypotheses",
            "Look up hypotheses by status, evidence count, or confidence.",
            "doc", Look, Query, Intermediate, Local),
        SpecTool::new(T, TL, "hypothesis", "Hypotheses", "investigation:hypothesis-summary", "Summarise a hypothesis",
            "Show supporting and contradicting evidence, with confidence.",
            "doc", Look, Query, Intermediate, Local),
        SpecTool::new(T, TL, "hypothesis", "Hypotheses", "investigation:rank-hypotheses", "Rank hypotheses",
            "Order hypotheses by how well the evidence supports them.",
            "doc", Look, Query, Intermediate, Local),
        // timeline (7)
        SpecTool::new(T, TL, "timeline", "Timeline", "investigation:create-timeline", "Start a timeline",
            "Create a timeline for this case.",
            "doc", RunAction, Mutate, Novice, Local),
        SpecTool::new(T, TL, "timeline", "Timeline", "investigation:add-entry", "Add a timeline entry",
            "Place an event, evidence, or hypothesis on the timeline.",
            "doc", RunAction, Mutate, Novice, Local),
        SpecTool::new(T, TL, "timeline", "Timeline", "investigation:set-time-precision", "Set time precision",
            "Say whether this time is exact, approximate, estimated, or unknown.",
            "doc", RunAction, Mutate, Intermediate, Local),
        SpecTool::new(T, TL, "timeline", "Timeline", "investigation:set-track", "Set the track",
            "Put this entry on a named track of a multi-track timeline.",
            "doc", RunAction, Mutate, Intermediate, Local),
        SpecTool::new(T, TL, "timeline", "Timeline", "investigation:query-timeline", "Search the timeline",
            "Look up timeline entries, optionally in a time range.",
            "doc", Look, Query, Intermediate, Local),
        SpecTool::new(T, TL, "timeline", "Timeline", "investigation:detect-sequences", "Find sequences",
            "Spot before/after, simultaneous, or repeating patterns.",
            "doc", Look, Query, Expert, Local),
        SpecTool::new(T, TL, "timeline", "Timeline", "investigation:reconcile-timelines", "Reconcile timelines",
            "Find overlaps, clashes, and gaps between two timelines.",
            "doc", Look, Query, Expert, Local),
        // link-analysis (7)
        SpecTool::new(T, TL, "link-analysis", "Links", "investigation:add-link", "Add a link",
            "Connect two people, events, or pieces of evidence with a typed link.",
            "graph", RunAction, Mutate, Novice, Local),
        SpecTool::new(T, TL, "link-analysis", "Links", "investigation:link-evidence", "Support the link",
            "Attach evidence that supports this link.",
            "graph", RunAction, Mutate, Intermediate, Local),
        SpecTool::new(T, TL, "link-analysis", "Links", "investigation:query-links", "Find links",
            "Look up links by type, strength, or who they connect.",
            "graph", Look, Query, Intermediate, Local),
        SpecTool::new(T, TL, "link-analysis", "Links", "investigation:find-path", "Find a path",
            "Find how two people or events connect through the link graph.",
            "graph", Look, Query, Intermediate, Local),
        SpecTool::new(T, TL, "link-analysis", "Links", "investigation:detect-clusters", "Find clusters",
            "Find tightly connected groups in the link graph.",
            "graph", Look, Query, Expert, Local),
        SpecTool::new(T, TL, "link-analysis", "Links", "investigation:compute-centrality", "Measure centrality",
            "See who sits at the centre of this network.",
            "graph", Look, Query, Expert, Local),
        SpecTool::new(T, TL, "link-analysis", "Links", "investigation:visualise-links", "Show the links",
            "Lay out the link graph so it can be read.",
            "graph", Look, Query, Intermediate, Local),
        // hypothesis-graph (26 named tools)
        SpecTool::new(T, TL, "hypothesis-graph", "Hypothesis graph", "investigation:create-hypothesis-graph", "Start a hypothesis graph",
            "Create a living, versioned hypothesis graph for this case.",
            "graph", RunAction, Mutate, Intermediate, Local),
        SpecTool::new(T, TL, "hypothesis-graph", "Hypothesis graph", "investigation:add-to-graph", "Add to the graph",
            "Add a hypothesis to the graph as a contribution.",
            "graph", RunAction, Mutate, Intermediate, Local),
        SpecTool::new(T, TL, "hypothesis-graph", "Hypothesis graph", "investigation:contribute-evaluation", "Contribute an evaluation",
            "Add your weighing of evidence against a hypothesis.",
            "graph", RunAction, Mutate, Intermediate, Local),
        SpecTool::new(T, TL, "hypothesis-graph", "Hypothesis graph", "investigation:contribute-confidence-revision", "Revise confidence",
            "Change a hypothesis confidence and say why.",
            "graph", RunAction, Mutate, Intermediate, Local),
        SpecTool::new(T, TL, "hypothesis-graph", "Hypothesis graph", "investigation:bridge-dark-link", "Bridge a hidden link",
            "Connect a hidden research link to a hypothesis on this graph.",
            "graph", RunAction, Mutate, Expert, Local),
        SpecTool::new(T, TL, "hypothesis-graph", "Hypothesis graph", "investigation:reframe-hypothesis", "Reframe a hypothesis",
            "Rewrite a hypothesis more clearly, with a reason.",
            "graph", RunAction, Mutate, Intermediate, Local),
        SpecTool::new(T, TL, "hypothesis-graph", "Hypothesis graph", "investigation:merge-hypotheses", "Merge hypotheses",
            "Combine two hypotheses into one.",
            "graph", RunAction, Mutate, Expert, Local),
        SpecTool::new(T, TL, "hypothesis-graph", "Hypothesis graph", "investigation:split-hypothesis", "Split a hypothesis",
            "Break a hypothesis into smaller ones.",
            "graph", RunAction, Mutate, Expert, Local),
        SpecTool::new(T, TL, "hypothesis-graph", "Hypothesis graph", "investigation:flag-gap", "Flag a gap",
            "Mark a missing hypothesis, missing evidence, clash, or stale area.",
            "graph", RunAction, Mutate, Intermediate, Local),
        SpecTool::new(T, TL, "hypothesis-graph", "Hypothesis graph", "investigation:close-gap", "Close a gap",
            "Record how a flagged gap was resolved.",
            "graph", RunAction, Mutate, Intermediate, Local),
        SpecTool::new(T, TL, "hypothesis-graph", "Hypothesis graph", "investigation:merge-contribution", "Accept a contribution",
            "Merge a pending contribution into the graph.",
            "graph", RunAction, Mutate, Expert, Local),
        SpecTool::new(T, TL, "hypothesis-graph", "Hypothesis graph", "investigation:reject-contribution", "Reject a contribution",
            "Turn down a contribution and say why.",
            "graph", RunAction, Mutate, Expert, Local),
        SpecTool::new(T, TL, "hypothesis-graph", "Hypothesis graph", "investigation:adjudicate-conflict", "Settle a clash",
            "Decide between two conflicting contributions.",
            "graph", RunAction, Mutate, Expert, Local),
        SpecTool::new(T, TL, "hypothesis-graph", "Hypothesis graph", "investigation:create-revision", "Snapshot the graph",
            "Save an immutable revision of the hypothesis graph.",
            "graph", RunAction, Mutate, Expert, Local),
        SpecTool::new(T, TL, "hypothesis-graph", "Hypothesis graph", "investigation:diff-revisions", "Compare revisions",
            "Show what changed between two snapshots.",
            "graph", Look, Query, Expert, Local),
        SpecTool::new(T, TL, "hypothesis-graph", "Hypothesis graph", "investigation:rollback-revision", "Roll back the graph",
            "Return the graph to an earlier snapshot.",
            "graph", RunAction, Mutate, Expert, Local),
        SpecTool::new(T, TL, "hypothesis-graph", "Hypothesis graph", "investigation:query-graph", "Search the graph",
            "Look up hypotheses, gaps, contributors, or hidden-link bridges.",
            "graph", Look, Query, Intermediate, Local),
        SpecTool::new(T, TL, "hypothesis-graph", "Hypothesis graph", "investigation:query-gaps", "Find gaps",
            "Look up gaps by kind, priority, or age.",
            "graph", Look, Query, Intermediate, Local),
        SpecTool::new(T, TL, "hypothesis-graph", "Hypothesis graph", "investigation:query-contributions", "Find contributions",
            "Look up contributions by person, kind, status, or time.",
            "graph", Look, Query, Intermediate, Local),
        SpecTool::new(T, TL, "hypothesis-graph", "Hypothesis graph", "investigation:query-dark-link-bridges", "Find hidden-link bridges",
            "Look up bridges from hidden research links into this graph.",
            "graph", Look, Query, Expert, Local),
        SpecTool::new(T, TL, "hypothesis-graph", "Hypothesis graph", "investigation:compute-confidence", "Compute confidence",
            "Combine evaluations and bridges into a confidence score.",
            "graph", Look, Query, Expert, Local),
        SpecTool::new(T, TL, "hypothesis-graph", "Hypothesis graph", "investigation:rank-graph-hypotheses", "Rank graph hypotheses",
            "Order hypotheses on this graph by confidence and support.",
            "graph", Look, Query, Expert, Local),
        SpecTool::new(T, TL, "hypothesis-graph", "Hypothesis graph", "investigation:visualise-graph", "Show the hypothesis graph",
            "Lay out the graph, highlighting confidence, gaps, people, or hidden-link bridges.",
            "graph", Look, Query, Intermediate, Local),
        SpecTool::new(T, TL, "hypothesis-graph", "Hypothesis graph", "investigation:subscribe-updates", "Watch for updates",
            "Subscribe to live changes on this graph.",
            "graph", RunAction, Mutate, Expert, Local),
        SpecTool::new(T, TL, "hypothesis-graph", "Hypothesis graph", "investigation:unsubscribe-updates", "Stop watching",
            "Unsubscribe from live changes on this graph.",
            "graph", RunAction, Mutate, Expert, Local),
        SpecTool::new(T, TL, "hypothesis-graph", "Hypothesis graph", "investigation:export-graph", "Save the graph",
            "Write the hypothesis graph out as a file.",
            "graph", RunAction, Mutate, Intermediate, Local),
        // scenario (9)
        SpecTool::new(T, TL, "scenario", "Scenarios", "investigation:create-scenario", "Create a scenario",
            "Start a best-case, worst-case, likely, black-swan, or branching scenario.",
            "doc", RunAction, Mutate, Intermediate, Local),
        SpecTool::new(T, TL, "scenario", "Scenarios", "investigation:set-probability", "Set probability",
            "Set how likely this scenario is, from none to certain.",
            "doc", RunAction, Mutate, Intermediate, Local),
        SpecTool::new(T, TL, "scenario", "Scenarios", "investigation:add-driving-factor", "Add a driving factor",
            "Add an event, trend, policy, or condition that drives this scenario.",
            "doc", RunAction, Mutate, Intermediate, Local),
        SpecTool::new(T, TL, "scenario", "Scenarios", "investigation:add-outcome", "Add an outcome",
            "Add a projected result with a number, unit, and range.",
            "doc", RunAction, Mutate, Intermediate, Local),
        SpecTool::new(T, TL, "scenario", "Scenarios", "investigation:set-scenario-base", "Link the basis",
            "Connect this scenario to the evidence or pattern it rests on.",
            "doc", RunAction, Mutate, Intermediate, Local),
        SpecTool::new(T, TL, "scenario", "Scenarios", "investigation:branch-scenario", "Branch the scenario",
            "Split this scenario at a decision point.",
            "doc", RunAction, Mutate, Expert, Local),
        SpecTool::new(T, TL, "scenario", "Scenarios", "investigation:query-scenarios", "Find scenarios",
            "Look up scenarios by kind, probability, or timeframe.",
            "doc", Look, Query, Intermediate, Local),
        SpecTool::new(T, TL, "scenario", "Scenarios", "investigation:compare-scenarios", "Compare scenarios",
            "Set two scenarios side by side.",
            "doc", Look, Query, Intermediate, Local),
        SpecTool::new(T, TL, "scenario", "Scenarios", "investigation:merge-scenarios", "Merge scenarios",
            "Combine several scenarios into one composite.",
            "doc", RunAction, Mutate, Expert, Local),
        // trend (7)
        SpecTool::new(T, TL, "trend", "Trends", "investigation:detect-trends", "Detect trends",
            "Find linear, exponential, cyclical, or seasonal trends in a series.",
            "doc", Look, Query, Intermediate, Local),
        SpecTool::new(T, TL, "trend", "Trends", "investigation:fit-model", "Fit a model",
            "Fit a statistical model to the selected numbers.",
            "doc", RunAction, Mutate, Expert, Local),
        SpecTool::new(T, TL, "trend", "Trends", "investigation:forecast-trend", "Project the trend",
            "Project a fitted model forward by a chosen horizon.",
            "doc", Look, Query, Intermediate, Local),
        SpecTool::new(T, TL, "trend", "Trends", "investigation:detect-anomalies", "Find anomalies",
            "Flag outliers in a time series.",
            "doc", Look, Query, Intermediate, Local),
        SpecTool::new(T, TL, "trend", "Trends", "investigation:seasonal-decompose", "Separate season and trend",
            "Split a series into trend, seasonal, and leftover parts.",
            "doc", Look, Query, Expert, Local),
        SpecTool::new(T, TL, "trend", "Trends", "investigation:correlate-trends", "Relate two trends",
            "See whether one trend leads, lags, or moves with another.",
            "doc", Look, Query, Expert, Local),
        SpecTool::new(T, TL, "trend", "Trends", "investigation:import-timeseries", "Import a series",
            "Bring time-series numbers in from a source.",
            "doc", RunAction, Mutate, Intermediate, Local),
        // risk (6)
        SpecTool::new(T, TL, "risk", "Risk", "investigation:assess-risk", "Assess risk",
            "Weigh probability times impact for this scenario.",
            "doc", Look, Query, Intermediate, Local),
        SpecTool::new(T, TL, "risk", "Risk", "investigation:build-risk-matrix", "Build a risk matrix",
            "Plot several scenarios by probability and impact.",
            "doc", Look, Query, Intermediate, Local),
        SpecTool::new(T, TL, "risk", "Risk", "investigation:identify-tail-risks", "Find tail risks",
            "Find low-probability, high-impact scenarios.",
            "doc", Look, Query, Expert, Local),
        SpecTool::new(T, TL, "risk", "Risk", "investigation:set-risk-threshold", "Set a risk threshold",
            "Set the risk level that should raise an alert.",
            "doc", RunAction, Mutate, Intermediate, Local),
        SpecTool::new(T, TL, "risk", "Risk", "investigation:monitor-risk", "Watch risk",
            "Compare current risk against the alert threshold.",
            "doc", Look, Query, Intermediate, Local),
        SpecTool::new(T, TL, "risk", "Risk", "investigation:risk-report", "Risk report",
            "Write a risk assessment for the parties on this case.",
            "doc", Look, Query, Intermediate, Local),
        // causal (5)
        SpecTool::new(T, TL, "causal", "Causes", "investigation:build-causal-model", "Build a cause model",
            "Draw cause-to-effect links among the selected variables.",
            "graph", RunAction, Mutate, Expert, Live("CausalFuzzyAndControl.caused")),
        SpecTool::new(T, TL, "causal", "Causes", "investigation:query-causal-path", "Find a causal path",
            "Find how one variable leads to another through causes.",
            "graph", Look, Query, Intermediate, Live("CausalFuzzyAndControl.caused")),
        SpecTool::new(T, TL, "causal", "Causes", "investigation:intervene", "Simulate an intervention",
            "Project what happens if one variable is set to a value.",
            "graph", Look, Query, Expert, Local),
        SpecTool::new(T, TL, "causal", "Causes", "investigation:counterfactual", "Ask a counterfactual",
            "Ask what would have happened if conditions had been different.",
            "graph", Look, Query, Expert, Local),
        SpecTool::new(T, TL, "causal", "Causes", "investigation:validate-causal-model", "Check the cause model",
            "Check this cause model against the available evidence.",
            "graph", Look, Query, Expert, Local),
    ];
    ROWS
}
