//! Extra office chains from TOOL_CHEST_SPEC.md §13 (formatting leftovers,
//! structure, context-markup, media-embed). Human copy only.

use super::row::{Contract, SpecTool};
use crate::browser::tool_proficiency::Proficiency;
use crate::tool_chest::core::intent_bus::ActionType;
use crate::tool_chest::core::tool::ToolKind;

const T: &str = "office";
const TL: &str = "Writing";

pub fn rows() -> &'static [SpecTool] {
    static ROWS: &[SpecTool] = &[
        row(
            "formatting",
            "Writing marks",
            "office:underline",
            "Underline",
            "Draw a line under the selected writing.",
            "doc",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Novice,
            Contract::Local,
        ),
        row(
            "formatting",
            "Writing marks",
            "office:strikethrough",
            "Strike through",
            "Cross out the selected writing.",
            "doc",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Novice,
            Contract::Local,
        ),
        row(
            "formatting",
            "Writing marks",
            "office:subscript",
            "Subscript",
            "Lower the selected writing.",
            "doc",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Intermediate,
            Contract::Local,
        ),
        row(
            "formatting",
            "Writing marks",
            "office:superscript",
            "Superscript",
            "Raise the selected writing.",
            "doc",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Intermediate,
            Contract::Local,
        ),
        row(
            "formatting",
            "Writing marks",
            "office:highlight",
            "Highlight",
            "Wash the selected writing with a marker colour.",
            "doc",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Novice,
            Contract::Local,
        ),
        row(
            "formatting",
            "Writing marks",
            "office:list",
            "List",
            "Turn the selected writing into a list.",
            "doc",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Novice,
            Contract::Local,
        ),
        row(
            "formatting",
            "Writing marks",
            "office:indent",
            "Indent",
            "Move the selected writing in or out.",
            "doc",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Novice,
            Contract::Local,
        ),
        row(
            "formatting",
            "Writing marks",
            "office:align_right",
            "Align right",
            "Line the selected writing up on the right.",
            "doc",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Novice,
            Contract::Local,
        ),
        row(
            "formatting",
            "Writing marks",
            "office:justify",
            "Justify",
            "Even the selected writing on both sides.",
            "doc",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Intermediate,
            Contract::Local,
        ),
        row(
            "structure",
            "Page structure",
            "office:insert-section",
            "Add a section",
            "Start a new section on this page.",
            "doc",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Novice,
            Contract::Local,
        ),
        row(
            "structure",
            "Page structure",
            "office:insert-table",
            "Add a table",
            "Insert a small table on this page.",
            "doc",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Novice,
            Contract::Local,
        ),
        row(
            "structure",
            "Page structure",
            "office:insert-footnote",
            "Add a footnote",
            "Attach a footnote to this place on the page.",
            "doc",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Intermediate,
            Contract::Local,
        ),
        row(
            "structure",
            "Page structure",
            "office:insert-citation",
            "Add a citation",
            "Link this writing to a source.",
            "doc",
            ToolKind::RunAction,
            ActionType::Annotate,
            Proficiency::Intermediate,
            Contract::Local,
        ),
        row(
            "structure",
            "Page structure",
            "office:insert-toc",
            "Table of contents",
            "Build a contents list from headings.",
            "doc",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Intermediate,
            Contract::Local,
        ),
        row(
            "structure",
            "Page structure",
            "office:insert-page-break",
            "Page break",
            "Start a new page here.",
            "doc",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Novice,
            Contract::Local,
        ),
        row(
            "structure",
            "Page structure",
            "office:insert-hyperlink",
            "Link",
            "Turn the selection into a link.",
            "doc",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Novice,
            Contract::Local,
        ),
        row(
            "structure",
            "Page structure",
            "office:insert-bookmark",
            "Bookmark",
            "Name this place on the page.",
            "doc",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Novice,
            Contract::Local,
        ),
        row(
            "context-markup",
            "Meaning marks",
            "office:tag-term",
            "Mark a term",
            "Tie this word to a meaning.",
            "doc",
            ToolKind::RunAction,
            ActionType::Annotate,
            Proficiency::Intermediate,
            Contract::Gated("Select writing and choose the term meaning first."),
        ),
        row(
            "context-markup",
            "Meaning marks",
            "office:tag-entity",
            "Mark a name",
            "Tie this name to a record.",
            "doc",
            ToolKind::RunAction,
            ActionType::Annotate,
            Proficiency::Intermediate,
            Contract::Gated("Select a name and choose its entity record first."),
        ),
        row(
            "context-markup",
            "Meaning marks",
            "office:tag-claimed-fact",
            "Mark a claim",
            "Tie this claim to sources.",
            "doc",
            ToolKind::RunAction,
            ActionType::Annotate,
            Proficiency::Intermediate,
            Contract::Gated("Select a claim and attach at least one source first."),
        ),
        row(
            "context-markup",
            "Meaning marks",
            "office:tag-quote",
            "Mark a quote",
            "Tie this quotation to who said it.",
            "doc",
            ToolKind::RunAction,
            ActionType::Annotate,
            Proficiency::Novice,
            Contract::Gated("Select the quotation and identify its speaker first."),
        ),
        row(
            "media-embed",
            "Place inside writing",
            "office:embed-image",
            "Place a picture",
            "Put a picture into this page.",
            "media",
            ToolKind::PlaceContainer,
            ActionType::Mutate,
            Proficiency::Novice,
            Contract::Place("media"),
        ),
        row(
            "media-embed",
            "Place inside writing",
            "office:embed-sheet",
            "Place a table",
            "Put a numbers table into this page.",
            "sheet",
            ToolKind::PlaceContainer,
            ActionType::Mutate,
            Proficiency::Novice,
            Contract::Place("sheet"),
        ),
        row(
            "media-embed",
            "Place inside writing",
            "office:embed-map",
            "Place a map",
            "Put a map into this page.",
            "map",
            ToolKind::PlaceContainer,
            ActionType::Mutate,
            Proficiency::Novice,
            Contract::Place("map"),
        ),
        row(
            "media-embed",
            "Place inside writing",
            "office:embed-graph",
            "Place a graph",
            "Put a relationship view into this page.",
            "graph",
            ToolKind::PlaceContainer,
            ActionType::Mutate,
            Proficiency::Intermediate,
            Contract::Place("graph"),
        ),
    ];
    ROWS
}

const fn row(
    chain: &'static str,
    chain_label: &'static str,
    id: &'static str,
    label: &'static str,
    tooltip: &'static str,
    icon: &'static str,
    kind: ToolKind,
    action: ActionType,
    proficiency: Proficiency,
    contract: Contract,
) -> SpecTool {
    SpecTool {
        toolbox: T,
        toolbox_label: TL,
        chain,
        chain_label,
        id,
        label,
        tooltip,
        icon,
        kind,
        action,
        proficiency,
        contract,
    }
}
