//! Portal worlds spec tools from TOOLBOX_HYPERMEDIA_SPEC_2.md §6.

use super::row::{Contract, SpecTool};
use crate::browser::tool_proficiency::Proficiency;
use crate::tool_chest::core::intent_bus::ActionType;
use crate::tool_chest::core::tool::ToolKind;

const T: &str = "portals";
const TL: &str = "Portals";

pub fn rows() -> &'static [SpecTool] {
    static ROWS: &[SpecTool] = &[
        SpecTool::new(
            T,
            TL,
            "world-building",
            "World building",
            "portals:create-world",
            "New world",
            "Start a named world with an environment.",
            "portal",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Novice,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "world-building",
            "World building",
            "portals:terrain-edit",
            "Sculpt terrain",
            "Raise and lower the world's ground.",
            "portal",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Intermediate,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "world-building",
            "World building",
            "portals:skybox-set",
            "Set skybox",
            "Choose the sky around this world.",
            "portal",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Novice,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "world-building",
            "World building",
            "portals:environment-light",
            "World light",
            "Set the world's ambient lighting.",
            "portal",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Intermediate,
            Contract::Live("Render.scene"),
        ),
        SpecTool::new(
            T,
            TL,
            "world-building",
            "World building",
            "portals:spawn-point",
            "Spawn point",
            "Mark where people arrive.",
            "portal",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Novice,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "world-building",
            "World building",
            "portals:boundary-set",
            "World boundary",
            "Set how far the world extends.",
            "portal",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Intermediate,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "world-building",
            "World building",
            "portals:world-save",
            "Save world",
            "Save the current world state.",
            "portal",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Novice,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "world-building",
            "World building",
            "portals:world-publish",
            "Publish world",
            "Publish this world to a portal host.",
            "portal",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Expert,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "objects",
            "World objects",
            "portals:place-prop",
            "Place a prop",
            "Put a prop in the world.",
            "portal",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Novice,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "objects",
            "World objects",
            "portals:place-furniture",
            "Place furniture",
            "Put furniture in the world.",
            "portal",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Novice,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "objects",
            "World objects",
            "portals:interactive-object",
            "Interactive object",
            "Place an object people can use.",
            "portal",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Intermediate,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "objects",
            "World objects",
            "portals:portal-anchor",
            "Portal anchor",
            "Place an entrance to another world.",
            "portal",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Intermediate,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "objects",
            "World objects",
            "portals:object-transform",
            "Transform object",
            "Move, rotate, or scale a placed object.",
            "portal",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Novice,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "objects",
            "World objects",
            "portals:object-duplicate",
            "Duplicate object",
            "Copy a placed object.",
            "portal",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Novice,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "objects",
            "World objects",
            "portals:object-delete",
            "Delete object",
            "Remove a placed object.",
            "portal",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Novice,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "portals",
            "Portal links",
            "portals:create-portal",
            "New portal",
            "Make a named link to another world.",
            "portal",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Intermediate,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "portals",
            "Portal links",
            "portals:portal-link",
            "Link portal",
            "Point this portal at a destination world.",
            "portal",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Intermediate,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "portals",
            "Portal links",
            "portals:portal-destination",
            "Portal destination",
            "Show where this portal leads.",
            "portal",
            ToolKind::Query,
            ActionType::Query,
            Proficiency::Novice,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "portals",
            "Portal links",
            "portals:portal-preview",
            "Preview portal",
            "Look through to the destination world.",
            "portal",
            ToolKind::Query,
            ActionType::Query,
            Proficiency::Intermediate,
            Contract::Live("Render.scene"),
        ),
        SpecTool::new(
            T,
            TL,
            "portals",
            "Portal links",
            "portals:portal-list",
            "List portals",
            "List every portal in this world.",
            "portal",
            ToolKind::Query,
            ActionType::Query,
            Proficiency::Novice,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "portals",
            "Portal links",
            "portals:portal-test",
            "Test portal",
            "Walk through this portal to check it.",
            "portal",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Intermediate,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "avatars",
            "Avatars",
            "portals:avatar-select",
            "Default avatar",
            "Choose the default body for this world.",
            "portal",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Novice,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "avatars",
            "Avatars",
            "portals:avatar-customise",
            "Customise avatar",
            "Change how this avatar looks.",
            "portal",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Intermediate,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "avatars",
            "Avatars",
            "portals:controller-map",
            "Map controllers",
            "Map hands and sticks to actions.",
            "portal",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Expert,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "avatars",
            "Avatars",
            "portals:avatar-preview",
            "Preview avatar",
            "Look at this avatar.",
            "portal",
            ToolKind::Query,
            ActionType::Query,
            Proficiency::Novice,
            Contract::Live("Render.scene"),
        ),
        SpecTool::new(
            T,
            TL,
            "avatars",
            "Avatars",
            "portals:avatar-spawn",
            "Spawn avatar",
            "Place an avatar at a point in the world.",
            "portal",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Intermediate,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "physics",
            "Physics",
            "portals:add-collider",
            "Add collider",
            "Give an object a collision shape.",
            "portal",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Intermediate,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "physics",
            "Physics",
            "portals:add-rigidbody",
            "Add rigid body",
            "Let an object fall and collide.",
            "portal",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Intermediate,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "physics",
            "Physics",
            "portals:add-trigger",
            "Add trigger",
            "Fire an event when something enters.",
            "portal",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Intermediate,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "physics",
            "Physics",
            "portals:physics-material",
            "Physics material",
            "Set friction and bounce.",
            "portal",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Intermediate,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "physics",
            "Physics",
            "portals:physics-bake",
            "Bake physics",
            "Bake the physics scene for a smoother run.",
            "portal",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Expert,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "inspect",
            "Inspect",
            "portals:world-statistics",
            "World stats",
            "Show object, polygon, and portal counts.",
            "inspect",
            ToolKind::Query,
            ActionType::Query,
            Proficiency::Novice,
            Contract::Live("Render.scene"),
        ),
        SpecTool::new(
            T,
            TL,
            "inspect",
            "Inspect",
            "portals:physics-inspector",
            "Physics inspector",
            "List bodies, colliders, and triggers.",
            "inspect",
            ToolKind::Query,
            ActionType::Query,
            Proficiency::Intermediate,
            Contract::Live("Render.scene"),
        ),
        SpecTool::new(
            T,
            TL,
            "inspect",
            "Inspect",
            "portals:portal-graph",
            "Portal graph",
            "Show how worlds link through portals.",
            "inspect",
            ToolKind::Query,
            ActionType::Query,
            Proficiency::Intermediate,
            Contract::Live("Render.scene"),
        ),
        SpecTool::new(
            T,
            TL,
            "inspect",
            "Inspect",
            "portals:player-list",
            "Who is here",
            "List people currently in this world.",
            "inspect",
            ToolKind::Query,
            ActionType::Query,
            Proficiency::Intermediate,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "inspect",
            "Inspect",
            "portals:metadata-view",
            "World details",
            "Show portal and world metadata.",
            "inspect",
            ToolKind::Query,
            ActionType::Query,
            Proficiency::Novice,
            Contract::Live("Render.scene"),
        ),
    ];
    ROWS
}
