//! Live production spec tools from TOOLBOX_HYPERMEDIA_SPEC_2.md §7.

use super::row::{Contract, SpecTool};
use crate::browser::tool_proficiency::Proficiency;
use crate::tool_chest::core::intent_bus::ActionType;
use crate::tool_chest::core::tool::ToolKind;

const T: &str = "productions";
const TL: &str = "Productions";

pub fn rows() -> &'static [SpecTool] {
    static ROWS: &[SpecTool] = &[
        SpecTool::new(
            T,
            TL,
            "dmx",
            "DMX",
            "productions:add-universe",
            "Add universe",
            "Add a DMX universe to this show.",
            "light",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Expert,
            Contract::Gated("Needs a lighting desk to add a DMX universe."),
        ),
        SpecTool::new(
            T,
            TL,
            "dmx",
            "DMX",
            "productions:patch-fixture",
            "Patch fixture",
            "Patch a fixture onto a DMX address.",
            "light",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Expert,
            Contract::Gated("Needs a DMX universe to patch a fixture onto a channel."),
        ),
        SpecTool::new(
            T,
            TL,
            "dmx",
            "DMX",
            "productions:unpatch-fixture",
            "Unpatch fixture",
            "Remove a fixture from the patch.",
            "light",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Expert,
            Contract::Gated("Needs a lighting desk to unpatch a fixture."),
        ),
        SpecTool::new(
            T,
            TL,
            "dmx",
            "DMX",
            "productions:fixture-profile",
            "Fixture profile",
            "Assign a channel map to a fixture.",
            "light",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Expert,
            Contract::Gated("Needs a lighting desk to assign a fixture profile."),
        ),
        SpecTool::new(
            T,
            TL,
            "dmx",
            "DMX",
            "productions:channel-assign",
            "Channel map",
            "Assign a custom channel map to a fixture.",
            "light",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Expert,
            Contract::Gated("Needs a patched DMX universe to assign channels."),
        ),
        SpecTool::new(
            T,
            TL,
            "dmx",
            "DMX",
            "productions:dmx-monitor",
            "DMX monitor",
            "Watch live DMX channel values.",
            "light",
            ToolKind::Query,
            ActionType::Query,
            Proficiency::Intermediate,
            Contract::Gated("Needs a live DMX universe to watch channel values."),
        ),
        SpecTool::new(
            T,
            TL,
            "dmx",
            "DMX",
            "productions:dmx-scene",
            "Save scene",
            "Save the current DMX look as a scene.",
            "light",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Intermediate,
            Contract::Gated("Needs a lighting desk to save a DMX scene."),
        ),
        SpecTool::new(
            T,
            TL,
            "dmx",
            "DMX",
            "productions:dmx-cue",
            "DMX cue",
            "Turn a saved scene into a cue with a fade.",
            "light",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Intermediate,
            Contract::Gated("Needs a lighting desk to turn a scene into a cue."),
        ),
        SpecTool::new(
            T,
            TL,
            "fixtures",
            "Fixtures",
            "productions:add-moving-head",
            "Moving head",
            "Place a moving-head fixture.",
            "light",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Intermediate,
            Contract::Gated("Needs a lighting desk to place a moving-head fixture."),
        ),
        SpecTool::new(
            T,
            TL,
            "fixtures",
            "Fixtures",
            "productions:add-led-par",
            "LED par",
            "Place an LED par fixture.",
            "light",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Novice,
            Contract::Gated("Needs a lighting desk to place an LED par."),
        ),
        SpecTool::new(
            T,
            TL,
            "fixtures",
            "Fixtures",
            "productions:add-laser",
            "Laser",
            "Place a laser fixture.",
            "light",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Expert,
            Contract::Gated("Needs a lighting desk to place a laser fixture."),
        ),
        SpecTool::new(
            T,
            TL,
            "fixtures",
            "Fixtures",
            "productions:add-strobe",
            "Strobe",
            "Place a strobe fixture.",
            "light",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Intermediate,
            Contract::Gated("Needs a lighting desk to place a strobe."),
        ),
        SpecTool::new(
            T,
            TL,
            "fixtures",
            "Fixtures",
            "productions:add-hazer",
            "Hazer",
            "Place a haze machine.",
            "light",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Intermediate,
            Contract::Gated("Needs a lighting desk to place a haze machine."),
        ),
        SpecTool::new(
            T,
            TL,
            "fixtures",
            "Fixtures",
            "productions:fixture-position",
            "Fixture position",
            "Set hang position and aim of a fixture.",
            "light",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Intermediate,
            Contract::Gated("Needs a lighting desk to set fixture hang and aim."),
        ),
        SpecTool::new(
            T,
            TL,
            "lighting",
            "Lighting",
            "productions:colour-mix",
            "Colour mix",
            "Set fixture colour mix.",
            "light",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Novice,
            Contract::Gated("Needs a lighting desk to mix fixture colour."),
        ),
        SpecTool::new(
            T,
            TL,
            "lighting",
            "Lighting",
            "productions:beam-shape",
            "Beam shape",
            "Set zoom, focus, and iris.",
            "light",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Intermediate,
            Contract::Gated("Needs a lighting desk to set zoom, focus, and iris."),
        ),
        SpecTool::new(
            T,
            TL,
            "lighting",
            "Lighting",
            "productions:gobo-select",
            "Gobo",
            "Pick and rotate a gobo.",
            "light",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Intermediate,
            Contract::Gated("Needs a lighting desk to pick and rotate a gobo."),
        ),
        SpecTool::new(
            T,
            TL,
            "lighting",
            "Lighting",
            "productions:position-set",
            "Pan and tilt",
            "Set pan and tilt on moving fixtures.",
            "light",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Novice,
            Contract::Gated("Needs a lighting desk to set pan and tilt."),
        ),
        SpecTool::new(
            T,
            TL,
            "lighting",
            "Lighting",
            "productions:intensity-set",
            "Intensity",
            "Set fixture intensity from dark to full.",
            "light",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Novice,
            Contract::Gated("Needs a lighting desk to set fixture intensity."),
        ),
        SpecTool::new(
            T,
            TL,
            "lighting",
            "Lighting",
            "productions:effect-run",
            "Lighting effect",
            "Run a chase, wave, random, or ramp.",
            "light",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Expert,
            Contract::Gated("Needs a lighting desk to run a chase, wave, or ramp."),
        ),
        SpecTool::new(
            T,
            TL,
            "projection",
            "Projection",
            "productions:add-surface",
            "Add surface",
            "Add a flat, curved, or architectural projection surface.",
            "stage",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Novice,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "projection",
            "Projection",
            "productions:surface-map",
            "Map surface",
            "Map content onto the surface geometry.",
            "stage",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Intermediate,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "projection",
            "Projection",
            "productions:edge-blend",
            "Edge blend",
            "Blend overlapping projector edges.",
            "stage",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Expert,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "projection",
            "Projection",
            "productions:geometry-correct",
            "Geometry correct",
            "Apply keystone and warp correction.",
            "stage",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Expert,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "projection",
            "Projection",
            "productions:calibration-point",
            "Calibration point",
            "Pin a calibration point on the surface.",
            "stage",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Intermediate,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "projection",
            "Projection",
            "productions:projection-content",
            "Projection content",
            "Assign a clip or still to this surface.",
            "stage",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Novice,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "projection",
            "Projection",
            "productions:projection-preview",
            "Preview projection",
            "Preview the mapped projection.",
            "stage",
            ToolKind::Query,
            ActionType::Query,
            Proficiency::Novice,
            Contract::Live("Render.scene"),
        ),
        SpecTool::new(
            T,
            TL,
            "cue-stack",
            "Cue stack",
            "productions:add-cue",
            "Add cue",
            "Add a cue to the stack.",
            "timeline",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Novice,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "cue-stack",
            "Cue stack",
            "productions:edit-cue",
            "Edit cue",
            "Change the selected cue.",
            "timeline",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Novice,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "cue-stack",
            "Cue stack",
            "productions:cue-sequence",
            "Cue order",
            "Order cues in the stack.",
            "timeline",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Intermediate,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "cue-stack",
            "Cue stack",
            "productions:cue-trigger",
            "Cue trigger",
            "Fire by hand, time, event, or SMPTE.",
            "timeline",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Intermediate,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "cue-stack",
            "Cue stack",
            "productions:cue-fade",
            "Cue fade",
            "Set fade in, fade out, and curve.",
            "timeline",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Intermediate,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "cue-stack",
            "Cue stack",
            "productions:cue-go",
            "Go",
            "Fire the next cue in the stack.",
            "timeline",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Novice,
            Contract::Gated("Needs a lighting desk or DMX universe to fire the next cue."),
        ),
        SpecTool::new(
            T,
            TL,
            "show-control",
            "Show control",
            "productions:smpte-sync",
            "SMPTE sync",
            "Lock the show to SMPTE timecode.",
            "timeline",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Expert,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "show-control",
            "Show control",
            "productions:midi-timecode",
            "MIDI timecode",
            "Lock the show to MIDI timecode.",
            "timeline",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Expert,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "show-control",
            "Show control",
            "productions:art-net-config",
            "Art-Net",
            "Set Art-Net network and universes.",
            "light",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Expert,
            Contract::Gated("Needs a lighting desk and a DMX universe on Art-Net."),
        ),
        SpecTool::new(
            T,
            TL,
            "show-control",
            "Show control",
            "productions:osc-config",
            "OSC",
            "Set Open Sound Control addresses.",
            "timeline",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Expert,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "show-control",
            "Show control",
            "productions:timeline-trigger",
            "Timeline trigger",
            "Map timeline positions to triggers.",
            "timeline",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Intermediate,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "inspect",
            "Inspect",
            "productions:dmx-monitor",
            "DMX monitor",
            "Watch live DMX channel values.",
            "inspect",
            ToolKind::Query,
            ActionType::Query,
            Proficiency::Intermediate,
            Contract::Gated("Needs a live DMX universe to watch channel values."),
        ),
        SpecTool::new(
            T,
            TL,
            "inspect",
            "Inspect",
            "productions:fixture-report",
            "Fixture report",
            "Report patched, online, and error fixtures.",
            "inspect",
            ToolKind::Query,
            ActionType::Query,
            Proficiency::Intermediate,
            Contract::Gated("Needs a lighting desk to report patched and online fixtures."),
        ),
        SpecTool::new(
            T,
            TL,
            "inspect",
            "Inspect",
            "productions:projection-analyser",
            "Projection analyser",
            "Check brightness, coverage, and overlap.",
            "inspect",
            ToolKind::Query,
            ActionType::Query,
            Proficiency::Intermediate,
            Contract::Live("Render.scene"),
        ),
        SpecTool::new(
            T,
            TL,
            "inspect",
            "Inspect",
            "productions:power-calculator",
            "Power draw",
            "Add up the show's total power draw.",
            "inspect",
            ToolKind::Query,
            ActionType::Query,
            Proficiency::Intermediate,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "inspect",
            "Inspect",
            "productions:metadata-view",
            "Production details",
            "Show production metadata.",
            "inspect",
            ToolKind::Query,
            ActionType::Query,
            Proficiency::Novice,
            Contract::Local,
        ),
    ];
    ROWS
}
