//! Research chains from TOOLBOX_RESEARCH_SPEC.md. New toolbox `research`.

use super::row::{Contract, SpecTool};
use crate::browser::tool_proficiency::Proficiency;
use crate::tool_chest::core::intent_bus::ActionType;
use crate::tool_chest::core::tool::ToolKind;
use ActionType::{Mutate, Query};
use Contract::{Gated, Local};
use Proficiency::{Expert, Intermediate, Novice};
use ToolKind::{Query as Look, RunAction};

const T: &str = "research";
const TL: &str = "Research";

pub fn rows() -> &'static [SpecTool] {
    #[rustfmt::skip]
    static ROWS: &[SpecTool] = &[
        // enquiry (10)
        SpecTool::new(T, TL, "enquiry", "Enquiry", "research:new-research", "Start research",
            "Open a new research project and say why it exists.",
            "doc", RunAction, Mutate, Novice, Local),
        SpecTool::new(T, TL, "enquiry", "Enquiry", "research:set-purpose", "Set the purpose",
            "Say whether this work explores, explains, evaluates, generates, confirms, integrates, critiques, or applies.",
            "doc", RunAction, Mutate, Novice, Local),
        SpecTool::new(T, TL, "enquiry", "Enquiry", "research:define-scope", "Set the scope",
            "Say what time, place, people, topics, and methods are in bounds.",
            "doc", RunAction, Mutate, Novice, Local),
        SpecTool::new(T, TL, "enquiry", "Enquiry", "research:add-constraint", "Add a constraint",
            "Add an ethical, legal, resource, method, access, or time limit.",
            "doc", RunAction, Mutate, Intermediate, Local),
        SpecTool::new(T, TL, "enquiry", "Enquiry", "research:add-question", "Add a question",
            "Add a research question, optionally under another one.",
            "doc", RunAction, Mutate, Novice, Local),
        SpecTool::new(T, TL, "enquiry", "Enquiry", "research:link-questions", "Link questions",
            "Say that one question depends on or informs another.",
            "doc", RunAction, Mutate, Intermediate, Local),
        SpecTool::new(T, TL, "enquiry", "Enquiry", "research:set-question-status", "Set question status",
            "Mark this question open, in progress, answered, reframed, deferred, or dropped.",
            "doc", RunAction, Mutate, Novice, Local),
        SpecTool::new(T, TL, "enquiry", "Enquiry", "research:link-investigation", "Link a case",
            "Connect a related investigation to this research.",
            "doc", RunAction, Mutate, Intermediate, Local),
        SpecTool::new(T, TL, "enquiry", "Enquiry", "research:set-research-status", "Set research status",
            "Mark this project proposing, active, paused, concluded, ongoing, or superseded.",
            "doc", RunAction, Mutate, Novice, Local),
        SpecTool::new(T, TL, "enquiry", "Enquiry", "research:query-research", "Search the project",
            "Look up questions, sources, findings, and constraints in this project.",
            "doc", Look, Query, Intermediate, Local),
        // corpus (10)
        SpecTool::new(T, TL, "corpus", "Sources", "research:add-corpus-item", "Add a source",
            "Add a paper, dataset, document, recording, web page, or archive item.",
            "doc", RunAction, Mutate, Novice, Local),
        SpecTool::new(T, TL, "corpus", "Sources", "research:import-literature", "Import literature",
            "Bring papers in from a library or file.",
            "doc", RunAction, Mutate, Intermediate, Local),
        SpecTool::new(T, TL, "corpus", "Sources", "research:import-dataset", "Import a dataset",
            "Bring a dataset in from a file or feed.",
            "doc", RunAction, Mutate, Intermediate,
            Gated("Needs a local dataset file or feed binding.")),
        SpecTool::new(T, TL, "corpus", "Sources", "research:import-web", "Import from the web",
            "Bring a web page, API, or linked data into the sources.",
            "doc", RunAction, Mutate, Intermediate,
            Gated("Needs network access and an approved web import path.")),
        SpecTool::new(T, TL, "corpus", "Sources", "research:set-corpus-confidence", "Set source confidence",
            "Say how far this source can be trusted.",
            "doc", RunAction, Mutate, Intermediate, Local),
        SpecTool::new(T, TL, "corpus", "Sources", "research:tag-corpus-item", "Tag a source",
            "Add labels so this source is easier to find later.",
            "doc", RunAction, Mutate, Novice, Local),
        SpecTool::new(T, TL, "corpus", "Sources", "research:query-corpus", "Find sources",
            "Look up sources by kind, confidence, tags, origin, or time.",
            "doc", Look, Query, Intermediate, Local),
        SpecTool::new(T, TL, "corpus", "Sources", "research:deduplicate-corpus", "Find duplicates",
            "Find duplicate or near-duplicate sources.",
            "doc", Look, Query, Intermediate, Local),
        SpecTool::new(T, TL, "corpus", "Sources", "research:extract-from-corpus", "Extract from a source",
            "Pull people, relations, topics, or frames from this source.",
            "doc", Look, Query, Intermediate, Local),
        SpecTool::new(T, TL, "corpus", "Sources", "research:annotate-corpus-item", "Annotate a source",
            "Add meaning marks and entity links on this source.",
            "doc", RunAction, Mutate, Intermediate, Local),
        // dynamics (10)
        SpecTool::new(T, TL, "dynamics", "Dynamics", "research:define-social-dynamics", "Define social dynamics",
            "Record networks, structures, power, and norms in play.",
            "graph", RunAction, Mutate, Intermediate, Local),
        SpecTool::new(T, TL, "dynamics", "Dynamics", "research:define-economic-dynamics", "Define economic dynamics",
            "Record markets, inequality, capital flows, and access.",
            "graph", RunAction, Mutate, Intermediate, Local),
        SpecTool::new(T, TL, "dynamics", "Dynamics", "research:define-spatiotemporal-dynamics", "Define place-and-time dynamics",
            "Record movement, spread, environmental change, or urban change.",
            "graph", RunAction, Mutate, Intermediate, Local),
        SpecTool::new(T, TL, "dynamics", "Dynamics", "research:link-dynamics", "Link two dynamics",
            "Connect two dynamics, even if they use different vocabularies.",
            "graph", RunAction, Mutate, Intermediate, Local),
        SpecTool::new(T, TL, "dynamics", "Dynamics", "research:query-dynamics", "Find dynamics",
            "Look up dynamics by kind, scope, or what they link to.",
            "graph", Look, Query, Intermediate, Local),
        SpecTool::new(T, TL, "dynamics", "Dynamics", "research:analyse-social-network", "Analyse the social network",
            "Find centres, communities, bridges, and holes in this network.",
            "graph", Look, Query, Expert, Local),
        SpecTool::new(T, TL, "dynamics", "Dynamics", "research:analyse-inequality", "Analyse inequality",
            "Look at inequality along chosen axes such as class, race, gender, or place.",
            "graph", Look, Query, Expert, Local),
        SpecTool::new(T, TL, "dynamics", "Dynamics", "research:analyse-diffusion", "Analyse spread",
            "Fit how something spreads — an S-curve, exponential growth, or through a network.",
            "graph", Look, Query, Expert, Local),
        SpecTool::new(T, TL, "dynamics", "Dynamics", "research:overlay-dynamics", "Overlay dynamics",
            "Lay two dynamics on the same place-and-time frame.",
            "graph", Look, Query, Intermediate, Local),
        SpecTool::new(T, TL, "dynamics", "Dynamics", "research:detect-cross-dynamic-patterns", "Find cross-dynamic patterns",
            "Spot patterns that only appear when several dynamics interact.",
            "graph", Look, Query, Expert, Local),
        // dark-links (9)
        SpecTool::new(T, TL, "dark-links", "Hidden links", "research:infer-dark-link", "Infer a hidden link",
            "Infer a hidden, latent, suppressed, or unspoken connection.",
            "graph", RunAction, Mutate, Expert, Local),
        SpecTool::new(T, TL, "dark-links", "Hidden links", "research:detect-provenance-gaps", "Find origin gaps",
            "Find missing records, deleted references, or broken derivation chains.",
            "graph", Look, Query, Intermediate, Local),
        SpecTool::new(T, TL, "dark-links", "Hidden links", "research:detect-concealment-patterns", "Find concealment patterns",
            "Spot inconsistent records, selective omission, or a coordinated story.",
            "graph", Look, Query, Expert, Local),
        SpecTool::new(T, TL, "dark-links", "Hidden links", "research:link-dark-link-evidence", "Support a hidden link",
            "Attach indirect sources that support this hidden connection.",
            "graph", RunAction, Mutate, Intermediate, Local),
        SpecTool::new(T, TL, "dark-links", "Hidden links", "research:set-dark-link-confidence", "Set hidden-link confidence",
            "Say how confident this inferred connection is.",
            "graph", RunAction, Mutate, Intermediate, Local),
        SpecTool::new(T, TL, "dark-links", "Hidden links", "research:query-dark-links", "Find hidden links",
            "Look up hidden links by kind, confidence, method, or who they connect.",
            "graph", Look, Query, Intermediate, Local),
        SpecTool::new(T, TL, "dark-links", "Hidden links", "research:confirm-dark-link", "Confirm a hidden link",
            "Promote a hidden link to a visible link once evidence is enough.",
            "graph", RunAction, Mutate, Intermediate, Local),
        SpecTool::new(T, TL, "dark-links", "Hidden links", "research:refute-dark-link", "Refute a hidden link",
            "Mark a hidden link as contradicted by evidence.",
            "graph", RunAction, Mutate, Intermediate, Local),
        SpecTool::new(T, TL, "dark-links", "Hidden links", "research:trace-dark-link-provenance", "Trace a hidden link",
            "Follow the full origin chain of this inferred connection.",
            "graph", Look, Query, Intermediate, Local),
        // inference (7)
        SpecTool::new(T, TL, "inference", "Inferences", "research:make-inference", "Make an inference",
            "Draw a conclusion from premises — deduct, induce, abduct, analogise, or cause.",
            "graph", RunAction, Mutate, Intermediate, Local),
        SpecTool::new(T, TL, "inference", "Inferences", "research:chain-inference", "Chain an inference",
            "Say this inference depends on an earlier one.",
            "graph", RunAction, Mutate, Intermediate, Local),
        SpecTool::new(T, TL, "inference", "Inferences", "research:set-inference-confidence", "Set inference confidence",
            "Say how confident this conclusion is.",
            "graph", RunAction, Mutate, Intermediate, Local),
        SpecTool::new(T, TL, "inference", "Inferences", "research:query-inferences", "Find inferences",
            "Look up inferences by kind, confidence, premises, or conclusion.",
            "graph", Look, Query, Intermediate, Local),
        SpecTool::new(T, TL, "inference", "Inferences", "research:validate-inference", "Check an inference",
            "Check premise reliability, reasoning, and whether the conclusion is grounded.",
            "graph", Look, Query, Intermediate, Local),
        SpecTool::new(T, TL, "inference", "Inferences", "research:trace-inference-chain", "Trace the inference chain",
            "Follow premises through to the conclusion.",
            "graph", Look, Query, Intermediate, Local),
        SpecTool::new(T, TL, "inference", "Inferences", "research:compare-inferences", "Compare inferences",
            "Set two inferences side by side for overlap or contradiction.",
            "graph", Look, Query, Intermediate, Local),
        // synthesis (9)
        SpecTool::new(T, TL, "synthesis", "Synthesis", "research:create-finding", "Create a finding",
            "State a finding from evidence and an optional inference.",
            "doc", RunAction, Mutate, Novice, Local),
        SpecTool::new(T, TL, "synthesis", "Synthesis", "research:set-finding-confidence", "Set finding confidence",
            "Say how confident this finding is.",
            "doc", RunAction, Mutate, Intermediate, Local),
        SpecTool::new(T, TL, "synthesis", "Synthesis", "research:mark-finding-contested", "Mark as contested",
            "Note that this finding is in dispute.",
            "doc", RunAction, Mutate, Intermediate, Local),
        SpecTool::new(T, TL, "synthesis", "Synthesis", "research:link-finding-to-question", "Link to a question",
            "Connect this finding to the question it answers.",
            "doc", RunAction, Mutate, Intermediate, Local),
        SpecTool::new(T, TL, "synthesis", "Synthesis", "research:create-synthesis", "Create a synthesis",
            "Weave findings into a narrative, review, theory, model, vocabulary, or framework.",
            "doc", RunAction, Mutate, Intermediate, Local),
        SpecTool::new(T, TL, "synthesis", "Synthesis", "research:add-finding-to-synthesis", "Add to the synthesis",
            "Include this finding in a synthesis.",
            "doc", RunAction, Mutate, Novice, Local),
        SpecTool::new(T, TL, "synthesis", "Synthesis", "research:query-findings", "Find findings",
            "Look up findings by confidence, dispute, or linked question.",
            "doc", Look, Query, Intermediate, Local),
        SpecTool::new(T, TL, "synthesis", "Synthesis", "research:query-syntheses", "Find syntheses",
            "Look up syntheses by kind or included findings.",
            "doc", Look, Query, Intermediate, Local),
        SpecTool::new(T, TL, "synthesis", "Synthesis", "research:export-synthesis", "Save the synthesis",
            "Write the synthesis out as a paper, report, model, or framework.",
            "doc", RunAction, Mutate, Intermediate, Local),
        // provenance (5)
        SpecTool::new(T, TL, "provenance", "Where it came from", "research:trace-provenance", "Trace origins",
            "Follow the full origin chain of a finding, inference, source, or hidden link.",
            "graph", Look, Query, Intermediate, Local),
        SpecTool::new(T, TL, "provenance", "Where it came from", "research:verify-provenance", "Check origins",
            "See whether origins are complete, with sources and changes recorded.",
            "graph", Look, Query, Intermediate, Local),
        SpecTool::new(T, TL, "provenance", "Where it came from", "research:detect-provenance-break", "Find origin breaks",
            "Find missing sources, unrecorded changes, or broken derivation links.",
            "graph", Look, Query, Intermediate, Local),
        SpecTool::new(T, TL, "provenance", "Where it came from", "research:compare-provenance", "Compare origins",
            "See shared sources, contributors, and derivation between two items.",
            "graph", Look, Query, Intermediate, Local),
        SpecTool::new(T, TL, "provenance", "Where it came from", "research:export-provenance-report", "Save an origin report",
            "Write an origin report for the whole project.",
            "graph", RunAction, Mutate, Intermediate, Local),
        // bootstrap (15)
        SpecTool::new(T, TL, "bootstrap", "Starting out", "research:assess-deficit", "Assess the starting gap",
            "See how much source, hypothesis, dynamics, and evidence coverage is still missing.",
            "doc", Look, Query, Intermediate, Local),
        SpecTool::new(T, TL, "bootstrap", "Starting out", "research:identify-frontier", "Identify the frontier",
            "Mark what is known, unknown, and not yet even asked.",
            "doc", Look, Query, Intermediate, Local),
        SpecTool::new(T, TL, "bootstrap", "Starting out", "research:generate-bootstrap-hypotheses", "Sketch first hypotheses",
            "Generate first-pass hypotheses from purpose and scope alone. Confidence starts low.",
            "doc", RunAction, Mutate, Intermediate, Local),
        SpecTool::new(T, TL, "bootstrap", "Starting out", "research:refine-bootstrap", "Refine a first hypothesis",
            "Rewrite a first-pass hypothesis with new evidence.",
            "doc", RunAction, Mutate, Intermediate, Local),
        SpecTool::new(T, TL, "bootstrap", "Starting out", "research:confirm-bootstrap", "Confirm a first hypothesis",
            "Confirm a first-pass hypothesis once evidence is enough.",
            "doc", RunAction, Mutate, Intermediate, Local),
        SpecTool::new(T, TL, "bootstrap", "Starting out", "research:reframe-bootstrap", "Reframe a first hypothesis",
            "Rewrite a first-pass hypothesis more clearly, with a reason.",
            "doc", RunAction, Mutate, Intermediate, Local),
        SpecTool::new(T, TL, "bootstrap", "Starting out", "research:disprove-bootstrap", "Disprove a first hypothesis",
            "Mark a first-pass hypothesis as contradicted by evidence.",
            "doc", RunAction, Mutate, Intermediate, Local),
        SpecTool::new(T, TL, "bootstrap", "Starting out", "research:supersede-bootstrap", "Replace a first hypothesis",
            "Replace a first-pass hypothesis with a better one.",
            "doc", RunAction, Mutate, Intermediate, Local),
        SpecTool::new(T, TL, "bootstrap", "Starting out", "research:promote-bootstrap", "Promote to a case hypothesis",
            "Turn a first-pass hypothesis into a full case hypothesis.",
            "doc", RunAction, Mutate, Expert, Local),
        SpecTool::new(T, TL, "bootstrap", "Starting out", "research:record-enrichment", "Record an enrichment",
            "Note a new source, finding, inference, hidden link, or dynamic, and what it unlocked.",
            "doc", RunAction, Mutate, Intermediate, Local),
        SpecTool::new(T, TL, "bootstrap", "Starting out", "research:query-enrichment-history", "Find enrichments",
            "Look up what was added, by whom, and which gaps it closed.",
            "doc", Look, Query, Intermediate, Local),
        SpecTool::new(T, TL, "bootstrap", "Starting out", "research:query-capabilities", "List unlocked analyses",
            "Show which analyses are available given what has been gathered so far.",
            "doc", Look, Query, Intermediate, Local),
        SpecTool::new(T, TL, "bootstrap", "Starting out", "research:suggest-enrichment", "Suggest what next",
            "Suggest which gaps to close or which first hypotheses to refine.",
            "doc", Look, Query, Intermediate, Local),
        SpecTool::new(T, TL, "bootstrap", "Starting out", "research:query-frontier", "Search the frontier",
            "Look up the known, unknown, or not-yet-asked zone.",
            "doc", Look, Query, Intermediate, Local),
        SpecTool::new(T, TL, "bootstrap", "Starting out", "research:identify-unknown-unknowns", "Spot unasked questions",
            "Suggest possible unknown-unknowns by analogy, gaps, or an observer's note.",
            "doc", Look, Query, Expert, Local),
    ];
    ROWS
}
