//! Extra spatial spec tools from TOOLBOX_CODE_SPEC.md (toolbox id `spatial`).

use super::row::{Contract, SpecTool};
use crate::browser::tool_proficiency::Proficiency;
use crate::tool_chest::core::intent_bus::ActionType;
use crate::tool_chest::core::tool::ToolKind;

const T: &str = "spatial";
const TL: &str = "Space";

pub fn rows() -> &'static [SpecTool] {
    #[rustfmt::skip]
    static ROWS: &[SpecTool] = &[
        SpecTool::new(T, TL, "scene", "Scene graph", "spatial:create-scene",
            "New scene", "Start an empty ten-axis scene.",
            "3d", ToolKind::PlaceContainer, ActionType::Mutate,
            Proficiency::Novice, Contract::Place("3d")),
        SpecTool::new(T, TL, "scene", "Scene graph", "spatial:add-node",
            "Add a node", "Add a node to the scene tree.",
            "3d", ToolKind::RunAction, ActionType::Mutate,
            Proficiency::Novice, Contract::Local),
        SpecTool::new(T, TL, "scene", "Scene graph", "spatial:remove-node",
            "Remove a node", "Remove a node and its children.",
            "3d", ToolKind::RunAction, ActionType::Mutate,
            Proficiency::Novice, Contract::Local),
        SpecTool::new(T, TL, "scene", "Scene graph", "spatial:set-transform",
            "Set pose", "Set a node's place, turn, scale, and time offset.",
            "3d", ToolKind::RunAction, ActionType::Mutate,
            Proficiency::Intermediate, Contract::Local),
        SpecTool::new(T, TL, "scene", "Scene graph", "spatial:set-mesh",
            "Set mesh", "Give this node a mesh.",
            "3d", ToolKind::RunAction, ActionType::Mutate,
            Proficiency::Intermediate, Contract::Local),
        SpecTool::new(T, TL, "scene", "Scene graph", "spatial:set-material",
            "Set material", "Give this node a look (shader and values).",
            "3d", ToolKind::RunAction, ActionType::Mutate,
            Proficiency::Intermediate, Contract::Local),
        SpecTool::new(T, TL, "scene", "Scene graph", "spatial:add-light",
            "Add a light", "Add a light to the scene.",
            "3d", ToolKind::RunAction, ActionType::Mutate,
            Proficiency::Novice, Contract::Local),
        SpecTool::new(T, TL, "scene", "Scene graph", "spatial:add-camera",
            "Add a camera", "Add a camera to the scene.",
            "3d", ToolKind::RunAction, ActionType::Mutate,
            Proficiency::Intermediate, Contract::Local),
        SpecTool::new(T, TL, "scene", "Scene graph", "spatial:link-semantic",
            "Link meaning", "Link this node to a record or meaning term.",
            "3d", ToolKind::RunAction, ActionType::Mutate,
            Proficiency::Expert, Contract::Local),
        SpecTool::new(T, TL, "scene", "Scene graph", "spatial:duplicate-node",
            "Duplicate", "Copy this node and its children.",
            "3d", ToolKind::RunAction, ActionType::Mutate,
            Proficiency::Novice, Contract::Local),
        SpecTool::new(T, TL, "mesh", "Mesh edit", "spatial:import-mesh",
            "Import a mesh", "Bring in a 3D mesh from a file.",
            "3d", ToolKind::RunAction, ActionType::Mutate,
            Proficiency::Novice, Contract::Gated("Needs a mesh file.")),
        SpecTool::new(T, TL, "mesh", "Mesh edit", "spatial:export-mesh",
            "Export a mesh", "Save this mesh to a file.",
            "3d", ToolKind::RunAction, ActionType::Mutate,
            Proficiency::Intermediate, Contract::Gated("Needs a place to save the mesh.")),
        SpecTool::new(T, TL, "mesh", "Mesh edit", "spatial:edit-vertex",
            "Move a vertex", "Move one vertex on this mesh.",
            "3d", ToolKind::RunAction, ActionType::Mutate,
            Proficiency::Expert, Contract::Local),
        SpecTool::new(T, TL, "mesh", "Mesh edit", "spatial:subdivide-mesh",
            "Subdivide", "Split faces to add detail.",
            "3d", ToolKind::RunAction, ActionType::Mutate,
            Proficiency::Expert, Contract::Local),
        SpecTool::new(T, TL, "mesh", "Mesh edit", "spatial:decimate-mesh",
            "Simplify", "Reduce the number of faces.",
            "3d", ToolKind::RunAction, ActionType::Mutate,
            Proficiency::Intermediate, Contract::Local),
        SpecTool::new(T, TL, "mesh", "Mesh edit", "spatial:compute-normals",
            "Recompute normals", "Recalculate lighting directions on this mesh.",
            "3d", ToolKind::RunAction, ActionType::Mutate,
            Proficiency::Intermediate, Contract::Local),
        SpecTool::new(T, TL, "mesh", "Mesh edit", "spatial:add-rig",
            "Add a rig", "Attach a skeleton for skinned motion.",
            "3d", ToolKind::RunAction, ActionType::Mutate,
            Proficiency::Expert, Contract::Local),
        SpecTool::new(T, TL, "mesh", "Mesh edit", "spatial:add-blend-space",
            "Add blend shapes", "Add blend shapes for facial or morph motion.",
            "3d", ToolKind::RunAction, ActionType::Mutate,
            Proficiency::Expert, Contract::Local),
        SpecTool::new(T, TL, "render", "Drawing", "spatial:render-scene",
            "Draw the scene", "Draw this scene through the chosen camera.",
            "3d", ToolKind::RunAction, ActionType::Mutate,
            Proficiency::Novice, Contract::Live("Render.scene")),
        SpecTool::new(T, TL, "render", "Drawing", "spatial:set-viewport",
            "Set viewport", "Set the drawing size and pixel format.",
            "3d", ToolKind::RunAction, ActionType::Mutate,
            Proficiency::Intermediate, Contract::Local),
        SpecTool::new(T, TL, "render", "Drawing", "spatial:set-clear-colour",
            "Set background", "Set the viewport background colour.",
            "3d", ToolKind::RunAction, ActionType::Mutate,
            Proficiency::Novice, Contract::Local),
        SpecTool::new(T, TL, "render", "Drawing", "spatial:add-post-process",
            "Add a pass", "Add a finishing pass such as bloom or tone mapping.",
            "3d", ToolKind::RunAction, ActionType::Mutate,
            Proficiency::Expert, Contract::Local),
        SpecTool::new(T, TL, "render", "Drawing", "spatial:capture-frame",
            "Capture a frame", "Save the current frame as a picture.",
            "3d", ToolKind::Query, ActionType::Query,
            Proficiency::Novice, Contract::Local),
        SpecTool::new(T, TL, "render", "Drawing", "spatial:set-render-budget",
            "Set time budget", "Cap how long each frame may take.",
            "3d", ToolKind::RunAction, ActionType::Mutate,
            Proficiency::Expert, Contract::Local),
        SpecTool::new(T, TL, "manifold-nav", "Ten-axis camera", "spatial:navigate-spatial",
            "Move in space", "Move the camera along left-right, up-down, and near-far.",
            "3d", ToolKind::RunAction, ActionType::Mutate,
            Proficiency::Novice, Contract::Local),
        SpecTool::new(T, TL, "manifold-nav", "Ten-axis camera", "spatial:navigate-temporal",
            "Move in time", "Move the camera along the time or version axis.",
            "3d", ToolKind::RunAction, ActionType::Mutate,
            Proficiency::Intermediate, Contract::Local),
        SpecTool::new(T, TL, "manifold-nav", "Ten-axis camera", "spatial:navigate-quantum",
            "Shift what-if", "Shift between verified fact and what-if branches.",
            "3d", ToolKind::RunAction, ActionType::Mutate,
            Proficiency::Expert, Contract::Local),
        SpecTool::new(T, TL, "manifold-nav", "Ten-axis camera", "spatial:navigate-topology",
            "Change topology", "Change whether space is flat, looping, or tree-like.",
            "3d", ToolKind::RunAction, ActionType::Mutate,
            Proficiency::Expert, Contract::Local),
        SpecTool::new(T, TL, "manifold-nav", "Ten-axis camera", "spatial:navigate-manifold",
            "Change domain", "Change the domain this camera is looking through.",
            "3d", ToolKind::RunAction, ActionType::Mutate,
            Proficiency::Expert, Contract::Local),
        SpecTool::new(T, TL, "manifold-nav", "Ten-axis camera", "spatial:navigate-spectral",
            "Shift spectrum", "Move along brightness, modulation, and signature.",
            "3d", ToolKind::RunAction, ActionType::Mutate,
            Proficiency::Expert, Contract::Local),
        SpecTool::new(T, TL, "manifold-nav", "Ten-axis camera", "spatial:focus-node",
            "Focus a node", "Aim the camera at a chosen node's ten-axis pose.",
            "3d", ToolKind::RunAction, ActionType::Mutate,
            Proficiency::Novice, Contract::Local),
        SpecTool::new(T, TL, "manifold-nav", "Ten-axis camera", "spatial:orbit",
            "Orbit", "Orbit the camera around a point in space.",
            "3d", ToolKind::RunAction, ActionType::Mutate,
            Proficiency::Novice, Contract::Live("Animation.evaluate_preset")),
        SpecTool::new(T, TL, "manifold-nav", "Ten-axis camera", "spatial:set-manifold-camera",
            "Set camera axes", "Choose which of the ten axes this camera can travel.",
            "3d", ToolKind::RunAction, ActionType::Mutate,
            Proficiency::Expert, Contract::Local),
        SpecTool::new(T, TL, "manifold-nav", "Ten-axis camera", "spatial:set-spectral-perception",
            "Set what it sees", "Set whether this camera sees human-visible light or a wider range.",
            "3d", ToolKind::RunAction, ActionType::Mutate,
            Proficiency::Expert, Contract::Local),
        SpecTool::new(T, TL, "design", "Layout", "spatial:place-ui-element",
            "Place a control", "Put a panel, label, or handle in the scene.",
            "3d", ToolKind::RunAction, ActionType::Mutate,
            Proficiency::Novice, Contract::Local),
        SpecTool::new(T, TL, "design", "Layout", "spatial:snap-to-grid",
            "Snap to grid", "Snap this node's place to a grid.",
            "3d", ToolKind::RunAction, ActionType::Mutate,
            Proficiency::Novice, Contract::Local),
        SpecTool::new(T, TL, "design", "Layout", "spatial:snap-to-surface",
            "Snap to surface", "Snap this node onto a mesh surface.",
            "3d", ToolKind::RunAction, ActionType::Mutate,
            Proficiency::Intermediate, Contract::Local),
        SpecTool::new(T, TL, "design", "Layout", "spatial:measure-distance",
            "Measure", "Measure the distance between two nodes.",
            "3d", ToolKind::Query, ActionType::Query,
            Proficiency::Novice, Contract::Local),
        SpecTool::new(T, TL, "design", "Layout", "spatial:align-nodes",
            "Align", "Line several nodes up along an axis.",
            "3d", ToolKind::RunAction, ActionType::Mutate,
            Proficiency::Novice, Contract::Local),
        SpecTool::new(T, TL, "design", "Layout", "spatial:group-nodes",
            "Group", "Group nodes into a named set.",
            "3d", ToolKind::RunAction, ActionType::Mutate,
            Proficiency::Novice, Contract::Local),
        SpecTool::new(T, TL, "design", "Layout", "spatial:set-spatial-layout",
            "Apply layout", "Arrange child nodes on a grid, ring, or tree.",
            "3d", ToolKind::RunAction, ActionType::Mutate,
            Proficiency::Intermediate, Contract::Local),
    ];
    ROWS
}
