//! 3D editing spec tools from TOOLBOX_HYPERMEDIA_SPEC_2.md §4.

use super::row::{Contract, SpecTool};
use crate::browser::tool_proficiency::Proficiency;
use crate::tool_chest::core::intent_bus::ActionType;
use crate::tool_chest::core::tool::ToolKind;

const T: &str = "spatial3d";
const TL: &str = "3D editing";

pub fn rows() -> &'static [SpecTool] {
    static ROWS: &[SpecTool] = &[
        SpecTool::new(
            T,
            TL,
            "object",
            "Scene objects",
            "spatial3d:add-mesh",
            "Add a mesh",
            "Place a cube, sphere, cylinder, plane, cone, or torus.",
            "3d",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Novice,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "object",
            "Scene objects",
            "spatial3d:import-mesh",
            "Import a mesh",
            "Bring in a glTF, OBJ, FBX, or STL mesh.",
            "3d",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Intermediate,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "object",
            "Scene objects",
            "spatial3d:delete-object",
            "Delete object",
            "Remove the selected object from the scene.",
            "3d",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Novice,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "object",
            "Scene objects",
            "spatial3d:duplicate-object",
            "Duplicate object",
            "Copy the selected object, linked or independent.",
            "3d",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Novice,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "object",
            "Scene objects",
            "spatial3d:parent-object",
            "Parent object",
            "Attach one object to another in the hierarchy.",
            "3d",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Intermediate,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "object",
            "Scene objects",
            "spatial3d:group-objects",
            "Group objects",
            "Group the selected objects together.",
            "3d",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Novice,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "object",
            "Scene objects",
            "spatial3d:snap-to-grid",
            "Snap to grid",
            "Snap the selected object onto the grid.",
            "3d",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Novice,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "object",
            "Scene objects",
            "spatial3d:transform-object",
            "Move, rotate, scale",
            "Set position, rotation, and scale of the selected object.",
            "3d",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Novice,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "modelling",
            "Mesh editing",
            "spatial3d:extrude",
            "Extrude",
            "Push selected faces, edges, or vertices out.",
            "3d",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Intermediate,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "modelling",
            "Mesh editing",
            "spatial3d:inset",
            "Inset faces",
            "Shrink selected faces inward.",
            "3d",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Intermediate,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "modelling",
            "Mesh editing",
            "spatial3d:bevel",
            "Bevel",
            "Round or chamfer selected edges.",
            "3d",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Intermediate,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "modelling",
            "Mesh editing",
            "spatial3d:loop-cut",
            "Loop cut",
            "Cut a ring of new edges around the mesh.",
            "3d",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Intermediate,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "modelling",
            "Mesh editing",
            "spatial3d:subdivide",
            "Subdivide",
            "Split selected faces into finer faces.",
            "3d",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Intermediate,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "modelling",
            "Mesh editing",
            "spatial3d:merge-vertices",
            "Merge vertices",
            "Join vertices at centre, first, last, or collapse.",
            "3d",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Expert,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "modelling",
            "Mesh editing",
            "spatial3d:knife-tool",
            "Knife",
            "Cut faces along a drawn path.",
            "3d",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Expert,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "modelling",
            "Mesh editing",
            "spatial3d:boolean-op",
            "Boolean",
            "Union, difference, or intersect two meshes.",
            "3d",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Expert,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "rigging",
            "Rigging",
            "spatial3d:add-bone",
            "Add a bone",
            "Add a bone to the rig.",
            "3d",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Intermediate,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "rigging",
            "Rigging",
            "spatial3d:weight-paint",
            "Weight paint",
            "Paint how much a bone moves each vertex.",
            "3d",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Expert,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "rigging",
            "Rigging",
            "spatial3d:inverse-kinematics",
            "Inverse kinematics",
            "Set up an IK chain toward a target.",
            "3d",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Expert,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "rigging",
            "Rigging",
            "spatial3d:bone-constraint",
            "Bone constraint",
            "Constrain a bone to a target.",
            "3d",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Expert,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "rigging",
            "Rigging",
            "spatial3d:pose-mirror",
            "Mirror pose",
            "Mirror the pose across an axis.",
            "3d",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Intermediate,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "rigging",
            "Rigging",
            "spatial3d:rig-test",
            "Test the rig",
            "Check for weight gaps and bone conflicts.",
            "3d",
            ToolKind::Query,
            ActionType::Query,
            Proficiency::Expert,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "animation",
            "Animation",
            "spatial3d:keyframe-insert",
            "Insert keyframe",
            "Record a value on this frame.",
            "timeline",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Intermediate,
            Contract::Live("Animation.evaluate_preset"),
        ),
        SpecTool::new(
            T,
            TL,
            "animation",
            "Animation",
            "spatial3d:keyframe-edit",
            "Edit keyframe",
            "Change a keyframe value or interpolation.",
            "timeline",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Intermediate,
            Contract::Live("Animation.evaluate_preset"),
        ),
        SpecTool::new(
            T,
            TL,
            "animation",
            "Animation",
            "spatial3d:dope-sheet",
            "Dope sheet",
            "Show keyframes across objects.",
            "timeline",
            ToolKind::Query,
            ActionType::Query,
            Proficiency::Intermediate,
            Contract::Live("Animation.evaluate_preset"),
        ),
        SpecTool::new(
            T,
            TL,
            "animation",
            "Animation",
            "spatial3d:graph-editor",
            "Graph editor",
            "Show the animation curve for a property.",
            "timeline",
            ToolKind::Query,
            ActionType::Query,
            Proficiency::Expert,
            Contract::Live("Animation.evaluate_preset"),
        ),
        SpecTool::new(
            T,
            TL,
            "animation",
            "Animation",
            "spatial3d:action-clip",
            "Action clip",
            "Save a reusable clip from a frame range.",
            "timeline",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Intermediate,
            Contract::Live("Animation.evaluate_preset"),
        ),
        SpecTool::new(
            T,
            TL,
            "animation",
            "Animation",
            "spatial3d:animation-mixer",
            "Mix clips",
            "Blend action clips on the timeline.",
            "timeline",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Expert,
            Contract::Live("Animation.evaluate_preset"),
        ),
        SpecTool::new(
            T,
            TL,
            "animation",
            "Animation",
            "spatial3d:motion-path",
            "Motion path",
            "Show the path an object takes over time.",
            "timeline",
            ToolKind::Query,
            ActionType::Query,
            Proficiency::Intermediate,
            Contract::Live("Animation.evaluate_preset"),
        ),
        SpecTool::new(
            T,
            TL,
            "materials",
            "Materials",
            "spatial3d:create-material",
            "New material",
            "Make a PBR, unlit, or custom-shader material.",
            "3d",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Novice,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "materials",
            "Materials",
            "spatial3d:assign-material",
            "Assign material",
            "Put a material on the selected object.",
            "3d",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Novice,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "materials",
            "Materials",
            "spatial3d:texture-paint",
            "Paint texture",
            "Paint onto the mesh texture.",
            "3d",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Intermediate,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "materials",
            "Materials",
            "spatial3d:uv-edit",
            "Edit UVs",
            "Unwrap and edit the UV map.",
            "3d",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Expert,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "materials",
            "Materials",
            "spatial3d:material-node",
            "Material nodes",
            "Edit the material node graph.",
            "3d",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Expert,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "materials",
            "Materials",
            "spatial3d:pbr-preset",
            "PBR preset",
            "Apply metal, wood, stone, glass, or fabric.",
            "3d",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Intermediate,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "camera-light",
            "Cameras and lights",
            "spatial3d:add-camera",
            "Add camera",
            "Place a camera with lens and orientation.",
            "3d",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Novice,
            Contract::Live("Render.gpu_set_camera"),
        ),
        SpecTool::new(
            T,
            TL,
            "camera-light",
            "Cameras and lights",
            "spatial3d:camera-frame",
            "Frame camera",
            "Point the camera at a target.",
            "3d",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Novice,
            Contract::Live("Render.gpu_set_camera"),
        ),
        SpecTool::new(
            T,
            TL,
            "camera-light",
            "Cameras and lights",
            "spatial3d:add-light",
            "Add a light",
            "Place a point, sun, spot, or area light.",
            "3d",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Novice,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "camera-light",
            "Cameras and lights",
            "spatial3d:light-type",
            "Light type",
            "Change the selected light's kind.",
            "3d",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Intermediate,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "camera-light",
            "Cameras and lights",
            "spatial3d:hdri-setup",
            "HDRI sky",
            "Set the scene's environment image.",
            "3d",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Intermediate,
            Contract::Live("Render.scene"),
        ),
        SpecTool::new(
            T,
            TL,
            "camera-light",
            "Cameras and lights",
            "spatial3d:shadow-setup",
            "Shadows",
            "Set shadow type, resolution, and bias.",
            "3d",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Intermediate,
            Contract::Live("Render.scene"),
        ),
        SpecTool::new(
            T,
            TL,
            "narrative",
            "Story",
            "spatial3d:add-scene",
            "Add a scene",
            "Add a named scene to the story.",
            "timeline",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Novice,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "narrative",
            "Story",
            "spatial3d:scene-sequence",
            "Scene order",
            "Order scenes in the story.",
            "timeline",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Intermediate,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "narrative",
            "Story",
            "spatial3d:camera-path",
            "Camera path",
            "Animate the camera along a path.",
            "timeline",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Intermediate,
            Contract::Live("Render.gpu_set_camera"),
        ),
        SpecTool::new(
            T,
            TL,
            "narrative",
            "Story",
            "spatial3d:storyboard-frame",
            "Storyboard frame",
            "Pin a still and a note to this scene.",
            "timeline",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Novice,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "narrative",
            "Story",
            "spatial3d:trigger-zone",
            "Trigger zone",
            "Fire an action when someone enters a zone.",
            "timeline",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Intermediate,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "narrative",
            "Story",
            "spatial3d:narrative-export",
            "Export story",
            "Export the story as a board or script.",
            "timeline",
            ToolKind::Query,
            ActionType::Query,
            Proficiency::Intermediate,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "inspect",
            "Inspect",
            "spatial3d:mesh-statistics",
            "Mesh stats",
            "Show vertex, face, and UV counts.",
            "inspect",
            ToolKind::Query,
            ActionType::Query,
            Proficiency::Novice,
            Contract::Live("Render.scene"),
        ),
        SpecTool::new(
            T,
            TL,
            "inspect",
            "Inspect",
            "spatial3d:material-inspector",
            "Material inspector",
            "Show material channels and textures.",
            "inspect",
            ToolKind::Query,
            ActionType::Query,
            Proficiency::Intermediate,
            Contract::Live("Render.scene"),
        ),
        SpecTool::new(
            T,
            TL,
            "inspect",
            "Inspect",
            "spatial3d:rig-inspector",
            "Rig inspector",
            "Show bones, constraints, and weights.",
            "inspect",
            ToolKind::Query,
            ActionType::Query,
            Proficiency::Intermediate,
            Contract::Live("Render.scene"),
        ),
        SpecTool::new(
            T,
            TL,
            "inspect",
            "Inspect",
            "spatial3d:scene-graph",
            "Scene graph",
            "Show the full object hierarchy.",
            "inspect",
            ToolKind::Query,
            ActionType::Query,
            Proficiency::Novice,
            Contract::Live("Render.scene"),
        ),
        SpecTool::new(
            T,
            TL,
            "inspect",
            "Inspect",
            "spatial3d:metadata-view",
            "Asset details",
            "Show format, vertex count, bones, and morphs.",
            "inspect",
            ToolKind::Query,
            ActionType::Query,
            Proficiency::Novice,
            Contract::Live("Render.scene"),
        ),
    ];
    ROWS
}
