//! Video production spec tools from TOOLBOX_HYPERMEDIA_SPEC.md §3
//! (transport, editing, transitions, colour, effects, generators, audio-sync, inspect, render).

use super::row::{Contract, SpecTool};
use crate::browser::tool_proficiency::Proficiency;
use crate::tool_chest::core::intent_bus::ActionType;
use crate::tool_chest::core::tool::ToolKind;

const T: &str = "video";
const TL: &str = "Moving pictures";

pub fn rows() -> &'static [SpecTool] {
    static ROWS: &[SpecTool] = &[
        SpecTool::new(
            T,
            TL,
            "transport",
            "Play and stop",
            "video:play",
            "Play",
            "Start playing from this frame.",
            "video",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Novice,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "transport",
            "Play and stop",
            "video:stop",
            "Stop",
            "Stop playing on the selected surface.",
            "video",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Novice,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "transport",
            "Play and stop",
            "video:mark-in",
            "Mark in",
            "Mark where this shot starts.",
            "video",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Novice,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "transport",
            "Play and stop",
            "video:mark-out",
            "Mark out",
            "Mark where this shot ends.",
            "video",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Novice,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "transport",
            "Play and stop",
            "video:shuttle",
            "Shuttle",
            "Play faster or slower, forwards or back.",
            "video",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Intermediate,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "transport",
            "Play and stop",
            "video:jog",
            "Jog",
            "Step one frame at a time.",
            "video",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Novice,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "editing",
            "Cut and join",
            "video:razor",
            "Razor",
            "Cut the selected clip at this frame.",
            "video",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Novice,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "editing",
            "Cut and join",
            "video:splice",
            "Splice",
            "Join selected clips together.",
            "video",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Novice,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "editing",
            "Cut and join",
            "video:overwrite",
            "Overwrite",
            "Put this clip over what is already there.",
            "video",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Intermediate,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "editing",
            "Cut and join",
            "video:insert",
            "Insert",
            "Put this clip in and push the rest along.",
            "video",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Intermediate,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "editing",
            "Cut and join",
            "video:ripple-delete",
            "Ripple delete",
            "Remove the clip and close the gap.",
            "video",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Intermediate,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "editing",
            "Cut and join",
            "video:lift",
            "Lift",
            "Take the clip out and leave a gap.",
            "video",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Intermediate,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "editing",
            "Cut and join",
            "video:append",
            "Append",
            "Put this clip at the end of the track.",
            "video",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Novice,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "editing",
            "Cut and join",
            "video:split-clip",
            "Split",
            "Split the clip into two at this frame.",
            "video",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Novice,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "editing",
            "Cut and join",
            "video:match-frame",
            "Match frame",
            "Find this frame in the source bin.",
            "video",
            ToolKind::Query,
            ActionType::Query,
            Proficiency::Intermediate,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "editing",
            "Cut and join",
            "video:replace",
            "Replace",
            "Swap this clip for another.",
            "video",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Intermediate,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "transitions",
            "Joins",
            "video:crossfade",
            "Crossfade",
            "Dissolve from one clip to the next.",
            "video",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Novice,
            Contract::Live("Animation.easing"),
        ),
        SpecTool::new(
            T,
            TL,
            "transitions",
            "Joins",
            "video:wipe",
            "Wipe",
            "Wipe from one clip to the next.",
            "video",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Intermediate,
            Contract::Live("Animation.easing"),
        ),
        SpecTool::new(
            T,
            TL,
            "transitions",
            "Joins",
            "video:dissolve",
            "Dissolve",
            "Softly blend from one clip to the next.",
            "video",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Novice,
            Contract::Live("Animation.easing"),
        ),
        SpecTool::new(
            T,
            TL,
            "transitions",
            "Joins",
            "video:push",
            "Push",
            "Push one clip in with the next.",
            "video",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Intermediate,
            Contract::Live("Animation.easing"),
        ),
        SpecTool::new(
            T,
            TL,
            "transitions",
            "Joins",
            "video:slide",
            "Slide",
            "Slide the next clip over this one.",
            "video",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Intermediate,
            Contract::Live("Animation.easing"),
        ),
        SpecTool::new(
            T,
            TL,
            "transitions",
            "Joins",
            "video:dip-to-black",
            "Dip to black",
            "Fade through black between clips.",
            "video",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Novice,
            Contract::Live("Animation.easing"),
        ),
        SpecTool::new(
            T,
            TL,
            "transitions",
            "Joins",
            "video:custom-transition",
            "Custom join",
            "Use a saved join between clips.",
            "video",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Expert,
            Contract::Live("Animation.evaluate_preset"),
        ),
        SpecTool::new(
            T,
            TL,
            "colour",
            "Colour",
            "video:lift-gamma-gain",
            "Lift, gamma, gain",
            "Grade shadows, midtones, and highlights.",
            "video",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Intermediate,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "colour",
            "Colour",
            "video:saturation",
            "Saturation",
            "Make the colours stronger or quieter.",
            "video",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Novice,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "colour",
            "Colour",
            "video:colour-wheels",
            "Colour wheels",
            "Grade shadows, midtones, and highlights with wheels.",
            "video",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Intermediate,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "colour",
            "Colour",
            "video:curves",
            "Curves",
            "Shape brightness with a curve.",
            "video",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Intermediate,
            Contract::Live("Animation.bezier_eval"),
        ),
        SpecTool::new(
            T,
            TL,
            "colour",
            "Colour",
            "video:hue-vs-hue",
            "Hue versus hue",
            "Shift one colour towards another.",
            "video",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Expert,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "colour",
            "Colour",
            "video:hue-vs-sat",
            "Hue versus saturation",
            "Change how strong one colour is.",
            "video",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Expert,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "colour",
            "Colour",
            "video:lut-apply",
            "Apply a look",
            "Apply a look-up table to this clip.",
            "video",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Intermediate,
            Contract::Gated("Needs a look-up table file."),
        ),
        SpecTool::new(
            T,
            TL,
            "colour",
            "Colour",
            "video:lut-export",
            "Export a look",
            "Save this grade as a look-up table.",
            "video",
            ToolKind::Query,
            ActionType::Query,
            Proficiency::Expert,
            Contract::Gated("Needs a place to save the look-up table."),
        ),
        SpecTool::new(
            T,
            TL,
            "effects",
            "Picture effects",
            "video:stabilise",
            "Steady",
            "Steady shaky pictures on this clip.",
            "video",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Intermediate,
            Contract::Gated("Needs the clip's motion analysed."),
        ),
        SpecTool::new(
            T,
            TL,
            "effects",
            "Picture effects",
            "video:speed-change",
            "Speed",
            "Change how fast the selected clip plays.",
            "video",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Intermediate,
            Contract::Live("Animation.easing"),
        ),
        SpecTool::new(
            T,
            TL,
            "effects",
            "Picture effects",
            "video:transform",
            "Place and size",
            "Move, scale, or turn the picture.",
            "video",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Novice,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "effects",
            "Picture effects",
            "video:chroma-key",
            "Green screen",
            "Cut out a key colour from the picture.",
            "video",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Intermediate,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "effects",
            "Picture effects",
            "video:mask",
            "Mask",
            "Hide part of the selected frame.",
            "video",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Intermediate,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "effects",
            "Picture effects",
            "video:motion-track",
            "Follow motion",
            "Follow a point in the picture.",
            "video",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Expert,
            Contract::Gated("Needs a track point and a range of frames."),
        ),
        SpecTool::new(
            T,
            TL,
            "effects",
            "Picture effects",
            "video:add-blur",
            "Blur",
            "Soften the selected picture.",
            "video",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Novice,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "generators",
            "Make a picture",
            "video:title-generator",
            "Title",
            "Make a title clip on this timeline.",
            "video",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Novice,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "generators",
            "Make a picture",
            "video:lower-third",
            "Lower third",
            "Make a name plate along the bottom.",
            "video",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Intermediate,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "generators",
            "Make a picture",
            "video:shape-generator",
            "Shape",
            "Make a shape clip on this timeline.",
            "video",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Novice,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "generators",
            "Make a picture",
            "video:colour-matte",
            "Colour fill",
            "Make a solid colour clip.",
            "video",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Novice,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "generators",
            "Make a picture",
            "video:noise-generator",
            "Noise",
            "Make a noise clip on this timeline.",
            "video",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Intermediate,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "audio-sync",
            "Picture and sound",
            "video:sync-from-audio",
            "Sync to sound",
            "Line the picture up with the sound.",
            "video",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Intermediate,
            Contract::Gated("Needs a picture clip and a sound clip to match."),
        ),
        SpecTool::new(
            T,
            TL,
            "audio-sync",
            "Picture and sound",
            "video:auto-align",
            "Auto-align",
            "Line several clips up by their sound.",
            "video",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Expert,
            Contract::Gated("Needs clips with matching sound."),
        ),
        SpecTool::new(
            T,
            TL,
            "audio-sync",
            "Picture and sound",
            "video:scrub-audio",
            "Scrub sound",
            "Hear the sound at this frame.",
            "video",
            ToolKind::Query,
            ActionType::Query,
            Proficiency::Novice,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "audio-sync",
            "Picture and sound",
            "video:extract-audio",
            "Lift the sound",
            "Take the sound out of the picture clip.",
            "video",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Intermediate,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "audio-sync",
            "Picture and sound",
            "video:link-clips",
            "Link clips",
            "Keep picture and sound clips together.",
            "video",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Novice,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "inspect",
            "Inspect",
            "video:waveform-monitor",
            "Waveform",
            "Show brightness across the selected frame.",
            "video",
            ToolKind::Query,
            ActionType::Query,
            Proficiency::Intermediate,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "inspect",
            "Inspect",
            "video:vectorscope",
            "Vectorscope",
            "Show colour on a round scope for this frame.",
            "video",
            ToolKind::Query,
            ActionType::Query,
            Proficiency::Intermediate,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "inspect",
            "Inspect",
            "video:histogram",
            "Histogram",
            "Show how much of each colour is in the frame.",
            "video",
            ToolKind::Query,
            ActionType::Query,
            Proficiency::Novice,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "inspect",
            "Inspect",
            "video:frame-info",
            "Frame details",
            "Show time, size, and format for this frame.",
            "video",
            ToolKind::Query,
            ActionType::Query,
            Proficiency::Novice,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "inspect",
            "Inspect",
            "video:metadata-view",
            "Picture details",
            "Show format, size, frame rate, and colour space.",
            "video",
            ToolKind::Query,
            ActionType::Query,
            Proficiency::Novice,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "render",
            "Finish",
            "video:render-queue",
            "Queue a finish",
            "Queue this piece to be finished.",
            "video",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Intermediate,
            Contract::Gated("Needs an output place and finish settings."),
        ),
        SpecTool::new(
            T,
            TL,
            "render",
            "Finish",
            "video:render-settings",
            "Finish settings",
            "Set format, quality, and size for the finish.",
            "video",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Intermediate,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "render",
            "Finish",
            "video:render-preview",
            "Preview frame",
            "Draw this frame of the scene.",
            "video",
            ToolKind::Query,
            ActionType::Query,
            Proficiency::Novice,
            Contract::Live("Render.scene"),
        ),
        SpecTool::new(
            T,
            TL,
            "render",
            "Finish",
            "video:export-preset",
            "Save a finish preset",
            "Save these finish settings on the selected surface.",
            "video",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Intermediate,
            Contract::Local,
        ),
        SpecTool::new(
            T,
            TL,
            "render",
            "Finish",
            "video:batch-render",
            "Finish several",
            "Finish several queued jobs.",
            "video",
            ToolKind::RunAction,
            ActionType::Mutate,
            Proficiency::Expert,
            Contract::Gated("Needs queued finish jobs."),
        ),
    ];
    ROWS
}
