use super::super::row::{Contract, SpecTool};
use crate::browser::tool_proficiency::Proficiency;
use crate::tool_chest::core::intent_bus::ActionType;
use crate::tool_chest::core::tool::ToolKind;

const T: &str = "audio";
const TL: &str = "Sound";

pub(super) static ROWS: &[SpecTool] = &[
    SpecTool::new(
        T,
        TL,
        "editing",
        "Clip cuts",
        "audio:split-clip",
        "Split",
        "Cut the selected clip in two at this place.",
        "audio",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Novice,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "editing",
        "Clip cuts",
        "audio:join-clips",
        "Join",
        "Join neighbouring clips into one.",
        "audio",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Novice,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "editing",
        "Clip cuts",
        "audio:trim-clip",
        "Trim",
        "Shorten the selected clip at the ends.",
        "audio",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Novice,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "editing",
        "Clip cuts",
        "audio:fade-in",
        "Fade in",
        "Soften the start of the selected clip.",
        "audio",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Novice,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "editing",
        "Clip cuts",
        "audio:fade-out",
        "Fade out",
        "Soften the end of the selected clip.",
        "audio",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Novice,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "editing",
        "Clip cuts",
        "audio:crossfade",
        "Crossfade",
        "Blend two clips where they meet.",
        "audio",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Intermediate,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "editing",
        "Clip cuts",
        "audio:time-stretch",
        "Stretch time",
        "Stretch the clip without changing pitch.",
        "audio",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Intermediate,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "editing",
        "Clip cuts",
        "audio:pitch-shift",
        "Shift pitch",
        "Change pitch without changing length.",
        "audio",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Intermediate,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "editing",
        "Clip cuts",
        "audio:reverse",
        "Reverse",
        "Play the selected clip backwards.",
        "audio",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Novice,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "editing",
        "Clip cuts",
        "audio:normalise",
        "Even the loudness",
        "Bring the clip's peak to a chosen level.",
        "audio",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Intermediate,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "synthesis",
        "Sound makers",
        "audio:osc-config",
        "Oscillator",
        "Set the oscillator wave, pitch, and detune.",
        "audio",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Intermediate,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "synthesis",
        "Sound makers",
        "audio:filter-config",
        "Filter",
        "Set the filter type, cutoff, and resonance.",
        "audio",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Intermediate,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "synthesis",
        "Sound makers",
        "audio:envelope-config",
        "Envelope",
        "Set attack, decay, sustain, and release.",
        "audio",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Intermediate,
        Contract::Live("Animation.bezier_eval"),
    ),
    SpecTool::new(
        T,
        TL,
        "synthesis",
        "Sound makers",
        "audio:lfo-config",
        "Slow wobble",
        "Set the slow wobble and what it moves.",
        "audio",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Intermediate,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "synthesis",
        "Sound makers",
        "audio:mod-routing",
        "Modulation",
        "Route a source to a target with an amount.",
        "audio",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Expert,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "synthesis",
        "Sound makers",
        "audio:preset-save",
        "Save sound",
        "Save this synthesiser sound on the selected rack.",
        "audio",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Intermediate,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "synthesis",
        "Sound makers",
        "audio:preset-load",
        "Load sound",
        "Load a saved synthesiser sound.",
        "audio",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Intermediate,
        Contract::Gated("Needs a saved sound to load onto this rack."),
    ),
    SpecTool::new(
        T,
        TL,
        "synthesis",
        "Sound makers",
        "audio:wavetable-import",
        "Bring in a wavetable",
        "Load a wavetable into this synthesiser.",
        "audio",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Expert,
        Contract::Gated("Needs a wavetable file to bring in."),
    ),
];
