use super::super::row::{Contract, SpecTool};
use crate::browser::tool_proficiency::Proficiency;
use crate::tool_chest::core::intent_bus::ActionType;
use crate::tool_chest::core::tool::ToolKind;

const T: &str = "audio";
const TL: &str = "Sound";

pub(super) static ROWS: &[SpecTool] = &[
    SpecTool::new(
        T,
        TL,
        "midi",
        "Notes",
        "audio:note-draw",
        "Draw a note",
        "Draw a note on the selected piano roll.",
        "audio",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Novice,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "midi",
        "Notes",
        "audio:note-edit",
        "Edit a note",
        "Change a note's pitch, start, or length.",
        "audio",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Novice,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "midi",
        "Notes",
        "audio:velocity-edit",
        "How hard",
        "Change how hard the selected note is struck.",
        "audio",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Intermediate,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "midi",
        "Notes",
        "audio:cc-edit",
        "Control curve",
        "Draw a control curve over time on this track.",
        "audio",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Intermediate,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "midi",
        "Notes",
        "audio:quantise",
        "Snap to the beat",
        "Snap notes on this track to the beat.",
        "audio",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Intermediate,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "midi",
        "Notes",
        "audio:transpose",
        "Transpose",
        "Move all notes on this track up or down.",
        "audio",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Intermediate,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "midi",
        "Notes",
        "audio:midi-import",
        "Bring in notes",
        "Load notes from a MIDI file onto this track.",
        "audio",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Intermediate,
        Contract::Gated("Needs a MIDI file to bring in."),
    ),
    SpecTool::new(
        T,
        TL,
        "effects",
        "Effects",
        "audio:add-effect",
        "Add an effect",
        "Put an effect on the selected track.",
        "audio",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Novice,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "effects",
        "Effects",
        "audio:reorder-effect",
        "Reorder effects",
        "Change the order of effects on this track.",
        "audio",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Intermediate,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "effects",
        "Effects",
        "audio:remove-effect",
        "Remove effect",
        "Take an effect off this track.",
        "audio",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Novice,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "effects",
        "Effects",
        "audio:reverb-config",
        "Room",
        "Set room size, damping, and wet or dry mix.",
        "audio",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Intermediate,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "effects",
        "Effects",
        "audio:delay-config",
        "Echo",
        "Set echo time, feedback, and mix.",
        "audio",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Intermediate,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "effects",
        "Effects",
        "audio:compressor-config",
        "Compressor",
        "Set threshold, ratio, attack, and release.",
        "audio",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Intermediate,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "effects",
        "Effects",
        "audio:eq-config",
        "Equaliser",
        "Set the bands of the equaliser on this track.",
        "audio",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Intermediate,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "effects",
        "Effects",
        "audio:saturation-config",
        "Warmth",
        "Set drive, mix, and character on this track.",
        "audio",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Intermediate,
        Contract::Local,
    ),
];
