use super::super::row::{Contract, SpecTool};
use crate::browser::tool_proficiency::Proficiency;
use crate::tool_chest::core::intent_bus::ActionType;
use crate::tool_chest::core::tool::ToolKind;

const T: &str = "audio";
const TL: &str = "Sound";

pub(super) static ROWS: &[SpecTool] = &[
    SpecTool::new(
        T,
        TL,
        "mixing",
        "Mix",
        "audio:set-send",
        "Send",
        "Set how much this track sends to a bus.",
        "audio",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Intermediate,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "mixing",
        "Mix",
        "audio:set-bus",
        "Bus output",
        "Route this track out through a bus.",
        "audio",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Intermediate,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "mixing",
        "Mix",
        "audio:automation-draw",
        "Draw automation",
        "Draw how a control moves over time.",
        "audio",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Intermediate,
        Contract::Live("Animation.bezier_eval"),
    ),
    SpecTool::new(
        T,
        TL,
        "mixing",
        "Mix",
        "audio:automation-edit",
        "Edit automation",
        "Move a point on an automation curve.",
        "audio",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Intermediate,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "mixing",
        "Mix",
        "audio:bounce-track",
        "Bounce track",
        "Mix this track down to a sound file.",
        "audio",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Expert,
        Contract::Gated("Needs a place to save the bounced sound."),
    ),
    SpecTool::new(
        T,
        TL,
        "mixing",
        "Mix",
        "audio:bounce-mix",
        "Bounce mix",
        "Mix the whole piece down to a sound file.",
        "audio",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Expert,
        Contract::Gated("Needs a place to save the mixed sound."),
    ),
    SpecTool::new(
        T,
        TL,
        "inspect",
        "Inspect",
        "audio:spectrum-analyser",
        "Spectrum",
        "Show the frequencies of the selected track.",
        "audio",
        ToolKind::Query,
        ActionType::Query,
        Proficiency::Intermediate,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "inspect",
        "Inspect",
        "audio:waveform-view",
        "Waveform",
        "Show the shape of the selected clip.",
        "audio",
        ToolKind::Query,
        ActionType::Query,
        Proficiency::Novice,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "inspect",
        "Inspect",
        "audio:phase-meter",
        "Phase",
        "Show how left and right line up on this track.",
        "audio",
        ToolKind::Query,
        ActionType::Query,
        Proficiency::Intermediate,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "inspect",
        "Inspect",
        "audio:loudness-meter",
        "Loudness",
        "Show how loud this track is over time.",
        "audio",
        ToolKind::Query,
        ActionType::Query,
        Proficiency::Intermediate,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "inspect",
        "Inspect",
        "audio:metadata-view",
        "Sound details",
        "Show sample rate, bit depth, channels, and length.",
        "audio",
        ToolKind::Query,
        ActionType::Query,
        Proficiency::Novice,
        Contract::Local,
    ),
];
