use super::super::row::{Contract, SpecTool};
use crate::browser::tool_proficiency::Proficiency;
use crate::tool_chest::core::intent_bus::ActionType;
use crate::tool_chest::core::tool::ToolKind;

const T: &str = "audio";
const TL: &str = "Sound";

pub(super) static ROWS: &[SpecTool] = &[
    SpecTool::new(
        T,
        TL,
        "transport",
        "Play and stop",
        "audio:play",
        "Play",
        "Start playing from this place on the timeline.",
        "audio",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Novice,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "transport",
        "Play and stop",
        "audio:stop",
        "Stop",
        "Stop playing and return to the start.",
        "audio",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Novice,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "transport",
        "Play and stop",
        "audio:record",
        "Record",
        "Record into the armed track on this surface.",
        "audio",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Intermediate,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "transport",
        "Play and stop",
        "audio:loop-region",
        "Loop",
        "Loop a stretch of the selected timeline.",
        "audio",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Novice,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "transport",
        "Play and stop",
        "audio:metronome",
        "Click",
        "Turn the click on or off, and set the beat.",
        "audio",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Novice,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "transport",
        "Play and stop",
        "audio:tempo-set",
        "Tempo",
        "Set how fast this piece plays.",
        "audio",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Novice,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "tracks",
        "Tracks",
        "audio:add-audio-track",
        "Add a sound track",
        "Add a sound track to this piece.",
        "audio",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Novice,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "tracks",
        "Tracks",
        "audio:add-midi-track",
        "Add a notes track",
        "Add a notes track with an instrument.",
        "audio",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Novice,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "tracks",
        "Tracks",
        "audio:add-bus",
        "Add a bus",
        "Add a bus so several tracks can share a path.",
        "audio",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Intermediate,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "tracks",
        "Tracks",
        "audio:delete-track",
        "Remove track",
        "Remove the selected track.",
        "audio",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Novice,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "tracks",
        "Tracks",
        "audio:rename-track",
        "Rename track",
        "Give the selected track a new name.",
        "audio",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Novice,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "tracks",
        "Tracks",
        "audio:track-volume",
        "Volume",
        "Set how loud the selected track is.",
        "audio",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Novice,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "tracks",
        "Tracks",
        "audio:track-pan",
        "Pan",
        "Sit the selected track left, centre, or right.",
        "audio",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Novice,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "tracks",
        "Tracks",
        "audio:track-routing",
        "Route track",
        "Send the selected track to a bus or the master.",
        "audio",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Intermediate,
        Contract::Local,
    ),
];
