use reqwest::blocking::Client;
use serde_json::{json, Value};
use std::collections::HashMap;
use std::time::Duration;

const GITHUB_API_URL: &str = "https://api.github.com";
const USER_AGENT: &str = "qualia-webizen-client";

/// Creates a reqwest client configured for GitHub API.
fn github_client(token: &str) -> Result<Client, String> {
    let mut headers = reqwest::header::HeaderMap::new();
    headers.insert(
        reqwest::header::AUTHORIZATION,
        reqwest::header::HeaderValue::from_str(&format!("token {}", token))
            .map_err(|e| format!("Invalid token header: {}", e))?,
    );
    headers.insert(
        reqwest::header::ACCEPT,
        reqwest::header::HeaderValue::from_static("application/vnd.github.v3+json"),
    );
    headers.insert(
        reqwest::header::USER_AGENT,
        reqwest::header::HeaderValue::from_static(USER_AGENT),
    );

    let client = Client::builder()
        .default_headers(headers)
        .timeout(Duration::from_secs(30))
        .build()
        .map_err(|e| format!("Failed to build client: {}", e))?;

    Ok(client)
}

/// Helper to parse GitHub API errors
fn handle_response(resp: reqwest::blocking::Response) -> Result<Value, String> {
    let status = resp.status();
    let text = resp
        .text()
        .map_err(|e| format!("Failed to read response: {}", e))?;
    if !status.is_success() {
        return Err(format!("GitHub API error ({}): {}", status, text));
    }
    serde_json::from_str(&text).map_err(|e| format!("Failed to parse GitHub JSON: {e}"))
}

/// Verifies a GitHub Personal Access Token (PAT).
pub fn verify_github_token(token: &str) -> Result<String, String> {
    let client = github_client(token)?;
    let resp = client
        .get(&format!("{}/user", GITHUB_API_URL))
        .send()
        .map_err(|e| format!("Failed to send request: {}", e))?;
    let json = handle_response(resp)?;
    let login = json["login"].as_str().unwrap_or("unknown").to_string();
    Ok(login)
}

/// Creates a new public GitHub repository. Returns the repository full name (e.g., "username/repo").
pub fn create_repository(token: &str, name: &str) -> Result<String, String> {
    let client = github_client(token)?;

    // First, verify the user to get their login so we can return the full name if auto_init takes time.
    let _login = verify_github_token(token)?;

    // Create the repo
    let resp = client
        .post(&format!("{}/user/repos", GITHUB_API_URL))
        .json(&json!({
            "name": name,
            "description": "Generated by Qualia Webizen",
            "private": false,
            "auto_init": true, // Automatically creates the main branch with a README
        }))
        .send()
        .map_err(|e| format!("Request failed: {}", e))?;

    let status = resp.status();
    let text = resp
        .text()
        .map_err(|e| format!("Failed to read text: {}", e))?;

    // 422 usually means the repository already exists
    if status.as_u16() == 422 && text.contains("already exists") {
        return Ok(format!("{}/{}", _login, name));
    }

    if !status.is_success() {
        return Err(format!(
            "GitHub API error creating repo ({}): {}",
            status, text
        ));
    }

    let result_json: Value =
        serde_json::from_str(&text).map_err(|e| format!("Invalid JSON: {}", e))?;
    let full_name = result_json["full_name"]
        .as_str()
        .ok_or_else(|| "No full_name in response".to_string())?;
    Ok(full_name.to_string())
}

/// Pushes a directory of files to a GitHub repository using the Git Data API.
/// `files` is a map of file path (e.g. "index.html") to its string content.
pub fn push_static_site(
    token: &str,
    full_name: &str,
    files: HashMap<String, String>,
) -> Result<(), String> {
    if files.is_empty() {
        return Ok(());
    }

    let client = github_client(token)?;
    let base_url = format!("{}/repos/{}", GITHUB_API_URL, full_name);

    // 1. Get the current commit SHA for the default branch (usually 'main' or 'master')
    let ref_resp = client
        .get(&format!("{}/git/ref/heads/main", base_url))
        .send()
        .map_err(|e| format!("Req failed: {}", e))?;
    let ref_json = if ref_resp.status().is_success() {
        handle_response(ref_resp)?
    } else {
        // Fallback to master if main doesn't exist
        let master_resp = client
            .get(&format!("{}/git/ref/heads/master", base_url))
            .send()
            .map_err(|e| format!("Req failed: {}", e))?;
        handle_response(master_resp)?
    };

    let latest_commit_sha = ref_json["object"]["sha"].as_str().unwrap_or_default();
    let ref_name = ref_json["ref"].as_str().unwrap_or_default();

    // 2. Get the base tree SHA
    let commit_resp = client
        .get(&format!("{}/git/commits/{}", base_url, latest_commit_sha))
        .send()
        .map_err(|e| format!("Req failed: {}", e))?;
    let commit_json = handle_response(commit_resp)?;
    let base_tree_sha = commit_json["tree"]["sha"].as_str().unwrap_or_default();

    // 3. Create a new Tree
    let mut tree_nodes = Vec::new();
    for (path, content) in files {
        tree_nodes.push(json!({
            "path": path,
            "mode": "100644",
            "type": "blob",
            "content": content
        }));
    }

    let tree_resp = client
        .post(&format!("{}/git/trees", base_url))
        .json(&json!({
            "base_tree": base_tree_sha,
            "tree": tree_nodes
        }))
        .send()
        .map_err(|e| format!("Req failed: {}", e))?;
    let new_tree_json = handle_response(tree_resp)?;
    let new_tree_sha = new_tree_json["sha"].as_str().unwrap_or_default();

    // 4. Create a new Commit
    let commit_resp = client
        .post(&format!("{}/git/commits", base_url))
        .json(&json!({
            "message": "Deploy static site from Webizen",
            "tree": new_tree_sha,
            "parents": [latest_commit_sha]
        }))
        .send()
        .map_err(|e| format!("Req failed: {}", e))?;
    let new_commit_json = handle_response(commit_resp)?;
    let new_commit_sha = new_commit_json["sha"].as_str().unwrap_or_default();

    // 5. Update the Reference
    let _update_ref_resp = client
        .patch(&format!("{}/git/{}", base_url, ref_name))
        .json(&json!({
            "sha": new_commit_sha,
            "force": false
        }))
        .send()
        .map_err(|e| format!("Req failed: {}", e))?;

    Ok(())
}
