use std::fmt::Write;

use super::{GeneratedShader, TargetBackend};
use crate::wgsl_forge::{ForgeError, KernelSpec, Op, Schedule, FORGE_SCHEMA_VERSION};

pub fn emit_wgsl(kernel: &KernelSpec, schedule: Schedule) -> Result<GeneratedShader, ForgeError> {
    kernel.validate()?;
    let semantic_hash = kernel.semantic_hash()?;
    let mut source = String::with_capacity(2_048);
    writeln!(source, "// Generated by Qualia WGSL Forge schema {FORGE_SCHEMA_VERSION}.")
        .map_err(|error| ForgeError::Emission(error.to_string()))?;
    writeln!(source, "// Kernel: {}@{}", kernel.id, kernel.semantic_version)
        .map_err(|error| ForgeError::Emission(error.to_string()))?;
    writeln!(source, "// Semantic hash: {semantic_hash}")
        .map_err(|error| ForgeError::Emission(error.to_string()))?;
    writeln!(
        source,
        "// Schedule: workgroup={}, items={}, vector={}",
        schedule.workgroup_size, schedule.items_per_invocation, schedule.vector_width
    )
    .map_err(|error| ForgeError::Emission(error.to_string()))?;

    emit_kernel_body(&mut source, kernel, schedule)?;

    let source_hash = blake3::hash(source.as_bytes()).to_hex().to_string();
    Ok(GeneratedShader {
        kernel_id: kernel.id.clone(),
        semantic_hash,
        source_hash,
        schedule,
        source,
    })
}

fn emit_kernel_body(
    source: &mut String,
    kernel: &KernelSpec,
    schedule: Schedule,
) -> Result<(), ForgeError> {
    if kernel.id == "topk" {
        return emit_topk_wgsl(source, kernel, schedule);
    }

    if kernel.id == "ray-probe" {
        // The ray-query enable extension must precede any other item.
        writeln!(source, "enable wgpu_ray_query;").map_err(|error| ForgeError::Emission(error.to_string()))?;
    }

    if kernel.id == "affine-f32" {
        writeln!(
            source,
            r#"
struct AffineParams {{
    length: u32,
    scale: f32,
    bias: f32,
    _pad: u32,
}}"#
        ).map_err(|error| ForgeError::Emission(error.to_string()))?;
    }

    if kernel.id == "p64-project" {
        writeln!(
            source,
            r#"
struct P64Words64 {{
    lanes: array<vec4<u32>, 4>,
}}"#
        ).map_err(|error| ForgeError::Emission(error.to_string()))?;
    }

    writeln!(source, "").map_err(|error| ForgeError::Emission(error.to_string()))?;
    for buffer in &kernel.buffers {
        // Acceleration structures bind without an address space.
        if buffer.element == crate::wgsl_forge::ir::BufferElement::AccelerationStructure {
            writeln!(
                source,
                "@group({}) @binding({}) var {}: acceleration_structure;",
                buffer.group, buffer.binding, buffer.name
            ).map_err(|error| ForgeError::Emission(error.to_string()))?;
            continue;
        }
        let access = match buffer.access {
            crate::wgsl_forge::ir::BufferAccess::StorageRead => "storage, read",
            crate::wgsl_forge::ir::BufferAccess::StorageReadWrite => "storage, read_write",
            crate::wgsl_forge::ir::BufferAccess::Uniform => "uniform",
        };
        let type_decl = match buffer.element {
            crate::wgsl_forge::ir::BufferElement::Scalar(crate::wgsl_forge::ir::ScalarType::F32) => "array<f32>",
            crate::wgsl_forge::ir::BufferElement::Scalar(crate::wgsl_forge::ir::ScalarType::U32) => "array<u32>",
            crate::wgsl_forge::ir::BufferElement::Scalar(crate::wgsl_forge::ir::ScalarType::I32) => "array<i32>",
            crate::wgsl_forge::ir::BufferElement::Scalar(crate::wgsl_forge::ir::ScalarType::U64Words) => "array<vec2<u32>>",
            crate::wgsl_forge::ir::BufferElement::AffineParams => "AffineParams",
            crate::wgsl_forge::ir::BufferElement::P64Words64 => "array<P64Words64>",
            crate::wgsl_forge::ir::BufferElement::AccelerationStructure => unreachable!("handled above"),
        };
        writeln!(
            source,
            "@group({}) @binding({}) var<{}> {}: {};",
            buffer.group, buffer.binding, access, buffer.name, type_decl
        ).map_err(|error| ForgeError::Emission(error.to_string()))?;
    }

    writeln!(
        source,
        r#"
const ITEMS_PER_INVOCATION: u32 = {}u;
const VECTOR_WIDTH: u32 = {}u;

@compute @workgroup_size({})
fn {}(@builtin(global_invocation_id) gid: vec3<u32>) {{"#,
        schedule.items_per_invocation,
        schedule.vector_width,
        schedule.workgroup_size,
        kernel.entry_point
    ).map_err(|error| ForgeError::Emission(error.to_string()))?;

    if kernel.id == "ray-probe" {
        // One ray per invocation: load the 8-float ray, intersect, store the hit.
        writeln!(source, "    let i = gid.x;").map_err(|error| ForgeError::Emission(error.to_string()))?;
        writeln!(source, "    if (i >= arrayLength(&hits)) {{ return; }}").map_err(|error| ForgeError::Emission(error.to_string()))?;
        writeln!(source, "    let base = i * 8u;").map_err(|error| ForgeError::Emission(error.to_string()))?;
        writeln!(source, "    let origin = vec3<f32>(rays[base], rays[base + 1u], rays[base + 2u]);").map_err(|error| ForgeError::Emission(error.to_string()))?;
        writeln!(source, "    let direction = vec3<f32>(rays[base + 3u], rays[base + 4u], rays[base + 5u]);").map_err(|error| ForgeError::Emission(error.to_string()))?;
        writeln!(source, "    let t_min = rays[base + 6u];").map_err(|error| ForgeError::Emission(error.to_string()))?;
        writeln!(source, "    let t_max = rays[base + 7u];").map_err(|error| ForgeError::Emission(error.to_string()))?;
        emit_ops(source, &kernel.ops, "    ")?;
        writeln!(source, "    hits[i] = hit_t;").map_err(|error| ForgeError::Emission(error.to_string()))?;
        writeln!(source, "}}").map_err(|error| ForgeError::Emission(error.to_string()))?;
    } else if kernel.id == "affine-f32" {
        // Keeping the optimized vectorized wrapper for affine-f32 specifically
        writeln!(
            source,
            "    for (var item: u32 = 0u; item < ITEMS_PER_INVOCATION; item = item + 1u) {{"
        ).map_err(|error| ForgeError::Emission(error.to_string()))?;
        writeln!(
            source,
            "        let global_id = (gid.x * ITEMS_PER_INVOCATION + item) * VECTOR_WIDTH;"
        ).map_err(|error| ForgeError::Emission(error.to_string()))?;
        
        if schedule.vector_width == 1 {
            writeln!(source, "        if (global_id < params.length) {{").map_err(|error| ForgeError::Emission(error.to_string()))?;
            emit_ops(source, &kernel.ops, "            ")?;
            writeln!(source, "        }}").map_err(|error| ForgeError::Emission(error.to_string()))?;
        } else {
            writeln!(source, "        if (global_id + {}u < params.length) {{", schedule.vector_width - 1).map_err(|error| ForgeError::Emission(error.to_string()))?;
            let constructor = (0..schedule.vector_width)
                .map(|index| format!("input[global_id + {index}u]"))
                .collect::<Vec<_>>()
                .join(", ");
            writeln!(source, "            let value = vec{}<f32>({});", schedule.vector_width, constructor).map_err(|error| ForgeError::Emission(error.to_string()))?;
            writeln!(source, "            let transformed = value * vec{}<f32>(params.scale) + vec{}<f32>(params.bias);", schedule.vector_width, schedule.vector_width).map_err(|error| ForgeError::Emission(error.to_string()))?;
            for index in 0..schedule.vector_width {
                let components = ["x", "y", "z", "w"];
                writeln!(source, "            output[global_id + {index}u] = transformed.{};", components[index as usize]).map_err(|error| ForgeError::Emission(error.to_string()))?;
            }
            writeln!(source, "        }} else {{").map_err(|error| ForgeError::Emission(error.to_string()))?;
            writeln!(source, "            for (var component: u32 = 0u; component < VECTOR_WIDTH; component = component + 1u) {{").map_err(|error| ForgeError::Emission(error.to_string()))?;
            writeln!(source, "                let global_id = global_id + component;").map_err(|error| ForgeError::Emission(error.to_string()))?;
            writeln!(source, "                if (global_id < params.length) {{").map_err(|error| ForgeError::Emission(error.to_string()))?;
            emit_ops(source, &kernel.ops, "                    ")?;
            writeln!(source, "                }}").map_err(|error| ForgeError::Emission(error.to_string()))?;
            writeln!(source, "            }}").map_err(|error| ForgeError::Emission(error.to_string()))?;
            writeln!(source, "        }}").map_err(|error| ForgeError::Emission(error.to_string()))?;
        }
        writeln!(source, "    }}\n}}").map_err(|error| ForgeError::Emission(error.to_string()))?;
    } else {
        // Generic loop for fused-ffn and other kernels
        writeln!(
            source,
            "    for (var item: u32 = 0u; item < ITEMS_PER_INVOCATION; item = item + 1u) {{"
        ).map_err(|error| ForgeError::Emission(error.to_string()))?;
        writeln!(
            source,
            "        let global_id = gid.x * ITEMS_PER_INVOCATION + item;"
        ).map_err(|error| ForgeError::Emission(error.to_string()))?;
        emit_ops(source, &kernel.ops, "        ")?;
        writeln!(source, "    }}\n}}").map_err(|error| ForgeError::Emission(error.to_string()))?;
    }

    Ok(())
}

/// Emits the top-k reduction kernel: one workgroup per block, the `k` largest
/// values of each block written to `output` in descending order.
///
/// This is the first kernel to exercise workgroup-shared memory and barrier
/// synchronisation. The shared arrays come from the IR (`kernel.shared_memory`)
/// and `Op::Barrier` lowers to `workgroupBarrier()`; the reduction control flow
/// is specialised here because it is not expressible in the scalar op set.
fn emit_topk_wgsl(
    source: &mut String,
    kernel: &KernelSpec,
    schedule: Schedule,
) -> Result<(), ForgeError> {
    let wg = schedule.workgroup_size;

    writeln!(
        source,
        r#"
struct TopKParams {{
    length: u32,
    k: u32,
    block_size: u32,
    _pad: u32,
}}
"#
    )
    .map_err(|error| ForgeError::Emission(error.to_string()))?;

    for buffer in &kernel.buffers {
        let access = match buffer.access {
            crate::wgsl_forge::ir::BufferAccess::StorageRead => "storage, read",
            crate::wgsl_forge::ir::BufferAccess::StorageReadWrite => "storage, read_write",
            crate::wgsl_forge::ir::BufferAccess::Uniform => "uniform",
        };
        let type_decl = match buffer.access {
            crate::wgsl_forge::ir::BufferAccess::Uniform => "TopKParams",
            _ => "array<f32>",
        };
        writeln!(
            source,
            "@group({}) @binding({}) var<{}> {}: {};",
            buffer.group, buffer.binding, access, buffer.name, type_decl
        )
        .map_err(|error| ForgeError::Emission(error.to_string()))?;
    }

    writeln!(source, "").map_err(|error| ForgeError::Emission(error.to_string()))?;
    for shared in &kernel.shared_memory {
        writeln!(
            source,
            "var<workgroup> {}: array<{}, {}>;",
            shared.name,
            shared.element.wgsl_name(),
            shared.length.resolve(wg)
        )
        .map_err(|error| ForgeError::Emission(error.to_string()))?;
    }

    writeln!(
        source,
        r#"
@compute @workgroup_size({wg})
fn {entry}(
    @builtin(local_invocation_id) lid: vec3<u32>,
    @builtin(workgroup_id) wid: vec3<u32>,
) {{
    let tid = lid.x;
    let block = wid.x;
    let base = block * {wg}u;
    let gidx = base + tid;
    // Sentinel = f32::MIN (0xff7fffff); threads past the input load it so they
    // never win, and selected slots are reset to it between extractions.
    let sentinel = bitcast<f32>(0xff7fffffu);
    var v = sentinel;
    if (gidx < params.length) {{
        v = input[gidx];
    }}
    s_val[tid] = v;
    s_idx[tid] = tid;
    workgroupBarrier();

    for (var i: u32 = 0u; i < params.k; i = i + 1u) {{
        r_val[tid] = s_val[tid];
        r_idx[tid] = s_idx[tid];
        workgroupBarrier();
        // Tree arg-max reduction over the working copy.
        for (var stride: u32 = {wg}u / 2u; stride > 0u; stride = stride / 2u) {{
            if (tid < stride) {{
                if (r_val[tid + stride] > r_val[tid]) {{
                    r_val[tid] = r_val[tid + stride];
                    r_idx[tid] = r_idx[tid + stride];
                }}
            }}
            workgroupBarrier();
        }}
        if (tid == 0u) {{
            output[block * params.k + i] = r_val[0];
            s_val[r_idx[0]] = sentinel;
        }}
        workgroupBarrier();
    }}
}}"#,
        wg = wg,
        entry = kernel.entry_point
    )
    .map_err(|error| ForgeError::Emission(error.to_string()))?;

    Ok(())
}

fn emit_ops(source: &mut String, ops: &[Op], indent: &str) -> Result<(), ForgeError> {
    for op in ops {
        match op {
            Op::StructLoad { buffer, field, destination } => {
                writeln!(source, "{indent}let {destination} = {buffer}.{field};").map_err(|error| ForgeError::Emission(error.to_string()))?;
            }
            Op::Load { buffer, index, destination } => {
                writeln!(source, "{indent}let {destination} = {buffer}[{index}];").map_err(|error| ForgeError::Emission(error.to_string()))?;
            }
            Op::Store { buffer, index, value } => {
                writeln!(source, "{indent}{buffer}[{index}] = {value};").map_err(|error| ForgeError::Emission(error.to_string()))?;
            }
            Op::Fma { a, b, c, destination } => {
                writeln!(source, "{indent}let {destination} = {a} * {b} + {c};").map_err(|error| ForgeError::Emission(error.to_string()))?;
            }
            Op::Mul { left, right, destination } => {
                writeln!(source, "{indent}let {destination} = {left} * {right};").map_err(|error| ForgeError::Emission(error.to_string()))?;
            }
            Op::Add { left, right, destination } => {
                writeln!(source, "{indent}let {destination} = {left} + {right};").map_err(|error| ForgeError::Emission(error.to_string()))?;
            }
            Op::DotProduct { left_buffer, left_base, right_buffer, right_base, len, destination } => {
                writeln!(source, "{indent}var {destination} = 0.0;").map_err(|error| ForgeError::Emission(error.to_string()))?;
                writeln!(source, "{indent}for (var i: u32 = 0u; i < {len}; i = i + 1u) {{").map_err(|error| ForgeError::Emission(error.to_string()))?;
                writeln!(source, "{indent}    {destination} = {destination} + {left_buffer}[{left_base} + i] * {right_buffer}[{right_base} + i];").map_err(|error| ForgeError::Emission(error.to_string()))?;
                writeln!(source, "{indent}}}").map_err(|error| ForgeError::Emission(error.to_string()))?;
            }
            Op::Loop { induction_var, start, end, step, body } => {
                writeln!(source, "{indent}for (var {induction_var}: u32 = {start}; {induction_var} < {end}; {induction_var} = {induction_var} + {step}) {{").map_err(|error| ForgeError::Emission(error.to_string()))?;
                emit_ops(source, body, &format!("{indent}    "))?;
                writeln!(source, "{indent}}}").map_err(|error| ForgeError::Emission(error.to_string()))?;
            }
            Op::Relu { operand, destination } => {
                writeln!(source, "{indent}let {destination} = max(0.0, {operand});").map_err(|error| ForgeError::Emission(error.to_string()))?;
            }
            Op::Gelu { operand, destination } => {
                // GELU approximation: 0.5 * x * (1.0 + tanh(sqrt(2/pi) * (x + 0.044715 * x^3)))
                writeln!(source, "{indent}let {destination} = 0.5 * {operand} * (1.0 + tanh(0.7978845608 * ({operand} + 0.044715 * {operand} * {operand} * {operand})));").map_err(|error| ForgeError::Emission(error.to_string()))?;
            }
            Op::MatrixMultiply { left_buffer, right_buffer, destination, m, n, k } => {
                writeln!(source, "{indent}// MatrixMultiply intrinsic placeholder").map_err(|error| ForgeError::Emission(error.to_string()))?;
            }
            Op::Barrier => {
                writeln!(source, "{indent}workgroupBarrier();").map_err(|error| ForgeError::Emission(error.to_string()))?;
            }
            Op::Intrinsic(crate::wgsl_forge::ir::Intrinsic::RayQuery {
                acceleration_structure,
                origin,
                direction,
                t_min,
                t_max,
                destination,
            }) => {
                // Hardware ray-query: initialise, proceed, read the committed hit.
                writeln!(source, "{indent}var rq: ray_query;").map_err(|error| ForgeError::Emission(error.to_string()))?;
                writeln!(source, "{indent}rayQueryInitialize(&rq, {acceleration_structure}, RayDesc(0u, 0xFFu, {t_min}, {t_max}, {origin}, {direction}));").map_err(|error| ForgeError::Emission(error.to_string()))?;
                writeln!(source, "{indent}rayQueryProceed(&rq);").map_err(|error| ForgeError::Emission(error.to_string()))?;
                writeln!(source, "{indent}let committed = rayQueryGetCommittedIntersection(&rq);").map_err(|error| ForgeError::Emission(error.to_string()))?;
                writeln!(source, "{indent}var {destination} = -1.0;").map_err(|error| ForgeError::Emission(error.to_string()))?;
                writeln!(source, "{indent}if (committed.kind != RAY_QUERY_INTERSECTION_NONE) {{ {destination} = committed.t; }}").map_err(|error| ForgeError::Emission(error.to_string()))?;
            }
            Op::Intrinsic(_) => {
                return Err(ForgeError::Emission("Intrinsics not implemented for WGSL yet".to_string()));
            }
        }
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::wgsl_forge::{BuiltinKernel, Schedule};

    #[test]
    fn emission_is_byte_deterministic() {
        let kernel = BuiltinKernel::AffineF32.spec();
        let first = emit_wgsl(&kernel, Schedule::default()).unwrap();
        let second = emit_wgsl(&kernel, Schedule::default()).unwrap();
        assert_eq!(first.source, second.source);
    }
}
