use super::super::row::{Contract, SpecTool};
use crate::browser::tool_proficiency::Proficiency;
use crate::tool_chest::core::intent_bus::ActionType;
use crate::tool_chest::core::tool::ToolKind;

pub(super) static ROWS: &[SpecTool] = &[
    SpecTool::new(
        "image",
        "Pictures",
        "layers",
        "Layers",
        "image:add-layer",
        "Add a layer",
        "Put a new layer on this picture.",
        "image",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Novice,
        Contract::Local,
    ),
    SpecTool::new(
        "image",
        "Pictures",
        "layers",
        "Layers",
        "image:delete-layer",
        "Remove a layer",
        "Take this layer off the picture.",
        "image",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Novice,
        Contract::Local,
    ),
    SpecTool::new(
        "image",
        "Pictures",
        "layers",
        "Layers",
        "image:reorder-layer",
        "Move a layer",
        "Change which layer sits in front.",
        "image",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Intermediate,
        Contract::Local,
    ),
    SpecTool::new(
        "image",
        "Pictures",
        "layers",
        "Layers",
        "image:merge-layers",
        "Merge layers",
        "Combine selected layers into one.",
        "image",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Intermediate,
        Contract::Local,
    ),
    SpecTool::new(
        "image",
        "Pictures",
        "layers",
        "Layers",
        "image:duplicate-layer",
        "Copy a layer",
        "Make a second copy of this layer.",
        "image",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Novice,
        Contract::Local,
    ),
    SpecTool::new(
        "image",
        "Pictures",
        "layers",
        "Layers",
        "image:group-layers",
        "Group layers",
        "Bundle selected layers together.",
        "image",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Intermediate,
        Contract::Local,
    ),
    SpecTool::new(
        "image",
        "Pictures",
        "layers",
        "Layers",
        "image:layer-opacity",
        "Layer fade",
        "Set how see-through this layer is.",
        "image",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Intermediate,
        Contract::Local,
    ),
    SpecTool::new(
        "image",
        "Pictures",
        "layers",
        "Layers",
        "image:layer-blend-mode",
        "Blend layers",
        "Choose how this layer mixes with the ones below.",
        "image",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Intermediate,
        Contract::Local,
    ),
    SpecTool::new(
        "image",
        "Pictures",
        "brushes",
        "Brushes",
        "image:brush-select",
        "Choose a brush",
        "Pick the brush shape for painting.",
        "image",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Novice,
        Contract::Local,
    ),
    SpecTool::new(
        "image",
        "Pictures",
        "brushes",
        "Brushes",
        "image:brush-size",
        "Brush size",
        "Set how wide the brush is.",
        "image",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Novice,
        Contract::Local,
    ),
    SpecTool::new(
        "image",
        "Pictures",
        "brushes",
        "Brushes",
        "image:brush-opacity",
        "Brush fade",
        "Set how strong each brush stroke is.",
        "image",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Intermediate,
        Contract::Local,
    ),
    SpecTool::new(
        "image",
        "Pictures",
        "brushes",
        "Brushes",
        "image:brush-hardness",
        "Brush edge",
        "Soften or harden the brush edge.",
        "image",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Intermediate,
        Contract::Local,
    ),
    SpecTool::new(
        "image",
        "Pictures",
        "brushes",
        "Brushes",
        "image:brush-flow",
        "Brush flow",
        "Set how quickly colour builds as you paint.",
        "image",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Intermediate,
        Contract::Local,
    ),
    SpecTool::new(
        "image",
        "Pictures",
        "brushes",
        "Brushes",
        "image:brush-colour",
        "Brush colour",
        "Set the colour this brush paints with.",
        "image",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Novice,
        Contract::Local,
    ),
    SpecTool::new(
        "image",
        "Pictures",
        "brushes",
        "Brushes",
        "image:eraser",
        "Eraser",
        "Rub pixels off the active layer.",
        "image",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Novice,
        Contract::Local,
    ),
    SpecTool::new(
        "image",
        "Pictures",
        "brushes",
        "Brushes",
        "image:clone-stamp",
        "Clone stamp",
        "Copy pixels from one spot to another.",
        "image",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Intermediate,
        Contract::Local,
    ),
    SpecTool::new(
        "image",
        "Pictures",
        "brushes",
        "Brushes",
        "image:heal-brush",
        "Heal brush",
        "Blend nearby texture over a blemish.",
        "image",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Expert,
        Contract::Local,
    ),
    SpecTool::new(
        "image",
        "Pictures",
        "brushes",
        "Brushes",
        "image:gradient-fill",
        "Gradient fill",
        "Fill an area with a colour fade.",
        "image",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Intermediate,
        Contract::Local,
    ),
];
