use super::super::row::{Contract, SpecTool};
use crate::browser::tool_proficiency::Proficiency;
use crate::tool_chest::core::intent_bus::ActionType;
use crate::tool_chest::core::tool::ToolKind;

pub(super) static ROWS: &[SpecTool] = &[
    SpecTool::new(
        "image",
        "Pictures",
        "masks",
        "Masks",
        "image:invert-mask",
        "Invert mask",
        "Swap what the mask shows and hides.",
        "image",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Intermediate,
        Contract::Local,
    ),
    SpecTool::new(
        "image",
        "Pictures",
        "masks",
        "Masks",
        "image:vector-mask",
        "Path mask",
        "Hide parts of this layer using a drawn path.",
        "image",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Expert,
        Contract::Local,
    ),
    SpecTool::new(
        "image",
        "Pictures",
        "masks",
        "Masks",
        "image:clipping-mask",
        "Clip to layer",
        "Show this layer only where the layer below has shape.",
        "image",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Expert,
        Contract::Local,
    ),
    SpecTool::new(
        "image",
        "Pictures",
        "colour",
        "Colour",
        "image:colour-picker",
        "Pick colour",
        "Sample a colour from the picture and make it active.",
        "image",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Novice,
        Contract::Local,
    ),
    SpecTool::new(
        "image",
        "Pictures",
        "colour",
        "Colour",
        "image:sample-colour",
        "Sample colour",
        "Read the colour at a point without changing the brush.",
        "image",
        ToolKind::Query,
        ActionType::Query,
        Proficiency::Intermediate,
        Contract::Local,
    ),
    SpecTool::new(
        "image",
        "Pictures",
        "colour",
        "Colour",
        "image:colour-profile",
        "Colour profile",
        "Assign a colour space to this picture.",
        "image",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Intermediate,
        Contract::Local,
    ),
    SpecTool::new(
        "image",
        "Pictures",
        "colour",
        "Colour",
        "image:convert-profile",
        "Convert colour space",
        "Convert this picture to another colour space.",
        "image",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Expert,
        Contract::Local,
    ),
    SpecTool::new(
        "image",
        "Pictures",
        "colour",
        "Colour",
        "image:gradient-map",
        "Gradient map",
        "Recolour the picture from dark to light along a gradient.",
        "image",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Expert,
        Contract::Local,
    ),
    SpecTool::new(
        "image",
        "Pictures",
        "colour",
        "Colour",
        "image:posterise",
        "Posterise",
        "Flatten the picture into fewer colour steps.",
        "image",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Intermediate,
        Contract::Local,
    ),
];
