use super::super::row::{Contract, SpecTool};
use crate::browser::tool_proficiency::Proficiency;
use crate::tool_chest::core::intent_bus::ActionType;
use crate::tool_chest::core::tool::ToolKind;

pub(super) static ROWS: &[SpecTool] = &[
    SpecTool::new(
        "image",
        "Pictures",
        "selection",
        "Selection",
        "image:rect-select",
        "Box select",
        "Draw a rectangle to select part of the picture.",
        "image",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Novice,
        Contract::Local,
    ),
    SpecTool::new(
        "image",
        "Pictures",
        "selection",
        "Selection",
        "image:lasso-select",
        "Lasso",
        "Draw a freehand outline to select.",
        "image",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Intermediate,
        Contract::Local,
    ),
    SpecTool::new(
        "image",
        "Pictures",
        "selection",
        "Selection",
        "image:magic-wand",
        "Magic wand",
        "Select nearby pixels of a similar colour.",
        "image",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Intermediate,
        Contract::Local,
    ),
    SpecTool::new(
        "image",
        "Pictures",
        "selection",
        "Selection",
        "image:vector-path-select",
        "Select along a path",
        "Select along a drawn path.",
        "image",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Expert,
        Contract::Local,
    ),
    SpecTool::new(
        "image",
        "Pictures",
        "selection",
        "Selection",
        "image:invert-selection",
        "Invert selection",
        "Select everything that is not selected.",
        "image",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Novice,
        Contract::Local,
    ),
    SpecTool::new(
        "image",
        "Pictures",
        "selection",
        "Selection",
        "image:feather-selection",
        "Soften selection",
        "Soften the edge of the selection.",
        "image",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Intermediate,
        Contract::Local,
    ),
    SpecTool::new(
        "image",
        "Pictures",
        "selection",
        "Selection",
        "image:refine-edge",
        "Refine edge",
        "Tighten the selection around hair or fine edges.",
        "image",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Expert,
        Contract::Local,
    ),
    SpecTool::new(
        "image",
        "Pictures",
        "filters",
        "Filters",
        "image:gaussian-blur",
        "Soften",
        "Soften this picture with a gentle blur.",
        "image",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Novice,
        Contract::Live("ComputerVision.gaussian_blur"),
    ),
    SpecTool::new(
        "image",
        "Pictures",
        "filters",
        "Filters",
        "image:sharpen",
        "Sharpen",
        "Make edges in this picture crisper.",
        "image",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Intermediate,
        Contract::Local,
    ),
    SpecTool::new(
        "image",
        "Pictures",
        "filters",
        "Filters",
        "image:colour-balance",
        "Colour balance",
        "Shift shadows, midtones, and highlights.",
        "image",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Intermediate,
        Contract::Local,
    ),
    SpecTool::new(
        "image",
        "Pictures",
        "filters",
        "Filters",
        "image:hue-saturation",
        "Hue and saturation",
        "Shift colour, richness, and lightness.",
        "image",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Intermediate,
        Contract::Local,
    ),
    SpecTool::new(
        "image",
        "Pictures",
        "filters",
        "Filters",
        "image:curves",
        "Tone curve",
        "Bend the light and dark of this picture.",
        "image",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Expert,
        Contract::Local,
    ),
    SpecTool::new(
        "image",
        "Pictures",
        "filters",
        "Filters",
        "image:levels",
        "Levels",
        "Set black, white, and mid-grey points.",
        "image",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Expert,
        Contract::Local,
    ),
    SpecTool::new(
        "image",
        "Pictures",
        "filters",
        "Filters",
        "image:distort",
        "Distort",
        "Warp this picture with a lens, ripple, wave, or twirl.",
        "image",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Expert,
        Contract::Local,
    ),
    SpecTool::new(
        "image",
        "Pictures",
        "filters",
        "Filters",
        "image:noise-reduction",
        "Reduce noise",
        "Smooth grain while keeping detail.",
        "image",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Expert,
        Contract::Local,
    ),
    SpecTool::new(
        "image",
        "Pictures",
        "masks",
        "Masks",
        "image:add-layer-mask",
        "Add a mask",
        "Hide parts of this layer without deleting them.",
        "image",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Novice,
        Contract::Local,
    ),
    SpecTool::new(
        "image",
        "Pictures",
        "masks",
        "Masks",
        "image:apply-mask",
        "Apply mask",
        "Bake the mask into the layer for good.",
        "image",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Intermediate,
        Contract::Local,
    ),
];
