use super::super::row::{Contract, SpecTool};
use crate::browser::tool_proficiency::Proficiency;
use crate::tool_chest::core::intent_bus::ActionType;
use crate::tool_chest::core::tool::ToolKind;

pub(super) static ROWS: &[SpecTool] = &[
    SpecTool::new(
        "image",
        "Pictures",
        "vector",
        "Vector",
        "image:pen-tool",
        "Pen",
        "Draw a path with points and curves.",
        "image",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Intermediate,
        Contract::Local,
    ),
    SpecTool::new(
        "image",
        "Pictures",
        "vector",
        "Vector",
        "image:shape-tool",
        "Shape",
        "Draw a rectangle, ellipse, polygon, or star.",
        "image",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Novice,
        Contract::Local,
    ),
    SpecTool::new(
        "image",
        "Pictures",
        "vector",
        "Vector",
        "image:path-edit",
        "Edit path",
        "Move a point on a drawn path.",
        "image",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Intermediate,
        Contract::Local,
    ),
    SpecTool::new(
        "image",
        "Pictures",
        "vector",
        "Vector",
        "image:text-on-path",
        "Text on a path",
        "Place writing along a drawn path.",
        "image",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Expert,
        Contract::Local,
    ),
    SpecTool::new(
        "image",
        "Pictures",
        "vector",
        "Vector",
        "image:vector-export",
        "Export paths",
        "Save the drawn paths as a drawing file.",
        "image",
        ToolKind::Query,
        ActionType::Query,
        Proficiency::Expert,
        Contract::Local,
    ),
    SpecTool::new(
        "image",
        "Pictures",
        "vector",
        "Vector",
        "image:svg-import",
        "Import drawing",
        "Bring a drawing into a vector layer.",
        "image",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Expert,
        Contract::Local,
    ),
    SpecTool::new(
        "image",
        "Pictures",
        "inspect",
        "Inspect",
        "image:histogram",
        "Tones",
        "Show how light and dark this picture is.",
        "image",
        ToolKind::Query,
        ActionType::Query,
        Proficiency::Novice,
        Contract::Live("ComputerVision.histogram"),
    ),
    SpecTool::new(
        "image",
        "Pictures",
        "inspect",
        "Inspect",
        "image:colour-sampler",
        "Colour samples",
        "Read colour at several points on the picture.",
        "image",
        ToolKind::Query,
        ActionType::Query,
        Proficiency::Intermediate,
        Contract::Local,
    ),
    SpecTool::new(
        "image",
        "Pictures",
        "inspect",
        "Inspect",
        "image:info-probe",
        "Pixel info",
        "Show position, colour, and layer at this point.",
        "image",
        ToolKind::Query,
        ActionType::Query,
        Proficiency::Novice,
        Contract::Local,
    ),
    SpecTool::new(
        "image",
        "Pictures",
        "inspect",
        "Inspect",
        "image:metadata-view",
        "Picture facts",
        "Show size, colour space, bit depth, and print resolution.",
        "image",
        ToolKind::Query,
        ActionType::Query,
        Proficiency::Intermediate,
        Contract::Local,
    ),
    SpecTool::new(
        "image",
        "Pictures",
        "inspect",
        "Inspect",
        "image:profile-inspector",
        "Colour profile details",
        "Show the colour profile attached to this picture.",
        "image",
        ToolKind::Query,
        ActionType::Query,
        Proficiency::Expert,
        Contract::Local,
    ),
];
