//! Part of poet browser toolbox registration.

use super::*;

pub(super) fn register_sheet_toolbox(reg: &mut Registry) {
    let tools: Vec<Box<dyn crate::tool_chest::core::tool::Tool>> = vec![
        Box::new(SimpleTool::new(
            ToolMetadata {
                id: "sheet:place_sheet".into(),
                label: "+ Spreadsheet".into(),
                icon: "sheet".into(),
                kind: ToolKind::PlaceContainer,
                capability_scope: Some(SCOPE_PLACE.into()),
                ontology_prefix: "hm".into(),
                description: "Place a spreadsheet container.".into(),
            },
            ActionType::Query,
        )),
        Box::new(SimpleTool::new(
            ToolMetadata {
                id: "sheet:import".into(),
                label: "Import Data".into(),
                icon: "import".into(),
                kind: ToolKind::RunAction,
                capability_scope: None,
                ontology_prefix: "hm".into(),
                description: "Import CSV/HCF data into active sheet.".into(),
            },
            ActionType::Mutate,
        )),
    ];

    reg.register_toolbox(Toolbox::new(
        ToolboxMetadata {
            id: "sheet".into(),
            label: "Spreadsheet & Tensors".into(),
            icon: "sheet".into(),
            ontology_prefix: "hm".into(),
            description: "Spreadsheets, tensor arrays, formulas, and data import.".into(),
            enabled_by_default: true,
            family: "sheet".into(),
        },
        vec![
            ToolChain::new(
                ToolChainMetadata {
                    id: "sheet:grid".into(),
                    label: "Tensor Dimensions & Formats".into(),
                    icon: "sheet".into(),
                    description: "Configure 1D/2D/3D/10D tensor dimensions and cell formatting."
                        .into(),
                },
                vec![Box::new(SimpleTool::new(
                    ToolMetadata {
                        id: "sheet:stats_mean".into(),
                        label: "Mean".into(),
                        icon: "sheet".into(),
                        kind: ToolKind::Query,
                        capability_scope: Some("Statistics.mean".into()),
                        ontology_prefix: "hm".into(),
                        description: "Mean of numbers on the selected sheet. Local compute; daemon upgrades to Statistics.mean.".into(),
                    },
                    ActionType::Query,
                )),
                Box::new(SimpleTool::new(
                    ToolMetadata {
                        id: "sheet:stats_median".into(),
                        label: "Median".into(),
                        icon: "sheet".into(),
                        kind: ToolKind::Query,
                        capability_scope: Some("Statistics.median".into()),
                        ontology_prefix: "hm".into(),
                        description: "Median of numbers on the selected sheet. Local compute; daemon upgrades to Statistics.median.".into(),
                    },
                    ActionType::Query,
                )),
                Box::new(SimpleTool::new(
                    ToolMetadata {
                        id: "sheet:stats_variance".into(),
                        label: "Variance".into(),
                        icon: "sheet".into(),
                        kind: ToolKind::Query,
                        capability_scope: Some("Statistics.variance".into()),
                        ontology_prefix: "hm".into(),
                        description: "Sample variance of numbers on the selected sheet. Local compute; daemon upgrades to Statistics.variance.".into(),
                    },
                    ActionType::Query,
                )),
                Box::new(SimpleTool::new(
                    ToolMetadata {
                        id: "sheet:stats_std_dev".into(),
                        label: "Std Dev".into(),
                        icon: "sheet".into(),
                        kind: ToolKind::Query,
                        capability_scope: Some("Statistics.std_dev".into()),
                        ontology_prefix: "hm".into(),
                        description: "Sample standard deviation on the selected sheet. Local compute; daemon upgrades to Statistics.std_dev.".into(),
                    },
                    ActionType::Query,
                )),
                Box::new(SimpleTool::new(
                    ToolMetadata {
                        id: "sheet:stats_min".into(),
                        label: "Min".into(),
                        icon: "sheet".into(),
                        kind: ToolKind::Query,
                        capability_scope: Some("Statistics.min".into()),
                        ontology_prefix: "hm".into(),
                        description: "Minimum of numbers on the selected sheet. Local compute; daemon upgrades to Statistics.min.".into(),
                    },
                    ActionType::Query,
                )),
                Box::new(SimpleTool::new(
                    ToolMetadata {
                        id: "sheet:stats_max".into(),
                        label: "Max".into(),
                        icon: "sheet".into(),
                        kind: ToolKind::Query,
                        capability_scope: Some("Statistics.max".into()),
                        ontology_prefix: "hm".into(),
                        description: "Maximum of numbers on the selected sheet. Local compute; daemon upgrades to Statistics.max.".into(),
                    },
                    ActionType::Query,
                )),
                Box::new(SimpleTool::new(
                    ToolMetadata {
                        id: "sheet:stats_sum".into(),
                        label: "Sum".into(),
                        icon: "sheet".into(),
                        kind: ToolKind::Query,
                        capability_scope: Some("Statistics.sum".into()),
                        ontology_prefix: "hm".into(),
                        description: "Sum of numbers on the selected sheet. Local compute; daemon upgrades to Statistics.sum.".into(),
                    },
                    ActionType::Query,
                )),
                Box::new(SimpleTool::new(
                    ToolMetadata {
                        id: "sheet:stats_skewness".into(),
                        label: "Skewness".into(),
                        icon: "sheet".into(),
                        kind: ToolKind::Query,
                        capability_scope: Some("Statistics.skewness".into()),
                        ontology_prefix: "hm".into(),
                        description: "Sample skewness on the selected sheet. Local compute; daemon upgrades to Statistics.skewness.".into(),
                    },
                    ActionType::Query,
                )),
                Box::new(SimpleTool::new(
                    ToolMetadata {
                        id: "sheet:stats_kurtosis".into(),
                        label: "Kurtosis".into(),
                        icon: "sheet".into(),
                        kind: ToolKind::Query,
                        capability_scope: Some("Statistics.kurtosis".into()),
                        ontology_prefix: "hm".into(),
                        description: "Excess kurtosis on the selected sheet. Local compute; daemon upgrades to Statistics.kurtosis.".into(),
                    },
                    ActionType::Query,
                )),
                Box::new(SimpleTool::new(
                    ToolMetadata {
                        id: "sheet:stats_quantile".into(),
                        label: "Quantile".into(),
                        icon: "sheet".into(),
                        kind: ToolKind::Query,
                        capability_scope: Some("Statistics.quantile".into()),
                        ontology_prefix: "hm".into(),
                        description: "Quantile (default q=0.95, or data-q) on the selected sheet. Local compute; daemon upgrades to Statistics.quantile.".into(),
                    },
                    ActionType::Query,
                )),
                Box::new(SimpleTool::new(
                    ToolMetadata {
                        id: "sheet:stats_iqr".into(),
                        label: "IQR".into(),
                        icon: "sheet".into(),
                        kind: ToolKind::Query,
                        capability_scope: Some("Statistics.iqr".into()),
                        ontology_prefix: "hm".into(),
                        description: "Interquartile range on the selected sheet. Local compute; daemon upgrades to Statistics.iqr.".into(),
                    },
                    ActionType::Query,
                )),
                Box::new(SimpleTool::new(
                    ToolMetadata {
                        id: "sheet:stats_mode".into(),
                        label: "Mode".into(),
                        icon: "sheet".into(),
                        kind: ToolKind::Query,
                        capability_scope: Some("Statistics.mode".into()),
                        ontology_prefix: "hm".into(),
                        description: "Modal value on the selected sheet. Local compute; daemon upgrades to Statistics.mode.".into(),
                    },
                    ActionType::Query,
                )),
                Box::new(SimpleTool::new(
                    ToolMetadata {
                        id: "sheet:stats_trimmed_mean".into(),
                        label: "Trimmed Mean".into(),
                        icon: "sheet".into(),
                        kind: ToolKind::Query,
                        capability_scope: Some("Statistics.trimmed_mean".into()),
                        ontology_prefix: "hm".into(),
                        description: "Trimmed mean (default proportion 0.1, or data-proportion). Local compute; daemon upgrades to Statistics.trimmed_mean.".into(),
                    },
                    ActionType::Query,
                )),
                Box::new(SimpleTool::new(
                    ToolMetadata {
                        id: "sheet:stats_mad".into(),
                        label: "MAD".into(),
                        icon: "sheet".into(),
                        kind: ToolKind::Query,
                        capability_scope: Some("Statistics.median_abs_deviation".into()),
                        ontology_prefix: "hm".into(),
                        description: "Median absolute deviation (scaled by default). Local compute; daemon upgrades to Statistics.median_abs_deviation.".into(),
                    },
                    ActionType::Query,
                )),
                Box::new(SimpleTool::new(
                    ToolMetadata {
                        id: "sheet:stats_pearson".into(),
                        label: "Pearson".into(),
                        icon: "sheet".into(),
                        kind: ToolKind::Query,
                        capability_scope: Some("Statistics.pearson".into()),
                        ontology_prefix: "hm".into(),
                        description: "Pearson r between the first and second halves of sheet numbers. Local compute; daemon upgrades to Statistics.pearson.".into(),
                    },
                    ActionType::Query,
                )),
                Box::new(SimpleTool::new(
                    ToolMetadata {
                        id: "sheet:stats_covariance".into(),
                        label: "Covariance".into(),
                        icon: "sheet".into(),
                        kind: ToolKind::Query,
                        capability_scope: Some("Statistics.covariance".into()),
                        ontology_prefix: "hm".into(),
                        description: "Sample covariance between series halves on the selected sheet. Local compute; daemon upgrades to Statistics.covariance.".into(),
                    },
                    ActionType::Query,
                )),
                Box::new(SimpleTool::new(
                    ToolMetadata {
                        id: "sheet:stats_z_score_outliers".into(),
                        label: "Z-Score Outliers".into(),
                        icon: "sheet".into(),
                        kind: ToolKind::Query,
                        capability_scope: Some("Statistics.z_score_outliers".into()),
                        ontology_prefix: "hm".into(),
                        description: "Z-score outlier indices (default threshold 3.0, or data-threshold). Local compute; daemon upgrades to Statistics.z_score_outliers.".into(),
                    },
                    ActionType::Query,
                )),
                Box::new(SimpleTool::new(
                    ToolMetadata {
                        id: "sheet:stats_argmax".into(),
                        label: "Argmax".into(),
                        icon: "sheet".into(),
                        kind: ToolKind::Query,
                        capability_scope: Some("Statistics.argmax".into()),
                        ontology_prefix: "hm".into(),
                        description: "Index of the maximum value on the selected sheet. Local compute; daemon upgrades to Statistics.argmax.".into(),
                    },
                    ActionType::Query,
                )),
                Box::new(SimpleTool::new(
                    ToolMetadata {
                        id: "sheet:stats_binomial_pmf".into(),
                        label: "Binomial PMF".into(),
                        icon: "sheet".into(),
                        kind: ToolKind::Query,
                        capability_scope: Some("Statistics.binomial_pmf".into()),
                        ontology_prefix: "hm".into(),
                        description: "Binomial PMF from sheet numbers or data-k/data-n/data-p. Local compute; daemon upgrades to Statistics.binomial_pmf.".into(),
                    },
                    ActionType::Query,
                )),
                Box::new(SimpleTool::new(
                    ToolMetadata {
                        id: "sheet:stats_binomial_cdf".into(),
                        label: "Binomial CDF".into(),
                        icon: "sheet".into(),
                        kind: ToolKind::Query,
                        capability_scope: Some("Statistics.binomial_cdf".into()),
                        ontology_prefix: "hm".into(),
                        description: "Binomial CDF from sheet numbers or data-k/data-n/data-p. Local compute; daemon upgrades to Statistics.binomial_cdf.".into(),
                    },
                    ActionType::Query,
                )),
                Box::new(SimpleTool::new(
                    ToolMetadata {
                        id: "sheet:stats_beta_pdf".into(),
                        label: "Beta PDF".into(),
                        icon: "sheet".into(),
                        kind: ToolKind::Query,
                        capability_scope: Some("Statistics.beta_pdf".into()),
                        ontology_prefix: "hm".into(),
                        description: "Beta PDF at the first sheet number (data-alpha/data-beta, default 2). Local compute; daemon upgrades to Statistics.beta_pdf.".into(),
                    },
                    ActionType::Query,
                )),
                Box::new(SimpleTool::new(
                    ToolMetadata {
                        id: "sheet:stats_chi_squared_pdf".into(),
                        label: "Chi-Squared PDF".into(),
                        icon: "sheet".into(),
                        kind: ToolKind::Query,
                        capability_scope: Some("Statistics.chi_squared_pdf".into()),
                        ontology_prefix: "hm".into(),
                        description: "Chi-squared PDF at the first sheet number (data-k, default 2). Local compute; daemon upgrades to Statistics.chi_squared_pdf.".into(),
                    },
                    ActionType::Query,
                )),
                Box::new(SimpleTool::new(
                    ToolMetadata {
                        id: "sheet:stats_chi_squared_cdf".into(),
                        label: "Chi-Squared CDF".into(),
                        icon: "sheet".into(),
                        kind: ToolKind::Query,
                        capability_scope: Some("Statistics.chi_squared_cdf".into()),
                        ontology_prefix: "hm".into(),
                        description: "Chi-squared CDF at the first sheet number (data-k, default 2). Local compute; daemon upgrades to Statistics.chi_squared_cdf.".into(),
                    },
                    ActionType::Query,
                )),
                Box::new(SimpleTool::new(
                    ToolMetadata {
                        id: "sheet:stats_chi_squared_quantile".into(),
                        label: "Chi-Squared Quantile".into(),
                        icon: "sheet".into(),
                        kind: ToolKind::Query,
                        capability_scope: Some("Statistics.chi_squared_quantile".into()),
                        ontology_prefix: "hm".into(),
                        description: "Chi-squared quantile (data-p default 0.95, data-k default 2). Local compute; daemon upgrades to Statistics.chi_squared_quantile.".into(),
                    },
                    ActionType::Query,
                )),
                Box::new(SimpleTool::new(
                    ToolMetadata {
                        id: "sheet:stats_autocorrelation".into(),
                        label: "Autocorrelation".into(),
                        icon: "sheet".into(),
                        kind: ToolKind::Query,
                        capability_scope: Some("Statistics.autocorrelation".into()),
                        ontology_prefix: "hm".into(),
                        description: "Sample autocorrelation at lag (data-lag, default 1). Local compute; daemon upgrades to Statistics.autocorrelation.".into(),
                    },
                    ActionType::Query,
                )),
                Box::new(SimpleTool::new(
                    ToolMetadata {
                        id: "sheet:stats_bootstrap_means".into(),
                        label: "Bootstrap Means".into(),
                        icon: "sheet".into(),
                        kind: ToolKind::Query,
                        capability_scope: Some("Statistics.bootstrap_means".into()),
                        ontology_prefix: "hm".into(),
                        description: "Bootstrap distribution of the mean (data-iterations/data-seed). Local compute; daemon upgrades to Statistics.bootstrap_means.".into(),
                    },
                    ActionType::Query,
                )),
                Box::new(SimpleTool::new(
                    ToolMetadata {
                        id: "sheet:stats_normal_pdf".into(),
                        label: "Normal PDF".into(),
                        icon: "sheet".into(),
                        kind: ToolKind::Query,
                        capability_scope: Some("Statistics.normal_pdf".into()),
                        ontology_prefix: "hm".into(),
                        description: "Normal PDF at the first sheet number (data-mu/data-sigma, default 0/1). Local compute; daemon upgrades to Statistics.normal_pdf.".into(),
                    },
                    ActionType::Query,
                )),
                Box::new(SimpleTool::new(
                    ToolMetadata {
                        id: "sheet:stats_normal_cdf".into(),
                        label: "Normal CDF".into(),
                        icon: "sheet".into(),
                        kind: ToolKind::Query,
                        capability_scope: Some("Statistics.normal_cdf".into()),
                        ontology_prefix: "hm".into(),
                        description: "Normal CDF at the first sheet number (data-mu/data-sigma, default 0/1). Local compute; daemon upgrades to Statistics.normal_cdf.".into(),
                    },
                    ActionType::Query,
                )),
                Box::new(SimpleTool::new(
                    ToolMetadata {
                        id: "sheet:stats_normal_quantile".into(),
                        label: "Normal Quantile".into(),
                        icon: "sheet".into(),
                        kind: ToolKind::Query,
                        capability_scope: Some("Statistics.normal_quantile".into()),
                        ontology_prefix: "hm".into(),
                        description: "Normal quantile (data-p default 0.975, data-mu/data-sigma). Local compute; daemon upgrades to Statistics.normal_quantile.".into(),
                    },
                    ActionType::Query,
                )),
                Box::new(SimpleTool::new(
                    ToolMetadata {
                        id: "sheet:stats_standard_normal_cdf".into(),
                        label: "Standard Normal CDF".into(),
                        icon: "sheet".into(),
                        kind: ToolKind::Query,
                        capability_scope: Some("Statistics.standard_normal_cdf".into()),
                        ontology_prefix: "hm".into(),
                        description: "Standard normal CDF Φ(z) from the first sheet number or data-z. Local compute; daemon upgrades to Statistics.standard_normal_cdf.".into(),
                    },
                    ActionType::Query,
                )),
                Box::new(SimpleTool::new(
                    ToolMetadata {
                        id: "sheet:stats_poisson_pmf".into(),
                        label: "Poisson PMF".into(),
                        icon: "sheet".into(),
                        kind: ToolKind::Query,
                        capability_scope: Some("Statistics.poisson_pmf".into()),
                        ontology_prefix: "hm".into(),
                        description: "Poisson PMF from sheet numbers or data-k/data-lambda. Local compute; daemon upgrades to Statistics.poisson_pmf.".into(),
                    },
                    ActionType::Query,
                )),
                Box::new(SimpleTool::new(
                    ToolMetadata {
                        id: "sheet:stats_poisson_cdf".into(),
                        label: "Poisson CDF".into(),
                        icon: "sheet".into(),
                        kind: ToolKind::Query,
                        capability_scope: Some("Statistics.poisson_cdf".into()),
                        ontology_prefix: "hm".into(),
                        description: "Poisson CDF from sheet numbers or data-k/data-lambda. Local compute; daemon upgrades to Statistics.poisson_cdf.".into(),
                    },
                    ActionType::Query,
                )),
                Box::new(SimpleTool::new(
                    ToolMetadata {
                        id: "sheet:stats_exponential_pdf".into(),
                        label: "Exponential PDF".into(),
                        icon: "sheet".into(),
                        kind: ToolKind::Query,
                        capability_scope: Some("Statistics.exponential_pdf".into()),
                        ontology_prefix: "hm".into(),
                        description: "Exponential PDF at the first sheet number (data-rate, default 1). Local compute; daemon upgrades to Statistics.exponential_pdf.".into(),
                    },
                    ActionType::Query,
                )),
                Box::new(SimpleTool::new(
                    ToolMetadata {
                        id: "sheet:stats_exponential_cdf".into(),
                        label: "Exponential CDF".into(),
                        icon: "sheet".into(),
                        kind: ToolKind::Query,
                        capability_scope: Some("Statistics.exponential_cdf".into()),
                        ontology_prefix: "hm".into(),
                        description: "Exponential CDF at the first sheet number (data-rate, default 1). Local compute; daemon upgrades to Statistics.exponential_cdf.".into(),
                    },
                    ActionType::Query,
                )),
                Box::new(SimpleTool::new(
                    ToolMetadata {
                        id: "sheet:stats_spearman".into(),
                        label: "Spearman".into(),
                        icon: "sheet".into(),
                        kind: ToolKind::Query,
                        capability_scope: Some("Statistics.spearman".into()),
                        ontology_prefix: "hm".into(),
                        description: "Spearman rank correlation between series halves on the selected sheet. Local compute; daemon upgrades to Statistics.spearman.".into(),
                    },
                    ActionType::Query,
                )),
                Box::new(SimpleTool::new(
                    ToolMetadata {
                        id: "sheet:stats_kendall".into(),
                        label: "Kendall".into(),
                        icon: "sheet".into(),
                        kind: ToolKind::Query,
                        capability_scope: Some("Statistics.kendall".into()),
                        ontology_prefix: "hm".into(),
                        description: "Kendall tau between series halves on the selected sheet. Local compute; daemon upgrades to Statistics.kendall.".into(),
                    },
                    ActionType::Query,
                )),
                Box::new(SimpleTool::new(
                    ToolMetadata {
                        id: "sheet:stats_winsorized_mean".into(),
                        label: "Winsorized Mean".into(),
                        icon: "sheet".into(),
                        kind: ToolKind::Query,
                        capability_scope: Some("Statistics.winsorized_mean".into()),
                        ontology_prefix: "hm".into(),
                        description: "Winsorized mean (default proportion 0.1, or data-proportion). Local compute; daemon upgrades to Statistics.winsorized_mean.".into(),
                    },
                    ActionType::Query,
                )),
                Box::new(SimpleTool::new(
                    ToolMetadata {
                        id: "sheet:stats_erf".into(),
                        label: "Erf".into(),
                        icon: "sheet".into(),
                        kind: ToolKind::Query,
                        capability_scope: Some("Statistics.erf".into()),
                        ontology_prefix: "hm".into(),
                        description: "Error function at the first sheet number or data-x. Local compute; daemon upgrades to Statistics.erf.".into(),
                    },
                    ActionType::Query,
                )),
                Box::new(SimpleTool::new(
                    ToolMetadata {
                        id: "sheet:stats_erfc".into(),
                        label: "Erfc".into(),
                        icon: "sheet".into(),
                        kind: ToolKind::Query,
                        capability_scope: Some("Statistics.erfc".into()),
                        ontology_prefix: "hm".into(),
                        description: "Complementary error function at the first sheet number or data-x. Local compute; daemon upgrades to Statistics.erfc.".into(),
                    },
                    ActionType::Query,
                )),
                Box::new(SimpleTool::new(
                    ToolMetadata {
                        id: "sheet:stats_uniform_pdf".into(),
                        label: "Uniform PDF".into(),
                        icon: "sheet".into(),
                        kind: ToolKind::Query,
                        capability_scope: Some("Statistics.uniform_pdf".into()),
                        ontology_prefix: "hm".into(),
                        description: "Uniform PDF at the first sheet number (data-a/data-b, default 0/1). Local compute; daemon upgrades to Statistics.uniform_pdf.".into(),
                    },
                    ActionType::Query,
                )),
                Box::new(SimpleTool::new(
                    ToolMetadata {
                        id: "sheet:stats_laplace_pdf".into(),
                        label: "Laplace PDF".into(),
                        icon: "sheet".into(),
                        kind: ToolKind::Query,
                        capability_scope: Some("Statistics.laplace_pdf".into()),
                        ontology_prefix: "hm".into(),
                        description: "Laplace PDF at the first sheet number (data-mu/data-b, default 0/1). Local compute; daemon upgrades to Statistics.laplace_pdf.".into(),
                    },
                    ActionType::Query,
                )),
                Box::new(SimpleTool::new(
                    ToolMetadata {
                        id: "sheet:stats_standard_pdf".into(),
                        label: "Standard Normal PDF".into(),
                        icon: "sheet".into(),
                        kind: ToolKind::Query,
                        capability_scope: Some("Statistics.standard_pdf".into()),
                        ontology_prefix: "hm".into(),
                        description: "Standard normal PDF φ(z) from the first sheet number or data-z. Local compute; daemon upgrades to Statistics.standard_pdf.".into(),
                    },
                    ActionType::Query,
                )),
                Box::new(SimpleTool::new(
                    ToolMetadata {
                        id: "sheet:stats_uniform_cdf".into(),
                        label: "Uniform CDF".into(),
                        icon: "sheet".into(),
                        kind: ToolKind::Query,
                        capability_scope: Some("Statistics.uniform_cdf".into()),
                        ontology_prefix: "hm".into(),
                        description: "Uniform CDF at the first sheet number (data-a/data-b, default 0/1). Local compute; daemon upgrades to Statistics.uniform_cdf.".into(),
                    },
                    ActionType::Query,
                )),
                Box::new(SimpleTool::new(
                    ToolMetadata {
                        id: "sheet:stats_laplace_cdf".into(),
                        label: "Laplace CDF".into(),
                        icon: "sheet".into(),
                        kind: ToolKind::Query,
                        capability_scope: Some("Statistics.laplace_cdf".into()),
                        ontology_prefix: "hm".into(),
                        description: "Laplace CDF at the first sheet number (data-mu/data-b, default 0/1). Local compute; daemon upgrades to Statistics.laplace_cdf.".into(),
                    },
                    ActionType::Query,
                )),
                Box::new(SimpleTool::new(
                    ToolMetadata {
                        id: "sheet:stats_lognormal_pdf".into(),
                        label: "Lognormal PDF".into(),
                        icon: "sheet".into(),
                        kind: ToolKind::Query,
                        capability_scope: Some("Statistics.lognormal_pdf".into()),
                        ontology_prefix: "hm".into(),
                        description: "Lognormal PDF at the first sheet number (data-mu/data-sigma, default 0/1). Local compute; daemon upgrades to Statistics.lognormal_pdf.".into(),
                    },
                    ActionType::Query,
                )),
                Box::new(SimpleTool::new(
                    ToolMetadata {
                        id: "sheet:stats_lognormal_cdf".into(),
                        label: "Lognormal CDF".into(),
                        icon: "sheet".into(),
                        kind: ToolKind::Query,
                        capability_scope: Some("Statistics.lognormal_cdf".into()),
                        ontology_prefix: "hm".into(),
                        description: "Lognormal CDF at the first sheet number (data-mu/data-sigma, default 0/1). Local compute; daemon upgrades to Statistics.lognormal_cdf.".into(),
                    },
                    ActionType::Query,
                )),
                Box::new(SimpleTool::new(
                    ToolMetadata {
                        id: "sheet:stats_standard_quantile".into(),
                        label: "Standard Normal Quantile".into(),
                        icon: "sheet".into(),
                        kind: ToolKind::Query,
                        capability_scope: Some("Statistics.standard_quantile".into()),
                        ontology_prefix: "hm".into(),
                        description: "Standard normal quantile Φ⁻¹(p) from data-p or first sheet number (default 0.975). Local compute; daemon upgrades to Statistics.standard_quantile.".into(),
                    },
                    ActionType::Query,
                )),
                Box::new(SimpleTool::new(
                    ToolMetadata {
                        id: "sheet:stats_ln_gamma".into(),
                        label: "Log-Gamma".into(),
                        icon: "sheet".into(),
                        kind: ToolKind::Query,
                        capability_scope: Some("Statistics.ln_gamma".into()),
                        ontology_prefix: "hm".into(),
                        description: "ln Γ(x) from the first sheet number or data-x. Local compute; daemon upgrades to Statistics.ln_gamma.".into(),
                    },
                    ActionType::Query,
                )),
                Box::new(SimpleTool::new(
                    ToolMetadata {
                        id: "sheet:stats_gamma_fn".into(),
                        label: "Gamma Function".into(),
                        icon: "sheet".into(),
                        kind: ToolKind::Query,
                        capability_scope: Some("Statistics.gamma_fn".into()),
                        ontology_prefix: "hm".into(),
                        description: "Γ(x) from the first sheet number or data-x. Local compute; daemon upgrades to Statistics.gamma_fn.".into(),
                    },
                    ActionType::Query,
                )),
                Box::new(SimpleTool::new(
                    ToolMetadata {
                        id: "sheet:stats_weibull_pdf".into(),
                        label: "Weibull PDF".into(),
                        icon: "sheet".into(),
                        kind: ToolKind::Query,
                        capability_scope: Some("Statistics.weibull_pdf".into()),
                        ontology_prefix: "hm".into(),
                        description: "Weibull PDF at the first sheet number (data-shape/data-scale, default 1/1). Local compute; daemon upgrades to Statistics.weibull_pdf.".into(),
                    },
                    ActionType::Query,
                )),
                Box::new(SimpleTool::new(
                    ToolMetadata {
                        id: "sheet:stats_gamma_pdf".into(),
                        label: "Gamma PDF".into(),
                        icon: "sheet".into(),
                        kind: ToolKind::Query,
                        capability_scope: Some("Statistics.gamma_pdf".into()),
                        ontology_prefix: "hm".into(),
                        description: "Gamma PDF at the first sheet number (data-shape/data-scale, default 1/1). Local compute; daemon upgrades to Statistics.gamma_pdf.".into(),
                    },
                    ActionType::Query,
                )),
                Box::new(SimpleTool::new(
                    ToolMetadata {
                        id: "sheet:stats_two_sided_p".into(),
                        label: "Two-Sided P".into(),
                        icon: "sheet".into(),
                        kind: ToolKind::Query,
                        capability_scope: Some("Statistics.two_sided_p".into()),
                        ontology_prefix: "hm".into(),
                        description: "Two-sided normal p-value from the first sheet number or data-z. Local compute; daemon upgrades to Statistics.two_sided_p.".into(),
                    },
                    ActionType::Query,
                )),
                Box::new(SimpleTool::new(
                    ToolMetadata {
                        id: "sheet:stats_chi_squared_upper_p".into(),
                        label: "Chi-Squared Upper P".into(),
                        icon: "sheet".into(),
                        kind: ToolKind::Query,
                        capability_scope: Some("Statistics.chi_squared_upper_p".into()),
                        ontology_prefix: "hm".into(),
                        description: "Chi-squared upper-tail p at the first sheet number (data-k, default 2). Local compute; daemon upgrades to Statistics.chi_squared_upper_p.".into(),
                    },
                    ActionType::Query,
                )),
                Box::new(SimpleTool::new(
                    ToolMetadata {
                        id: "sheet:stats_students_t_pdf".into(),
                        label: "Student's t PDF".into(),
                        icon: "sheet".into(),
                        kind: ToolKind::Query,
                        capability_scope: Some("Statistics.students_t_pdf".into()),
                        ontology_prefix: "hm".into(),
                        description: "Student's t PDF at the first sheet number (data-nu, default 10). Local compute; daemon upgrades to Statistics.students_t_pdf.".into(),
                    },
                    ActionType::Query,
                )),
                Box::new(SimpleTool::new(
                    ToolMetadata {
                        id: "sheet:stats_fisher_f_pdf".into(),
                        label: "Fisher F PDF".into(),
                        icon: "sheet".into(),
                        kind: ToolKind::Query,
                        capability_scope: Some("Statistics.fisher_f_pdf".into()),
                        ontology_prefix: "hm".into(),
                        description: "Fisher F PDF at the first sheet number (data-d1/data-d2, default 5/10). Local compute; daemon upgrades to Statistics.fisher_f_pdf.".into(),
                    },
                    ActionType::Query,
                )),
                Box::new(SimpleTool::new(
                    ToolMetadata {
                        id: "sheet:stats_gammp".into(),
                        label: "Gammp".into(),
                        icon: "sheet".into(),
                        kind: ToolKind::Query,
                        capability_scope: Some("Statistics.gammp".into()),
                        ontology_prefix: "hm".into(),
                        description: "Regularized lower incomplete gamma P(a,x) from sheet numbers or data-a/data-x. Local compute; daemon upgrades to Statistics.gammp.".into(),
                    },
                    ActionType::Query,
                )),
                Box::new(SimpleTool::new(
                    ToolMetadata {
                        id: "sheet:stats_gammq".into(),
                        label: "Gammq".into(),
                        icon: "sheet".into(),
                        kind: ToolKind::Query,
                        capability_scope: Some("Statistics.gammq".into()),
                        ontology_prefix: "hm".into(),
                        description: "Regularized upper incomplete gamma Q(a,x) from sheet numbers or data-a/data-x. Local compute; daemon upgrades to Statistics.gammq.".into(),
                    },
                    ActionType::Query,
                )),
                Box::new(SimpleTool::new(
                    ToolMetadata {
                        id: "sheet:stats_betai".into(),
                        label: "Betai".into(),
                        icon: "sheet".into(),
                        kind: ToolKind::Query,
                        capability_scope: Some("Statistics.betai".into()),
                        ontology_prefix: "hm".into(),
                        description: "Regularized incomplete beta I_x(a,b) from sheet numbers or data-a/data-b/data-x. Local compute; daemon upgrades to Statistics.betai.".into(),
                    },
                    ActionType::Query,
                )),
                Box::new(SimpleTool::new(
                    ToolMetadata {
                        id: "sheet:stats_students_t_cdf".into(),
                        label: "Student's t CDF".into(),
                        icon: "sheet".into(),
                        kind: ToolKind::Query,
                        capability_scope: Some("Statistics.students_t_cdf".into()),
                        ontology_prefix: "hm".into(),
                        description: "Student's t CDF at the first sheet number (data-nu, default 10). Local compute; daemon upgrades to Statistics.students_t_cdf.".into(),
                    },
                    ActionType::Query,
                )),
                Box::new(SimpleTool::new(
                    ToolMetadata {
                        id: "sheet:stats_students_t_two_sided_p".into(),
                        label: "Student's t Two-Sided P".into(),
                        icon: "sheet".into(),
                        kind: ToolKind::Query,
                        capability_scope: Some("Statistics.students_t_two_sided_p".into()),
                        ontology_prefix: "hm".into(),
                        description: "Student's t two-sided p at the first sheet number (data-nu, default 10). Local compute; daemon upgrades to Statistics.students_t_two_sided_p.".into(),
                    },
                    ActionType::Query,
                )),
                Box::new(SimpleTool::new(
                    ToolMetadata {
                        id: "sheet:stats_students_t_upper_p".into(),
                        label: "Student's t Upper P".into(),
                        icon: "sheet".into(),
                        kind: ToolKind::Query,
                        capability_scope: Some("Statistics.students_t_upper_p".into()),
                        ontology_prefix: "hm".into(),
                        description: "Student's t upper-tail p at the first sheet number (data-nu, default 10). Local compute; daemon upgrades to Statistics.students_t_upper_p.".into(),
                    },
                    ActionType::Query,
                )),
                Box::new(SimpleTool::new(
                    ToolMetadata {
                        id: "sheet:stats_students_t_quantile".into(),
                        label: "Student's t Quantile".into(),
                        icon: "sheet".into(),
                        kind: ToolKind::Query,
                        capability_scope: Some("Statistics.students_t_quantile".into()),
                        ontology_prefix: "hm".into(),
                        description: "Student's t quantile (data-p default 0.975, data-nu default 10). Local compute; daemon upgrades to Statistics.students_t_quantile.".into(),
                    },
                    ActionType::Query,
                )),
                Box::new(SimpleTool::new(
                    ToolMetadata {
                        id: "sheet:stats_fisher_f_cdf".into(),
                        label: "Fisher F CDF".into(),
                        icon: "sheet".into(),
                        kind: ToolKind::Query,
                        capability_scope: Some("Statistics.fisher_f_cdf".into()),
                        ontology_prefix: "hm".into(),
                        description: "Fisher F CDF at the first sheet number (data-d1/data-d2, default 5/10). Local compute; daemon upgrades to Statistics.fisher_f_cdf.".into(),
                    },
                    ActionType::Query,
                )),
                Box::new(SimpleTool::new(
                    ToolMetadata {
                        id: "sheet:stats_fisher_f_upper_p".into(),
                        label: "Fisher F Upper P".into(),
                        icon: "sheet".into(),
                        kind: ToolKind::Query,
                        capability_scope: Some("Statistics.fisher_f_upper_p".into()),
                        ontology_prefix: "hm".into(),
                        description: "Fisher F upper-tail p at the first sheet number (data-d1/data-d2, default 5/10). Local compute; daemon upgrades to Statistics.fisher_f_upper_p.".into(),
                    },
                    ActionType::Query,
                )),
                Box::new(SimpleTool::new(
                    ToolMetadata {
                        id: "sheet:stats_fisher_f_quantile".into(),
                        label: "Fisher F Quantile".into(),
                        icon: "sheet".into(),
                        kind: ToolKind::Query,
                        capability_scope: Some("Statistics.fisher_f_quantile".into()),
                        ontology_prefix: "hm".into(),
                        description: "Fisher F quantile (data-p default 0.95, data-d1/data-d2 default 5/10). Local compute; daemon upgrades to Statistics.fisher_f_quantile.".into(),
                    },
                    ActionType::Query,
                )),
                Box::new(SimpleTool::new(
                    ToolMetadata {
                        id: "sheet:stats_tukey_fences".into(),
                        label: "Tukey Fences".into(),
                        icon: "sheet".into(),
                        kind: ToolKind::Query,
                        capability_scope: Some("Statistics.tukey_fences".into()),
                        ontology_prefix: "hm".into(),
                        description: "Tukey fence bounds on the selected sheet (data-k, default 1.5). Local compute; daemon upgrades to Statistics.tukey_fences.".into(),
                    },
                    ActionType::Query,
                )),
                Box::new(SimpleTool::new(
                    ToolMetadata {
                        id: "sheet:stats_empirical_cdf".into(),
                        label: "Empirical CDF".into(),
                        icon: "sheet".into(),
                        kind: ToolKind::Query,
                        capability_scope: Some("Statistics.empirical_cdf".into()),
                        ontology_prefix: "hm".into(),
                        description: "Empirical CDF at data-x or the last sheet number. Local compute; daemon upgrades to Statistics.empirical_cdf.".into(),
                    },
                    ActionType::Query,
                )),
                Box::new(SimpleTool::new(
                    ToolMetadata {
                        id: "sheet:stats_entropy".into(),
                        label: "Entropy".into(),
                        icon: "sheet".into(),
                        kind: ToolKind::Query,
                        capability_scope: Some("Statistics.entropy".into()),
                        ontology_prefix: "hm".into(),
                        description: "Shannon entropy of sheet numbers as a mass vector. Local compute; daemon upgrades to Statistics.entropy.".into(),
                    },
                    ActionType::Query,
                )),
                Box::new(SimpleTool::new(
                    ToolMetadata {
                        id: "sheet:stats_kl_divergence".into(),
                        label: "KL Divergence".into(),
                        icon: "sheet".into(),
                        kind: ToolKind::Query,
                        capability_scope: Some("Statistics.kl_divergence".into()),
                        ontology_prefix: "hm".into(),
                        description: "KL(p‖q) between series halves on the selected sheet. Local compute; daemon upgrades to Statistics.kl_divergence.".into(),
                    },
                    ActionType::Query,
                )),
                Box::new(SimpleTool::new(
                    ToolMetadata {
                        id: "sheet:stats_cross_entropy".into(),
                        label: "Cross Entropy".into(),
                        icon: "sheet".into(),
                        kind: ToolKind::Query,
                        capability_scope: Some("Statistics.cross_entropy".into()),
                        ontology_prefix: "hm".into(),
                        description: "Cross-entropy H(p,q) between series halves on the selected sheet. Local compute; daemon upgrades to Statistics.cross_entropy.".into(),
                    },
                    ActionType::Query,
                )),
                Box::new(SimpleTool::new(
                    ToolMetadata {
                        id: "sheet:stats_entropy_from_counts".into(),
                        label: "Entropy From Counts".into(),
                        icon: "sheet".into(),
                        kind: ToolKind::Query,
                        capability_scope: Some("Statistics.entropy_from_counts".into()),
                        ontology_prefix: "hm".into(),
                        description: "Shannon entropy from non-negative floored sheet counts. Local compute; daemon upgrades to Statistics.entropy_from_counts.".into(),
                    },
                    ActionType::Query,
                )),
                Box::new(SimpleTool::new(
                    ToolMetadata {
                        id: "sheet:stats_moving_average".into(),
                        label: "Moving Average".into(),
                        icon: "sheet".into(),
                        kind: ToolKind::Query,
                        capability_scope: Some("Statistics.moving_average".into()),
                        ontology_prefix: "hm".into(),
                        description: "Simple moving average (data-window, default 3). Local compute; daemon upgrades to Statistics.moving_average.".into(),
                    },
                    ActionType::Query,
                )),
                Box::new(SimpleTool::new(
                    ToolMetadata {
                        id: "sheet:stats_modified_z_score_outliers".into(),
                        label: "Modified Z Outliers".into(),
                        icon: "sheet".into(),
                        kind: ToolKind::Query,
                        capability_scope: Some("Statistics.modified_z_score_outliers".into()),
                        ontology_prefix: "hm".into(),
                        description: "Modified z-score outlier indices (default threshold 3.5, or data-threshold). Local compute; daemon upgrades to Statistics.modified_z_score_outliers.".into(),
                    },
                    ActionType::Query,
                )),
                Box::new(SimpleTool::new(
                    ToolMetadata {
                        id: "sheet:stats_iqr_outliers".into(),
                        label: "IQR Outliers".into(),
                        icon: "sheet".into(),
                        kind: ToolKind::Query,
                        capability_scope: Some("Statistics.iqr_outliers".into()),
                        ontology_prefix: "hm".into(),
                        description: "IQR/Tukey outlier indices (data-k, default 1.5). Local compute; daemon upgrades to Statistics.iqr_outliers.".into(),
                    },
                    ActionType::Query,
                )),
                Box::new(SimpleTool::new(
                    ToolMetadata {
                        id: "sheet:stats_exponential_smoothing".into(),
                        label: "Exp. Smoothing".into(),
                        icon: "sheet".into(),
                        kind: ToolKind::Query,
                        capability_scope: Some("Statistics.exponential_smoothing".into()),
                        ontology_prefix: "hm".into(),
                        description: "Single exponential smoothing (data-alpha, default 0.3). Local compute; daemon upgrades to Statistics.exponential_smoothing.".into(),
                    },
                    ActionType::Query,
                )),
                Box::new(SimpleTool::new(
                    ToolMetadata {
                        id: "sheet:stats_adf_proxy".into(),
                        label: "ADF Proxy".into(),
                        icon: "sheet".into(),
                        kind: ToolKind::Query,
                        capability_scope: Some("Statistics.adf_proxy".into()),
                        ontology_prefix: "hm".into(),
                        description: "ADF stationarity proxy on sheet numbers. Local compute; daemon upgrades to Statistics.adf_proxy.".into(),
                    },
                    ActionType::Query,
                )),
                Box::new(SimpleTool::new(
                    ToolMetadata {
                        id: "sheet:stats_histogram".into(),
                        label: "Histogram".into(),
                        icon: "sheet".into(),
                        kind: ToolKind::Query,
                        capability_scope: Some("Statistics.histogram".into()),
                        ontology_prefix: "hm".into(),
                        description: "Equal-width histogram (data-bins, default 10). Local compute; daemon upgrades to Statistics.histogram.".into(),
                    },
                    ActionType::Query,
                )),
                Box::new(SimpleTool::new(
                    ToolMetadata {
                        id: "sheet:stats_ks_1sample".into(),
                        label: "KS 1-Sample".into(),
                        icon: "sheet".into(),
                        kind: ToolKind::Query,
                        capability_scope: Some("Statistics.ks_1sample".into()),
                        ontology_prefix: "hm".into(),
                        description: "One-sample KS vs Uniform(0,1) on sheet numbers. Local compute; daemon upgrades to Statistics.ks_1sample.".into(),
                    },
                    ActionType::Query,
                )),
                Box::new(SimpleTool::new(
                    ToolMetadata {
                        id: "sheet:stats_grubbs_test".into(),
                        label: "Grubbs Test".into(),
                        icon: "sheet".into(),
                        kind: ToolKind::Query,
                        capability_scope: Some("Statistics.grubbs_test".into()),
                        ontology_prefix: "hm".into(),
                        description: "Grubbs single-outlier test (data-alpha, default 0.05). Local compute; daemon upgrades to Statistics.grubbs_test.".into(),
                    },
                    ActionType::Query,
                )),
                Box::new(SimpleTool::new(
                    ToolMetadata {
                        id: "sheet:stats_one_sample_t".into(),
                        label: "One-Sample t".into(),
                        icon: "sheet".into(),
                        kind: ToolKind::Query,
                        capability_scope: Some("Statistics.one_sample_t".into()),
                        ontology_prefix: "hm".into(),
                        description: "One-sample t-test (data-mu, default 0). Local compute; daemon upgrades to Statistics.one_sample_t.".into(),
                    },
                    ActionType::Query,
                )),
                Box::new(SimpleTool::new(
                    ToolMetadata {
                        id: "sheet:stats_two_sample_t".into(),
                        label: "Two-Sample t".into(),
                        icon: "sheet".into(),
                        kind: ToolKind::Query,
                        capability_scope: Some("Statistics.two_sample_t".into()),
                        ontology_prefix: "hm".into(),
                        description: "Two-sample t-test between series halves (data-equal-var, default 1). Local compute; daemon upgrades to Statistics.two_sample_t.".into(),
                    },
                    ActionType::Query,
                )),
                Box::new(SimpleTool::new(
                    ToolMetadata {
                        id: "sheet:stats_paired_t".into(),
                        label: "Paired t".into(),
                        icon: "sheet".into(),
                        kind: ToolKind::Query,
                        capability_scope: Some("Statistics.paired_t".into()),
                        ontology_prefix: "hm".into(),
                        description: "Paired t-test between series halves. Local compute; daemon upgrades to Statistics.paired_t.".into(),
                    },
                    ActionType::Query,
                )),
                Box::new(SimpleTool::new(
                    ToolMetadata {
                        id: "sheet:stats_linear_regression".into(),
                        label: "Linear Regression".into(),
                        icon: "sheet".into(),
                        kind: ToolKind::Query,
                        capability_scope: Some("Statistics.linear_regression".into()),
                        ontology_prefix: "hm".into(),
                        description: "Simple OLS of series halves (x,y). Local compute; daemon upgrades to Statistics.linear_regression.".into(),
                    },
                    ActionType::Query,
                )),
                Box::new(SimpleTool::new(
                    ToolMetadata {
                        id: "sheet:stats_chi_square_gof".into(),
                        label: "χ² GOF".into(),
                        icon: "sheet".into(),
                        kind: ToolKind::Query,
                        capability_scope: Some("Statistics.chi_square_gof".into()),
                        ontology_prefix: "hm".into(),
                        description: "Chi-square goodness-of-fit (observed then expected halves). Local compute; daemon upgrades to Statistics.chi_square_gof.".into(),
                    },
                    ActionType::Query,
                )),
                Box::new(SimpleTool::new(
                    ToolMetadata {
                        id: "sheet:stats_chi_square_independence".into(),
                        label: "χ² Independence".into(),
                        icon: "sheet".into(),
                        kind: ToolKind::Query,
                        capability_scope: Some("Statistics.chi_square_independence".into()),
                        ontology_prefix: "hm".into(),
                        description: "Chi-square independence on a contingency table (data-cols, default 2). Local compute; daemon upgrades to Statistics.chi_square_independence.".into(),
                    },
                    ActionType::Query,
                )),
                Box::new(SimpleTool::new(
                    ToolMetadata {
                        id: "sheet:stats_correlation_p_value".into(),
                        label: "Correlation P".into(),
                        icon: "sheet".into(),
                        kind: ToolKind::Query,
                        capability_scope: Some("Statistics.correlation_p_value".into()),
                        ontology_prefix: "hm".into(),
                        description: "P-value for correlation (Pearson of halves, or data-r/data-n). Local compute; daemon upgrades to Statistics.correlation_p_value.".into(),
                    },
                    ActionType::Query,
                )),
                Box::new(SimpleTool::new(
                    ToolMetadata {
                        id: "sheet:stats_friedman".into(),
                        label: "Friedman".into(),
                        icon: "sheet".into(),
                        kind: ToolKind::Query,
                        capability_scope: Some("Statistics.friedman".into()),
                        ontology_prefix: "hm".into(),
                        description: "Friedman test across blocks (data-treatments, default 3). Local compute; daemon upgrades to Statistics.friedman.".into(),
                    },
                    ActionType::Query,
                )),
                Box::new(SimpleTool::new(
                    ToolMetadata {
                        id: "sheet:stats_ljung_box".into(),
                        label: "Ljung–Box".into(),
                        icon: "sheet".into(),
                        kind: ToolKind::Query,
                        capability_scope: Some("Statistics.ljung_box".into()),
                        ontology_prefix: "hm".into(),
                        description: "Ljung–Box Q from sheet ACF (data-h). Local compute; daemon upgrades to Statistics.ljung_box.".into(),
                    },
                    ActionType::Query,
                )),
                Box::new(SimpleTool::new(
                    ToolMetadata {
                        id: "sheet:stats_mann_whitney_u".into(),
                        label: "Mann–Whitney U".into(),
                        icon: "sheet".into(),
                        kind: ToolKind::Query,
                        capability_scope: Some("Statistics.mann_whitney_u".into()),
                        ontology_prefix: "hm".into(),
                        description: "Mann–Whitney U between series halves. Local compute; daemon upgrades to Statistics.mann_whitney_u.".into(),
                    },
                    ActionType::Query,
                )),
                Box::new(SimpleTool::new(
                    ToolMetadata {
                        id: "sheet:stats_mcnemar".into(),
                        label: "McNemar".into(),
                        icon: "sheet".into(),
                        kind: ToolKind::Query,
                        capability_scope: Some("Statistics.mcnemar".into()),
                        ontology_prefix: "hm".into(),
                        description: "McNemar test from discordant counts (first two numbers or data-b/data-c). Local compute; daemon upgrades to Statistics.mcnemar.".into(),
                    },
                    ActionType::Query,
                )),
                Box::new(SimpleTool::new(
                    ToolMetadata {
                        id: "sheet:stats_mutual_information".into(),
                        label: "Mutual Information".into(),
                        icon: "sheet".into(),
                        kind: ToolKind::Query,
                        capability_scope: Some("Statistics.mutual_information".into()),
                        ontology_prefix: "hm".into(),
                        description: "Mutual information of floored series halves. Local compute; daemon upgrades to Statistics.mutual_information.".into(),
                    },
                    ActionType::Query,
                )),
                Box::new(SimpleTool::new(
                    ToolMetadata {
                        id: "sheet:stats_one_way_anova".into(),
                        label: "One-Way ANOVA".into(),
                        icon: "sheet".into(),
                        kind: ToolKind::Query,
                        capability_scope: Some("Statistics.one_way_anova".into()),
                        ontology_prefix: "hm".into(),
                        description: "One-way ANOVA across equal groups (data-groups, default 2). Local compute; daemon upgrades to Statistics.one_way_anova.".into(),
                    },
                    ActionType::Query,
                )),
                Box::new(SimpleTool::new(
                    ToolMetadata {
                        id: "sheet:stats_mahalanobis_sq".into(),
                        label: "Mahalanobis²".into(),
                        icon: "sheet".into(),
                        kind: ToolKind::Query,
                        capability_scope: Some("Statistics.mahalanobis_sq".into()),
                        ontology_prefix: "hm".into(),
                        description: "Squared Mahalanobis distance (data-dim; x, mean, optional inv_cov). Local compute; daemon upgrades to Statistics.mahalanobis_sq.".into(),
                    },
                    ActionType::Query,
                )),
                Box::new(SimpleTool::new(
                    ToolMetadata {
                        id: "sheet:stats_mvn_log_pdf".into(),
                        label: "MVN Log PDF".into(),
                        icon: "sheet".into(),
                        kind: ToolKind::Query,
                        capability_scope: Some("Statistics.mvn_log_pdf".into()),
                        ontology_prefix: "hm".into(),
                        description: "Multivariate normal log-density (data-dim; x, mean, optional cov). Local compute; daemon upgrades to Statistics.mvn_log_pdf.".into(),
                    },
                    ActionType::Query,
                )),
                Box::new(SimpleTool::new(
                    ToolMetadata {
                        id: "sheet:stats_mvn_pdf".into(),
                        label: "MVN PDF".into(),
                        icon: "sheet".into(),
                        kind: ToolKind::Query,
                        capability_scope: Some("Statistics.mvn_pdf".into()),
                        ontology_prefix: "hm".into(),
                        description: "Multivariate normal density (data-dim; x, mean, optional cov). Local compute; daemon upgrades to Statistics.mvn_pdf.".into(),
                    },
                    ActionType::Query,
                )),
                Box::new(SimpleTool::new(
                    ToolMetadata {
                        id: "sheet:stats_mvn_sample".into(),
                        label: "MVN Sample".into(),
                        icon: "sheet".into(),
                        kind: ToolKind::Query,
                        capability_scope: Some("Statistics.mvn_sample".into()),
                        ontology_prefix: "hm".into(),
                        description: "Draw one MVN sample (data-dim/data-seed; mean, optional cov). Local compute; daemon upgrades to Statistics.mvn_sample.".into(),
                    },
                    ActionType::Query,
                )),
                Box::new(SimpleTool::new(
                    ToolMetadata {
                        id: "sheet:stats_mvn_mle".into(),
                        label: "MVN MLE".into(),
                        icon: "sheet".into(),
                        kind: ToolKind::Query,
                        capability_scope: Some("Statistics.mvn_mle".into()),
                        ontology_prefix: "hm".into(),
                        description: "MVN mean/covariance MLE on row-major sheet (data-dim/data-n). Local compute; daemon upgrades to Statistics.mvn_mle.".into(),
                    },
                    ActionType::Query,
                )),
                Box::new(SimpleTool::new(
                    ToolMetadata {
                        id: "sheet:stats_validate_probability".into(),
                        label: "Validate Prob".into(),
                        icon: "sheet".into(),
                        kind: ToolKind::Query,
                        capability_scope: Some("Statistics.validate_probability".into()),
                        ontology_prefix: "hm".into(),
                        description: "Validate non-negative masses that sum to 1. Local compute; daemon upgrades to Statistics.validate_probability.".into(),
                    },
                    ActionType::Query,
                )),
                Box::new(SimpleTool::new(
                    ToolMetadata {
                        id: "sheet:stats_simplex_project".into(),
                        label: "Simplex Project".into(),
                        icon: "sheet".into(),
                        kind: ToolKind::Query,
                        capability_scope: Some("Statistics.simplex_project".into()),
                        ontology_prefix: "hm".into(),
                        description: "Euclidean projection onto the probability simplex. Local compute; daemon upgrades to Statistics.simplex_project.".into(),
                    },
                    ActionType::Query,
                )),
                Box::new(SimpleTool::new(
                    ToolMetadata {
                        id: "sheet:stats_fisher_distance".into(),
                        label: "Fisher Distance".into(),
                        icon: "sheet".into(),
                        kind: ToolKind::Query,
                        capability_scope: Some("Statistics.fisher_distance".into()),
                        ontology_prefix: "hm".into(),
                        description: "Fisher–Rao geodesic distance between series halves. Local compute; daemon upgrades to Statistics.fisher_distance.".into(),
                    },
                    ActionType::Query,
                )),
                Box::new(SimpleTool::new(
                    ToolMetadata {
                        id: "sheet:stats_neg_entropy".into(),
                        label: "Neg-Entropy".into(),
                        icon: "sheet".into(),
                        kind: ToolKind::Query,
                        capability_scope: Some("Statistics.neg_entropy".into()),
                        ontology_prefix: "hm".into(),
                        description: "Negative entropy Σ pᵢ ln(pᵢ) over sheet masses. Local compute; daemon upgrades to Statistics.neg_entropy.".into(),
                    },
                    ActionType::Query,
                )),
                Box::new(SimpleTool::new(
                    ToolMetadata {
                        id: "sheet:poly_eval".into(),
                        label: "Poly Eval".into(),
                        icon: "sheet".into(),
                        kind: ToolKind::Query,
                        capability_scope: Some("PolynomialAlgebra.eval".into()),
                        ontology_prefix: "hm".into(),
                        description: "Horner-evaluate little-endian coeffs at x (data-x or trailing number). Local compute; daemon upgrades to PolynomialAlgebra.eval.".into(),
                    },
                    ActionType::Query,
                )),
                Box::new(SimpleTool::new(
                    ToolMetadata {
                        id: "sheet:poly_add".into(),
                        label: "Poly Add".into(),
                        icon: "sheet".into(),
                        kind: ToolKind::Query,
                        capability_scope: Some("PolynomialAlgebra.add".into()),
                        ontology_prefix: "hm".into(),
                        description: "Add two polynomials (halves or data-a-len). Local compute; daemon upgrades to PolynomialAlgebra.add.".into(),
                    },
                    ActionType::Query,
                )),
                Box::new(SimpleTool::new(
                    ToolMetadata {
                        id: "sheet:poly_sub".into(),
                        label: "Poly Sub".into(),
                        icon: "sheet".into(),
                        kind: ToolKind::Query,
                        capability_scope: Some("PolynomialAlgebra.sub".into()),
                        ontology_prefix: "hm".into(),
                        description: "Subtract two polynomials (halves or data-a-len). Local compute; daemon upgrades to PolynomialAlgebra.sub.".into(),
                    },
                    ActionType::Query,
                )),
                Box::new(SimpleTool::new(
                    ToolMetadata {
                        id: "sheet:poly_mul".into(),
                        label: "Poly Mul".into(),
                        icon: "sheet".into(),
                        kind: ToolKind::Query,
                        capability_scope: Some("PolynomialAlgebra.mul".into()),
                        ontology_prefix: "hm".into(),
                        description: "Multiply two polynomials (schoolbook). Local compute; daemon upgrades to PolynomialAlgebra.mul.".into(),
                    },
                    ActionType::Query,
                )),
                Box::new(SimpleTool::new(
                    ToolMetadata {
                        id: "sheet:poly_gcd".into(),
                        label: "Poly GCD".into(),
                        icon: "sheet".into(),
                        kind: ToolKind::Query,
                        capability_scope: Some("PolynomialAlgebra.gcd".into()),
                        ontology_prefix: "hm".into(),
                        description: "Monic Euclidean gcd of two polynomials. Local compute; daemon upgrades to PolynomialAlgebra.gcd.".into(),
                    },
                    ActionType::Query,
                )),
                Box::new(SimpleTool::new(
                    ToolMetadata {
                        id: "sheet:poly_degree".into(),
                        label: "Poly Degree".into(),
                        icon: "sheet".into(),
                        kind: ToolKind::Query,
                        capability_scope: Some("PolynomialAlgebra.degree".into()),
                        ontology_prefix: "hm".into(),
                        description: "Degree of little-endian coeffs (null if zero). Local compute; daemon upgrades to PolynomialAlgebra.degree.".into(),
                    },
                    ActionType::Query,
                )),
                Box::new(SimpleTool::new(
                    ToolMetadata {
                        id: "sheet:poly_leading".into(),
                        label: "Poly Leading".into(),
                        icon: "sheet".into(),
                        kind: ToolKind::Query,
                        capability_scope: Some("PolynomialAlgebra.leading".into()),
                        ontology_prefix: "hm".into(),
                        description: "Leading coefficient of sheet polynomial. Local compute; daemon upgrades to PolynomialAlgebra.leading.".into(),
                    },
                    ActionType::Query,
                )),
                Box::new(SimpleTool::new(
                    ToolMetadata {
                        id: "sheet:poly_is_zero".into(),
                        label: "Poly Is Zero".into(),
                        icon: "sheet".into(),
                        kind: ToolKind::Query,
                        capability_scope: Some("PolynomialAlgebra.is_zero".into()),
                        ontology_prefix: "hm".into(),
                        description: "True iff trimmed coefficient list is empty. Local compute; daemon upgrades to PolynomialAlgebra.is_zero.".into(),
                    },
                    ActionType::Query,
                )),
                Box::new(SimpleTool::new(
                    ToolMetadata {
                        id: "sheet:poly_scale".into(),
                        label: "Poly Scale".into(),
                        icon: "sheet".into(),
                        kind: ToolKind::Query,
                        capability_scope: Some("PolynomialAlgebra.scale".into()),
                        ontology_prefix: "hm".into(),
                        description: "Scale every coefficient by s (data-s or trailing number). Local compute; daemon upgrades to PolynomialAlgebra.scale.".into(),
                    },
                    ActionType::Query,
                )),
                Box::new(SimpleTool::new(
                    ToolMetadata {
                        id: "sheet:poly_zero".into(),
                        label: "Poly Zero".into(),
                        icon: "sheet".into(),
                        kind: ToolKind::Query,
                        capability_scope: Some("PolynomialAlgebra.zero".into()),
                        ontology_prefix: "hm".into(),
                        description: "The zero polynomial (empty coeffs). Local compute; daemon upgrades to PolynomialAlgebra.zero.".into(),
                    },
                    ActionType::Query,
                )),
                Box::new(SimpleTool::new(
                    ToolMetadata {
                        id: "sheet:poly_constant".into(),
                        label: "Poly Constant".into(),
                        icon: "sheet".into(),
                        kind: ToolKind::Query,
                        capability_scope: Some("PolynomialAlgebra.constant".into()),
                        ontology_prefix: "hm".into(),
                        description: "Constant polynomial from data-c or first sheet number. Local compute; daemon upgrades to PolynomialAlgebra.constant.".into(),
                    },
                    ActionType::Query,
                )),
                Box::new(SimpleTool::new(
                    ToolMetadata {
                        id: "sheet:poly_derivative".into(),
                        label: "Poly Derivative".into(),
                        icon: "sheet".into(),
                        kind: ToolKind::Query,
                        capability_scope: Some("PolynomialAlgebra.derivative".into()),
                        ontology_prefix: "hm".into(),
                        description: "First derivative of little-endian coeffs. Local compute; daemon upgrades to PolynomialAlgebra.derivative.".into(),
                    },
                    ActionType::Query,
                )),
                Box::new(SimpleTool::new(
                    ToolMetadata {
                        id: "sheet:poly_monic".into(),
                        label: "Poly Monic".into(),
                        icon: "sheet".into(),
                        kind: ToolKind::Query,
                        capability_scope: Some("PolynomialAlgebra.monic".into()),
                        ontology_prefix: "hm".into(),
                        description: "Scale little-endian coeffs so the leading coefficient is 1. Local compute; daemon upgrades to PolynomialAlgebra.monic.".into(),
                    },
                    ActionType::Query,
                )),
                Box::new(SimpleTool::new(
                    ToolMetadata {
                        id: "sheet:poly_div_rem".into(),
                        label: "Poly Div/Rem".into(),
                        icon: "sheet".into(),
                        kind: ToolKind::Query,
                        capability_scope: Some("PolynomialAlgebra.div_rem".into()),
                        ontology_prefix: "hm".into(),
                        description: "Long division of two polynomials (halves or data-a-len) → quotient and remainder. Local compute; daemon upgrades to PolynomialAlgebra.div_rem.".into(),
                    },
                    ActionType::Query,
                )),
                Box::new(SimpleTool::new(
                    ToolMetadata {
                        id: "sheet:poly_resultant".into(),
                        label: "Poly Resultant".into(),
                        icon: "sheet".into(),
                        kind: ToolKind::Query,
                        capability_scope: Some("PolynomialAlgebra.resultant".into()),
                        ontology_prefix: "hm".into(),
                        description: "Euclidean resultant of two sheet polynomials (zero iff common root). Local compute; daemon upgrades to PolynomialAlgebra.resultant.".into(),
                    },
                    ActionType::Query,
                )),
                Box::new(SimpleTool::new(
                    ToolMetadata {
                        id: "sheet:stats_simplex_project_idempotent".into(),
                        label: "Simplex Idempotent".into(),
                        icon: "sheet".into(),
                        kind: ToolKind::Query,
                        capability_scope: Some("Statistics.simplex_project_idempotent".into()),
                        ontology_prefix: "hm".into(),
                        description: "Check project(project(p)) ≈ project(p) on sheet masses. Local compute; daemon upgrades to Statistics.simplex_project_idempotent.".into(),
                    },
                    ActionType::Query,
                )),
                Box::new(SimpleTool::new(
                    ToolMetadata {
                        id: "sheet:stats_fisher_inner_product".into(),
                        label: "Fisher Inner Prod".into(),
                        icon: "sheet".into(),
                        kind: ToolKind::Query,
                        capability_scope: Some("Statistics.fisher_inner_product".into()),
                        ontology_prefix: "hm".into(),
                        description: "Fisher metric ⟨u,v⟩_p from thirds (p, u, v). Local compute; daemon upgrades to Statistics.fisher_inner_product.".into(),
                    },
                    ActionType::Query,
                )),
                Box::new(SimpleTool::new(
                    ToolMetadata {
                        id: "sheet:stats_neg_entropy_grad".into(),
                        label: "Neg-Entropy Grad".into(),
                        icon: "sheet".into(),
                        kind: ToolKind::Query,
                        capability_scope: Some("Statistics.neg_entropy_grad".into()),
                        ontology_prefix: "hm".into(),
                        description: "Gradient ∇ψ(p)_i = ln(pᵢ)+1 over sheet masses. Local compute; daemon upgrades to Statistics.neg_entropy_grad.".into(),
                    },
                    ActionType::Query,
                )),
                Box::new(SimpleTool::new(
                    ToolMetadata {
                        id: "sheet:stats_kl_bregman_form".into(),
                        label: "KL Bregman".into(),
                        icon: "sheet".into(),
                        kind: ToolKind::Query,
                        capability_scope: Some("Statistics.kl_bregman_form".into()),
                        ontology_prefix: "hm".into(),
                        description: "KL via Bregman generator ψ=neg-entropy on series halves. Local compute; daemon upgrades to Statistics.kl_bregman_form.".into(),
                    },
                    ActionType::Query,
                )),
                Box::new(SimpleTool::new(
                    ToolMetadata {
                        id: "sheet:stats_bregman_pythagorean_test".into(),
                        label: "Bregman Pythag".into(),
                        icon: "sheet".into(),
                        kind: ToolKind::Query,
                        capability_scope: Some("Statistics.bregman_pythagorean_test".into()),
                        ontology_prefix: "hm".into(),
                        description: "Bregman–Pythagorean KL parts from thirds (p, q★, q). Local compute; daemon upgrades to Statistics.bregman_pythagorean_test.".into(),
                    },
                    ActionType::Query,
                )),
                Box::new(SimpleTool::new(
                    ToolMetadata {
                        id: "sheet:stats_probability_hash".into(),
                        label: "Prob Hash".into(),
                        icon: "sheet".into(),
                        kind: ToolKind::Query,
                        capability_scope: Some("Statistics.probability_hash".into()),
                        ontology_prefix: "hm".into(),
                        description: "FNV-1a hash over f32 bit patterns of sheet masses. Local compute; daemon upgrades to Statistics.probability_hash.".into(),
                    },
                    ActionType::Query,
                ))],
            ),
            ToolChain::new(
                ToolChainMetadata {
                    id: "sheet:tools".into(),
                    label: "Spreadsheet Tools".into(),
                    icon: "tools".into(),
                    description: "Place spreadsheets and import external tabular data.".into(),
                },
                tools,
            ),
        ],
    ));
}
