use super::{Cat, QApp, Stat};

pub(super) fn apps() -> Vec<QApp> {
    vec![
        QApp {
            id: "historical-linguistics",
            name: "Historical Linguistics",
            tagline: "Language Change",
            desc: "Sound-change annotation, comparative-reconstruction tools, language-family trees, and etymology knowledge graphs.",
            icon: "clock-history",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "morphology",
            name: "Morphology",
            tagline: "Word Structure",
            desc: "Morpheme-segmentation tools, inflectional-paradigm annotation, derivational-process graphs, and cross-language morphology comparison.",
            icon: "diagram-2",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "pragmatics",
            name: "Pragmatics",
            tagline: "Language in Context",
            desc: "Speech-act annotation, implicature-analysis tools, conversational-structure graphs, and cross-cultural pragmatics comparison.",
            icon: "chat-left",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "semantics",
            name: "Semantics",
            tagline: "Meaning",
            desc: "Lexical-semantic annotation, formal-semantic tools, frame-semantic analysis, and cross-linguistic meaning-comparison graphs.",
            icon: "type",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "semiotics",
            name: "Semiotics",
            tagline: "Signs & Meaning",
            desc: "Sign-system annotation, Peirce and Saussure theory tools, cultural-sign mapping, and visual-semiotics analysis graphs.",
            icon: "signpost",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "syntax",
            name: "Syntax",
            tagline: "Sentence Structure",
            desc: "Phrase-structure tree annotation, dependency-parse management, cross-linguistic word-order analysis, and syntactic-theory comparison.",
            icon: "braces-asterisk",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        // Specialised Intersectional & Applied Studies
        QApp {
            id: "disaster-studies",
            name: "Disaster Studies",
            tagline: "Hazard & Response",
            desc: "Disaster-event cataloguing, vulnerability-assessment tools, emergency-management annotation, and resilience-planning knowledge graphs.",
            icon: "exclamation-triangle",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "futures-studies-and-foresight",
            name: "Futures Studies",
            tagline: "Forecasting",
            desc: "Scenario-development tools, trend-analysis annotation, weak-signal tracking, and strategic-foresight knowledge graphs.",
            icon: "binoculars",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "leisure-studies",
            name: "Leisure Studies",
            tagline: "Play & Rest",
            desc: "Recreation-behaviour analysis, tourism-data annotation, work-leisure-balance policy tools, and leisure-culture knowledge graphs.",
            icon: "umbrella",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "philanthropy-and-nonprofit-studies",
            name: "Philanthropy & Nonprofit Studies",
            tagline: "Civil Society",
            desc: "Giving-pattern analysis, non-profit governance annotation, civil-society mapping, and philanthropic-strategy knowledge graphs.",
            icon: "gift",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        // Advanced Historical & Textual Studies
        QApp {
            id: "architectural-history",
            name: "Architectural History",
            tagline: "Buildings Over Time",
            desc: "Building-survey annotation, architectural-style classification, site-change documentation, and urban-morphology knowledge graphs.",
            icon: "buildings",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "childrens-literature",
            name: "Children's Literature",
            tagline: "Young Readers",
            desc: "Picture-book analysis, young adult genre tools, childhood-studies annotation, and reading-development knowledge graphs.",
            icon: "book",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "history-of-art-and-architecture",
            name: "History of Art & Architecture",
            tagline: "Built & Visual Heritage",
            desc: "Cross-period art-and-architecture comparison, monumental chronology tools, patronage-network graphs, and heritage-conservation annotation.",
            icon: "bank2",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "intellectual-history",
            name: "Intellectual History",
            tagline: "Ideas Over Time",
            desc: "Idea-genealogy mapping, conceptual-change annotation, intellectual-biography tools, and text-influence knowledge graphs.",
            icon: "lightbulb-fill",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "maritime-history",
            name: "Maritime History",
            tagline: "Sea & Commerce",
            desc: "Ship-voyage annotation, port-economy mapping, naval-battle knowledge graphs, and maritime-culture comparison tools.",
            icon: "compass",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "military-history",
            name: "Military History",
            tagline: "War & Strategy",
            desc: "Battle-event annotation, order-of-battle management, strategic-analysis tools, and military-technology evolution graphs.",
            icon: "flag",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "oral-history",
            name: "Oral History",
            tagline: "Living Memory",
            desc: "Interview-transcript management, narrator-biography annotation, memory-community mapping, and oral-history ethics tools.",
            icon: "mic",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "paleography",
            name: "Paleography",
            tagline: "Ancient Scripts",
            desc: "Script-dating tools, hands-comparison annotation, manuscript-genealogy graphs, and historical-writing-system analysis.",
            icon: "pen-fill",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "public-history",
            name: "Public History",
            tagline: "History in Public",
            desc: "Community-history project management, heritage-site annotation, public-memory analysis, and museum-collaboration tools.",
            icon: "bank",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "textual-criticism",
            name: "Textual Criticism",
            tagline: "Manuscript Scholarship",
            desc: "Witness-collation tools, stemmatics annotation, editorial-decision graphs, and critical-apparatus management.",
            icon: "journal-code",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        // Critical & Cultural Sub-Disciplines
        QApp {
            id: "animal-studies-human-animal-studies",
            name: "Animal Studies",
            tagline: "Human-Animal Relations",
            desc: "Multispecies-ethnography annotation, animal-rights philosophy tools, zoohistory mapping, and anthrozoology knowledge graphs.",
            icon: "bug",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "body-studies",
            name: "Body Studies",
            tagline: "Embodiment",
            desc: "Corporeal-theory annotation, medical-body-image analysis, embodiment-practice tools, and somatic-knowledge graphs.",
            icon: "person",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "critical-race-and-ethnic-studies",
            name: "Critical Race & Ethnic Studies",
            tagline: "Race & Ethnicity",
            desc: "Critical-race-theory annotation, ethnic-formation analysis, racial-justice mapping, and intersectionality knowledge graphs.",
            icon: "people",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "critical-theory",
            name: "Critical Theory",
            tagline: "Frankfurt School & Beyond",
            desc: "Dialectical-theory annotation, ideology-critique tools, cultural-industry analysis, and critical-theory genealogy graphs.",
            icon: "diagram-3",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "deaf-studies",
            name: "Deaf Studies",
            tagline: "Deaf Culture",
            desc: "Sign-language annotation, Deaf-community history, audism-critique tools, and bilingual-deaf-education knowledge graphs.",
            icon: "ear",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "diaspora-studies",
            name: "Diaspora Studies",
            tagline: "Displacement & Belonging",
            desc: "Diaspora-community mapping, transnational-identity annotation, migratory-culture analysis, and homeland-relation graphs.",
            icon: "globe2",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "fat-studies",
            name: "Fat Studies",
            tagline: "Body Size & Society",
            desc: "Fat-politics annotation, weight-stigma analysis, body-positive movement mapping, and anti-diet-culture knowledge graphs.",
            icon: "person-heart",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "indigenous-language-revitalization",
            name: "Indigenous Language Revitalisation",
            tagline: "Language & Identity",
            desc: "Endangered-language documentation tools, revitalisation-programme annotation, orthography-development graphs, and community-language knowledge.",
            icon: "chat-heart",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "material-culture-studies",
            name: "Material Culture Studies",
            tagline: "Objects & Meaning",
            desc: "Artefact-biography annotation, object-biography tools, consumption-culture analysis, and material-world knowledge graphs.",
            icon: "box-seam",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "memory-studies",
            name: "Memory Studies",
            tagline: "Collective Memory",
            desc: "Collective-memory annotation, commemoration-site mapping, memorial-culture analysis, and traumatic-memory knowledge graphs.",
            icon: "hourglass-split",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "whiteness-studies",
            name: "Whiteness Studies",
            tagline: "Race & Privilege",
            desc: "White-privilege analysis, racial-formation annotation, colour-blindness critique tools, and anti-racist pedagogy knowledge graphs.",
            icon: "people-fill",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        // Interdisciplinary Science & Mathematics
        QApp {
            id: "biogeochemistry",
            name: "Biogeochemistry",
            tagline: "Earth-Life Chemistry",
            desc: "Nutrient-cycle modelling, isotope-data annotation, earth-system chemistry tools, and biogeochemical-flux knowledge graphs.",
            icon: "recycle",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "bioinformatics",
            name: "Bioinformatics (LA)",
            tagline: "Computational Biology",
            desc: "Sequence-analysis tools, genome-annotation management, pathway-database integration, and biological-data knowledge graphs.",
            icon: "bezier2",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "chemical-physics",
            name: "Chemical Physics",
            tagline: "Quantum Chemistry",
            desc: "Quantum-chemical calculation annotation, spectroscopic-data management, reaction-dynamics modelling, and molecular-property graphs.",
            icon: "lightning",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "computational-linguistics",
            name: "Computational Linguistics",
            tagline: "NLP Science",
            desc: "NLP-experiment annotation, parser-evaluation tools, corpus-linguistic analysis, and computational-language knowledge graphs.",
            icon: "terminal",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "cryptography",
            name: "Cryptography (LA)",
            tagline: "Codes & Ciphers",
            desc: "Historical-cipher annotation, cryptanalysis tools, number-theory education modules, and modern-cryptography knowledge graphs.",
            icon: "lock",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "environmental-chemistry",
            name: "Environmental Chemistry",
            tagline: "Pollutants & Cycles",
            desc: "Pollutant-fate modelling, atmospheric-chemistry annotation, water-quality analysis, and toxicology knowledge graphs.",
            icon: "droplet",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "geochemistry",
            name: "Geochemistry",
            tagline: "Earth's Chemistry",
            desc: "Isotope-system annotation, mineral-composition databases, geochemical-proxy tools, and mantle-chemistry knowledge graphs.",
            icon: "globe",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "mathematical-biology",
            name: "Mathematical Biology",
            tagline: "Math in Life",
            desc: "Reaction-diffusion modelling, neural-network ODE tools, population-genetics analysis, and mathematical-biology knowledge graphs.",
            icon: "flower2",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "mathematical-economics",
            name: "Mathematical Economics",
            tagline: "Formal Economics",
            desc: "General-equilibrium modelling, game-theory annotation, optimisation tools, and mathematical-economics knowledge graphs.",
            icon: "graph-up",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "systems-biology",
            name: "Systems Biology",
            tagline: "Biological Networks",
            desc: "Network-biology annotation, metabolic-flux analysis, signalling-pathway tools, and whole-cell modelling knowledge graphs.",
            icon: "diagram-3-fill",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        // Design, Media & Spatial Studies
        QApp {
            id: "architectural-studies",
            name: "Architectural Studies",
            tagline: "Design & Theory",
            desc: "Design-process annotation, architectural-theory tools, building-performance analysis, and spatial-practice knowledge graphs.",
            icon: "house",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "cyberculture-studies",
            name: "Cyberculture Studies",
            tagline: "Digital Society",
            desc: "Online-community ethnography, platform-politics annotation, digital-identity analysis, and internet-culture knowledge graphs.",
            icon: "wifi",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "environmental-design",
            name: "Environmental Design",
            tagline: "Built Environment",
            desc: "Sustainable-design annotation, urban-environment analysis, place-making tools, and built-environment knowledge graphs.",
            icon: "tree",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "landscape-studies",
            name: "Landscape Studies",
            tagline: "Landscape",
            desc: "Landscape-character annotation, scenic-quality analysis, cultural-landscape mapping, and landscape-ecology knowledge graphs.",
            icon: "image",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "media-ecology",
            name: "Media Ecology",
            tagline: "Media Environments",
            desc: "Media-environment annotation, McLuhan-theory tools, media-bias analysis, and information-ecology knowledge graphs.",
            icon: "broadcast",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "spatial-data-science",
            name: "Spatial Data Science",
            tagline: "GeoData",
            desc: "Geospatial-analysis tools, mapping-workflow annotation, location-intelligence dashboards, and spatial-data knowledge graphs.",
            icon: "map",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "urban-ecology",
            name: "Urban Ecology",
            tagline: "City Ecosystems",
            desc: "Urban-biodiversity surveys, green-infrastructure annotation, urban-heat-island analysis, and city-ecosystem knowledge graphs.",
            icon: "buildings",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "urban-planning-and-design",
            name: "Urban Planning & Design",
            tagline: "City Making",
            desc: "Master-plan annotation, zoning-policy analysis, participatory-planning tools, and urban-design knowledge graphs.",
            icon: "grid",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        // Advanced Critical Theory & Cultural Critique
        QApp {
            id: "affect-theory",
            name: "Affect Theory",
            tagline: "Emotion & Culture",
            desc: "Affective-turn annotation, emotion-politics analysis, body-affect tools, and affect-theory knowledge graphs.",
            icon: "emoji-smile",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "biopolitics",
            name: "Biopolitics",
            tagline: "Life & Power",
            desc: "Biopolitical-theory annotation, biopower analysis, governmentality tools, and life-politics knowledge graphs.",
            icon: "person",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "capital-studies",
            name: "Capital Studies",
            tagline: "Capitalism & Critique",
            desc: "Capital-accumulation analysis, Marxist-theory annotation, financialisation tools, and capitalist-critique knowledge graphs.",
            icon: "currency-dollar",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "critical-disability-studies",
            name: "Critical Disability Studies",
            tagline: "Disability & Power",
            desc: "Crip-theory annotation, ableism-critique tools, disability-justice mapping, and normate-critique knowledge graphs.",
            icon: "person-wheelchair",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "critical-film-studies",
            name: "Critical Film Studies",
            tagline: "Cinema & Theory",
            desc: "Psychoanalytic-film-theory annotation, gaze-theory tools, national-cinema analysis, and critical-cinema knowledge graphs.",
            icon: "camera-reels",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "critical-gentrification-studies",
            name: "Critical Gentrification Studies",
            tagline: "Urban Displacement",
            desc: "Gentrification-process annotation, displacement-mapping tools, anti-gentrification movement graphs, and urban-justice knowledge graphs.",
            icon: "buildings",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "cultural-ecology",
            name: "Cultural Ecology",
            tagline: "Culture & Environment",
            desc: "Human-environment adaptation analysis, cultural-landscape annotation, resource-use modelling, and cultural-ecology knowledge graphs.",
            icon: "tree-fill",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "decolonial-studies",
            name: "Decolonial Studies",
            tagline: "Decolonisation",
            desc: "Colonial-matrix annotation, decolonial-thought tools, epistemic-justice analysis, and decolonisation knowledge graphs.",
            icon: "arrow-counterclockwise",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "eco-critical-theory",
            name: "Eco-Critical Theory",
            tagline: "Nature & Text",
            desc: "Ecocriticism annotation, environmental-literature analysis, nature-writing tools, and eco-critical knowledge graphs.",
            icon: "tree",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "eco-feminism",
            name: "Eco-Feminism",
            tagline: "Gender & Environment",
            desc: "Eco-feminist theory annotation, nature-woman relation analysis, environmental-justice feminist tools, and eco-feminist knowledge graphs.",
            icon: "flower1",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "eco-queer-theory",
            name: "Eco-Queer Theory",
            tagline: "Queering Nature",
            desc: "Queer-ecology annotation, nature-normativity critique tools, eco-queer-practice analysis, and queer-environment knowledge graphs.",
            icon: "rainbow",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "environmental-justice",
            name: "Environmental Justice",
            tagline: "Justice & Environment",
            desc: "Environmental-injustice mapping, sacrifice-zone annotation, EJ-movement history tools, and environmental-racism knowledge graphs.",
            icon: "exclamation-octagon",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "film-philosophy",
            name: "Film Philosophy",
            tagline: "Cinema & Thought",
            desc: "Film-ontology annotation, Deleuze-cinema tools, philosophical-film analysis, and film-philosophy knowledge graphs.",
            icon: "camera-video",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "gender-studies",
            name: "Gender Studies",
            tagline: "Gender Theory",
            desc: "Gender-performance annotation, feminist-theory tools, trans-studies analysis, and gender-knowledge graphs.",
            icon: "gender-ambiguous",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "global-critical-studies",
            name: "Global Critical Studies",
            tagline: "Transnational Critique",
            desc: "Global-south theory annotation, world-system analysis, transnational-feminist tools, and global-justice knowledge graphs.",
            icon: "globe2",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "grassroots-studies",
            name: "Grassroots Studies",
            tagline: "Community Movements",
            desc: "Social-movement annotation, community-organising tools, grassroots-politics analysis, and movement-strategy knowledge graphs.",
            icon: "people",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "grief-studies",
            name: "Grief Studies",
            tagline: "Loss & Mourning",
            desc: "Grief-narrative annotation, mourning-ritual comparison, loss-psychology tools, and bereavement-culture knowledge graphs.",
            icon: "heart-break",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "haunted-humanities",
            name: "Haunted Humanities",
            tagline: "Spectrality & Memory",
            desc: "Spectrality-theory annotation, haunted-landscape mapping, ghost-narrative analysis, and spectral-humanities knowledge graphs.",
            icon: "moon",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "hermeneutics",
            name: "Hermeneutics",
            tagline: "Interpretation",
            desc: "Interpretation-theory annotation, Gadamer and Ricoeur tools, textual-interpretation graphs, and hermeneutic-circle analysis.",
            icon: "book-open",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "historiography",
            name: "Historiography",
            tagline: "Writing History",
            desc: "Historical-method annotation, theory-of-history tools, historiographic-school comparison, and historical-writing knowledge graphs.",
            icon: "pencil-fill",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "ideology-critique",
            name: "Ideology Critique",
            tagline: "False Consciousness",
            desc: "Ideological-form annotation, Althusser and Gramsci tools, hegemony-analysis, and ideology-critique knowledge graphs.",
            icon: "eye-slash",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "indigenous-feminisms",
            name: "Indigenous Feminisms",
            tagline: "Decolonial Gender",
            desc: "Indigenous-feminist theory annotation, land-body-sovereignty analysis, Two-Spirit knowledge tools, and indigenous-gender knowledge graphs.",
            icon: "flower2",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "integral-studies",
            name: "Integral Studies",
            tagline: "Holistic Frameworks",
            desc: "Integral-theory annotation, AQAL-framework tools, developmental-psychology integration, and holistic-knowledge graphs.",
            icon: "grid-3x3-gap",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "intermedia-studies",
            name: "Intermedia Studies",
            tagline: "Media Crossings",
            desc: "Intermedial-relation annotation, medium-specificity analysis, cross-media adaptation tools, and intermedia knowledge graphs.",
            icon: "layers-half",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "landscape-phenomenology",
            name: "Landscape Phenomenology",
            tagline: "Place & Perception",
            desc: "Phenomenological-place annotation, dwelling-theory tools, landscape-experience mapping, and topophilia knowledge graphs.",
            icon: "map-fill",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "liberation-studies",
            name: "Liberation Studies",
            tagline: "Freedom & Justice",
            desc: "Liberation-theology annotation, political-liberation theory tools, freedom-struggle mapping, and liberation knowledge graphs.",
            icon: "unlock",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "literature-and-law",
            name: "Literature & Law",
            tagline: "Narrative & Justice",
            desc: "Legal-narrative annotation, law-in-literature tools, narrative-justice analysis, and law-literature knowledge graphs.",
            icon: "balance-scale",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "materialist-aesthetics",
            name: "Materialist Aesthetics",
            tagline: "Matter & Beauty",
            desc: "New-materialist-theory annotation, matter-affect tools, post-humanist aesthetics, and materialist-aesthetics knowledge graphs.",
            icon: "layers",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "media-theory",
            name: "Media Theory",
            tagline: "Theorising Media",
            desc: "Media-theory annotation, platform-theory tools, algorithmic-culture analysis, and media-archaeology knowledge graphs.",
            icon: "display",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "metamodernism",
            name: "Metamodernism",
            tagline: "After Postmodernism",
            desc: "Metamodern-theory annotation, oscillation-between-modernism tools, sincerity-irony analysis, and metamodern-culture knowledge graphs.",
            icon: "arrow-left-right",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "post-critical-pedagogy",
            name: "Post-Critical Pedagogy",
            tagline: "Education & Affect",
            desc: "Post-critical pedagogy annotation, reparative-reading tools, affective-education analysis, and pedagogy-beyond-critique knowledge graphs.",
            icon: "mortarboard",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "posthumanities",
            name: "Posthumanities",
            tagline: "Beyond the Human",
            desc: "Posthuman-theory annotation, more-than-human-world tools, post-anthropocentric analysis, and posthumanities knowledge graphs.",
            icon: "robot",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "poststructuralism",
            name: "Poststructuralism",
            tagline: "Derrida & Foucault",
            desc: "Deconstruction annotation, discourse-analysis tools, power-knowledge graphs, and poststructuralist theory knowledge bases.",
            icon: "puzzle",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "psychoanalysis",
            name: "Psychoanalysis",
            tagline: "Unconscious",
            desc: "Freudian and Lacanian theory annotation, dream-analysis tools, transference-mapping, and psychoanalytic knowledge graphs.",
            icon: "brain",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "queer-cinema-studies",
            name: "Queer Cinema Studies",
            tagline: "Queer Film",
            desc: "Queer-film-history annotation, new-queer-cinema tools, queer-gaze analysis, and queer-cinema knowledge graphs.",
            icon: "rainbow",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "queer-theory",
            name: "Queer Theory",
            tagline: "Queering",
            desc: "Queer-theory annotation, heteronormativity-critique tools, gender-performativity analysis, and queer-theory knowledge graphs.",
            icon: "gender-ambiguous",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "race-critical-theory",
            name: "Race Critical Theory",
            tagline: "CRT",
            desc: "Critical-race-theory annotation, structural-racism analysis, intersectionality tools, and race-critical knowledge graphs.",
            icon: "people",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "race-studies",
            name: "Race Studies",
            tagline: "Race in Society",
            desc: "Race-formation analysis, racial-categorisation history, anti-racism tools, and race-studies knowledge graphs.",
            icon: "people-fill",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "race-theory",
            name: "Race Theory",
            tagline: "Theorising Race",
            desc: "Race-concept genealogy annotation, racial-capitalism analysis, Afro-pessimism tools, and race-theory knowledge graphs.",
            icon: "diagram-3",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "radical-media-studies",
            name: "Radical Media Studies",
            tagline: "Activist Media",
            desc: "Counter-hegemonic media annotation, alternative-media tools, media-justice analysis, and radical-media knowledge graphs.",
            icon: "broadcast",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "regionalism",
            name: "Regionalism",
            tagline: "Place & Identity",
            desc: "Regional-identity annotation, place-identity analysis, regional-literature tools, and regional-culture knowledge graphs.",
            icon: "pin-map",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "revisionist-critical-theory",
            name: "Revisionist Critical Theory",
            tagline: "Rethinking",
            desc: "Revisionist-theory annotation, second-generation Frankfurt School tools, immanent-critique analysis, and revisionist knowledge graphs.",
            icon: "arrow-repeat",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "rural-studies",
            name: "Rural Studies",
            tagline: "Country Life",
            desc: "Rural-change analysis, agrarian-economy annotation, rural-identity tools, and rural-society knowledge graphs.",
            icon: "tree",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "screen-philosophy",
            name: "Screen Philosophy",
            tagline: "Screen & Thought",
            desc: "Screen-ontology annotation, medium-philosophy tools, digital-screen analysis, and screen-philosophy knowledge graphs.",
            icon: "display-fill",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "site-specificity-theory",
            name: "Site-Specificity Theory",
            tagline: "Art in Place",
            desc: "Site-specific-art annotation, place-responsive practice tools, installation-art analysis, and site-specificity knowledge graphs.",
            icon: "geo",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "social-activism",
            name: "Social Activism",
            tagline: "Change-Making",
            desc: "Activism-history annotation, social-movement-tactics tools, campaign-analysis graphs, and social-change knowledge bases.",
            icon: "megaphone",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "soft-skills-theory",
            name: "Soft Skills Theory",
            tagline: "Interpersonal Competence",
            desc: "Soft-skill taxonomy annotation, emotional-intelligence tools, communication-competence analysis, and professional-development knowledge graphs.",
            icon: "chat-heart",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "spinoza-studies",
            name: "Spinoza Studies",
            tagline: "Spinozist Philosophy",
            desc: "Ethics annotation, affect-theory genealogy, immanence-philosophy tools, and Spinozist knowledge graphs.",
            icon: "infinity",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "structuralism",
            name: "Structuralism",
            tagline: "Deep Structures",
            desc: "Structural-theory annotation, Lévi-Strauss and Saussure tools, sign-system analysis, and structuralism knowledge graphs.",
            icon: "diagram-2-fill",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "trauma-studies",
            name: "Trauma Studies",
            tagline: "Wound & Recovery",
            desc: "Trauma-narrative annotation, vicarious-trauma tools, post-traumatic-testimony analysis, and trauma-studies knowledge graphs.",
            icon: "bandaid",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "urban-theory",
            name: "Urban Theory",
            tagline: "City Thought",
            desc: "Urban-theory annotation, Lefebvre and Harvey tools, right-to-the-city analysis, and urban-theory knowledge graphs.",
            icon: "buildings",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "visual-studies",
            name: "Visual Studies",
            tagline: "Visual Culture",
            desc: "Visuality-theory annotation, image-politics tools, scopic-regime analysis, and visual-studies knowledge graphs.",
            icon: "eye-fill",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "vital-materialism",
            name: "Vital Materialism",
            tagline: "Lively Matter",
            desc: "New-materialist annotation, agentic-matter tools, vibrant-matter analysis, and vital-materialism knowledge graphs.",
            icon: "lightning",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "white-studies",
            name: "White Studies",
            tagline: "Whiteness Scholarship",
            desc: "White-identity annotation, white-privilege analysis, anti-racist pedagogy tools, and whiteness knowledge graphs.",
            icon: "people",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
    ]
}
