use super::{Cat, QApp, Stat};

pub(super) fn apps() -> Vec<QApp> {
    vec![
        QApp {
            id: "animation-and-digital-arts",
            name: "Animation & Digital Arts",
            tagline: "Digital Creation",
            desc: "Animation-history annotation, digital-art process documentation, computational-aesthetics analysis, and media-art knowledge graphs.",
            icon: "play-btn",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "book-arts-and-papermaking",
            name: "Book Arts & Papermaking",
            tagline: "Book Craft",
            desc: "Bookbinding-technique annotation, paper-history cataloguing, letterpress-design tools, and artists-book knowledge graphs.",
            icon: "book",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "ceramics",
            name: "Ceramics",
            tagline: "Clay & Fire",
            desc: "Glaze-chemistry annotation, kiln-log management, ceramic-tradition comparison, and studio-practice documentation.",
            icon: "cup-hot",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "cinematography",
            name: "Cinematography",
            tagline: "Visual Storytelling",
            desc: "Shot-design annotation, lighting-scheme documentation, lens-choice graphs, and cinematographic-style comparison.",
            icon: "camera-video",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "dramaturgy",
            name: "Dramaturgy",
            tagline: "Theatre Research",
            desc: "Play-structure analysis, production-research management, dramaturgical-annotation tools, and theatre-history knowledge graphs.",
            icon: "file-earmark-text",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "musicology",
            name: "Musicology",
            tagline: "Music Scholarship",
            desc: "Score-analysis tools, performance-practice history, music-criticism annotation, and compositional-style knowledge graphs.",
            icon: "music-note-list",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "photography",
            name: "Photography",
            tagline: "Photographic Arts",
            desc: "Photo-archive management, darkroom-technique annotation, documentary-photography analysis, and photographic-history graphs.",
            icon: "camera",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "playwriting",
            name: "Playwriting",
            tagline: "Dramatic Writing",
            desc: "Dramatic-structure annotation, character-arc tools, dialogue-analysis, and play-development workshop management.",
            icon: "pencil",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "printmaking",
            name: "Printmaking",
            tagline: "Print Media",
            desc: "Printmaking-technique annotation, matrix-condition records, edition-management tools, and printmaking-tradition comparison.",
            icon: "printer",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "screenwriting",
            name: "Screenwriting",
            tagline: "Script Craft",
            desc: "Three-act structure annotation, scene-beat management, character-motivation graphs, and script-development tools.",
            icon: "display",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "sculpture",
            name: "Sculpture",
            tagline: "Three-Dimensional Art",
            desc: "Material-process annotation, site-specific documentation, public-art proposal management, and sculpture-history knowledge graphs.",
            icon: "cube",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        // Advanced Sub-Disciplines
        QApp {
            id: "applied-linguistics",
            name: "Applied Linguistics",
            tagline: "Language in Use",
            desc: "Language-acquisition research tools, TESOL-curriculum annotation, discourse-analysis dashboards, and language-policy graphs.",
            icon: "chat-text",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "family-studies",
            name: "Family Studies",
            tagline: "Family & Kinship",
            desc: "Family-structure analysis, kinship-network visualisation, intergenerational-data tools, and family-policy annotation.",
            icon: "house",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "gerontology",
            name: "Gerontology",
            tagline: "Ageing",
            desc: "Healthy-ageing indicator dashboards, elder-care policy annotation, life-course research tools, and social-gerontology graphs.",
            icon: "person-cane",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "penology",
            name: "Penology",
            tagline: "Punishment & Rehabilitation",
            desc: "Incarceration-data analysis, sentencing-policy annotation, rehabilitation-programme evaluation, and prison-reform knowledge graphs.",
            icon: "lock",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "psycholinguistics",
            name: "Psycholinguistics",
            tagline: "Language & Mind",
            desc: "Language-processing experiment annotation, reading-research tools, bilingualism-data management, and aphasia-study graphs.",
            icon: "chat-left-dots",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "social-and-cultural-analysis",
            name: "Social & Cultural Analysis",
            tagline: "Critical Social Theory",
            desc: "Interdisciplinary social-theory annotation, cultural-critique graphs, urban-culture analysis, and power-structure mapping.",
            icon: "diagram-2-fill",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "sociolinguistics",
            name: "Sociolinguistics",
            tagline: "Language & Society",
            desc: "Dialect variation mapping, language-attitude surveys, code-switching annotation, and language-change modelling.",
            icon: "chat-dots",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        // Niche Natural & Physical Sciences
        QApp {
            id: "atmospheric-science",
            name: "Atmospheric Science",
            tagline: "Atmosphere",
            desc: "Weather-data ingestion, atmospheric-chemistry annotation, climate-model comparison, and storm-event cataloguing.",
            icon: "cloud",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "behavioral-ecology",
            name: "Behavioral Ecology",
            tagline: "Behaviour in Nature",
            desc: "Ethogram management, foraging-theory modelling, mating-system analysis, and animal-communication annotation.",
            icon: "bug",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "kinesiology-and-movement-studies",
            name: "Kinesiology",
            tagline: "Movement Science",
            desc: "Biomechanical-data analysis, motor-learning research tools, sport-performance annotation, and exercise-physiology graphs.",
            icon: "person-arms-up",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "marine-biology",
            name: "Marine Biology",
            tagline: "Ocean Life",
            desc: "Marine-species cataloguing, coral-reef survey management, oceanographic-dataset integration, and fish-stock assessment tools.",
            icon: "water",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "materials-science",
            name: "Materials Science",
            tagline: "Matter & Properties",
            desc: "Crystal-structure annotation, mechanical-property databases, materials-characterisation tool integration, and phase-diagram analysis.",
            icon: "grid-3x3",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "meteorology",
            name: "Meteorology",
            tagline: "Weather",
            desc: "Synoptic-chart annotation, forecast-verification tools, extreme-weather event cataloguing, and climate-reanalysis dashboards.",
            icon: "cloud-lightning",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "mycology",
            name: "Mycology",
            tagline: "Fungi",
            desc: "Fungal-specimen cataloguing, mycorrhizal-network analysis, spore-dispersal modelling, and medical-mycology annotation tools.",
            icon: "tree",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "paleontology",
            name: "Paleontology",
            tagline: "Ancient Life",
            desc: "Fossil-occurrence database, stratigraphic-range charts, phylogenetic-placement annotation, and taphonomy-analysis tools.",
            icon: "layers",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "sports-studies",
            name: "Sports Studies",
            tagline: "Sport & Society",
            desc: "Sport-sociology annotation, performance-analytics integration, athlete-welfare policy tools, and sport-media analysis graphs.",
            icon: "trophy",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        // Advanced Philosophical & Theoretical Studies
        QApp {
            id: "aesthetics",
            name: "Aesthetics",
            tagline: "Beauty & Art",
            desc: "Aesthetic-theory annotation, art-ontology construction, taste-philosophy graphs, and cross-cultural beauty-concept comparison.",
            icon: "palette2",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "epistemology",
            name: "Epistemology",
            tagline: "Knowledge & Belief",
            desc: "Belief-network annotation, justification-theory tools, social-epistemology graphs, and knowledge-attribution analysis.",
            icon: "lightbulb",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "metaphysics",
            name: "Metaphysics",
            tagline: "Being & Reality",
            desc: "Ontological-category annotation, modal-reality graphs, persistence-theory tools, and formal-metaphysics knowledge bases.",
            icon: "infinity",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "phenomenology",
            name: "Phenomenology",
            tagline: "Experience",
            desc: "Phenomenological-description annotation, intentionality-graph construction, lived-experience analysis, and husserl/heidegger study tools.",
            icon: "eye",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "philosophy-of-mind",
            name: "Philosophy of Mind",
            tagline: "Consciousness",
            desc: "Consciousness-theory annotation, mental-state taxonomy, qualia-analysis tools, and functionalism-debate knowledge graphs.",
            icon: "brain",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "philosophy-of-religion",
            name: "Philosophy of Religion",
            tagline: "God & Reason",
            desc: "Theism-argument annotation, theodicy-analysis tools, religious-language philosophy, and comparative-religion knowledge graphs.",
            icon: "stars",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "philosophy-of-science",
            name: "Philosophy of Science",
            tagline: "Scientific Method",
            desc: "Scientific-explanation annotation, theory-choice modelling, realism-debate graphs, and demarcation-criterion analysis.",
            icon: "gear-wide",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "social-and-political-philosophy",
            name: "Social & Political Philosophy",
            tagline: "Justice & Society",
            desc: "Social-contract theory annotation, distributive-justice graphs, liberty-concept comparison, and political-legitimacy analysis.",
            icon: "balance-scale",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        // Specialised Religious & Theological Studies
        QApp {
            id: "biblical-studies",
            name: "Biblical Studies",
            tagline: "Scripture",
            desc: "Biblical-text annotation, source-criticism tools, inter-testamental literature graphs, and ancient-Near-East context integration.",
            icon: "book-half",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "buddhist-studies",
            name: "Buddhist Studies",
            tagline: "Buddhism",
            desc: "Pali and Sanskrit text annotation, Buddhist-philosophy graphs, meditation-tradition comparison, and sangha-history mapping.",
            icon: "circle",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "canon-law",
            name: "Canon Law",
            tagline: "Church Law",
            desc: "Canonical-text annotation, ecclesiastical-court record management, council-decree comparison, and church-governance ontology.",
            icon: "file-earmark-check",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "hindu-studies",
            name: "Hindu Studies",
            tagline: "Hinduism",
            desc: "Sanskrit text management, Vedic-tradition comparison, temple-iconography annotation, and Hindu-philosophy knowledge graphs.",
            icon: "triangle",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "islamic-studies",
            name: "Islamic Studies",
            tagline: "Islam",
            desc: "Arabic Quranic annotation, hadith-classification tools, fiqh-comparison graphs, and Islamic-history chronology management.",
            icon: "moon-stars",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "missiology",
            name: "Missiology",
            tagline: "Christian Mission",
            desc: "Mission-history annotation, cross-cultural evangelism analysis, contextualisation-theory graphs, and church-growth research tools.",
            icon: "geo",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "patristics",
            name: "Patristics",
            tagline: "Church Fathers",
            desc: "Patristic-text annotation, council-proceeding management, doctrinal-development graphs, and early-Christian manuscript tools.",
            icon: "journal",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        // Advanced Literary & Media Studies
        QApp {
            id: "arthurian-studies",
            name: "Arthurian Studies",
            tagline: "Arthurian Legend",
            desc: "Arthurian-manuscript cataloguing, legend-variant comparison, chivalry-ideology analysis, and quest-narrative knowledge graphs.",
            icon: "shield",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "comics-and-graphic-novel-studies",
            name: "Comics & Graphic Novel Studies",
            tagline: "Sequential Art",
            desc: "Comics-history annotation, panel-layout analysis, sequential-art theory tools, and graphic-novel knowledge graphs.",
            icon: "image",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "fan-studies",
            name: "Fan Studies",
            tagline: "Fandom & Participation",
            desc: "Fan-community mapping, transformative-works analysis, participatory-culture graphs, and fandom-history annotation.",
            icon: "heart",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "poetry-and-poetics",
            name: "Poetry & Poetics",
            tagline: "Verse & Form",
            desc: "Prosody-analysis tools, poetic-tradition comparison, formal-innovation annotation, and cross-cultural poetics knowledge graphs.",
            icon: "pen",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "science-fiction-and-fantasy-studies",
            name: "Science Fiction & Fantasy",
            tagline: "Speculative Fiction",
            desc: "SF/F genre-history annotation, utopian-narrative analysis, world-building documentation, and speculative-fiction knowledge graphs.",
            icon: "rocket",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "utopian-studies",
            name: "Utopian Studies",
            tagline: "Imagined Futures",
            desc: "Utopian-text annotation, dystopian-critique tools, political-imagination mapping, and alternative-society knowledge graphs.",
            icon: "sun",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        // Deep Linguistics & Semiotics
    ]
}
