use super::{Cat, QApp, Stat};

pub(super) fn apps() -> Vec<QApp> {
    vec![
        // ── Liberal Arts & Humanities ─────────────────────────────────────────
        // Social Sciences
        QApp {
            id: "african-american-studies",
            name: "African American Studies",
            tagline: "Race & Identity",
            desc: "History, culture, and political thought of African American communities; intersections of race, power, and social justice.",
            icon: "people",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "anthropology",
            name: "Anthropology",
            tagline: "Human Cultures",
            desc: "Cross-cultural study of human societies, kinship, ritual, language, and material culture — from fieldwork notes to comparative analysis.",
            icon: "globe2",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "archaeology",
            name: "Archaeology",
            tagline: "Material Past",
            desc: "Excavation data management, artefact cataloguing, stratigraphy analysis, and site-level knowledge-graph synthesis.",
            icon: "search",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "area-and-regional-studies",
            name: "Area & Regional Studies",
            tagline: "World Regions",
            desc: "Interdisciplinary deep-dives into world regions: language, history, politics, economy, and culture woven into a semantic graph.",
            icon: "map",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "cultural-studies",
            name: "Cultural Studies",
            tagline: "Culture & Power",
            desc: "Critical analysis of media, identity, and ideological formations; trace cultural texts through annotated semantic provenance chains.",
            icon: "broadcast",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "economics",
            name: "Economics",
            tagline: "Markets & Policy",
            desc: "Microeconomic and macroeconomic modelling, policy simulation, data visualisation, and institutional analysis tools.",
            icon: "currency-exchange",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "gender-and-sexuality-studies",
            name: "Gender & Sexuality Studies",
            tagline: "Identity & Power",
            desc: "Intersectional analysis of gender, sexuality, and embodiment across historical periods, cultures, and legal regimes.",
            icon: "person-heart",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "geography-human-geography",
            name: "Human Geography",
            tagline: "Space & Society",
            desc: "Spatial analysis of human settlement, migration, place-making, and political territory with GeoSPARQL integration.",
            icon: "geo-alt",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "history",
            name: "History",
            tagline: "Past & Narrative",
            desc: "Primary source management, timeline construction, historiographic comparison, and causal-chain provenance annotation.",
            icon: "clock-history",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "international-relations",
            name: "International Relations",
            tagline: "Global Politics",
            desc: "State-actor modelling, treaty analysis, conflict mapping, and international-law ontology over the NQuin graph.",
            icon: "flag",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "political-science",
            name: "Political Science",
            tagline: "Power & Governance",
            desc: "Comparative politics, electoral systems, legislative text analysis, and deontic-logic policy evaluation.",
            icon: "building",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "psychology",
            name: "Psychology",
            tagline: "Mind & Behaviour",
            desc: "Experimental design, psychometric analysis, cognitive-model simulation, and clinical case management with FHIR integration.",
            icon: "brain",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "sociology",
            name: "Sociology",
            tagline: "Society & Structure",
            desc: "Social-network analysis, survey data processing, inequality measurement, and institutional-change modelling.",
            icon: "diagram-3",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        // Humanities
        QApp {
            id: "art-history",
            name: "Art History",
            tagline: "Visual Culture",
            desc: "Iconographic analysis, provenance tracking, museum-collection integration, and art-movement timeline visualisation.",
            icon: "palette",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "classics",
            name: "Classics",
            tagline: "Ancient World",
            desc: "Greek and Latin text annotation, papyrus transcription, numismatic cataloguing, and ancient-world spatial mapping.",
            icon: "columns-gap",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "comparative-literature",
            name: "Comparative Literature",
            tagline: "World Literature",
            desc: "Cross-cultural literary analysis, translation comparison, genre evolution, and inter-textual citation graphs.",
            icon: "book",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "creative-writing",
            name: "Creative Writing",
            tagline: "Narrative Craft",
            desc: "Story structure tools, character-relationship graphs, revision tracking, and AI-assisted stylometric analysis.",
            icon: "pencil-square",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "dance",
            name: "Dance",
            tagline: "Movement & Form",
            desc: "Choreographic notation, performance annotation, movement-analysis timelines, and embodied-practice knowledge capture.",
            icon: "person-walking",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "english-language-and-literature",
            name: "English Literature",
            tagline: "Language & Text",
            desc: "Literary period analysis, close-reading annotation, stylometric comparison, and canonical text knowledge graphs.",
            icon: "journal-text",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "ethics",
            name: "Ethics",
            tagline: "Moral Philosophy",
            desc: "Normative theory modelling, applied-ethics case analysis, deontic-logic rule authoring, and bioethical deliberation tools.",
            icon: "shield-check",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "film-and-media-studies",
            name: "Film & Media Studies",
            tagline: "Screen Culture",
            desc: "Shot-list annotation, genre taxonomy, auteur-study graphs, and narrative-structure visualisation over media corpora.",
            icon: "camera-reels",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "foreign-languages-and-literatures",
            name: "Foreign Languages",
            tagline: "Multilingual Study",
            desc: "Multilingual corpus management, comparative grammar tools, interlingual citation mapping, and translation memory integration.",
            icon: "translate",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "linguistics",
            name: "Linguistics",
            tagline: "Language Science",
            desc: "Syntactic parsing, phonological analysis, corpus frequency tools, and cross-language typological comparison.",
            icon: "chat-square-text",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "music-history",
            name: "Music History",
            tagline: "Musical Time",
            desc: "Period-style analysis, composer biography graphs, score-metadata annotation, and performance-practice timeline.",
            icon: "music-note-list",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "music-performance",
            name: "Music Performance",
            tagline: "Performative Practice",
            desc: "Rehearsal logging, interpretive annotation, ensemble scheduling, and acoustic-analysis integration.",
            icon: "music-note",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "music-theory",
            name: "Music Theory",
            tagline: "Harmonic Structure",
            desc: "Voice-leading analysis, set-theory tools, Schenkerian reduction aids, and spectral-content annotation.",
            icon: "music-player",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "philosophy",
            name: "Philosophy",
            tagline: "Reason & Inquiry",
            desc: "Argument mapping, logical-form analysis, philosophical-tradition comparison, and modal-logic claim annotation.",
            icon: "lightbulb",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "religion-and-theology",
            name: "Religion & Theology",
            tagline: "Sacred Traditions",
            desc: "Scripture annotation, denominational comparison, ritual-practice mapping, and theological argument graphs.",
            icon: "stars",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "studio-art",
            name: "Studio Art",
            tagline: "Creative Practice",
            desc: "Portfolio management, media-process documentation, critique annotation, and exhibition planning tools.",
            icon: "easel",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "theater-and-drama",
            name: "Theater & Drama",
            tagline: "Performance Arts",
            desc: "Script annotation, production timeline, blocking notation, and dramaturgy research graph.",
            icon: "mask",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        // Natural Sciences
    ]
}
