use super::{Cat, QApp, Stat};

pub(super) fn apps() -> Vec<QApp> {
    vec![
        QApp {
            id: "astronomy",
            name: "Astronomy",
            tagline: "Celestial Objects",
            desc: "Observational log management, coordinate cross-matching, light-curve analysis, and sky-survey data integration.",
            icon: "stars",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "astrophysics",
            name: "Astrophysics",
            tagline: "Cosmic Physics",
            desc: "Spectral-energy distribution fitting, cosmological parameter estimation, gravitational-wave event annotation.",
            icon: "moon-stars",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "biology",
            name: "Biology",
            tagline: "Life Sciences",
            desc: "Organism ontology browsing, experimental protocol management, gene-function annotation, and biodiversity data integration.",
            icon: "flower1",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "botany",
            name: "Botany",
            tagline: "Plant Science",
            desc: "Plant taxonomy, specimen herbarium management, phenology tracking, and chloroplast-genome annotation tools.",
            icon: "tree",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "chemistry",
            name: "Chemistry",
            tagline: "Molecular Science",
            desc: "Reaction-scheme annotation, reagent inventory management, spectra comparison, and lab-notebook integration.",
            icon: "droplet-half",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "earth-science",
            name: "Earth Science",
            tagline: "Geosystems",
            desc: "Stratigraphic column annotation, rock-unit mapping, seismic-event cataloguing, and geochemical data graphs.",
            icon: "globe",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "ecology",
            name: "Ecology",
            tagline: "Ecosystems",
            desc: "Population-dynamics modelling, trophic-network visualisation, biodiversity indices, and habitat-change mapping.",
            icon: "tree-fill",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "environmental-science",
            name: "Environmental Science",
            tagline: "Earth Systems",
            desc: "Pollution monitoring dashboards, climate-data ingestion, carbon-cycle modelling, and remediation-plan annotation.",
            icon: "wind",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "evolutionary-biology",
            name: "Evolutionary Biology",
            tagline: "Life History",
            desc: "Phylogenetic tree construction, molecular-clock calibration, fitness-landscape visualisation, and fossil-record annotation.",
            icon: "diagram-2",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "geology",
            name: "Geology",
            tagline: "Earth Materials",
            desc: "Rock and mineral classification, thin-section image annotation, fault-mapping tools, and geologic-time-scale integration.",
            icon: "layers",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "neuroscience",
            name: "Neuroscience",
            tagline: "Brain & Nervous System",
            desc: "Neural-circuit annotation, EEG/fMRI data ingestion, connectome browsing, and cognitive-function mapping.",
            icon: "cpu",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "oceanography",
            name: "Oceanography",
            tagline: "Ocean Systems",
            desc: "Hydrographic profile management, current-flow modelling, bathymetric mapping, and marine-biodiversity cataloguing.",
            icon: "water",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "physics",
            name: "Physics",
            tagline: "Physical Laws",
            desc: "Experimental-data analysis, symbolic equation annotation, particle-physics event browsing, and lab-notebook integration.",
            icon: "lightning",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "zoology",
            name: "Zoology",
            tagline: "Animal Science",
            desc: "Species taxonomy management, ethogram annotation, zoogeographic distribution mapping, and museum-specimen cataloguing.",
            icon: "bug",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        // Formal Sciences
        QApp {
            id: "computer-science",
            name: "Computer Science",
            tagline: "Computation",
            desc: "Algorithm documentation, complexity analysis, code-artefact provenance, and system-architecture knowledge graphs.",
            icon: "code-slash",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "logic",
            name: "Logic",
            tagline: "Formal Reasoning",
            desc: "Proof management, modal and temporal logic annotation, formal-language tools, and model-checking integration.",
            icon: "braces",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "mathematics",
            name: "Mathematics",
            tagline: "Pure Math",
            desc: "Theorem annotation, proof-graph construction, conjecture tracking, and cross-field mathematical-concept mapping.",
            icon: "calculator",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "statistics",
            name: "Statistics",
            tagline: "Data Analysis",
            desc: "Hypothesis-test documentation, sample-size planning, distribution fitting, and reproducible-analysis provenance.",
            icon: "bar-chart",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        // Interdisciplinary & Area Studies
        QApp {
            id: "american-studies",
            name: "American Studies",
            tagline: "US Culture",
            desc: "Interdisciplinary analysis of US history, literature, politics, and culture through multi-modal semantic lenses.",
            icon: "flag-fill",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "asian-studies",
            name: "Asian Studies",
            tagline: "Asia & Pacific",
            desc: "Comparative study of East, South, and Southeast Asian history, languages, philosophy, and contemporary politics.",
            icon: "compass",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "cognitive-science",
            name: "Cognitive Science",
            tagline: "Mind & Computation",
            desc: "Interdisciplinary mind-model annotation bridging neuroscience, AI, linguistics, and philosophy of mind.",
            icon: "diagram-3-fill",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "communication-studies",
            name: "Communication Studies",
            tagline: "Media & Rhetoric",
            desc: "Rhetorical analysis, media-content coding, public-discourse mapping, and organisational-communication graphs.",
            icon: "megaphone",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "european-studies",
            name: "European Studies",
            tagline: "Europe",
            desc: "EU policy analysis, comparative European history, multilingual corpus tools, and transnational-movement mapping.",
            icon: "geo",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "folklore-and-mythology",
            name: "Folklore & Mythology",
            tagline: "Oral Traditions",
            desc: "Motif cataloguing, narrative-variant comparison, ethnographic fieldnote management, and tradition-diffusion mapping.",
            icon: "book-half",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "global-studies",
            name: "Global Studies",
            tagline: "Globalisation",
            desc: "Transnational flows analysis, global-governance ontology, development-indicator dashboards, and diasporic-community mapping.",
            icon: "globe2",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "history-of-science-and-medicine",
            name: "History of Science",
            tagline: "Science in History",
            desc: "Scientific-revolution timeline, instrument-catalogue annotation, medical-practice history, and laboratory-notebook analysis.",
            icon: "hourglass",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "indigenous-and-native-american-studies",
            name: "Indigenous Studies",
            tagline: "First Peoples",
            desc: "Land-sovereignty mapping, oral-history management, tribal-governance annotation, and language-revitalisation tools.",
            icon: "house-heart",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "jewish-studies",
            name: "Jewish Studies",
            tagline: "Jewish History & Culture",
            desc: "Hebrew and Yiddish text annotation, Talmudic commentary graphs, diaspora-history mapping, and Shoah documentation tools.",
            icon: "star",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "latin-american-studies",
            name: "Latin American Studies",
            tagline: "Latin America",
            desc: "Colonial-archive annotation, social-movement mapping, literary-boom analysis, and indigenous-rights tracking.",
            icon: "map-fill",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "medieval-and-renaissance-studies",
            name: "Medieval & Renaissance",
            tagline: "Pre-Modern Europe",
            desc: "Manuscript cataloguing, codicological description, court-culture analysis, and vernacular-literature knowledge graphs.",
            icon: "shield",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "middle-eastern-studies",
            name: "Middle Eastern Studies",
            tagline: "MENA Region",
            desc: "Arabic, Persian, and Turkish text tools; regional-politics analysis; Islamic-art ontology; and conflict-history mapping.",
            icon: "moon",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "peace-and-conflict-studies",
            name: "Peace & Conflict Studies",
            tagline: "War & Peace",
            desc: "Conflict-event data management, mediation-process annotation, peacebuilding-ontology construction, and reconciliation mapping.",
            icon: "peace",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "rhetoric-and-composition",
            name: "Rhetoric & Composition",
            tagline: "Persuasion & Writing",
            desc: "Argument-structure analysis, genre-theory tools, writing-process annotation, and public-discourse visualisation.",
            icon: "chat-quote",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "science-technology-and-society-sts",
            name: "Science, Technology & Society",
            tagline: "STS",
            desc: "Actor-network mapping, sociotechnical-system analysis, technology-policy annotation, and laboratory-studies tools.",
            icon: "gear",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "urban-studies",
            name: "Urban Studies",
            tagline: "Cities & Space",
            desc: "Urban-data dashboards, neighbourhood-change mapping, planning-document annotation, and housing-policy analysis.",
            icon: "buildings",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        // Applied & Specialised Liberal Arts
        QApp {
            id: "criminology-and-criminal-justice",
            name: "Criminology",
            tagline: "Crime & Justice",
            desc: "Crime-pattern analysis, sentencing-disparity tools, victimology annotation, and criminal-justice-system ontology.",
            icon: "shield-exclamation",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "education-studies",
            name: "Education Studies",
            tagline: "Teaching & Learning",
            desc: "Curriculum-design tools, learning-outcome annotation, pedagogical-theory comparison, and classroom-research management.",
            icon: "mortarboard",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "journalism",
            name: "Journalism",
            tagline: "News & Media",
            desc: "Source management, fact-check provenance, investigative-data annotation, and publication-ethics policy tools.",
            icon: "newspaper",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "library-and-information-science",
            name: "Library & Information Science",
            tagline: "Information Organisation",
            desc: "Cataloguing tools, metadata-standard comparison, information-retrieval benchmarking, and archival-description graphs.",
            icon: "archive",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "museum-studies",
            name: "Museum Studies",
            tagline: "Collections & Curation",
            desc: "Collection-management annotation, exhibition-design tools, conservation-record graphs, and visitor-experience analysis.",
            icon: "bank",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "public-health",
            name: "Public Health",
            tagline: "Population Health",
            desc: "Epidemiological-data dashboards, intervention-efficacy annotation, health-equity analysis, and policy-impact mapping.",
            icon: "heart-pulse",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "public-policy",
            name: "Public Policy",
            tagline: "Policy Analysis",
            desc: "Policy-document annotation, impact-evaluation tools, stakeholder-mapping, and legislative-process knowledge graphs.",
            icon: "file-earmark-text",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        // Emerging Interdisciplinary
        QApp {
            id: "african-studies",
            name: "African Studies",
            tagline: "Africa",
            desc: "Pan-African history, postcolonial politics, oral-literature annotation, and language-distribution mapping across the continent.",
            icon: "globe-americas",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "celtic-studies",
            name: "Celtic Studies",
            tagline: "Celtic Cultures",
            desc: "Old Irish and Welsh text annotation, Celtic-archaeology data management, and druidic tradition comparative analysis.",
            icon: "tree",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "chicano-and-latino-studies",
            name: "Chicano & Latino Studies",
            tagline: "Latino Culture",
            desc: "Borderlands theory annotation, immigration-history mapping, Latinx literature graphs, and activism-archive management.",
            icon: "people-fill",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "digital-humanities",
            name: "Digital Humanities",
            tagline: "Humanities + Tech",
            desc: "Text-encoding tools, corpus-analysis dashboards, digital-archive management, and network-analysis of cultural datasets.",
            icon: "laptop",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "disability-studies",
            name: "Disability Studies",
            tagline: "Ability & Access",
            desc: "Social-model annotation, accessibility-policy analysis, disability-history mapping, and crip-theory knowledge graphs.",
            icon: "person-wheelchair",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "environmental-humanities",
            name: "Environmental Humanities",
            tagline: "Ecology & Culture",
            desc: "Nature-culture relation annotation, environmental-literature analysis, land-ethics philosophy, and ecocritical-theory graphs.",
            icon: "tree-fill",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "ethnomusicology",
            name: "Ethnomusicology",
            tagline: "World Music",
            desc: "Field-recording management, music-culture ethnography, organological classification, and cross-cultural analysis tools.",
            icon: "music-note-beamed",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "food-studies",
            name: "Food Studies",
            tagline: "Foodways & Culture",
            desc: "Culinary-history annotation, food-system mapping, dietary-practice comparison, and gastronomy knowledge graphs.",
            icon: "egg-fried",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "game-studies",
            name: "Game Studies",
            tagline: "Play & Design",
            desc: "Ludology and narratology annotation, game-design document management, player-behaviour analysis, and game-history timelines.",
            icon: "controller",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "human-rights-studies",
            name: "Human Rights Studies",
            tagline: "Rights & Justice",
            desc: "International human-rights law annotation, atrocity-documentation tools, transitional-justice graphs, and treaty-compliance analysis.",
            icon: "person-check",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "medical-humanities",
            name: "Medical Humanities",
            tagline: "Medicine & Culture",
            desc: "Illness-narrative annotation, medical-ethics deliberation, patient-experience graphs, and cross-cultural healing-practice comparison.",
            icon: "hospital",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "oceanic-and-pacific-island-studies",
            name: "Pacific Island Studies",
            tagline: "Oceania",
            desc: "Indigenous Pacific knowledge systems, maritime-navigation history, decolonial-politics annotation, and island-ecology mapping.",
            icon: "water",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "postcolonial-studies",
            name: "Postcolonial Studies",
            tagline: "Empire & After",
            desc: "Colonial-discourse analysis, decolonisation-movement mapping, subaltern-studies annotation, and postcolonial-text comparison.",
            icon: "arrow-counterclockwise",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "poverty-and-inequality-studies",
            name: "Poverty & Inequality",
            tagline: "Social Stratification",
            desc: "Income-distribution analysis, poverty-indicator dashboards, intersectional-inequality mapping, and redistribution-policy tools.",
            icon: "graph-down",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "scandinavian-studies",
            name: "Scandinavian Studies",
            tagline: "Nordic Cultures",
            desc: "Old Norse text annotation, Nordic-welfare-state analysis, Scandinavian-literature graphs, and Viking-age archaeology tools.",
            icon: "snow",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "slavic-studies",
            name: "Slavic Studies",
            tagline: "Slavic Worlds",
            desc: "Cyrillic text management, Slavic-literary tradition graphs, Cold War history annotation, and Orthodox-culture comparison.",
            icon: "bookmarks",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "sound-studies",
            name: "Sound Studies",
            tagline: "Acoustics & Culture",
            desc: "Soundscape annotation, acoustic-ecology mapping, noise-politics analysis, and audio-archive knowledge graphs.",
            icon: "volume-up",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "translation-studies",
            name: "Translation Studies",
            tagline: "Across Languages",
            desc: "Translation-memory management, equivalence-theory annotation, cultural-mediation graphs, and interpreter-training tools.",
            icon: "arrow-left-right",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "visual-and-critical-studies",
            name: "Visual & Critical Studies",
            tagline: "Image & Power",
            desc: "Visual-culture annotation, spectacle-theory graphs, image-politics analysis, and art-world institutional critique.",
            icon: "eye",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "sustainability-studies",
            name: "Sustainability Studies",
            tagline: "Futures",
            desc: "Sustainability-indicator dashboards, SDG-alignment annotation, systems-thinking tools, and circular-economy knowledge graphs.",
            icon: "recycle",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "queer-studies",
            name: "Queer Studies",
            tagline: "LGBTQ+ Scholarship",
            desc: "Queer-theory annotation, LGBTQ+ history mapping, archival-recovery tools, and intersectional identity graphs.",
            icon: "rainbow",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        // Specialised Natural & Social Sciences
    ]
}
