use super::{Cat, QApp, Stat};

pub(super) fn apps() -> Vec<QApp> {
    vec![
        QApp {
            id: "astrobiology",
            name: "Astrobiology",
            tagline: "Life in the Universe",
            desc: "Habitability-parameter analysis, biosignature cataloguing, prebiotic-chemistry annotation, and exoplanet-data integration.",
            icon: "stars",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "behavioral-economics",
            name: "Behavioral Economics",
            tagline: "Decision Science",
            desc: "Cognitive-bias annotation, experimental-design tools, prospect-theory modelling, and nudge-policy evaluation.",
            icon: "graph-up-arrow",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "biomathematics",
            name: "Biomathematics",
            tagline: "Math of Life",
            desc: "Population-growth modelling, epidemiological-ODE solvers, ecological-stability analysis, and biostatistics dashboards.",
            icon: "calculator",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "biophysics",
            name: "Biophysics",
            tagline: "Physics of Life",
            desc: "Membrane-mechanics modelling, single-molecule experiment annotation, protein-folding visualisation, and ion-channel analysis.",
            icon: "lightning-charge",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "demography-and-population-studies",
            name: "Demography",
            tagline: "Population Dynamics",
            desc: "Census-data analysis, fertility/mortality modelling, migration-flow mapping, and demographic-transition visualisation.",
            icon: "people",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "geophysics",
            name: "Geophysics",
            tagline: "Earth Physics",
            desc: "Seismic-wave analysis, magnetic-field mapping, gravity-anomaly processing, and deep-earth structure annotation.",
            icon: "globe",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "planetary-science",
            name: "Planetary Science",
            tagline: "Planets",
            desc: "Planetary-surface mapping, impact-crater cataloguing, atmospheric-composition analysis, and mission-data annotation.",
            icon: "circle",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "political-economy",
            name: "Political Economy",
            tagline: "Power & Markets",
            desc: "State-market relation analysis, comparative-capitalism tools, class-structure modelling, and political-economic ontology.",
            icon: "bank",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "social-psychology",
            name: "Social Psychology",
            tagline: "Self & Society",
            desc: "Group-dynamics experiment annotation, attitude-change modelling, social-identity graphs, and intergroup-relations analysis.",
            icon: "people-fill",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        // Pre-Professional
        QApp {
            id: "art-conservation",
            name: "Art Conservation",
            tagline: "Preservation",
            desc: "Condition-report management, treatment-record annotation, materials-analysis graphs, and preventive-conservation tools.",
            icon: "tools",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "arts-management-and-administration",
            name: "Arts Management",
            tagline: "Cultural Organisations",
            desc: "Non-profit governance annotation, grant-writing tools, cultural-policy analysis, and arts-organisation knowledge graphs.",
            icon: "clipboard-data",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "bioethics",
            name: "Bioethics",
            tagline: "Life & Ethics",
            desc: "Clinical-ethics consultation tools, research-ethics protocol annotation, end-of-life decision graphs, and policy-deliberation support.",
            icon: "heart-pulse",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "curatorial-studies",
            name: "Curatorial Studies",
            tagline: "Exhibition Making",
            desc: "Exhibition-concept development, artist-estate management, institutional-critique annotation, and curatorial-practice graphs.",
            icon: "grid-1x2",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "leadership-studies",
            name: "Leadership Studies",
            tagline: "Leadership",
            desc: "Leadership-theory annotation, organisational-change modelling, team-dynamics analysis, and ethical-leadership frameworks.",
            icon: "person-raised-hand",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "legal-studies",
            name: "Legal Studies",
            tagline: "Law & Society",
            desc: "Case-law annotation, statutory-interpretation tools, legal-reasoning graphs, and comparative-law ontology construction.",
            icon: "file-earmark-check",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "social-work",
            name: "Social Work",
            tagline: "Community Practice",
            desc: "Client-case management tools, community-needs assessment, policy-practice annotation, and social-welfare-system graphs.",
            icon: "house-heart",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        // Highly Specialised Language & Regional Studies
        QApp {
            id: "ancient-near-eastern-studies",
            name: "Ancient Near Eastern Studies",
            tagline: "Mesopotamia & Beyond",
            desc: "Cuneiform-tablet cataloguing, ancient-language tools, archaeological-site management, and ancient Near East ontology.",
            icon: "columns-gap",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "appalachian-studies",
            name: "Appalachian Studies",
            tagline: "Appalachia",
            desc: "Regional-history annotation, oral-tradition management, coal-economy analysis, and Appalachian-culture knowledge graphs.",
            icon: "mountain",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "arctic-studies",
            name: "Arctic Studies",
            tagline: "Polar Regions",
            desc: "Permafrost-data integration, Inuit and Sami knowledge systems, polar-geopolitics annotation, and climate-impact mapping.",
            icon: "snow2",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "balkan-studies",
            name: "Balkan Studies",
            tagline: "Southeast Europe",
            desc: "South Slavic language tools, Ottoman-legacy analysis, Balkan-conflict history annotation, and EU-accession policy tracking.",
            icon: "geo-alt",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "caribbean-studies",
            name: "Caribbean Studies",
            tagline: "Caribbean",
            desc: "Plantation-economy history, creolisation-theory annotation, Caribbean-literature graphs, and island-sovereignty analysis.",
            icon: "water",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "central-asian-studies",
            name: "Central Asian Studies",
            tagline: "Eurasia",
            desc: "Silk Road history, Turkic-language tools, steppe-archaeology annotation, and post-Soviet-transition analysis.",
            icon: "map",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "egyptology",
            name: "Egyptology",
            tagline: "Ancient Egypt",
            desc: "Hieroglyphic-text annotation, papyrus-decipherment tools, monument-catalogue management, and ancient Egyptian chronology.",
            icon: "triangle",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "francophone-studies",
            name: "Francophone Studies",
            tagline: "French-Speaking World",
            desc: "Francophone-literature analysis, colonial-history annotation, African-French-language tools, and la Francophonie policy graphs.",
            icon: "translate",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "germanic-languages-and-literatures",
            name: "Germanic Languages",
            tagline: "Germanic Traditions",
            desc: "Middle High German text tools, German-literary-tradition graphs, Scandinavian-philology annotation, and Germanic-mythology analysis.",
            icon: "book",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "hispanic-and-luso-brazilian-studies",
            name: "Hispanic & Luso-Brazilian Studies",
            tagline: "Iberian World",
            desc: "Spanish and Portuguese text tools, Golden Age literary analysis, Latin American colonial-history annotation, and Lusophone-culture graphs.",
            icon: "globe-americas",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "philology",
            name: "Philology",
            tagline: "Textual Scholarship",
            desc: "Manuscript-stemma construction, critical-edition annotation, textual-variant analysis, and historical-language comparison tools.",
            icon: "journal-text",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "romance-languages-and-literatures",
            name: "Romance Languages",
            tagline: "Romance Traditions",
            desc: "Comparative Romance linguistics, medieval-romance literature annotation, and cross-Romance corpus analysis tools.",
            icon: "chat-square",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "south-asian-studies",
            name: "South Asian Studies",
            tagline: "South Asia",
            desc: "Sanskrit and Pali text tools, South Asian-history annotation, partition-studies mapping, and subcontinental-culture graphs.",
            icon: "compass",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        QApp {
            id: "southeast-asian-studies",
            name: "Southeast Asian Studies",
            tagline: "ASEAN & Beyond",
            desc: "Mainland and island Southeast Asian history, language-diversity mapping, colonial-legacy annotation, and ASEAN-policy graphs.",
            icon: "globe-asia-australia",
            route: None,
            stat: Stat::Active,
            cat: Cat::Academic,
        },
        // Specialised Arts & Performance
    ]
}
