[package]
name = "qualia-cooperative-core"
version = "0.0.40"
edition = "2021"

[dependencies]
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
uuid = { workspace = true, features = ["v4", "serde", "js"] }
chrono = { workspace = true, default-features = true, features = ["serde"] }
sha2 = { workspace = true, default-features = true }
hex = { workspace = true }

[features]
default = []
qualia = []
