// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `parse_file_record`, `parse_sharing`, `sharing_to_json`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`

Future<ChatFileSharing> defaultChatFileSharing({required String sessionId}) =>
    RustApi.instance.api
        .crateApiChatFilesDefaultChatFileSharing(sessionId: sessionId);

Future<AttachChatFileResult> attachChatFile(
        {required String sessionId,
        required String sourcePath,
        required ChatFileSharing sharing}) =>
    RustApi.instance.api.crateApiChatFilesAttachChatFile(
        sessionId: sessionId, sourcePath: sourcePath, sharing: sharing);

Future<List<ChatFileRecord>> listChatFiles({required String sessionId}) =>
    RustApi.instance.api.crateApiChatFilesListChatFiles(sessionId: sessionId);

Future<ChatFileRecord> setChatFileSharing(
        {required String sessionId,
        required String fileId,
        required ChatFileSharing sharing}) =>
    RustApi.instance.api.crateApiChatFilesSetChatFileSharing(
        sessionId: sessionId, fileId: fileId, sharing: sharing);

Future<ChatFilePreview> previewChatFile({required String sourcePath}) =>
    RustApi.instance.api
        .crateApiChatFilesPreviewChatFile(sourcePath: sourcePath);

Future<String> getChatFileLocalPath(
        {required String sessionId,
        required String fileId,
        required String variant}) =>
    RustApi.instance.api.crateApiChatFilesGetChatFileLocalPath(
        sessionId: sessionId, fileId: fileId, variant: variant);

class AttachChatFileResult {
  final ChatFileRecord file;
  final BigInt messageLamport;

  const AttachChatFileResult({
    required this.file,
    required this.messageLamport,
  });

  @override
  int get hashCode => file.hashCode ^ messageLamport.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AttachChatFileResult &&
          runtimeType == other.runtimeType &&
          file == other.file &&
          messageLamport == other.messageLamport;
}

class ChatFilePreview {
  final String mimeType;
  final String extension_;
  final int? pageCount;
  final String textPreview;
  final String parseStatus;
  final String? parseError;
  final String mediaKind;
  final int? imageWidth;
  final int? imageHeight;

  const ChatFilePreview({
    required this.mimeType,
    required this.extension_,
    this.pageCount,
    required this.textPreview,
    required this.parseStatus,
    this.parseError,
    required this.mediaKind,
    this.imageWidth,
    this.imageHeight,
  });

  @override
  int get hashCode =>
      mimeType.hashCode ^
      extension_.hashCode ^
      pageCount.hashCode ^
      textPreview.hashCode ^
      parseStatus.hashCode ^
      parseError.hashCode ^
      mediaKind.hashCode ^
      imageWidth.hashCode ^
      imageHeight.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChatFilePreview &&
          runtimeType == other.runtimeType &&
          mimeType == other.mimeType &&
          extension_ == other.extension_ &&
          pageCount == other.pageCount &&
          textPreview == other.textPreview &&
          parseStatus == other.parseStatus &&
          parseError == other.parseError &&
          mediaKind == other.mediaKind &&
          imageWidth == other.imageWidth &&
          imageHeight == other.imageHeight;
}

class ChatFileRecord {
  final String fileId;
  final String originalName;
  final String mimeType;
  final String extension_;
  final String sha256;
  final BigInt byteSize;
  final int? pageCount;
  final String textPreview;
  final String authorDid;
  final String? authorName;
  final BigInt? messageLamport;
  final BigInt attachedAt;
  final ChatFileSharing sharing;
  final String parseStatus;
  final String? parseError;
  final String mediaKind;
  final int? imageWidth;
  final int? imageHeight;
  final String? thumbnailRelPath;
  final String? visionLexiconId;
  final String? visionFacet;
  final String? visionStatus;

  const ChatFileRecord({
    required this.fileId,
    required this.originalName,
    required this.mimeType,
    required this.extension_,
    required this.sha256,
    required this.byteSize,
    this.pageCount,
    required this.textPreview,
    required this.authorDid,
    this.authorName,
    this.messageLamport,
    required this.attachedAt,
    required this.sharing,
    required this.parseStatus,
    this.parseError,
    required this.mediaKind,
    this.imageWidth,
    this.imageHeight,
    this.thumbnailRelPath,
    this.visionLexiconId,
    this.visionFacet,
    this.visionStatus,
  });

  @override
  int get hashCode =>
      fileId.hashCode ^
      originalName.hashCode ^
      mimeType.hashCode ^
      extension_.hashCode ^
      sha256.hashCode ^
      byteSize.hashCode ^
      pageCount.hashCode ^
      textPreview.hashCode ^
      authorDid.hashCode ^
      authorName.hashCode ^
      messageLamport.hashCode ^
      attachedAt.hashCode ^
      sharing.hashCode ^
      parseStatus.hashCode ^
      parseError.hashCode ^
      mediaKind.hashCode ^
      imageWidth.hashCode ^
      imageHeight.hashCode ^
      thumbnailRelPath.hashCode ^
      visionLexiconId.hashCode ^
      visionFacet.hashCode ^
      visionStatus.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChatFileRecord &&
          runtimeType == other.runtimeType &&
          fileId == other.fileId &&
          originalName == other.originalName &&
          mimeType == other.mimeType &&
          extension_ == other.extension_ &&
          sha256 == other.sha256 &&
          byteSize == other.byteSize &&
          pageCount == other.pageCount &&
          textPreview == other.textPreview &&
          authorDid == other.authorDid &&
          authorName == other.authorName &&
          messageLamport == other.messageLamport &&
          attachedAt == other.attachedAt &&
          sharing == other.sharing &&
          parseStatus == other.parseStatus &&
          parseError == other.parseError &&
          mediaKind == other.mediaKind &&
          imageWidth == other.imageWidth &&
          imageHeight == other.imageHeight &&
          thumbnailRelPath == other.thumbnailRelPath &&
          visionLexiconId == other.visionLexiconId &&
          visionFacet == other.visionFacet &&
          visionStatus == other.visionStatus;
}

class ChatFileSharing {
  final String visibility;
  final bool allowDownload;
  final bool allowLlmContext;
  final bool allowRelaySync;
  final List<String> allowedDids;
  final BigInt? expiresAt;

  const ChatFileSharing({
    required this.visibility,
    required this.allowDownload,
    required this.allowLlmContext,
    required this.allowRelaySync,
    required this.allowedDids,
    this.expiresAt,
  });

  @override
  int get hashCode =>
      visibility.hashCode ^
      allowDownload.hashCode ^
      allowLlmContext.hashCode ^
      allowRelaySync.hashCode ^
      allowedDids.hashCode ^
      expiresAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChatFileSharing &&
          runtimeType == other.runtimeType &&
          visibility == other.visibility &&
          allowDownload == other.allowDownload &&
          allowLlmContext == other.allowLlmContext &&
          allowRelaySync == other.allowRelaySync &&
          allowedDids == other.allowedDids &&
          expiresAt == other.expiresAt;
}
