// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `parse_agent_config`, `parse_outcome_sharing`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`

Future<ParticipantAgentConfig> getLocalAgentConfig(
        {required String sessionId}) =>
    RustApi.instance.api
        .crateApiChatAgentsGetLocalAgentConfig(sessionId: sessionId);

Future<ParticipantAgentConfig> updateAgentOutcomeSharing(
        {required String sessionId, required OutcomeSharingPolicy policy}) =>
    RustApi.instance.api.crateApiChatAgentsUpdateAgentOutcomeSharing(
        sessionId: sessionId, policy: policy);

Future<OutcomeSharingPolicy> getDefaultOutcomeSharing(
        {required String sessionId}) =>
    RustApi.instance.api
        .crateApiChatAgentsGetDefaultOutcomeSharing(sessionId: sessionId);

class OutcomeSharingPolicy {
  final String visibility;
  final bool shareProvenance;
  final bool shareModelAttribution;
  final bool allowPeerLlmContext;
  final List<String> allowedDids;

  const OutcomeSharingPolicy({
    required this.visibility,
    required this.shareProvenance,
    required this.shareModelAttribution,
    required this.allowPeerLlmContext,
    required this.allowedDids,
  });

  @override
  int get hashCode =>
      visibility.hashCode ^
      shareProvenance.hashCode ^
      shareModelAttribution.hashCode ^
      allowPeerLlmContext.hashCode ^
      allowedDids.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OutcomeSharingPolicy &&
          runtimeType == other.runtimeType &&
          visibility == other.visibility &&
          shareProvenance == other.shareProvenance &&
          shareModelAttribution == other.shareModelAttribution &&
          allowPeerLlmContext == other.allowPeerLlmContext &&
          allowedDids == other.allowedDids;
}

class ParticipantAgentConfig {
  final String principalDid;
  final String subAgentDid;
  final String? modelId;
  final String backend;
  final OutcomeSharingPolicy outcomeSharing;
  final BigInt updatedAt;

  const ParticipantAgentConfig({
    required this.principalDid,
    required this.subAgentDid,
    this.modelId,
    required this.backend,
    required this.outcomeSharing,
    required this.updatedAt,
  });

  @override
  int get hashCode =>
      principalDid.hashCode ^
      subAgentDid.hashCode ^
      modelId.hashCode ^
      backend.hashCode ^
      outcomeSharing.hashCode ^
      updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ParticipantAgentConfig &&
          runtimeType == other.runtimeType &&
          principalDid == other.principalDid &&
          subAgentDid == other.subAgentDid &&
          modelId == other.modelId &&
          backend == other.backend &&
          outcomeSharing == other.outcomeSharing &&
          updatedAt == other.updatedAt;
}
