// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

BigInt registerQappManifest({required QappManifest manifest}) =>
    RustApi.instance.api
        .crateApiQappApiRegisterQappManifest(manifest: manifest);

BigInt registerQappFromInstalledManifest({required String qappName}) =>
    RustApi.instance.api
        .crateApiQappApiRegisterQappFromInstalledManifest(qappName: qappName);

BigInt qappIdHash({required String appId}) =>
    RustApi.instance.api.crateApiQappApiQappIdHash(appId: appId);

Uint8List compileAnatomyWildcardQuery() =>
    RustApi.instance.api.crateApiQappApiCompileAnatomyWildcardQuery();

Float32List executeQappScopedQuery(
        {required BigInt appIdHash, required List<int> queryBytecode}) =>
    RustApi.instance.api.crateApiQappApiExecuteQappScopedQuery(
        appIdHash: appIdHash, queryBytecode: queryBytecode);

/// Zero-copy friendly result: fixed scratch buffer length + values copied once for Dart.
Float32List executeQappScopedQueryZeroAlloc(
        {required BigInt appIdHash, required List<int> queryBytecode}) =>
    RustApi.instance.api.crateApiQappApiExecuteQappScopedQueryZeroAlloc(
        appIdHash: appIdHash, queryBytecode: queryBytecode);

BigInt submitDicomIngest(
        {required String filePath, required BigInt patientDidHash}) =>
    RustApi.instance.api.crateApiQappApiSubmitDicomIngest(
        filePath: filePath, patientDidHash: patientDidHash);

int dicomIngestStatus({required BigInt jobId}) =>
    RustApi.instance.api.crateApiQappApiDicomIngestStatus(jobId: jobId);

Uint8List executeDicomVolumeQuery(
        {required BigInt patientDidHash, required BigInt seriesHash}) =>
    RustApi.instance.api.crateApiQappApiExecuteDicomVolumeQuery(
        patientDidHash: patientDidHash, seriesHash: seriesHash);

String evalComorbidityJsonFromDaemon(
        {required BigInt patientDidHash, required BigInt targetOrganHash}) =>
    RustApi.instance.api.crateApiQappApiEvalComorbidityJsonFromDaemon(
        patientDidHash: patientDidHash, targetOrganHash: targetOrganHash);

String? installedQappVersion({required String qappName}) => RustApi.instance.api
    .crateApiQappApiInstalledQappVersion(qappName: qappName);

String checkQappUpdate({required String qappName}) =>
    RustApi.instance.api.crateApiQappApiCheckQappUpdate(qappName: qappName);

String checkQappUpdateFromPath(
        {required String qappName, required String sourcePath}) =>
    RustApi.instance.api.crateApiQappApiCheckQappUpdateFromPath(
        qappName: qappName, sourcePath: sourcePath);

String listQappUpdateOffers() =>
    RustApi.instance.api.crateApiQappApiListQappUpdateOffers();

String applyQappUpdate({required String qappName}) =>
    RustApi.instance.api.crateApiQappApiApplyQappUpdate(qappName: qappName);

String applyQappUpdateFromPath(
        {required String qappName, required String sourcePath}) =>
    RustApi.instance.api.crateApiQappApiApplyQappUpdateFromPath(
        qappName: qappName, sourcePath: sourcePath);

String executionErrorLabel({required String code}) =>
    RustApi.instance.api.crateApiQappApiExecutionErrorLabel(code: code);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<QappManifest>>
abstract class QappManifest implements RustOpaqueInterface {}
