// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `default_gguf`, `load_yaml`, `resolved_url`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `RawDownload`, `RawLLM`, `RawOntology`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`

/// Load all LLM entries from `resources/llms.yaml`.
///
/// Returns an empty vec if the catalog file cannot be read — the UI should
/// surface this as "catalog not found" rather than crashing.
Future<List<LLMResource>> loadLlmResources() =>
    RustApi.instance.api.crateApiResourceCatalogLoadLlmResources();

/// Load all ontology entries from `resources/ontologies.yaml`.
Future<List<OntologyResource>> loadOntologyResources() =>
    RustApi.instance.api.crateApiResourceCatalogLoadOntologyResources();

/// Initiate a GGUF model download.
///
/// The full download pipeline (streaming fetch → GGufSharder pointer map →
/// WAL provenance Quin → CapabilityProfile) is implemented in
/// `qualia-cli resources download <id>`. This function invokes that CLI
/// command as a subprocess so the async I/O runs in the CLI's tokio runtime.
Future<String> downloadLlm({required String id}) =>
    RustApi.instance.api.crateApiResourceCatalogDownloadLlm(id: id);

/// Initiate an ontology download + .q42 import.
///
/// Full pipeline: streaming fetch → `ingest::streaming_import_rdf` → WAL
/// provenance Quin. Implemented in `qualia-cli resources import-ontology <id>`.
Future<String> importOntology({required String id}) =>
    RustApi.instance.api.crateApiResourceCatalogImportOntology(id: id);

class LLMResource {
  final String id;
  final String name;
  final String? provider;

  /// Always `"gguf"` for Qualia-compatible models.
  final String format;
  final String? quantization;
  final int? sizeMb;
  final int? ramEstimateMb;
  final String? license;
  final List<String>? tags;
  final List<String>? recommendedFor;

  /// Resolved download URL (HuggingFace or direct).
  final String? downloadUrl;
  final String? notes;

  const LLMResource({
    required this.id,
    required this.name,
    this.provider,
    required this.format,
    this.quantization,
    this.sizeMb,
    this.ramEstimateMb,
    this.license,
    this.tags,
    this.recommendedFor,
    this.downloadUrl,
    this.notes,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      provider.hashCode ^
      format.hashCode ^
      quantization.hashCode ^
      sizeMb.hashCode ^
      ramEstimateMb.hashCode ^
      license.hashCode ^
      tags.hashCode ^
      recommendedFor.hashCode ^
      downloadUrl.hashCode ^
      notes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LLMResource &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          provider == other.provider &&
          format == other.format &&
          quantization == other.quantization &&
          sizeMb == other.sizeMb &&
          ramEstimateMb == other.ramEstimateMb &&
          license == other.license &&
          tags == other.tags &&
          recommendedFor == other.recommendedFor &&
          downloadUrl == other.downloadUrl &&
          notes == other.notes;
}

class OntologyResource {
  final String id;
  final String name;
  final String? acronym;
  final String? domain;
  final String format;
  final int? sizeEstimateMb;
  final String? license;
  final String? downloadUrl;
  final String? notes;

  const OntologyResource({
    required this.id,
    required this.name,
    this.acronym,
    this.domain,
    required this.format,
    this.sizeEstimateMb,
    this.license,
    this.downloadUrl,
    this.notes,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      acronym.hashCode ^
      domain.hashCode ^
      format.hashCode ^
      sizeEstimateMb.hashCode ^
      license.hashCode ^
      downloadUrl.hashCode ^
      notes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OntologyResource &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          acronym == other.acronym &&
          domain == other.domain &&
          format == other.format &&
          sizeEstimateMb == other.sizeEstimateMb &&
          license == other.license &&
          downloadUrl == other.downloadUrl &&
          notes == other.notes;
}
