// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `parse_profile`, `parse_sharing`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`

Future<UserProfile> getUserProfile() =>
    RustApi.instance.api.crateApiSocialApiGetUserProfile();

Future<UserProfile> saveUserProfile({required UserProfile profile}) =>
    RustApi.instance.api.crateApiSocialApiSaveUserProfile(profile: profile);

Future<ConnectInviteSummary> generateConnectInvite({String? frontDoorId}) =>
    RustApi.instance.api
        .crateApiSocialApiGenerateConnectInvite(frontDoorId: frontDoorId);

Future<ChatContact> acceptConnectInvite({required String input}) =>
    RustApi.instance.api.crateApiSocialApiAcceptConnectInvite(input: input);

Future<ChatContact> updateChatContactCategories(
        {required String contactDid, required List<String> categories}) =>
    RustApi.instance.api.crateApiSocialApiUpdateChatContactCategories(
        contactDid: contactDid, categories: categories);

Future<List<ChatContact>> listChatContacts() =>
    RustApi.instance.api.crateApiSocialApiListChatContacts();

class ChatContact {
  final String actorId;
  final String displayName;
  final String did;
  final String source;
  final BigInt addedAt;
  final List<String> categories;

  const ChatContact({
    required this.actorId,
    required this.displayName,
    required this.did,
    required this.source,
    required this.addedAt,
    required this.categories,
  });

  @override
  int get hashCode =>
      actorId.hashCode ^
      displayName.hashCode ^
      did.hashCode ^
      source.hashCode ^
      addedAt.hashCode ^
      categories.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChatContact &&
          runtimeType == other.runtimeType &&
          actorId == other.actorId &&
          displayName == other.displayName &&
          did == other.did &&
          source == other.source &&
          addedAt == other.addedAt &&
          categories == other.categories;
}

class ConnectInviteSummary {
  final String code;
  final String inviteJson;
  final String mailtoUrl;
  final String inviterDid;
  final BigInt expiresAt;

  const ConnectInviteSummary({
    required this.code,
    required this.inviteJson,
    required this.mailtoUrl,
    required this.inviterDid,
    required this.expiresAt,
  });

  @override
  int get hashCode =>
      code.hashCode ^
      inviteJson.hashCode ^
      mailtoUrl.hashCode ^
      inviterDid.hashCode ^
      expiresAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ConnectInviteSummary &&
          runtimeType == other.runtimeType &&
          code == other.code &&
          inviteJson == other.inviteJson &&
          mailtoUrl == other.mailtoUrl &&
          inviterDid == other.inviterDid &&
          expiresAt == other.expiresAt;
}

class SharingPolicy {
  final bool shareDisplayName;
  final bool sharePublicDid;
  final bool shareActiveModel;
  final bool shareLlmOutcomes;
  final bool shareOntologyScope;
  final bool shareInstalledQapps;
  final bool shareDaemonStatus;
  final bool allowGroupChatInvites;
  final bool allowDirectoryLookup;
  final bool allowEmailInvites;

  const SharingPolicy({
    required this.shareDisplayName,
    required this.sharePublicDid,
    required this.shareActiveModel,
    required this.shareLlmOutcomes,
    required this.shareOntologyScope,
    required this.shareInstalledQapps,
    required this.shareDaemonStatus,
    required this.allowGroupChatInvites,
    required this.allowDirectoryLookup,
    required this.allowEmailInvites,
  });

  @override
  int get hashCode =>
      shareDisplayName.hashCode ^
      sharePublicDid.hashCode ^
      shareActiveModel.hashCode ^
      shareLlmOutcomes.hashCode ^
      shareOntologyScope.hashCode ^
      shareInstalledQapps.hashCode ^
      shareDaemonStatus.hashCode ^
      allowGroupChatInvites.hashCode ^
      allowDirectoryLookup.hashCode ^
      allowEmailInvites.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SharingPolicy &&
          runtimeType == other.runtimeType &&
          shareDisplayName == other.shareDisplayName &&
          sharePublicDid == other.sharePublicDid &&
          shareActiveModel == other.shareActiveModel &&
          shareLlmOutcomes == other.shareLlmOutcomes &&
          shareOntologyScope == other.shareOntologyScope &&
          shareInstalledQapps == other.shareInstalledQapps &&
          shareDaemonStatus == other.shareDaemonStatus &&
          allowGroupChatInvites == other.allowGroupChatInvites &&
          allowDirectoryLookup == other.allowDirectoryLookup &&
          allowEmailInvites == other.allowEmailInvites;
}

class UserProfile {
  final String displayName;
  final String? bio;
  final String publicDid;
  final String? activeFrontDoorId;
  final String? relayBaseUrl;
  final SharingPolicy sharing;
  final BigInt updatedAt;

  const UserProfile({
    required this.displayName,
    this.bio,
    required this.publicDid,
    this.activeFrontDoorId,
    this.relayBaseUrl,
    required this.sharing,
    required this.updatedAt,
  });

  @override
  int get hashCode =>
      displayName.hashCode ^
      bio.hashCode ^
      publicDid.hashCode ^
      activeFrontDoorId.hashCode ^
      relayBaseUrl.hashCode ^
      sharing.hashCode ^
      updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UserProfile &&
          runtimeType == other.runtimeType &&
          displayName == other.displayName &&
          bio == other.bio &&
          publicDid == other.publicDid &&
          activeFrontDoorId == other.activeFrontDoorId &&
          relayBaseUrl == other.relayBaseUrl &&
          sharing == other.sharing &&
          updatedAt == other.updatedAt;
}
