use anyhow::Result;
use reqwest::blocking::get;
use serde::Deserialize;
use std::fs::File;
use std::io::Write;

const SHOELACE_CEM_URL: &str = "https://unpkg.com/@shoelace-style/shoelace/dist/custom-elements.json";

#[derive(Debug, Deserialize)]
struct CustomElementsManifest {
    modules: Vec<Module>,
}

#[derive(Debug, Deserialize)]
struct Module {
    declarations: Option<Vec<Declaration>>,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
struct Declaration {
    kind: String,
    name: String,
    custom_element: Option<bool>,
    tag_name: Option<String>,
    members: Option<Vec<Member>>,
}

#[derive(Debug, Deserialize)]
struct Member {
    kind: String,
    name: String,
    #[serde(rename = "type")]
    member_type: Option<TypeDef>,
    default: Option<String>,
}

#[derive(Debug, Deserialize)]
struct TypeDef {
    text: String,
}

fn map_ts_type_to_rust(ts_type: &str) -> &'static str {
    // A simplistic mapping to no_std compatible types where possible
    match ts_type {
        "boolean" => "bool",
        "number" => "f64", // Using f64 as a safe default for JS numbers
        "string" => "String",
        _ if ts_type.contains('|') => "String", // For union strings like 'primary' | 'success'
        _ => "String", // Fallback
    }
}

fn sanitize_ident(name: &str) -> String {
    let mut safe = name.replace('-', "_");
    // Rust keywords check
    if ["type", "for", "loop", "match", "let", "const", "mut", "fn", "struct", "enum"].contains(&safe.as_str()) {
        safe = format!("r#{}", safe);
    }
    safe
}

fn main() -> Result<()> {
    println!("Fetching Shoelace Custom Elements Manifest...");
    let response = get(SHOELACE_CEM_URL)?;
    let manifest: CustomElementsManifest = response.json()?;

    let out_file_path = "generated_dioxus_components.rs";
    let mut out = File::create(out_file_path)?;

    writeln!(out, "// AUTO-GENERATED BY WEBIZEN-COMPONENT-HARVESTER")?;
    writeln!(out, "// These components wrap Shoelace Custom Elements in Dioxus macros.\n")?;
    writeln!(out, "#![allow(non_snake_case)]")?;
    writeln!(out, "use dioxus::prelude::*;")?;
    writeln!(out, "use core::option::Option;\n")?;

    for module in manifest.modules {
        if let Some(declarations) = module.declarations {
            for decl in declarations {
                if decl.kind == "class" && decl.custom_element == Some(true) {
                    if let Some(tag_name) = &decl.tag_name {
                        generate_dioxus_macro(&mut out, &decl, tag_name)?;
                    }
                }
            }
        }
    }

    println!("Successfully generated Dioxus components to {}", out_file_path);
    Ok(())
}

fn generate_dioxus_macro(out: &mut File, decl: &Declaration, tag_name: &str) -> Result<()> {
    writeln!(out, "/// Dioxus wrapper for `{}`", tag_name)?;
    writeln!(out, "#[component]")?;
    writeln!(out, "pub fn {}(", decl.name)?;
    
    // Properties
    let mut props = Vec::new();
    if let Some(members) = &decl.members {
        for member in members {
            if member.kind == "field" && !member.name.starts_with('_') {
                let rust_type = if let Some(t) = &member.member_type {
                    map_ts_type_to_rust(&t.text)
                } else {
                    "String"
                };
                
                let safe_name = sanitize_ident(&member.name);
                writeln!(out, "    {}: Option<{}>,", safe_name, rust_type)?;
                props.push((safe_name, member.name.clone()));
            }
        }
    }
    
    // Standard Dioxus children
    writeln!(out, "    children: Element,")?;
    writeln!(out, ") -> Element {{")?;
    writeln!(out, "    rsx! {{")?;
    writeln!(out, "        {} {{", tag_name)?;
    
    // Inject QualiaTheme mappings to strip native Shoelace colors
    writeln!(out, "            style: \"--sl-color-primary-500: var(--qualia-primary); --sl-color-primary-600: var(--qualia-primary-hover); --sl-color-success-500: var(--qualia-success); --sl-color-danger-500: var(--qualia-danger); --sl-color-neutral-500: var(--qualia-neutral); --sl-color-neutral-0: var(--qualia-bg);\",")?;
    
    // Pass properties to RSX
    for (safe_name, orig_name) in props {
        // Dioxus requires string interpolation or raw attributes for custom elements
        // if they are not standard HTML.
        writeln!(out, "            \"{orig_name}\": {safe_name}.unwrap_or_default(),")?;
    }
    
    writeln!(out, "            {{children}}")?;
    writeln!(out, "        }}")?;
    writeln!(out, "    }}")?;
    writeln!(out, "}}\n")?;
    
    Ok(())
}
