//! Compute-graph IR (a typed DAG) — the backend-portable representation the forge lowers
//! to every target in one pass. See [`docs/plans/dag-ir-forge.md`].
//!
//! # Phase 1 (this slice)
//!
//! Establishes the *spine*: the graph types, a topological [`lower_graph`] walk, the
//! [`Lowerer`] visitor trait (one method per op-class), and the [`KernelSpec::to_graph`]
//! bridge for the function-backed WGSL kernels (`gemm`/`gemv`/`fft`). The WGSL leaf
//! emission **delegates** to the proven `emit_*_wgsl` functions, so the generated bytes
//! are identical *by construction* (the certify-cache `source_hash` is unchanged). Native
//! from-scratch graph templates replace the delegations in later phases.
//!
//! The full op-node vocabulary is fixed here (the enum is the contract); only the seed
//! arms have a real lowering today — the rest lower to an explicit `Err`, never a silent
//! no-op.
//!
//! Build-time note: the in-memory graph uses `Vec` (this is emit-time construction, not
//! the runtime zero-copy NQuin ABI). The zero-copy quin encoding is Phase 6.

use super::core::KernelSpec;
use crate::wgsl_forge::{ForgeError, Schedule};

/// Maximum data-flow inputs to a single node.
pub const MAX_IN: usize = 4;

/// Arena index of a node within a [`ComputeGraph`]. [`NodeId::EXTERNAL`] marks a graph
/// input (a [`TensorRef`] produced outside the graph).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct NodeId(pub u32);

impl NodeId {
    /// Sentinel producer for a tensor that enters the graph from outside.
    pub const EXTERNAL: NodeId = NodeId(u32::MAX);
}

/// Identifies one output tensor of a producing node (nodes may emit more than one later).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct TensorId(pub u32);

/// Fixed-rank (≤4) tensor shape — no `Vec`, so a [`TensorRef`] stays `Copy`. A dim of `0`
/// means "runtime-parameterized" (resolved from a params buffer at dispatch — e.g. GEMM's
/// `M`/`N`/`K`), which is how the dimension-independent WGSL kernels are represented.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct Shape {
    pub dims: [u32; 4],
    pub rank: u8,
}

impl Shape {
    /// A rank-0 scalar.
    pub fn scalar() -> Self {
        Shape { dims: [1, 1, 1, 1], rank: 0 }
    }

    /// Build from a slice of up to 4 dims (extra dims are dropped).
    pub fn new(dims: &[u32]) -> Self {
        let mut d = [1u32; 4];
        let rank = dims.len().min(4);
        d[..rank].copy_from_slice(&dims[..rank]);
        Shape { dims: d, rank: rank as u8 }
    }

    /// Product of the declared dims (0 if any runtime-parameterized dim is present).
    pub fn elements(&self) -> u64 {
        self.dims
            .iter()
            .take(self.rank.max(1) as usize)
            .map(|&x| x as u64)
            .product()
    }
}

/// Element type of a tensor edge.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum DType {
    F32,
    F16,
    U32,
    Q4K,
    Q8_0,
    Ternary,
}

/// Storage layout of a tensor edge (row-major dense for now).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Layout {
    RowMajor,
}

/// A typed data-flow edge: the `tensor`-th output of `producer`, with its shape/dtype.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct TensorRef {
    pub producer: NodeId,
    pub tensor: TensorId,
    pub shape: Shape,
    pub dtype: DType,
    pub layout: Layout,
}

impl TensorRef {
    /// A graph input produced outside the graph.
    pub fn external(shape: Shape, dtype: DType) -> Self {
        TensorRef {
            producer: NodeId::EXTERNAL,
            tensor: TensorId(0),
            shape,
            dtype,
            layout: Layout::RowMajor,
        }
    }

    /// A graph input identified by index `idx` — the executor supplies its data as
    /// `externals[idx]`. Use this (not [`external`](Self::external)) when a graph has more
    /// than one input (e.g. an FFN block's activations + weight matrices).
    pub fn input(idx: u32, shape: Shape, dtype: DType) -> Self {
        TensorRef {
            producer: NodeId::EXTERNAL,
            tensor: TensorId(idx),
            shape,
            dtype,
            layout: Layout::RowMajor,
        }
    }
}

/// Elementwise function kinds. Phase 1 carries the affine subset; the LLM kit
/// (Silu/Gelu/Exp/RecipSqrt/…) lands in Phase 3.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum EwKind {
    Mul,
    Add,
    Sub,
    Div,
    Fma,
    Scale,
    Bias,
    Silu,
    Gelu,
    Relu,
    Exp,
    RecipSqrt,
    Recip,
}

/// Reduction kinds for [`OpNode::Reduce`].
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum RedKind {
    Sum,
    Max,
    Mean,
    L2,
}

/// Axis selector for reductions / softmax / stencils.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Axis {
    Last,
    Penultimate,
    Index(u8),
}

/// Stencil neighbourhood kind ([`OpNode::Stencil`], Phase 7).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum StencilKind {
    Laplacian,
    Divergence,
    Advection,
    RopePair,
}

/// Scatter-accumulate reduction ([`OpNode::ScatterAccum`], Phase 7).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum AccumKind {
    Add,
    Max,
}

/// Spatial-proximity query kind ([`OpNode::Neighbor`], Phase 7 — RT-backed).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum NbKind {
    /// Fixed-radius nearest neighbours.
    Frnn,
    /// k nearest neighbours.
    Knn,
    /// All within range.
    Range,
}

/// How a >3-D `Neighbor` query is encoded into the 3-D BVH (or refused → grid fallback).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum NeighborEnc {
    /// Native 3-D points (no projection).
    Native3D,
    /// Project to 3-D before building the BVH (method is a Phase-7 detail).
    Project,
}

/// An op-CLASS and its compile-time payload — the node label of the compute DAG. Twelve
/// arms by design (plan §2). Seed arms (`Elementwise`/`MatMul`/`Gemv`/`Fft`) have a real
/// lowering today; the rest are declared so the vocabulary is fixed, and lower to an
/// explicit `Err` until their phase builds them.
#[derive(Debug, Clone, Copy, PartialEq)]
pub enum OpNode {
    Elementwise { f: EwKind },
    MatMul { m: u32, n: u32, k: u32, tc: bool, trans_b: bool },
    Gemv { m: u32, n: u32 },
    Fft { len: u32, inverse: bool },
    Reduce { op: RedKind, axis: Axis },
    GatherDequant { scheme: DType, block: u32 },
    Broadcast { shape: Shape },
    Softmax { axis: Axis },
    Stencil { kind: StencilKind, halo: u32, axis: Axis },
    ScatterAccum { op: AccumKind },
    Neighbor { kind: NbKind, k_or_r: f32, dims: u8, enc: NeighborEnc },
}

/// One node of a [`ComputeGraph`]: an op, its input edges, its single output edge, and a
/// per-node [`Schedule`].
#[derive(Debug, Clone, PartialEq)]
pub struct GraphNode {
    pub op: OpNode,
    pub ins: [Option<TensorRef>; MAX_IN],
    pub n_in: u8,
    pub out: TensorRef,
    pub sched: Schedule,
}

/// A directed acyclic compute graph. Acyclic **by construction**: [`ComputeGraph::push`]
/// only accepts inputs that reference already-added nodes (or `EXTERNAL`), so insertion
/// order is a valid topological order. `nodes[i].out.producer == NodeId(i)`.
#[derive(Debug, Clone, Default)]
pub struct ComputeGraph {
    pub nodes: Vec<GraphNode>,
    pub outputs: Vec<NodeId>,
}

impl ComputeGraph {
    /// Empty graph.
    pub fn new() -> Self {
        Self::default()
    }

    /// Append a node and return a [`TensorRef`] to its output. Enforces:
    /// - at most [`MAX_IN`] inputs;
    /// - every non-external input references an **already-added** node (→ acyclic, and
    ///   insertion order is topological);
    /// - each input edge's declared shape/dtype matches its producer's output (shape
    ///   compatibility) — runtime-parameterized dims (`0`) are treated as wildcards.
    pub fn push(
        &mut self,
        op: OpNode,
        ins: &[TensorRef],
        out_shape: Shape,
        out_dtype: DType,
        sched: Schedule,
    ) -> Result<TensorRef, ForgeError> {
        if ins.len() > MAX_IN {
            return Err(ForgeError::Emission(format!(
                "ComputeGraph::push: {} inputs exceeds MAX_IN={MAX_IN}",
                ins.len()
            )));
        }
        for inp in ins {
            if inp.producer == NodeId::EXTERNAL {
                continue;
            }
            let pidx = inp.producer.0 as usize;
            if pidx >= self.nodes.len() {
                return Err(ForgeError::Emission(
                    "ComputeGraph::push: input references a non-existent/future node (would create a cycle)".to_string(),
                ));
            }
            let prod_out = &self.nodes[pidx].out;
            if prod_out.dtype != inp.dtype || !shapes_compatible(prod_out.shape, inp.shape) {
                return Err(ForgeError::Emission(
                    "ComputeGraph::push: input edge shape/dtype mismatch vs producer output".to_string(),
                ));
            }
        }
        let id = NodeId(self.nodes.len() as u32);
        let out = TensorRef {
            producer: id,
            tensor: TensorId(0),
            shape: out_shape,
            dtype: out_dtype,
            layout: Layout::RowMajor,
        };
        let mut arr: [Option<TensorRef>; MAX_IN] = [None; MAX_IN];
        for (slot, inp) in arr.iter_mut().zip(ins.iter()) {
            *slot = Some(*inp);
        }
        self.nodes.push(GraphNode {
            op,
            ins: arr,
            n_in: ins.len() as u8,
            out,
            sched,
        });
        Ok(out)
    }

    /// Mark a tensor as a graph output.
    pub fn mark_output(&mut self, t: TensorRef) {
        self.outputs.push(t.producer);
    }

    /// Number of nodes.
    pub fn len(&self) -> usize {
        self.nodes.len()
    }

    /// Whether the graph has no nodes.
    pub fn is_empty(&self) -> bool {
        self.nodes.is_empty()
    }
}

/// Two shapes are compatible if equal, or if either is runtime-parameterized (any dim 0)
/// — the dimension-independent kernels (GEMM/GEMV/FFT read dims from a params buffer) use
/// `0` as a wildcard, so a strict equality check would wrongly reject them.
fn shapes_compatible(a: Shape, b: Shape) -> bool {
    if a == b {
        return true;
    }
    let dynamic = |s: &Shape| s.dims.iter().any(|&d| d == 0);
    dynamic(&a) || dynamic(&b)
}

/// A backend code generator. `lower_graph` calls exactly one method per node, in
/// topological order. Op-classes a backend has not implemented yet use the default
/// methods, which return an explicit `Err` (never a silent no-op).
pub trait Lowerer {
    fn elementwise(&mut self, _node: &GraphNode) -> Result<(), ForgeError> {
        unsupported("elementwise")
    }
    fn matmul(&mut self, _node: &GraphNode) -> Result<(), ForgeError> {
        unsupported("matmul")
    }
    fn gemv(&mut self, _node: &GraphNode) -> Result<(), ForgeError> {
        unsupported("gemv")
    }
    fn fft(&mut self, _node: &GraphNode) -> Result<(), ForgeError> {
        unsupported("fft")
    }
    fn reduce(&mut self, _node: &GraphNode) -> Result<(), ForgeError> {
        unsupported("reduce")
    }
    fn gather_dequant(&mut self, _node: &GraphNode) -> Result<(), ForgeError> {
        unsupported("gather_dequant")
    }
    fn broadcast(&mut self, _node: &GraphNode) -> Result<(), ForgeError> {
        unsupported("broadcast")
    }
    fn softmax(&mut self, _node: &GraphNode) -> Result<(), ForgeError> {
        unsupported("softmax")
    }
    fn stencil(&mut self, _node: &GraphNode) -> Result<(), ForgeError> {
        unsupported("stencil")
    }
    fn scatter_accum(&mut self, _node: &GraphNode) -> Result<(), ForgeError> {
        unsupported("scatter_accum")
    }
    fn neighbor(&mut self, _node: &GraphNode) -> Result<(), ForgeError> {
        unsupported("neighbor")
    }
}

fn unsupported(op: &str) -> Result<(), ForgeError> {
    Err(ForgeError::Emission(format!(
        "op-node '{op}' has no lowering on this backend yet"
    )))
}

/// Walk the graph in topological (insertion) order and dispatch each node to its
/// [`Lowerer`] method. The single, backend-agnostic lowering driver — every backend is a
/// `Lowerer` impl, so there are no per-`kernel.id` branches.
pub fn lower_graph<L: Lowerer>(graph: &ComputeGraph, lowerer: &mut L) -> Result<(), ForgeError> {
    for node in &graph.nodes {
        match node.op {
            OpNode::Elementwise { .. } => lowerer.elementwise(node)?,
            OpNode::MatMul { .. } => lowerer.matmul(node)?,
            OpNode::Gemv { .. } => lowerer.gemv(node)?,
            OpNode::Fft { .. } => lowerer.fft(node)?,
            OpNode::Reduce { .. } => lowerer.reduce(node)?,
            OpNode::GatherDequant { .. } => lowerer.gather_dequant(node)?,
            OpNode::Broadcast { .. } => lowerer.broadcast(node)?,
            OpNode::Softmax { .. } => lowerer.softmax(node)?,
            OpNode::Stencil { .. } => lowerer.stencil(node)?,
            OpNode::ScatterAccum { .. } => lowerer.scatter_accum(node)?,
            OpNode::Neighbor { .. } => lowerer.neighbor(node)?,
        }
    }
    Ok(())
}

impl KernelSpec {
    /// Bridge a single-kernel [`KernelSpec`] to a one-node [`ComputeGraph`] — the Phase-1
    /// path for the function-backed WGSL kernels (`gemm`/`gemv`/`fft`). Dims are
    /// runtime-parameterized (read from a params buffer), so the node carries `0` (dynamic)
    /// shapes; the emitted WGSL is dimension-independent. Returns `Err` for ids without a
    /// graph bridge yet — the caller keeps the legacy emit branch for those.
    pub fn to_graph(&self) -> Result<ComputeGraph, ForgeError> {
        let mut g = ComputeGraph::new();
        let sched = Schedule::default();
        let dyn2 = Shape::new(&[0, 0]);
        let dyn1 = Shape::new(&[0]);
        match self.id.as_str() {
            "gemm" => {
                let a = TensorRef::external(dyn2, DType::F32);
                let b = TensorRef::external(dyn2, DType::F32);
                let out = g.push(
                    OpNode::MatMul { m: 0, n: 0, k: 0, tc: false, trans_b: false },
                    &[a, b],
                    dyn2,
                    DType::F32,
                    sched,
                )?;
                g.mark_output(out);
            }
            "gemv" => {
                let a = TensorRef::external(dyn2, DType::F32);
                let x = TensorRef::external(dyn1, DType::F32);
                let out = g.push(OpNode::Gemv { m: 0, n: 0 }, &[a, x], dyn1, DType::F32, sched)?;
                g.mark_output(out);
            }
            "fft" => {
                let inp = TensorRef::external(dyn1, DType::F32);
                let out = g.push(
                    OpNode::Fft { len: 0, inverse: false },
                    &[inp],
                    dyn1,
                    DType::F32,
                    sched,
                )?;
                g.mark_output(out);
            }
            other => {
                return Err(ForgeError::Emission(format!(
                    "KernelSpec::to_graph: no graph bridge for kernel id '{other}'"
                )))
            }
        }
        Ok(g)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::wgsl_forge::ir::BuiltinKernel;

    fn ext(shape: &[u32]) -> TensorRef {
        TensorRef::external(Shape::new(shape), DType::F32)
    }

    /// A two-node chain builds, the second node consumes the first's output, and the
    /// output's producer is the second node (insertion order == topo order).
    #[test]
    fn two_node_chain_builds_in_topo_order() {
        let mut g = ComputeGraph::new();
        let a = ext(&[4, 4]);
        let b = ext(&[4, 4]);
        let mm = g
            .push(
                OpNode::MatMul { m: 4, n: 4, k: 4, tc: false, trans_b: false },
                &[a, b],
                Shape::new(&[4, 4]),
                DType::F32,
                Schedule::default(),
            )
            .unwrap();
        assert_eq!(mm.producer, NodeId(0));
        let relu = g
            .push(
                OpNode::Elementwise { f: EwKind::Relu },
                &[mm],
                Shape::new(&[4, 4]),
                DType::F32,
                Schedule::default(),
            )
            .unwrap();
        assert_eq!(relu.producer, NodeId(1));
        assert_eq!(g.len(), 2);
        // The second node's input must reference the first.
        assert_eq!(g.nodes[1].ins[0].unwrap().producer, NodeId(0));
    }

    /// An input that references a not-yet-added node is rejected (cycle guard).
    #[test]
    fn forward_reference_is_rejected() {
        let mut g = ComputeGraph::new();
        let phantom = TensorRef {
            producer: NodeId(7), // no such node yet
            tensor: TensorId(0),
            shape: Shape::new(&[2, 2]),
            dtype: DType::F32,
            layout: Layout::RowMajor,
        };
        let r = g.push(
            OpNode::Elementwise { f: EwKind::Relu },
            &[phantom],
            Shape::new(&[2, 2]),
            DType::F32,
            Schedule::default(),
        );
        assert!(r.is_err());
    }

    /// An input edge whose declared (static) shape disagrees with its producer's output
    /// is rejected. Dynamic (0) dims are wildcards and must NOT trip this.
    #[test]
    fn shape_mismatch_is_rejected_but_dynamic_is_allowed() {
        let mut g = ComputeGraph::new();
        let a = ext(&[4, 4]);
        let b = ext(&[4, 4]);
        let mm = g
            .push(
                OpNode::MatMul { m: 4, n: 4, k: 4, tc: false, trans_b: false },
                &[a, b],
                Shape::new(&[4, 4]),
                DType::F32,
                Schedule::default(),
            )
            .unwrap();
        // Wrong static shape on the edge → reject.
        let mut wrong = mm;
        wrong.shape = Shape::new(&[8, 8]);
        assert!(g
            .push(
                OpNode::Elementwise { f: EwKind::Relu },
                &[wrong],
                Shape::new(&[8, 8]),
                DType::F32,
                Schedule::default(),
            )
            .is_err());
        // Dynamic edge shape (wildcard) → accepted.
        let mut dynamic = mm;
        dynamic.shape = Shape::new(&[0, 0]);
        assert!(g
            .push(
                OpNode::Elementwise { f: EwKind::Relu },
                &[dynamic],
                Shape::new(&[4, 4]),
                DType::F32,
                Schedule::default(),
            )
            .is_ok());
    }

    /// `MAX_IN + 1` inputs are rejected.
    #[test]
    fn too_many_inputs_rejected() {
        let mut g = ComputeGraph::new();
        let ins: Vec<TensorRef> = (0..(MAX_IN + 1)).map(|_| ext(&[2])).collect();
        assert!(g
            .push(
                OpNode::Elementwise { f: EwKind::Add },
                &ins,
                Shape::new(&[2]),
                DType::F32,
                Schedule::default(),
            )
            .is_err());
    }

    /// The `gemm`/`gemv`/`fft` bridges each produce a single-node graph with the expected
    /// op-class; an unknown id is a clean `Err`.
    #[test]
    fn to_graph_bridges_seed_kernels() {
        let gemm = BuiltinKernel::Gemm.spec().to_graph().unwrap();
        assert_eq!(gemm.len(), 1);
        assert!(matches!(gemm.nodes[0].op, OpNode::MatMul { .. }));

        let gemv = BuiltinKernel::Gemv.spec().to_graph().unwrap();
        assert_eq!(gemv.len(), 1);
        assert!(matches!(gemv.nodes[0].op, OpNode::Gemv { .. }));

        let fft = BuiltinKernel::Fft.spec().to_graph().unwrap();
        assert_eq!(fft.len(), 1);
        assert!(matches!(fft.nodes[0].op, OpNode::Fft { .. }));

        // A kernel without a bridge yet → explicit Err, not a panic.
        assert!(BuiltinKernel::AffineF32.spec().to_graph().is_err());
    }

    /// `lower_graph` dispatches each node to the matching `Lowerer` method; a recording
    /// lowerer sees exactly the ops in topo order, and an unimplemented op-class errors.
    #[test]
    fn lower_graph_dispatches_in_order() {
        struct Recorder(Vec<&'static str>);
        impl Lowerer for Recorder {
            fn matmul(&mut self, _: &GraphNode) -> Result<(), ForgeError> {
                self.0.push("matmul");
                Ok(())
            }
            fn elementwise(&mut self, _: &GraphNode) -> Result<(), ForgeError> {
                self.0.push("elementwise");
                Ok(())
            }
        }
        let mut g = ComputeGraph::new();
        let a = ext(&[4, 4]);
        let b = ext(&[4, 4]);
        let mm = g
            .push(
                OpNode::MatMul { m: 4, n: 4, k: 4, tc: false, trans_b: false },
                &[a, b],
                Shape::new(&[4, 4]),
                DType::F32,
                Schedule::default(),
            )
            .unwrap();
        g.push(
            OpNode::Elementwise { f: EwKind::Silu },
            &[mm],
            Shape::new(&[4, 4]),
            DType::F32,
            Schedule::default(),
        )
        .unwrap();
        let mut rec = Recorder(Vec::new());
        lower_graph(&g, &mut rec).unwrap();
        assert_eq!(rec.0, vec!["matmul", "elementwise"]);

        // A graph with an unimplemented op-class errors (no silent skip).
        let mut g2 = ComputeGraph::new();
        g2.push(
            OpNode::Reduce { op: RedKind::Sum, axis: Axis::Last },
            &[ext(&[8])],
            Shape::new(&[1]),
            DType::F32,
            Schedule::default(),
        )
        .unwrap();
        let mut rec2 = Recorder(Vec::new());
        assert!(lower_graph(&g2, &mut rec2).is_err());
    }
}
