use super::*;

// ───────────────────────────────────────────────────────────────────────────
//  Manifest registry
// ───────────────────────────────────────────────────────────────────────────

/// The canonical capability manifest table for computational-geometry ops.
///
/// **P10.1 claim-to-code audit.** Every entry's `maturity` MUST agree with
/// the corresponding row in `native-computational-geometry-EXECUTION.md`. As
/// of 2026-07-05 the CG library is at `Implemented` across P0–P9 (own
/// `#[cfg(test)]` green; 752-test suite green) but NOT `Verified` (CC0
/// golden-vector corpus not fetched; GPU-on-adapter differentials not run;
/// `mcp_server --lib` gate cleared but full `done` integration pending). So
/// every current entry honestly carries `Maturity::Implemented`. When a task
/// clears its acceptance gates, raise its row here AND in the execution plan
/// in the same change.
pub const GEOMETRY_OP_MANIFESTS: &[OpManifest] = &[
    // ── P1 — Predicates (exact sign decisions; hot zero-heap) ──
    OpManifest {
        op: "orientation_2",
        description: "Robust 2-D orientation predicate (filtered → FMA-compensated residual; no exact-expansion fallback, unlike orient_3d/incircle/insphere).",
        backends: &[Backend::Scalar, Backend::Exact, Backend::Wasm],
        determinism: DeterminismClass::BitExact,
        limits: ResourceLimits {
            max_input_points: 3,
            max_output_bytes: 64,
            max_memory_bytes: 1024,
            max_time_us: 100,
        },
        topology_critical: true,
        maturity: Maturity::Implemented,
        exactness: ExactnessClass::ExactPredicate,
        allocation: AllocationClass::HotZeroHeap,
        dimensionality: Dimensionality::D2,
    },
    OpManifest {
        op: "orient_3d",
        description: "Robust 3-D orientation predicate (filtered → exact fallback).",
        backends: &[Backend::Scalar, Backend::Exact, Backend::Wasm],
        determinism: DeterminismClass::BitExact,
        limits: ResourceLimits {
            max_input_points: 4,
            max_output_bytes: 64,
            max_memory_bytes: 1024,
            max_time_us: 100,
        },
        topology_critical: true,
        maturity: Maturity::Implemented,
        exactness: ExactnessClass::ExactPredicate,
        allocation: AllocationClass::HotZeroHeap,
        dimensionality: Dimensionality::D3,
    },
    OpManifest {
        op: "incircle",
        description: "2-D in-circle predicate (filtered → exact fallback).",
        backends: &[Backend::Scalar, Backend::Exact, Backend::Wasm],
        determinism: DeterminismClass::BitExact,
        limits: ResourceLimits {
            max_input_points: 4,
            max_output_bytes: 64,
            max_memory_bytes: 1024,
            max_time_us: 100,
        },
        topology_critical: true,
        maturity: Maturity::Implemented,
        exactness: ExactnessClass::ExactPredicate,
        allocation: AllocationClass::HotZeroHeap,
        dimensionality: Dimensionality::D2,
    },
    OpManifest {
        op: "insphere",
        description: "3-D in-sphere predicate (filtered → exact fallback).",
        backends: &[Backend::Scalar, Backend::Exact, Backend::Wasm],
        determinism: DeterminismClass::BitExact,
        limits: ResourceLimits {
            max_input_points: 5,
            max_output_bytes: 64,
            max_memory_bytes: 1024,
            max_time_us: 100,
        },
        topology_critical: true,
        maturity: Maturity::Implemented,
        exactness: ExactnessClass::ExactPredicate,
        allocation: AllocationClass::HotZeroHeap,
        dimensionality: Dimensionality::D3,
    },
    // ── P1.7 — Exact construction (re-predicable coordinates) ──
    OpManifest {
        op: "construct_segment_intersection_2",
        description: "Exact 2-D segment-segment intersection point (re-predicable).",
        backends: &[Backend::Scalar, Backend::Exact, Backend::Wasm],
        determinism: DeterminismClass::BitExact,
        limits: ResourceLimits {
            max_input_points: 4,
            max_output_bytes: 128,
            max_memory_bytes: 4096,
            max_time_us: 100,
        },
        topology_critical: false,
        maturity: Maturity::Implemented,
        exactness: ExactnessClass::ExactConstruction,
        allocation: AllocationClass::HotZeroHeap,
        dimensionality: Dimensionality::D2,
    },
    // ── P2 — Hulls (predicate-driven; cold build) ──
    OpManifest {
        op: "convex_hull_2",
        description: "2-D convex hull via monotone chain with exact predicate fallback.",
        backends: &[Backend::Scalar, Backend::Simd, Backend::Wasm, Backend::Exact],
        determinism: DeterminismClass::BitExact,
        limits: ResourceLimits {
            max_input_points: 1_000_000,
            max_output_bytes: 8 * 1024 * 1024,
            max_memory_bytes: 64 * 1024 * 1024,
            max_time_us: 0,
        },
        topology_critical: true,
        maturity: Maturity::Implemented,
        exactness: ExactnessClass::ExactPredicate,
        allocation: AllocationClass::ColdBounded,
        dimensionality: Dimensionality::D2,
    },
    OpManifest {
        op: "convex_hull_3",
        description: "3-D convex hull (incremental; rejects all-coplanar input — see P10 audit).",
        backends: &[Backend::Scalar, Backend::Wasm, Backend::Exact],
        determinism: DeterminismClass::BitExact,
        limits: ResourceLimits {
            max_input_points: 100_000,
            max_output_bytes: 16 * 1024 * 1024,
            max_memory_bytes: 128 * 1024 * 1024,
            max_time_us: 0,
        },
        topology_critical: true,
        maturity: Maturity::Implemented,
        exactness: ExactnessClass::ExactPredicate,
        allocation: AllocationClass::ColdBounded,
        dimensionality: Dimensionality::D3,
    },
    // ── P3 — Delaunay / Voronoi (predicate-driven; cold build) ──
    OpManifest {
        op: "delaunay_2",
        description: "2-D Delaunay triangulation with incircle exact predicate.",
        backends: &[Backend::Scalar, Backend::Wasm, Backend::Exact],
        determinism: DeterminismClass::BitExact,
        limits: ResourceLimits {
            max_input_points: 100_000,
            max_output_bytes: 16 * 1024 * 1024,
            max_memory_bytes: 128 * 1024 * 1024,
            max_time_us: 0,
        },
        topology_critical: true,
        maturity: Maturity::Implemented,
        exactness: ExactnessClass::ExactPredicate,
        allocation: AllocationClass::ColdBounded,
        dimensionality: Dimensionality::D2,
    },
    OpManifest {
        op: "voronoi_2",
        description: "Voronoi diagram as Delaunay dual (connectivity exact from Delaunay; vertex coords are f64 circumcenters — approximate).",
        backends: &[Backend::Scalar, Backend::Wasm],
        determinism: DeterminismClass::BitExact,
        limits: ResourceLimits {
            max_input_points: 100_000,
            max_output_bytes: 32 * 1024 * 1024,
            max_memory_bytes: 128 * 1024 * 1024,
            max_time_us: 0,
        },
        topology_critical: false,
        maturity: Maturity::Implemented,
        exactness: ExactnessClass::ApproximateMetric,
        allocation: AllocationClass::ColdBounded,
        dimensionality: Dimensionality::D2,
    },
    OpManifest {
        op: "delaunay_3",
        description: "3-D Delaunay tetrahedralization (Bowyer-Watson; empty-circumsphere).",
        backends: &[Backend::Scalar, Backend::Wasm, Backend::Exact],
        determinism: DeterminismClass::BitExact,
        limits: ResourceLimits {
            max_input_points: 50_000,
            max_output_bytes: 32 * 1024 * 1024,
            max_memory_bytes: 256 * 1024 * 1024,
            max_time_us: 0,
        },
        topology_critical: true,
        maturity: Maturity::Implemented,
        exactness: ExactnessClass::ExactPredicate,
        allocation: AllocationClass::ColdBounded,
        dimensionality: Dimensionality::D3,
    },
    OpManifest {
        op: "conforming_delaunay_2",
        description: "Constrained 2-D Delaunay with edge constraints (approximate collinearity — P13 supplies real refinement).",
        backends: &[Backend::Scalar, Backend::Wasm],
        determinism: DeterminismClass::BitExact,
        limits: ResourceLimits {
            max_input_points: 50_000,
            max_output_bytes: 16 * 1024 * 1024,
            max_memory_bytes: 128 * 1024 * 1024,
            max_time_us: 0,
        },
        topology_critical: false,
        maturity: Maturity::Implemented,
        exactness: ExactnessClass::ApproximateMetric,
        allocation: AllocationClass::ColdBounded,
        dimensionality: Dimensionality::D2,
    },
    // ── P3 — Spatial index (BVH / kd-tree; cold build, hot query) ──
    OpManifest {
        op: "bvh_3d",
        description: "3-D BVH construction + closest/overlap query (cold build, hot query).",
        backends: &[Backend::Scalar, Backend::Wasm],
        determinism: DeterminismClass::BitExact,
        limits: ResourceLimits {
            max_input_points: 1_000_000,
            max_output_bytes: 64 * 1024 * 1024,
            max_memory_bytes: 128 * 1024 * 1024,
            max_time_us: 0,
        },
        topology_critical: false,
        maturity: Maturity::Implemented,
        exactness: ExactnessClass::ApproximateMetric,
        allocation: AllocationClass::ColdBounded,
        dimensionality: Dimensionality::D3,
    },
    OpManifest {
        op: "kd_tree_3d",
        description: "3-D kd-tree construction + nearest/radius query.",
        backends: &[Backend::Scalar, Backend::Wasm],
        determinism: DeterminismClass::BitExact,
        limits: ResourceLimits {
            max_input_points: 1_000_000,
            max_output_bytes: 64 * 1024 * 1024,
            max_memory_bytes: 128 * 1024 * 1024,
            max_time_us: 0,
        },
        topology_critical: false,
        maturity: Maturity::Implemented,
        exactness: ExactnessClass::ApproximateMetric,
        allocation: AllocationClass::ColdBounded,
        dimensionality: Dimensionality::D3,
    },
    OpManifest {
        op: "box_join",
        description: "BVH-driven box join (candidate pair enumeration).",
        backends: &[Backend::Scalar, Backend::Wgpu, Backend::Wasm],
        determinism: DeterminismClass::BitExact,
        limits: ResourceLimits {
            max_input_points: 1_000_000,
            max_output_bytes: 64 * 1024 * 1024,
            max_memory_bytes: 128 * 1024 * 1024,
            max_time_us: 0,
        },
        topology_critical: false,
        maturity: Maturity::Implemented,
        exactness: ExactnessClass::ApproximateMetric,
        allocation: AllocationClass::ColdBounded,
        dimensionality: Dimensionality::D3,
    },
    OpManifest {
        op: "spatial_order",
        description: "Morton/Hilbert curve encoding for spatial sorting (2-D/3-D).",
        backends: &[Backend::Scalar, Backend::Wasm],
        determinism: DeterminismClass::BitExact,
        limits: ResourceLimits {
            max_input_points: 1_000_000,
            max_output_bytes: 16 * 1024 * 1024,
            max_memory_bytes: 64 * 1024 * 1024,
            max_time_us: 0,
        },
        topology_critical: false,
        maturity: Maturity::Implemented,
        exactness: ExactnessClass::Structural,
        allocation: AllocationClass::HotZeroHeap,
        dimensionality: Dimensionality::DN,
    },
    OpManifest {
        op: "nearest_site",
        description: "Brute-force nearest-site query.",
        backends: &[Backend::Scalar, Backend::Simd, Backend::Wasm],
        determinism: DeterminismClass::BitExact,
        limits: ResourceLimits {
            max_input_points: 1_000_000,
            max_output_bytes: 64,
            max_memory_bytes: 64 * 1024 * 1024,
            max_time_us: 0,
        },
        topology_critical: false,
        maturity: Maturity::Implemented,
        exactness: ExactnessClass::ApproximateMetric,
        allocation: AllocationClass::ColdBounded,
        dimensionality: Dimensionality::D2,
    },
    // ── P2.8 / P3.7 — Topology + spatial-index .10d sections ──
    OpManifest {
        op: "triangle_topology",
        description: "Build half-edge topology from triangle list.",
        backends: &[Backend::Scalar, Backend::Wasm],
        determinism: DeterminismClass::BitExact,
        limits: ResourceLimits {
            max_input_points: 1_000_000,
            max_output_bytes: 64 * 1024 * 1024,
            max_memory_bytes: 128 * 1024 * 1024,
            max_time_us: 0,
        },
        topology_critical: false,
        maturity: Maturity::Implemented,
        exactness: ExactnessClass::Structural,
        allocation: AllocationClass::ColdBounded,
        dimensionality: Dimensionality::DN,
    },
    OpManifest {
        op: "mesh_topology",
        description: "Encode mesh topology to .10d section with Euler characteristic.",
        backends: &[Backend::Scalar, Backend::Wasm],
        determinism: DeterminismClass::BitExact,
        limits: ResourceLimits {
            max_input_points: 1_000_000,
            max_output_bytes: 64 * 1024 * 1024,
            max_memory_bytes: 128 * 1024 * 1024,
            max_time_us: 0,
        },
        topology_critical: false,
        maturity: Maturity::Implemented,
        exactness: ExactnessClass::Structural,
        allocation: AllocationClass::ColdBounded,
        dimensionality: Dimensionality::DimensionIndependent,
    },
    // ── P4 — 2-D booleans / Minkowski (approximate metric; f64 intersections) ──
    OpManifest {
        op: "boolean_2",
        description: "2-D polygon boolean ops (union/intersection/difference) — area-based, f64.",
        backends: &[Backend::Scalar, Backend::Wasm],
        determinism: DeterminismClass::BitExact,
        limits: ResourceLimits {
            max_input_points: 100_000,
            max_output_bytes: 16 * 1024 * 1024,
            max_memory_bytes: 64 * 1024 * 1024,
            max_time_us: 0,
        },
        topology_critical: false,
        maturity: Maturity::Implemented,
        exactness: ExactnessClass::ApproximateMetric,
        allocation: AllocationClass::ColdBounded,
        dimensionality: Dimensionality::D2,
    },
    OpManifest {
        op: "minkowski_2",
        description: "2-D Minkowski sum/difference: O(n+m) edge-merge for convex polygons, non-convex decomposition + pairwise convex sum for general polygons, brute-force hull fallback.",
        backends: &[Backend::Scalar, Backend::Wasm, Backend::Exact],
        determinism: DeterminismClass::BitExact,
        limits: ResourceLimits {
            max_input_points: 100_000,
            max_output_bytes: 16 * 1024 * 1024,
            max_memory_bytes: 64 * 1024 * 1024,
            max_time_us: 0,
        },
        topology_critical: false,
        maturity: Maturity::Implemented,
        exactness: ExactnessClass::ExactPredicate,
        allocation: AllocationClass::ColdBounded,
        dimensionality: Dimensionality::D2,
    },
    // ── P5 — 3-D mesh processing (approximate; f64 intersections) ──
    OpManifest {
        op: "tri_tri_intersect_3",
        description: "3-D triangle-triangle intersection classification.",
        backends: &[Backend::Scalar, Backend::Wasm, Backend::Exact],
        determinism: DeterminismClass::BitExact,
        limits: ResourceLimits {
            max_input_points: 6,
            max_output_bytes: 256,
            max_memory_bytes: 4096,
            max_time_us: 100,
        },
        topology_critical: true,
        maturity: Maturity::Implemented,
        exactness: ExactnessClass::ExactPredicate,
        allocation: AllocationClass::HotZeroHeap,
        dimensionality: Dimensionality::D3,
    },
    OpManifest {
        op: "boolean_3",
        description: "3-D mesh boolean (union/intersection/difference) — approximate, f64 intersections (P12 supplies exact CSG).",
        backends: &[Backend::Scalar, Backend::Wasm],
        determinism: DeterminismClass::BitExact,
        limits: ResourceLimits {
            max_input_points: 100_000,
            max_output_bytes: 64 * 1024 * 1024,
            max_memory_bytes: 256 * 1024 * 1024,
            max_time_us: 0,
        },
        topology_critical: false,
        maturity: Maturity::Implemented,
        exactness: ExactnessClass::ApproximateMetric,
        allocation: AllocationClass::ColdBounded,
        dimensionality: Dimensionality::D3,
    },
    OpManifest {
        op: "decimate_qem",
        description: "3-D mesh decimation via quadric error metrics (LOD generation).",
        backends: &[Backend::Scalar, Backend::Wasm],
        determinism: DeterminismClass::BitExact,
        limits: ResourceLimits {
            max_input_points: 500_000,
            max_output_bytes: 64 * 1024 * 1024,
            max_memory_bytes: 256 * 1024 * 1024,
            max_time_us: 0,
        },
        topology_critical: false,
        maturity: Maturity::Implemented,
        exactness: ExactnessClass::ApproximateMetric,
        allocation: AllocationClass::ColdBounded,
        dimensionality: Dimensionality::D3,
    },
    OpManifest {
        op: "isotropic_remesh",
        description: "Isotropic remeshing (edge-length targeting; manifold + orientation preserved).",
        backends: &[Backend::Scalar, Backend::Wasm],
        determinism: DeterminismClass::BitExact,
        limits: ResourceLimits {
            max_input_points: 500_000,
            max_output_bytes: 64 * 1024 * 1024,
            max_memory_bytes: 256 * 1024 * 1024,
            max_time_us: 0,
        },
        topology_critical: false,
        maturity: Maturity::Implemented,
        exactness: ExactnessClass::ApproximateMetric,
        allocation: AllocationClass::ColdBounded,
        dimensionality: Dimensionality::D3,
    },
    OpManifest {
        op: "exact_construct_3",
        description: "Exact 3-D construction (segment-plane/triangle intersection; re-predicable).",
        backends: &[Backend::Scalar, Backend::Exact, Backend::Wasm],
        determinism: DeterminismClass::BitExact,
        limits: ResourceLimits {
            max_input_points: 8,
            max_output_bytes: 256,
            max_memory_bytes: 8192,
            max_time_us: 100,
        },
        topology_critical: false,
        maturity: Maturity::Implemented,
        exactness: ExactnessClass::ExactConstruction,
        allocation: AllocationClass::HotZeroHeap,
        dimensionality: Dimensionality::D3,
    },
    // ── P6 — Reconstruction / meshing / TDA ──
    OpManifest {
        op: "alpha_shape_2d",
        description: "2-D alpha shapes (simplex classification over a range of α).",
        backends: &[Backend::Scalar, Backend::Wasm, Backend::Exact],
        determinism: DeterminismClass::BitExact,
        limits: ResourceLimits {
            max_input_points: 100_000,
            max_output_bytes: 32 * 1024 * 1024,
            max_memory_bytes: 128 * 1024 * 1024,
            max_time_us: 0,
        },
        topology_critical: true,
        maturity: Maturity::Implemented,
        exactness: ExactnessClass::ExactPredicate,
        allocation: AllocationClass::ColdBounded,
        dimensionality: Dimensionality::D2,
    },
    OpManifest {
        op: "alpha_shape_3d",
        description: "3-D alpha shapes + alpha-wrap surface extraction (watertight).",
        backends: &[Backend::Scalar, Backend::Wasm, Backend::Exact],
        determinism: DeterminismClass::BitExact,
        limits: ResourceLimits {
            max_input_points: 50_000,
            max_output_bytes: 64 * 1024 * 1024,
            max_memory_bytes: 256 * 1024 * 1024,
            max_time_us: 0,
        },
        topology_critical: true,
        maturity: Maturity::Implemented,
        exactness: ExactnessClass::ExactPredicate,
        allocation: AllocationClass::ColdBounded,
        dimensionality: Dimensionality::D3,
    },
    OpManifest {
        op: "marching_cubes",
        description: "Marching-cubes isosurface extraction (canonical 256-case Lorensen–Cline table; 2-manifold).",
        backends: &[Backend::Scalar, Backend::Wasm],
        determinism: DeterminismClass::BitExact,
        limits: ResourceLimits {
            max_input_points: 1_000_000,
            max_output_bytes: 64 * 1024 * 1024,
            max_memory_bytes: 256 * 1024 * 1024,
            max_time_us: 0,
        },
        topology_critical: false,
        maturity: Maturity::Implemented,
        exactness: ExactnessClass::TopologyGuaranteed,
        allocation: AllocationClass::ColdBounded,
        dimensionality: Dimensionality::D3,
    },
    OpManifest {
        op: "poisson_reconstruct_3d",
        description: "Oriented-point SDF reconstruction (nearest-normal signed distance + marching cubes; NOT real Poisson — P13 supplies real screened-Poisson).",
        backends: &[Backend::Scalar, Backend::Wasm],
        determinism: DeterminismClass::BitExact,
        limits: ResourceLimits {
            max_input_points: 50_000,
            max_output_bytes: 64 * 1024 * 1024,
            max_memory_bytes: 256 * 1024 * 1024,
            max_time_us: 0,
        },
        topology_critical: false,
        maturity: Maturity::Implemented,
        exactness: ExactnessClass::ApproximateMetric,
        allocation: AllocationClass::ColdBounded,
        dimensionality: Dimensionality::D3,
    },
    OpManifest {
        op: "point_set_3d",
        description: "3-D point-set processing: kNN/CkNN neighbourhood, average spacing, outlier removal, local density.",
        backends: &[Backend::Scalar, Backend::Simd, Backend::Wgpu, Backend::Wasm],
        determinism: DeterminismClass::BitExact,
        limits: ResourceLimits {
            max_input_points: 500_000,
            max_output_bytes: 64 * 1024 * 1024,
            max_memory_bytes: 256 * 1024 * 1024,
            max_time_us: 0,
        },
        topology_critical: false,
        maturity: Maturity::Implemented,
        exactness: ExactnessClass::ApproximateMetric,
        allocation: AllocationClass::ColdBounded,
        dimensionality: Dimensionality::D3,
    },
    // ── P8 — Spectral / TDA / statistical manifold (10-D Tensor10D) ──
    OpManifest {
        op: "vr_filtration",
        description: "Vietoris-Rips filtration over Tensor10D point cloud.",
        backends: &[Backend::Scalar, Backend::Wgpu, Backend::Wasm],
        determinism: DeterminismClass::BitExact,
        limits: ResourceLimits {
            max_input_points: 10_000,
            max_output_bytes: 64 * 1024 * 1024,
            max_memory_bytes: 256 * 1024 * 1024,
            max_time_us: 0,
        },
        topology_critical: true,
        maturity: Maturity::Implemented,
        exactness: ExactnessClass::Structural,
        allocation: AllocationClass::ColdBounded,
        dimensionality: Dimensionality::D10,
    },
    OpManifest {
        op: "persistence",
        description: "Persistent homology barcode (H0/H1) from filtered complex.",
        backends: &[Backend::Scalar, Backend::Wasm],
        determinism: DeterminismClass::BitExact,
        limits: ResourceLimits {
            max_input_points: 50_000,
            max_output_bytes: 16 * 1024 * 1024,
            max_memory_bytes: 128 * 1024 * 1024,
            max_time_us: 0,
        },
        topology_critical: true,
        maturity: Maturity::Implemented,
        exactness: ExactnessClass::TopologyGuaranteed,
        allocation: AllocationClass::ColdBounded,
        dimensionality: Dimensionality::D10,
    },
    OpManifest {
        op: "alpha_filtration_2d",
        description: "2-D alpha filtration for persistent homology (TDA).",
        backends: &[Backend::Scalar, Backend::Wasm, Backend::Exact],
        determinism: DeterminismClass::BitExact,
        limits: ResourceLimits {
            max_input_points: 50_000,
            max_output_bytes: 32 * 1024 * 1024,
            max_memory_bytes: 128 * 1024 * 1024,
            max_time_us: 0,
        },
        topology_critical: true,
        maturity: Maturity::Implemented,
        exactness: ExactnessClass::ExactPredicate,
        allocation: AllocationClass::ColdBounded,
        dimensionality: Dimensionality::D2,
    },
    OpManifest {
        op: "cknn_laplacian",
        description: "CkNN graph Laplacian and local density estimation.",
        backends: &[Backend::Scalar, Backend::Simd, Backend::Wgpu, Backend::Wasm],
        determinism: DeterminismClass::BitExact,
        limits: ResourceLimits {
            max_input_points: 100_000,
            max_output_bytes: 32 * 1024 * 1024,
            max_memory_bytes: 128 * 1024 * 1024,
            max_time_us: 0,
        },
        topology_critical: false,
        maturity: Maturity::Implemented,
        exactness: ExactnessClass::ApproximateMetric,
        allocation: AllocationClass::ColdBounded,
        dimensionality: Dimensionality::D10,
    },
    OpManifest {
        op: "cknn_laplacian_3d",
        description: "3-D CkNN graph Laplacian (Laplace-Beltrami discrete approximation).",
        backends: &[Backend::Scalar, Backend::Wasm],
        determinism: DeterminismClass::BitExact,
        limits: ResourceLimits {
            max_input_points: 100_000,
            max_output_bytes: 32 * 1024 * 1024,
            max_memory_bytes: 128 * 1024 * 1024,
            max_time_us: 0,
        },
        topology_critical: false,
        maturity: Maturity::Implemented,
        exactness: ExactnessClass::ApproximateMetric,
        allocation: AllocationClass::ColdBounded,
        dimensionality: Dimensionality::D3,
    },
    OpManifest {
        op: "nn_query",
        description: "Nearest-neighbour inference query (radius + kNN).",
        backends: &[Backend::Scalar, Backend::Simd, Backend::Wgpu, Backend::Wasm],
        determinism: DeterminismClass::BitExact,
        limits: ResourceLimits {
            max_input_points: 1_000_000,
            max_output_bytes: 8 * 1024 * 1024,
            max_memory_bytes: 64 * 1024 * 1024,
            max_time_us: 0,
        },
        topology_critical: false,
        maturity: Maturity::Implemented,
        exactness: ExactnessClass::ApproximateMetric,
        allocation: AllocationClass::ColdBounded,
        dimensionality: Dimensionality::D10,
    },
    OpManifest {
        op: "gpu_oracle",
        description: "GPU acceleration + CPU oracle for P8 batch distances/density/circumradius.",
        backends: &[Backend::Scalar, Backend::Wgpu, Backend::Wasm],
        determinism: DeterminismClass::Tolerance,
        limits: ResourceLimits {
            max_input_points: 100_000,
            max_output_bytes: 64 * 1024 * 1024,
            max_memory_bytes: 256 * 1024 * 1024,
            max_time_us: 0,
        },
        topology_critical: false,
        maturity: Maturity::Implemented,
        exactness: ExactnessClass::ApproximateMetric,
        allocation: AllocationClass::ColdBounded,
        dimensionality: Dimensionality::D10,
    },
    OpManifest {
        op: "natural_neighbour",
        description: "Natural-neighbour interpolation (Laplace coordinates; linear precision verified).",
        backends: &[Backend::Scalar, Backend::Wasm],
        determinism: DeterminismClass::BitExact,
        limits: ResourceLimits {
            max_input_points: 50_000,
            max_output_bytes: 4 * 1024 * 1024,
            max_memory_bytes: 64 * 1024 * 1024,
            max_time_us: 0,
        },
        topology_critical: false,
        maturity: Maturity::Implemented,
        exactness: ExactnessClass::ApproximateMetric,
        allocation: AllocationClass::ColdBounded,
        dimensionality: Dimensionality::D2,
    },
    // ── P9.5 — Authoring ops (primitive generation; structural) ──
    OpManifest {
        op: "create_box",
        description: "Generate a box mesh with custom dimensions.",
        backends: &[Backend::Scalar, Backend::Wasm],
        determinism: DeterminismClass::BitExact,
        limits: ResourceLimits {
            max_input_points: 0,
            max_output_bytes: 1024,
            max_memory_bytes: 4096,
            max_time_us: 100,
        },
        topology_critical: false,
        maturity: Maturity::Implemented,
        exactness: ExactnessClass::Structural,
        allocation: AllocationClass::ColdBounded,
        dimensionality: Dimensionality::D3,
    },
    OpManifest {
        op: "create_sphere",
        description: "Generate a UV sphere mesh.",
        backends: &[Backend::Scalar, Backend::Wasm],
        determinism: DeterminismClass::BitExact,
        limits: ResourceLimits {
            max_input_points: 0,
            max_output_bytes: 16 * 1024 * 1024,
            max_memory_bytes: 32 * 1024 * 1024,
            max_time_us: 0,
        },
        topology_critical: false,
        maturity: Maturity::Implemented,
        exactness: ExactnessClass::Structural,
        allocation: AllocationClass::ColdBounded,
        dimensionality: Dimensionality::D3,
    },
    OpManifest {
        op: "create_cylinder",
        description: "Generate a cylinder mesh.",
        backends: &[Backend::Scalar, Backend::Wasm],
        determinism: DeterminismClass::BitExact,
        limits: ResourceLimits {
            max_input_points: 0,
            max_output_bytes: 4 * 1024 * 1024,
            max_memory_bytes: 8 * 1024 * 1024,
            max_time_us: 0,
        },
        topology_critical: false,
        maturity: Maturity::Implemented,
        exactness: ExactnessClass::Structural,
        allocation: AllocationClass::ColdBounded,
        dimensionality: Dimensionality::D3,
    },
    OpManifest {
        op: "create_plane",
        description: "Generate a plane mesh in the XZ plane.",
        backends: &[Backend::Scalar, Backend::Wasm],
        determinism: DeterminismClass::BitExact,
        limits: ResourceLimits {
            max_input_points: 0,
            max_output_bytes: 256,
            max_memory_bytes: 1024,
            max_time_us: 100,
        },
        topology_critical: false,
        maturity: Maturity::Implemented,
        exactness: ExactnessClass::Structural,
        allocation: AllocationClass::ColdBounded,
        dimensionality: Dimensionality::D3,
    },
    OpManifest {
        op: "create_torus",
        description: "Generate a torus mesh.",
        backends: &[Backend::Scalar, Backend::Wasm],
        determinism: DeterminismClass::BitExact,
        limits: ResourceLimits {
            max_input_points: 0,
            max_output_bytes: 16 * 1024 * 1024,
            max_memory_bytes: 32 * 1024 * 1024,
            max_time_us: 0,
        },
        topology_critical: false,
        maturity: Maturity::Implemented,
        exactness: ExactnessClass::Structural,
        allocation: AllocationClass::ColdBounded,
        dimensionality: Dimensionality::D3,
    },
    OpManifest {
        op: "create_grid",
        description: "Generate a subdivided grid mesh.",
        backends: &[Backend::Scalar, Backend::Wasm],
        determinism: DeterminismClass::BitExact,
        limits: ResourceLimits {
            max_input_points: 0,
            max_output_bytes: 16 * 1024 * 1024,
            max_memory_bytes: 32 * 1024 * 1024,
            max_time_us: 0,
        },
        topology_critical: false,
        maturity: Maturity::Implemented,
        exactness: ExactnessClass::Structural,
        allocation: AllocationClass::ColdBounded,
        dimensionality: Dimensionality::D3,
    },
    // ── P9.5 — Authoring: mesh booleans + edits (tool-dispatched; 3-D) ──
    OpManifest {
        op: "boolean_union",
        description: "Authoring 3-D mesh union (approximate; f64 intersections — P12 supplies exact CSG).",
        backends: &[Backend::Scalar, Backend::Wasm],
        determinism: DeterminismClass::BitExact,
        limits: ResourceLimits {
            max_input_points: 100_000,
            max_output_bytes: 64 * 1024 * 1024,
            max_memory_bytes: 256 * 1024 * 1024,
            max_time_us: 0,
        },
        topology_critical: false,
        maturity: Maturity::Implemented,
        exactness: ExactnessClass::ApproximateMetric,
        allocation: AllocationClass::ColdBounded,
        dimensionality: Dimensionality::D3,
    },
    OpManifest {
        op: "boolean_intersect",
        description: "Authoring 3-D mesh intersection (approximate; f64 intersections — P12 supplies exact CSG).",
        backends: &[Backend::Scalar, Backend::Wasm],
        determinism: DeterminismClass::BitExact,
        limits: ResourceLimits {
            max_input_points: 100_000,
            max_output_bytes: 64 * 1024 * 1024,
            max_memory_bytes: 256 * 1024 * 1024,
            max_time_us: 0,
        },
        topology_critical: false,
        maturity: Maturity::Implemented,
        exactness: ExactnessClass::ApproximateMetric,
        allocation: AllocationClass::ColdBounded,
        dimensionality: Dimensionality::D3,
    },
    OpManifest {
        op: "boolean_difference",
        description: "Authoring 3-D mesh difference (approximate; f64 intersections — P12 supplies exact CSG).",
        backends: &[Backend::Scalar, Backend::Wasm],
        determinism: DeterminismClass::BitExact,
        limits: ResourceLimits {
            max_input_points: 100_000,
            max_output_bytes: 64 * 1024 * 1024,
            max_memory_bytes: 256 * 1024 * 1024,
            max_time_us: 0,
        },
        topology_critical: false,
        maturity: Maturity::Implemented,
        exactness: ExactnessClass::ApproximateMetric,
        allocation: AllocationClass::ColdBounded,
        dimensionality: Dimensionality::D3,
    },
    OpManifest {
        op: "drag_vertex",
        description: "Authoring edit: drag a mesh vertex with prior-τ consent gate.",
        backends: &[Backend::Scalar, Backend::Wasm],
        determinism: DeterminismClass::BitExact,
        limits: ResourceLimits {
            max_input_points: 1_000_000,
            max_output_bytes: 64 * 1024 * 1024,
            max_memory_bytes: 128 * 1024 * 1024,
            max_time_us: 0,
        },
        topology_critical: false,
        maturity: Maturity::Implemented,
        exactness: ExactnessClass::Structural,
        allocation: AllocationClass::ColdBounded,
        dimensionality: Dimensionality::D3,
    },
    // ── P11.9 — Half-plane intersection + 2-D randomized LP ──
    OpManifest {
        op: "half_plane_intersection",
        description: "2-D half-plane intersection (sort-and-intersect + deque); bounded/empty/unbounded.",
        backends: &[Backend::Scalar, Backend::Wasm, Backend::Exact],
        determinism: DeterminismClass::BitExact,
        limits: ResourceLimits {
            max_input_points: 1_000_000,
            max_output_bytes: 16 * 1024 * 1024,
            max_memory_bytes: 64 * 1024 * 1024,
            max_time_us: 0,
        },
        topology_critical: false,
        maturity: Maturity::Implemented,
        exactness: ExactnessClass::ExactPredicate,
        allocation: AllocationClass::ColdBounded,
        dimensionality: Dimensionality::D2,
    },
    OpManifest {
        op: "linear_program_2d",
        description: "2-D LP (Seidel randomized incremental); seeded determinism + feasible/infeasible/unbounded certificates.",
        backends: &[Backend::Scalar, Backend::Wasm, Backend::Exact],
        determinism: DeterminismClass::BitExact,
        limits: ResourceLimits {
            max_input_points: 1_000_000,
            max_output_bytes: 64,
            max_memory_bytes: 64 * 1024 * 1024,
            max_time_us: 0,
        },
        topology_critical: false,
        maturity: Maturity::Implemented,
        exactness: ExactnessClass::ExactPredicate,
        allocation: AllocationClass::ColdBounded,
        dimensionality: Dimensionality::D2,
    },
    // ── P11.13 — Rotating calipers + smallest enclosing disk ──
    OpManifest {
        op: "rotating_calipers",
        description: "Rotating calipers: diameter (farthest pair), width (min-width), antipodal pairs over a CCW convex polygon.",
        backends: &[Backend::Scalar, Backend::Wasm, Backend::Exact],
        determinism: DeterminismClass::BitExact,
        limits: ResourceLimits {
            max_input_points: 1_000_000,
            max_output_bytes: 16 * 1024 * 1024,
            max_memory_bytes: 64 * 1024 * 1024,
            max_time_us: 0,
        },
        topology_critical: false,
        maturity: Maturity::Implemented,
        exactness: ExactnessClass::ExactPredicate,
        allocation: AllocationClass::ColdBounded,
        dimensionality: Dimensionality::D2,
    },
    OpManifest {
        op: "smallest_enclosing_disk",
        description: "Smallest enclosing disk (Welzl randomized incremental); seeded determinism + support set certificate.",
        backends: &[Backend::Scalar, Backend::Wasm, Backend::Exact],
        determinism: DeterminismClass::BitExact,
        limits: ResourceLimits {
            max_input_points: 1_000_000,
            max_output_bytes: 64,
            max_memory_bytes: 64 * 1024 * 1024,
            max_time_us: 0,
        },
        topology_critical: false,
        maturity: Maturity::Implemented,
        exactness: ExactnessClass::ExactPredicate,
        allocation: AllocationClass::ColdBounded,
        dimensionality: Dimensionality::D2,
    },
    // ── P11.5 — Monotone partition + triangulation ──
    OpManifest {
        op: "triangulate_polygon",
        description: "Simple-polygon triangulation via monotone partition + linear monotone triangulation, with ear-clipping fallback.",
        backends: &[Backend::Scalar, Backend::Wasm, Backend::Exact],
        determinism: DeterminismClass::BitExact,
        limits: ResourceLimits {
            max_input_points: 100_000,
            max_output_bytes: 16 * 1024 * 1024,
            max_memory_bytes: 128 * 1024 * 1024,
            max_time_us: 0,
        },
        topology_critical: true,
        maturity: Maturity::Implemented,
        exactness: ExactnessClass::ExactPredicate,
        allocation: AllocationClass::ColdBounded,
        dimensionality: Dimensionality::D2,
    },
    // ── P11.6 — Point location in planar subdivisions ──
    OpManifest {
        op: "point_location",
        description: "Point location in planar subdivisions: walking location in triangulations (O(√n) expected) and slab decomposition (O(log n) query, O(n log n) preprocessing).",
        backends: &[Backend::Scalar, Backend::Wasm, Backend::Exact],
        determinism: DeterminismClass::BitExact,
        limits: ResourceLimits {
            max_input_points: 100_000,
            max_output_bytes: 64,
            max_memory_bytes: 128 * 1024 * 1024,
            max_time_us: 0,
        },
        topology_critical: false,
        maturity: Maturity::Implemented,
        exactness: ExactnessClass::ExactPredicate,
        allocation: AllocationClass::ColdBounded,
        dimensionality: Dimensionality::D2,
    },
    // ── P11.6 gap — Trapezoidal map with randomized incremental point location ──
    OpManifest {
        op: "trapezoidal_map",
        description: "Trapezoidal map: randomized incremental construction with search DAG for O(log n) expected point location. Seeded-deterministic insertion order, non-crossing segment input, bounding-box-clipped trapezoids.",
        backends: &[Backend::Scalar, Backend::Wasm, Backend::Exact],
        determinism: DeterminismClass::BitExact,
        limits: ResourceLimits {
            max_input_points: 100_000,
            max_output_bytes: 64,
            max_memory_bytes: 128 * 1024 * 1024,
            max_time_us: 0,
        },
        topology_critical: false,
        maturity: Maturity::Implemented,
        exactness: ExactnessClass::ExactPredicate,
        allocation: AllocationClass::ColdBounded,
        dimensionality: Dimensionality::D2,
    },
    // ── P11.7 — Kirkpatrick hierarchy for O(log n) point location ──
    OpManifest {
        op: "kirkpatrick_hierarchy",
        description: "Kirkpatrick hierarchy: guaranteed O(log n) point location in triangulated planar subdivisions via independent-set vertex removal and retriangulation. Bounding triangle, multi-level refinement, deterministic.",
        backends: &[Backend::Scalar, Backend::Wasm, Backend::Exact],
        determinism: DeterminismClass::BitExact,
        limits: ResourceLimits {
            max_input_points: 100_000,
            max_output_bytes: 64,
            max_memory_bytes: 128 * 1024 * 1024,
            max_time_us: 0,
        },
        topology_critical: false,
        maturity: Maturity::Implemented,
        exactness: ExactnessClass::ExactPredicate,
        allocation: AllocationClass::ColdBounded,
        dimensionality: Dimensionality::D2,
    },
    // ── P11.12 — Simplex/halfspace range reporting ──
    OpManifest {
        op: "range_reporting",
        description: "Simplex and halfspace range reporting: kd-tree (O(√n+k) expected), simplicial partition tree (O(n^{1+ε}+k)), and cutting tree (grid-based, O(log n+k) for halfspace). Cross-validated against brute-force oracle.",
        backends: &[Backend::Scalar, Backend::Wasm, Backend::Exact],
        determinism: DeterminismClass::BitExact,
        limits: ResourceLimits {
            max_input_points: 100_000,
            max_output_bytes: 16 * 1024 * 1024,
            max_memory_bytes: 128 * 1024 * 1024,
            max_time_us: 0,
        },
        topology_critical: false,
        maturity: Maturity::Implemented,
        exactness: ExactnessClass::ExactPredicate,
        allocation: AllocationClass::ColdBounded,
        dimensionality: Dimensionality::D2,
    },
    // ── P11.14 — Ham-sandwich cuts, centrepoints, width coresets ──
    OpManifest {
        op: "ham_sandwich_centrepoint",
        description: "Ham-sandwich cuts (simultaneous bisection of two point sets), centrepoints (Tukey depth ≥ n/3 via arrangement search), and directional-width coresets (Dudley construction, O(1/ε) points).",
        backends: &[Backend::Scalar, Backend::Wasm, Backend::Exact],
        determinism: DeterminismClass::BitExact,
        limits: ResourceLimits {
            max_input_points: 10_000,
            max_output_bytes: 16 * 1024 * 1024,
            max_memory_bytes: 128 * 1024 * 1024,
            max_time_us: 0,
        },
        topology_critical: false,
        maturity: Maturity::Implemented,
        exactness: ExactnessClass::ExactPredicate,
        allocation: AllocationClass::ColdBounded,
        dimensionality: Dimensionality::D2,
    },
    // ── P12.1 — N-ary CSG on 2D polygons + 2D mesh co-refinement ──
    OpManifest {
        op: "nary_csg_2d",
        description: "N-ary CSG operations (union/intersection/difference/symmetric-difference) on N 2D polygons via Sutherland-Hodgman convex-polygon clipping (not DCEL overlays). 2D mesh co-refinement: split two triangle meshes at edge-edge intersections for compatible boundaries.",
        backends: &[Backend::Scalar, Backend::Wasm, Backend::Exact],
        determinism: DeterminismClass::BitExact,
        limits: ResourceLimits {
            max_input_points: 50_000,
            max_output_bytes: 16 * 1024 * 1024,
            max_memory_bytes: 128 * 1024 * 1024,
            max_time_us: 0,
        },
        topology_critical: true,
        maturity: Maturity::Implemented,
        exactness: ExactnessClass::ExactPredicate,
        allocation: AllocationClass::ColdBounded,
        dimensionality: Dimensionality::D2,
    },
    // ── P12.2 — Exact 2D arrangement with exact construction ──
    OpManifest {
        op: "exact_arrangement_2d",
        description: "Exact 2D line arrangement using exact-construction intersection points (ExactPoint2 from exact_kernel). Vertices carry exact rational coordinates; orientation predicates cross-multiply to eliminate division. Zone traversal with exact predicates. Euler V-E+F=2 verified.",
        backends: &[Backend::Scalar, Backend::Exact],
        determinism: DeterminismClass::BitExact,
        limits: ResourceLimits {
            max_input_points: 10_000,
            max_output_bytes: 16 * 1024 * 1024,
            max_memory_bytes: 128 * 1024 * 1024,
            max_time_us: 0,
        },
        topology_critical: true,
        maturity: Maturity::Implemented,
        exactness: ExactnessClass::ExactConstruction,
        allocation: AllocationClass::ColdBounded,
        dimensionality: Dimensionality::D2,
    },
    // ── P12.3 — Exact 3D mesh co-refinement ──
    OpManifest {
        op: "corefine_3d",
        description: "3D mesh co-refinement: split two triangle meshes along their intersection curves for compatible boundaries. BVH-accelerated broad phase (P12.5) reduces candidate pairs from O(nm) to O(n log m + k) with no false negatives vs brute-force oracle. Uses tri_tri_intersect_3_exact for exact-rational intersection points, exact expansion comparison for point dedup, and exact orient_3d for coplanarity tests. Workspace bounded by 42-MiB Sentinel ceiling.",
        backends: &[Backend::Scalar, Backend::Exact],
        determinism: DeterminismClass::BitExact,
        limits: ResourceLimits {
            max_input_points: 50_000,
            max_output_bytes: 32 * 1024 * 1024,
            max_memory_bytes: 256 * 1024 * 1024,
            max_time_us: 0,
        },
        topology_critical: true,
        maturity: Maturity::Implemented,
        exactness: ExactnessClass::ExactConstruction,
        allocation: AllocationClass::ColdBounded,
        dimensionality: Dimensionality::D3,
    },
    // ── P12.4 — Exact 3D boolean operations ──
    OpManifest {
        op: "boolean_3_exact",
        description: "3-D mesh boolean (union/intersection/difference) with exact-rational intersection points. Uses tri_tri_intersect_3_exact for exact construction of split geometry and orient_3d-based ray-triangle intersection for classification. Upgrades boolean_3 from ApproximateMetric to ExactConstruction.",
        backends: &[Backend::Scalar, Backend::Exact],
        determinism: DeterminismClass::BitExact,
        limits: ResourceLimits {
            max_input_points: 50_000,
            max_output_bytes: 32 * 1024 * 1024,
            max_memory_bytes: 256 * 1024 * 1024,
            max_time_us: 0,
        },
        topology_critical: true,
        maturity: Maturity::Implemented,
        exactness: ExactnessClass::ExactConstruction,
        allocation: AllocationClass::ColdBounded,
        dimensionality: Dimensionality::D3,
    },
    // ── P12.2 — Simulation of Simplicity for orient_3d ──
    OpManifest {
        op: "orient_3d_sos",
        description: "3-D orientation predicate with Simulation of Simplicity (Edelsbrunner-Mücke 1990). When orient_3d returns Zero (coplanar), evaluates 12 first-order cofactors (2D orientations in coordinate planes) in order of increasing symbolic-perturbation power. Never returns Zero. Deterministic, zero-heap.",
        backends: &[Backend::Scalar, Backend::Exact],
        determinism: DeterminismClass::BitExact,
        limits: ResourceLimits {
            max_input_points: 4,
            max_output_bytes: 16,
            max_memory_bytes: 1,
            max_time_us: 100,
        },
        topology_critical: true,
        maturity: Maturity::Implemented,
        exactness: ExactnessClass::ExactPredicate,
        allocation: AllocationClass::HotZeroHeap,
        dimensionality: Dimensionality::D3,
    },
    // ── P12.4 — Per-facet exact constrained Delaunay re-triangulation ──
    OpManifest {
        op: "cdt_retriangulate_facet",
        description: "Per-facet constrained Delaunay re-triangulation: given a 3-D triangle and intersection constraint segments on its surface, projects to 2-D (dropping the dominant normal axis), runs conforming Delaunay with exact incircle predicate, and maps back to 3-D. Every constraint edge is present in the output; no output triangle crosses a constraint.",
        backends: &[Backend::Scalar, Backend::Exact],
        determinism: DeterminismClass::BitExact,
        limits: ResourceLimits {
            max_input_points: 100,
            max_output_bytes: 1024 * 1024,
            max_memory_bytes: 4 * 1024 * 1024,
            max_time_us: 0,
        },
        topology_critical: true,
        maturity: Maturity::Implemented,
        exactness: ExactnessClass::ExactPredicate,
        allocation: AllocationClass::ColdBounded,
        dimensionality: Dimensionality::D3,
    },
    // ── P12.6 — Radial sort and Weiler 3-D arrangement model ──
    OpManifest {
        op: "build_arrangement_3d",
        description: "Weiler 3-D arrangement model: radial-sorts facets around non-manifold edges by outward-normal angle, identifies shells (connected closed surface components) and volumetric regions. Validates incidence/involution invariants: every edge has ≥1 facet, every triangle's edges are present, radial ordering matches input facets.",
        backends: &[Backend::Scalar, Backend::Exact],
        determinism: DeterminismClass::BitExact,
        limits: ResourceLimits {
            max_input_points: 50_000,
            max_output_bytes: 16 * 1024 * 1024,
            max_memory_bytes: 128 * 1024 * 1024,
            max_time_us: 0,
        },
        topology_critical: true,
        maturity: Maturity::Implemented,
        exactness: ExactnessClass::ExactPredicate,
        allocation: AllocationClass::ColdBounded,
        dimensionality: Dimensionality::D3,
    },
    // ── P12.7 — Arbitrary n-ary boolean-expression evaluator ──
    OpManifest {
        op: "nary_boolean",
        description: "N-ary boolean-expression evaluator: supports union, intersection, difference, xor, and complement over expression trees with 2+ mesh operands. Uses pairwise reduction of binary boolean_3 operations — which use f64 intersection points, so this op is ApproximateMetric, not ExactConstruction, despite reducing over topology-critical booleans. Region classification via bitmask (u64, up to 64 operands). Deterministic bottom-up evaluation.",
        backends: &[Backend::Scalar, Backend::Exact],
        determinism: DeterminismClass::BitExact,
        limits: ResourceLimits {
            max_input_points: 100_000,
            max_output_bytes: 64 * 1024 * 1024,
            max_memory_bytes: 256 * 1024 * 1024,
            max_time_us: 0,
        },
        // Reduces over binary boolean_3, which is itself topology_critical:false
        // + ApproximateMetric — nary_boolean is no more topology-critical than
        // the f64 booleans it composes, and has no exact fallback to justify the
        // stricter flag. (Was topology_critical:true + ExactConstruction, which
        // overstated both: it neither guarantees topology nor constructs exactly.)
        topology_critical: false,
        maturity: Maturity::Implemented,
        exactness: ExactnessClass::ApproximateMetric,
        allocation: AllocationClass::ColdBounded,
        dimensionality: Dimensionality::D3,
    },
    // ── P12.8 — Coplanar-region simplification and snap rounding ──
    OpManifest {
        op: "simplify_coplanar_regions",
        description: "Coplanar-region simplification: merges adjacent coplanar triangles with matching region labels into larger polygonal regions, then re-triangulates each region via fan triangulation. Uses exact orient_3d for coplanarity testing. Region labels preserved. Deterministic flood-fill with sorted traversal.",
        backends: &[Backend::Scalar, Backend::Exact],
        determinism: DeterminismClass::BitExact,
        limits: ResourceLimits {
            max_input_points: 50_000,
            max_output_bytes: 16 * 1024 * 1024,
            max_memory_bytes: 128 * 1024 * 1024,
            max_time_us: 0,
        },
        topology_critical: true,
        maturity: Maturity::Implemented,
        exactness: ExactnessClass::ExactPredicate,
        allocation: AllocationClass::ColdBounded,
        dimensionality: Dimensionality::D3,
    },
    // ── P12.8b — Snap rounding ──
    OpManifest {
        op: "snap_round_3d",
        description: "Topology-preserving snap rounding: rounds 3D coordinates to a grid with spacing epsilon. Verifies no triangle becomes degenerate after rounding. Fails closed if topology would change.",
        backends: &[Backend::Scalar, Backend::Exact],
        determinism: DeterminismClass::BitExact,
        limits: ResourceLimits {
            max_input_points: 50_000,
            max_output_bytes: 16 * 1024 * 1024,
            max_memory_bytes: 128 * 1024 * 1024,
            max_time_us: 0,
        },
        topology_critical: true,
        maturity: Maturity::Implemented,
        exactness: ExactnessClass::ExactPredicate,
        allocation: AllocationClass::ColdBounded,
        dimensionality: Dimensionality::D3,
    },
    // ── P12.9 — CSG/arrangement .10d sections and repair ──
    OpManifest {
        op: "encode_csg_section",
        description: "Serialize CSG expression tree, exact-point pool, region labels, and output mesh into canonical .10d section with per-section CRC-32C. Round-trip verified: encode → decode is bit-identical. Expression tree uses tagged byte encoding for Operand/Union/Intersection/Difference/Xor/Complement nodes.",
        backends: &[Backend::Scalar, Backend::Exact],
        determinism: DeterminismClass::BitExact,
        limits: ResourceLimits {
            max_input_points: 100_000,
            max_output_bytes: 64 * 1024 * 1024,
            max_memory_bytes: 256 * 1024 * 1024,
            max_time_us: 0,
        },
        topology_critical: true,
        maturity: Maturity::Implemented,
        exactness: ExactnessClass::ExactConstruction,
        allocation: AllocationClass::ColdBounded,
        dimensionality: Dimensionality::D3,
    },
    // ── P12.9b — Mesh repair ──
    OpManifest {
        op: "repair_mesh",
        description: "Mesh repair: removes degenerate triangles, detects and removes duplicate sheets (identical triangles with opposite winding), reports non-manifold edges, extracts shells (connected components). Returns cleaned mesh and repair report.",
        backends: &[Backend::Scalar, Backend::Exact],
        determinism: DeterminismClass::BitExact,
        limits: ResourceLimits {
            max_input_points: 100_000,
            max_output_bytes: 32 * 1024 * 1024,
            max_memory_bytes: 128 * 1024 * 1024,
            max_time_us: 0,
        },
        topology_critical: true,
        maturity: Maturity::Implemented,
        exactness: ExactnessClass::ExactPredicate,
        allocation: AllocationClass::ColdBounded,
        dimensionality: Dimensionality::D3,
    },
    // ── Convex decomposition (Hertel-Mehlhorn + triangulation-only) ──
    OpManifest {
        op: "convex_decomposition",
        description: "Convex decomposition of simple polygons: Hertel-Mehlhorn (triangulate + merge convex pairs, ≤4× optimal) and triangulation-only fallback.",
        backends: &[Backend::Scalar, Backend::Wasm, Backend::Exact],
        determinism: DeterminismClass::BitExact,
        limits: ResourceLimits {
            max_input_points: 100_000,
            max_output_bytes: 16 * 1024 * 1024,
            max_memory_bytes: 128 * 1024 * 1024,
            max_time_us: 0,
        },
        topology_critical: false,
        maturity: Maturity::Implemented,
        exactness: ExactnessClass::ExactPredicate,
        allocation: AllocationClass::ColdBounded,
        dimensionality: Dimensionality::D2,
    },
    // ── P11.3 — DCEL subdivision, overlay, and polygon-set booleans ──
    OpManifest {
        op: "dcel_overlay",
        description: "DCEL planar overlay of two simple polygons: split edges at intersections, label faces by (in_a, in_b), extract union/intersection/difference/xor boundary cycles with holes; Euler and area identities.",
        backends: &[Backend::Scalar, Backend::Wasm, Backend::Exact],
        determinism: DeterminismClass::BitExact,
        limits: ResourceLimits {
            max_input_points: 100_000,
            max_output_bytes: 64 * 1024 * 1024,
            max_memory_bytes: 128 * 1024 * 1024,
            max_time_us: 0,
        },
        topology_critical: true,
        maturity: Maturity::Implemented,
        exactness: ExactnessClass::ExactPredicate,
        allocation: AllocationClass::ColdBounded,
        dimensionality: Dimensionality::D2,
    },
    // ── P11.8 — Arrangements, point-line duality, topological sweep ──
    OpManifest {
        op: "line_arrangement",
        description: "Line arrangement construction (all pairwise intersections → V/E/F subdivision with bbox clipping), zone traversal (face sequence crossed by a query line), and point-line duality (round-trip + incidence preservation).",
        backends: &[Backend::Scalar, Backend::Wasm, Backend::Exact],
        determinism: DeterminismClass::BitExact,
        limits: ResourceLimits {
            max_input_points: 10_000,
            max_output_bytes: 64 * 1024 * 1024,
            max_memory_bytes: 128 * 1024 * 1024,
            max_time_us: 0,
        },
        topology_critical: true,
        maturity: Maturity::Implemented,
        exactness: ExactnessClass::ExactPredicate,
        allocation: AllocationClass::ColdBounded,
        dimensionality: Dimensionality::D2,
    },
    // ── P11.10 — Interval, segment, priority-search and range trees ──
    OpManifest {
        op: "range_trees",
        description: "Interval tree (stabbing), segment tree (stabbing), priority search tree (x-range + y-bounded), 1-D and 2-D range trees (orthogonal range reporting/counting). All results match linear-scan oracles; caller buffers report exact capacity needs.",
        backends: &[Backend::Scalar, Backend::Wasm, Backend::Exact],
        determinism: DeterminismClass::BitExact,
        limits: ResourceLimits {
            max_input_points: 100_000,
            max_output_bytes: 64 * 1024 * 1024,
            max_memory_bytes: 128 * 1024 * 1024,
            max_time_us: 0,
        },
        topology_critical: false,
        maturity: Maturity::Implemented,
        exactness: ExactnessClass::ExactPredicate,
        allocation: AllocationClass::ColdBounded,
        dimensionality: Dimensionality::D2,
    },
    // ── P13.1 — Mesh quality metrics and size/anisotropy fields ──
    OpManifest {
        op: "mesh_quality",
        description: "Per-element triangle/tet quality (min/max angle, radius-edge, aspect, dihedral, scaled Jacobian, signed volume) and isotropic size / anisotropic metric-tensor fields with field-conformance checking. Inverted/degenerate cells fail closed.",
        backends: &[Backend::Scalar, Backend::Wasm],
        determinism: DeterminismClass::BitExact,
        limits: ResourceLimits {
            max_input_points: 1_000_000,
            max_output_bytes: 64 * 1024 * 1024,
            max_memory_bytes: 128 * 1024 * 1024,
            max_time_us: 0,
        },
        topology_critical: false,
        maturity: Maturity::Implemented,
        exactness: ExactnessClass::ApproximateMetric,
        allocation: AllocationClass::ColdBounded,
        dimensionality: Dimensionality::D3,
    },
    // ── P13.2 — Delaunay refinement for PSLGs with Steiner points ──
    OpManifest {
        op: "delaunay_refine_2",
        description: "Ruppert Delaunay refinement of a 2-D PSLG: segment encroachment recovery + bad-triangle circumcenter insertion. Terminates for min-angle <= 20.7 deg; meets declared angle/size targets.",
        backends: &[Backend::Scalar, Backend::Wasm],
        determinism: DeterminismClass::BitExact,
        limits: ResourceLimits {
            max_input_points: 100_000,
            max_output_bytes: 128 * 1024 * 1024,
            max_memory_bytes: 256 * 1024 * 1024,
            max_time_us: 0,
        },
        topology_critical: true,
        maturity: Maturity::Implemented,
        exactness: ExactnessClass::TopologyGuaranteed,
        allocation: AllocationClass::ColdBounded,
        dimensionality: Dimensionality::D2,
    },
    // ── P13.3 — Optimal fixed-vertex triangulation objectives ──
    OpManifest {
        op: "triangulation_optimise",
        description: "Edge-flip hill-climbing to optimise a fixed-vertex triangulation for a declared objective (max-min angle, min-max angle, min-max edge ratio, min-max radius-edge, max-min area, min-max aspect). Convex-quad flip validity; deterministic tie-breaking.",
        backends: &[Backend::Scalar, Backend::Wasm],
        determinism: DeterminismClass::BitExact,
        limits: ResourceLimits {
            max_input_points: 50_000,
            max_output_bytes: 32 * 1024 * 1024,
            max_memory_bytes: 64 * 1024 * 1024,
            max_time_us: 0,
        },
        topology_critical: false,
        maturity: Maturity::Implemented,
        exactness: ExactnessClass::ApproximateMetric,
        allocation: AllocationClass::ColdBounded,
        dimensionality: Dimensionality::D2,
    },
    // ── P13.4 — Quadtree balanced meshing (2-D) ──
    OpManifest {
        op: "quadtree_balanced_mesh_2d",
        description: "Size-field-driven quadtree decomposition with 2:1 balance and conforming triangulation. Hanging edge-midpoints resolved by per-cell centre-fan templates; shared vertices deduplicated on the finest-level grid. Identical input → bit-identical mesh.",
        backends: &[Backend::Scalar, Backend::Wasm],
        determinism: DeterminismClass::BitExact,
        limits: ResourceLimits {
            max_input_points: 1_000_000,
            max_output_bytes: 128 * 1024 * 1024,
            max_memory_bytes: 256 * 1024 * 1024,
            max_time_us: 0,
        },
        topology_critical: true,
        maturity: Maturity::Implemented,
        exactness: ExactnessClass::TopologyGuaranteed,
        allocation: AllocationClass::ColdBounded,
        dimensionality: Dimensionality::D2,
    },
    // ── P13.4 — Octree balanced meshing (3-D) ──
    OpManifest {
        op: "octree_balanced_mesh_3d",
        description: "Size-field-driven octree decomposition with 2:1 balance, leaf hexahedron extraction (deduplicated vertices), and 6-tet-per-hex Freudenthal split. Hex mesh preserves hanging nodes (conforming product); tet split is conforming for uniform meshes and documented as non-conforming across T-junction faces for graded meshes.",
        backends: &[Backend::Scalar, Backend::Wasm],
        determinism: DeterminismClass::BitExact,
        limits: ResourceLimits {
            max_input_points: 1_000_000,
            max_output_bytes: 256 * 1024 * 1024,
            max_memory_bytes: 512 * 1024 * 1024,
            max_time_us: 0,
        },
        topology_critical: true,
        maturity: Maturity::Implemented,
        exactness: ExactnessClass::TopologyGuaranteed,
        allocation: AllocationClass::ColdBounded,
        dimensionality: Dimensionality::D3,
    },
    // ── P13.5 — Advancing-front surface meshing (2-D) ──
    OpManifest {
        op: "advancing_front_surface_2d",
        description: "Advancing-front 2-D triangulation from a closed CCW boundary polyline and a target-size function. Shortest-edge-first deterministic ordering; equilateral-vertex placement with snap-to-existing; self-crossing guard rejects any candidate whose new edges properly intersect a non-adjacent front edge; front collapses on exhaustion guaranteeing monotone shrinkage. Identical input → bit-identical mesh.",
        backends: &[Backend::Scalar, Backend::Wasm],
        determinism: DeterminismClass::BitExact,
        limits: ResourceLimits {
            max_input_points: 1_000_000,
            max_output_bytes: 128 * 1024 * 1024,
            max_memory_bytes: 256 * 1024 * 1024,
            max_time_us: 0,
        },
        topology_critical: true,
        maturity: Maturity::Implemented,
        exactness: ExactnessClass::TopologyGuaranteed,
        allocation: AllocationClass::ColdBounded,
        dimensionality: Dimensionality::D2,
    },
    // ── P13.5 — Advancing-front volume meshing (3-D) ──
    OpManifest {
        op: "advancing_front_volume_3d",
        description: "Advancing-front 3-D tetrahedralisation from a closed orientable surface mesh and a target-size function. Smallest-area-face-first deterministic ordering; inradius-offset apex placement with snap-to-existing; self-crossing guard rejects any candidate whose new edges properly intersect a non-adjacent front face (Möller–Trumbore); front collapses on exhaustion guaranteeing monotone shrinkage. Identical input → bit-identical mesh.",
        backends: &[Backend::Scalar, Backend::Wasm],
        determinism: DeterminismClass::BitExact,
        limits: ResourceLimits {
            max_input_points: 1_000_000,
            max_output_bytes: 256 * 1024 * 1024,
            max_memory_bytes: 512 * 1024 * 1024,
            max_time_us: 0,
        },
        topology_critical: true,
        maturity: Maturity::Implemented,
        exactness: ExactnessClass::TopologyGuaranteed,
        allocation: AllocationClass::ColdBounded,
        dimensionality: Dimensionality::D3,
    },
    // ── P13.7 — Tetrahedral quality improvement & sliver handling ──
    OpManifest {
        op: "tet_quality_improve",
        description: "Tetrahedral mesh quality improvement via four monotonic passes (2-3/3-2 flip, optimisation-based smooth, Delaunay cavity Steiner insertion, sliver exudation by local perturbation). Boundary faces and fixed vertices are never moved; every accepted operation strictly increases the local worst-case score under the selected objective (min dihedral / radius-edge ratio / scaled Jacobian) and preserves positive tet orientation. Identical input -> bit-identical mesh.",
        backends: &[Backend::Scalar, Backend::Wasm],
        determinism: DeterminismClass::BitExact,
        limits: ResourceLimits {
            max_input_points: 1_000_000,
            max_output_bytes: 256 * 1024 * 1024,
            max_memory_bytes: 512 * 1024 * 1024,
            max_time_us: 0,
        },
        topology_critical: true,
        maturity: Maturity::Implemented,
        exactness: ExactnessClass::TopologyGuaranteed,
        allocation: AllocationClass::ColdBounded,
        dimensionality: Dimensionality::D3,
    },
    // ── P13.8 — Anisotropic remeshing with feature preservation ──
    OpManifest {
        op: "anisotropic_remesh",
        description: "Anisotropic surface remeshing against a metric-tensor field: metric-long edge refinement, metric-weighted relaxation, tagged corner/crease endpoint preservation, and BVH-pruned exact closest-triangle projection. Public output is caller-buffered; internal scratch is Tier-2 cold construction.",
        backends: &[Backend::Scalar, Backend::Wasm],
        determinism: DeterminismClass::BitExact,
        limits: ResourceLimits {
            max_input_points: 1_000_000,
            max_output_bytes: 256 * 1024 * 1024,
            max_memory_bytes: 512 * 1024 * 1024,
            max_time_us: 0,
        },
        topology_critical: true,
        maturity: Maturity::Implemented,
        exactness: ExactnessClass::TopologyGuaranteed,
        allocation: AllocationClass::ColdBounded,
        dimensionality: Dimensionality::D3,
    },
    // ── P13.9 — Mixed-cell topology foundation ──
    OpManifest {
        op: "mixed_cell_topology",
        description: "Flat mixed-cell topology for triangles, quads, tetrahedra, and hexahedra: POD cell records, validation, triangle/tet conversion, hex-to-tet loss-reporting path, and deterministic boundary-face extraction.",
        backends: &[Backend::Scalar, Backend::Wasm],
        determinism: DeterminismClass::BitExact,
        limits: ResourceLimits {
            max_input_points: 1_000_000,
            max_output_bytes: 256 * 1024 * 1024,
            max_memory_bytes: 512 * 1024 * 1024,
            max_time_us: 0,
        },
        topology_critical: true,
        maturity: Maturity::Implemented,
        exactness: ExactnessClass::TopologyGuaranteed,
        allocation: AllocationClass::ColdBounded,
        dimensionality: Dimensionality::D3,
    },
    // ── P14.1-P14.6 — DDG operators and surface solvers ──
    OpManifest {
        op: "ddg_operators",
        description: "Discrete differential-geometry operators: oriented simplex boundaries, vector areas, vertex normals, area gradients, angle-defect curvature, cotangent Laplacian, lumped mass, Jacobi Poisson, heat step, and mean-curvature-flow step.",
        backends: &[Backend::Scalar, Backend::Wasm],
        determinism: DeterminismClass::BitExact,
        limits: ResourceLimits {
            max_input_points: 1_000_000,
            max_output_bytes: 256 * 1024 * 1024,
            max_memory_bytes: 512 * 1024 * 1024,
            max_time_us: 0,
        },
        topology_critical: false,
        maturity: Maturity::Implemented,
        exactness: ExactnessClass::ApproximateMetric,
        allocation: AllocationClass::ColdBounded,
        dimensionality: Dimensionality::D3,
    },
    // ── P13.6 — Screened-Poisson reconstruction ──
    OpManifest {
        op: "screened_poisson_reconstruct_3d",
        description: "Screened-Poisson height-field reconstruction over oriented samples: assembles and solves a screened regular-grid Laplacian system, reports residual/sample error, and emits deterministic triangles.",
        backends: &[Backend::Scalar, Backend::Wasm],
        determinism: DeterminismClass::BitExact,
        limits: ResourceLimits {
            max_input_points: 1_000_000,
            max_output_bytes: 256 * 1024 * 1024,
            max_memory_bytes: 512 * 1024 * 1024,
            max_time_us: 0,
        },
        topology_critical: true,
        maturity: Maturity::Implemented,
        exactness: ExactnessClass::TopologyGuaranteed,
        allocation: AllocationClass::ColdBounded,
        dimensionality: Dimensionality::D3,
    },
    // ── P13.10 — FEM-ready certificates ──
    OpManifest {
        op: "fem_mesh_certificate",
        description: "FEM-ready mesh certificate with mixed-cell topology validation, material/boundary metadata counts, boundary/interior-face counts, quality extrema, provenance hash, and canonical CRC-guarded encoding.",
        backends: &[Backend::Scalar, Backend::Wasm],
        determinism: DeterminismClass::BitExact,
        limits: ResourceLimits {
            max_input_points: 1_000_000,
            max_output_bytes: 64 * 1024 * 1024,
            max_memory_bytes: 128 * 1024 * 1024,
            max_time_us: 0,
        },
        topology_critical: true,
        maturity: Maturity::Implemented,
        exactness: ExactnessClass::TopologyGuaranteed,
        allocation: AllocationClass::ColdBounded,
        dimensionality: Dimensionality::D3,
    },
    // P15 - Deterministic geometry primitives and graph builders
    OpManifest {
        op: "deterministic_geometry",
        description: "Scalar deterministic reference layer for scan/reduce, nearest pairs, all-nearest neighbours, kNN graphs, Euclidean MST, and greedy geometric spanners with stable tie-breaking.",
        backends: &[Backend::Scalar, Backend::Wasm],
        determinism: DeterminismClass::BitExact,
        limits: ResourceLimits {
            max_input_points: 1_000_000,
            max_output_bytes: 256 * 1024 * 1024,
            max_memory_bytes: 512 * 1024 * 1024,
            max_time_us: 0,
        },
        topology_critical: false,
        maturity: Maturity::Implemented,
        exactness: ExactnessClass::ApproximateMetric,
        allocation: AllocationClass::ColdBounded,
        dimensionality: Dimensionality::D3,
    },
    // P16 - Motion planning scalar reference layer
    OpManifest {
        op: "motion_planning",
        description: "Deterministic 2-D motion-planning primitives: SE(2) pose normalization, polygonal segment collision, visibility-graph shortest path, and seeded roadmap construction.",
        backends: &[Backend::Scalar, Backend::Wasm],
        determinism: DeterminismClass::BitExact,
        limits: ResourceLimits {
            max_input_points: 1_000_000,
            max_output_bytes: 256 * 1024 * 1024,
            max_memory_bytes: 512 * 1024 * 1024,
            max_time_us: 0,
        },
        topology_critical: false,
        maturity: Maturity::Implemented,
        exactness: ExactnessClass::ApproximateMetric,
        allocation: AllocationClass::ColdBounded,
        dimensionality: Dimensionality::D2,
    },
    // P17 - Mathematical geometry scalar reference layer
    OpManifest {
        op: "math_geometry",
        description: "Dimension-focused mathematical geometry helpers: affine frames, tetrahedral barycentrics, quaternions/SLERP, translation registration, and AABB separating-plane certificates.",
        backends: &[Backend::Scalar, Backend::Wasm],
        determinism: DeterminismClass::BitExact,
        limits: ResourceLimits {
            max_input_points: 1_000_000,
            max_output_bytes: 128 * 1024 * 1024,
            max_memory_bytes: 256 * 1024 * 1024,
            max_time_us: 0,
        },
        topology_critical: false,
        maturity: Maturity::Implemented,
        exactness: ExactnessClass::ApproximateMetric,
        allocation: AllocationClass::ColdBounded,
        dimensionality: Dimensionality::DN,
    },
    // P18 - Parametric CAD scalar reference layer
    OpManifest {
        op: "parametric_cad",
        description: "Parametric CAD primitives: Bezier/B-spline/NURBS evaluation, tensor-product surface evaluation, tube generation along polylines, and exhaustive shape-distance metrics.",
        backends: &[Backend::Scalar, Backend::Wasm],
        determinism: DeterminismClass::BitExact,
        limits: ResourceLimits {
            max_input_points: 1_000_000,
            max_output_bytes: 256 * 1024 * 1024,
            max_memory_bytes: 512 * 1024 * 1024,
            max_time_us: 0,
        },
        topology_critical: false,
        maturity: Maturity::Implemented,
        exactness: ExactnessClass::ApproximateMetric,
        allocation: AllocationClass::ColdBounded,
        dimensionality: Dimensionality::D3,
    },
    // P19 - Geometry integration descriptors and conformance records
    OpManifest {
        op: "geometry_integration",
        description: "Versioned schema descriptors, typed operation descriptors, cross-target conformance records, and literature-expansion closeout summaries for the computational-geometry stack.",
        backends: &[Backend::Scalar, Backend::Wasm],
        determinism: DeterminismClass::BitExact,
        limits: ResourceLimits {
            max_input_points: 1_000_000,
            max_output_bytes: 64 * 1024 * 1024,
            max_memory_bytes: 128 * 1024 * 1024,
            max_time_us: 0,
        },
        topology_critical: false,
        maturity: Maturity::Implemented,
        exactness: ExactnessClass::Structural,
        allocation: AllocationClass::ColdBounded,
        dimensionality: Dimensionality::DimensionIndependent,
    },
];
