use super::super::row::{Contract, SpecTool};
use crate::browser::tool_proficiency::Proficiency;
use crate::tool_chest::core::intent_bus::ActionType;
use crate::tool_chest::core::tool::ToolKind;

const T: &str = "productions";
const TL: &str = "Productions";

pub(super) static ROWS: &[SpecTool] = &[
    SpecTool::new(
        T,
        TL,
        "cue-stack",
        "Cue stack",
        "productions:add-cue",
        "Add cue",
        "Add a cue to the stack.",
        "timeline",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Novice,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "cue-stack",
        "Cue stack",
        "productions:edit-cue",
        "Edit cue",
        "Change the selected cue.",
        "timeline",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Novice,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "cue-stack",
        "Cue stack",
        "productions:cue-sequence",
        "Cue order",
        "Order cues in the stack.",
        "timeline",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Intermediate,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "cue-stack",
        "Cue stack",
        "productions:cue-trigger",
        "Cue trigger",
        "Fire by hand, time, event, or SMPTE.",
        "timeline",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Intermediate,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "cue-stack",
        "Cue stack",
        "productions:cue-fade",
        "Cue fade",
        "Set fade in, fade out, and curve.",
        "timeline",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Intermediate,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "cue-stack",
        "Cue stack",
        "productions:cue-go",
        "Go",
        "Fire the next cue in the stack.",
        "timeline",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Novice,
        Contract::Gated("Needs a lighting desk or DMX universe to fire the next cue."),
    ),
    SpecTool::new(
        T,
        TL,
        "show-control",
        "Show control",
        "productions:smpte-sync",
        "SMPTE sync",
        "Lock the show to SMPTE timecode.",
        "timeline",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Expert,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "show-control",
        "Show control",
        "productions:midi-timecode",
        "MIDI timecode",
        "Lock the show to MIDI timecode.",
        "timeline",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Expert,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "show-control",
        "Show control",
        "productions:art-net-config",
        "Art-Net",
        "Set Art-Net network and universes.",
        "light",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Expert,
        Contract::Gated("Needs a lighting desk and a DMX universe on Art-Net."),
    ),
    SpecTool::new(
        T,
        TL,
        "show-control",
        "Show control",
        "productions:osc-config",
        "OSC",
        "Set Open Sound Control addresses.",
        "timeline",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Expert,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "show-control",
        "Show control",
        "productions:timeline-trigger",
        "Timeline trigger",
        "Map timeline positions to triggers.",
        "timeline",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Intermediate,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "inspect",
        "Inspect",
        "productions:inspect-dmx-monitor",
        "DMX monitor",
        "Watch live DMX channel values.",
        "inspect",
        ToolKind::Query,
        ActionType::Query,
        Proficiency::Intermediate,
        Contract::Gated("Needs a live DMX universe to watch channel values."),
    ),
    SpecTool::new(
        T,
        TL,
        "inspect",
        "Inspect",
        "productions:fixture-report",
        "Fixture report",
        "Report patched, online, and error fixtures.",
        "inspect",
        ToolKind::Query,
        ActionType::Query,
        Proficiency::Intermediate,
        Contract::Gated("Needs a lighting desk to report patched and online fixtures."),
    ),
    SpecTool::new(
        T,
        TL,
        "inspect",
        "Inspect",
        "productions:projection-analyser",
        "Projection analyser",
        "Check brightness, coverage, and overlap.",
        "inspect",
        ToolKind::Query,
        ActionType::Query,
        Proficiency::Intermediate,
        Contract::Live("Render.scene"),
    ),
    SpecTool::new(
        T,
        TL,
        "inspect",
        "Inspect",
        "productions:power-calculator",
        "Power draw",
        "Add up the show's total power draw.",
        "inspect",
        ToolKind::Query,
        ActionType::Query,
        Proficiency::Intermediate,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "inspect",
        "Inspect",
        "productions:metadata-view",
        "Production details",
        "Show production metadata.",
        "inspect",
        ToolKind::Query,
        ActionType::Query,
        Proficiency::Novice,
        Contract::Local,
    ),
];
