use super::super::row::{Contract, SpecTool};
use crate::browser::tool_proficiency::Proficiency;
use crate::tool_chest::core::intent_bus::ActionType;
use crate::tool_chest::core::tool::ToolKind;

const T: &str = "productions";
const TL: &str = "Productions";

pub(super) static ROWS: &[SpecTool] = &[
    SpecTool::new(
        T,
        TL,
        "dmx",
        "DMX",
        "productions:add-universe",
        "Add universe",
        "Add a DMX universe to this show.",
        "light",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Expert,
        Contract::Gated("Needs a lighting desk to add a DMX universe."),
    ),
    SpecTool::new(
        T,
        TL,
        "dmx",
        "DMX",
        "productions:patch-fixture",
        "Patch fixture",
        "Patch a fixture onto a DMX address.",
        "light",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Expert,
        Contract::Gated("Needs a DMX universe to patch a fixture onto a channel."),
    ),
    SpecTool::new(
        T,
        TL,
        "dmx",
        "DMX",
        "productions:unpatch-fixture",
        "Unpatch fixture",
        "Remove a fixture from the patch.",
        "light",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Expert,
        Contract::Gated("Needs a lighting desk to unpatch a fixture."),
    ),
    SpecTool::new(
        T,
        TL,
        "dmx",
        "DMX",
        "productions:fixture-profile",
        "Fixture profile",
        "Assign a channel map to a fixture.",
        "light",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Expert,
        Contract::Gated("Needs a lighting desk to assign a fixture profile."),
    ),
    SpecTool::new(
        T,
        TL,
        "dmx",
        "DMX",
        "productions:channel-assign",
        "Channel map",
        "Assign a custom channel map to a fixture.",
        "light",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Expert,
        Contract::Gated("Needs a patched DMX universe to assign channels."),
    ),
    SpecTool::new(
        T,
        TL,
        "dmx",
        "DMX",
        "productions:dmx-monitor",
        "DMX monitor",
        "Watch live DMX channel values.",
        "light",
        ToolKind::Query,
        ActionType::Query,
        Proficiency::Intermediate,
        Contract::Gated("Needs a live DMX universe to watch channel values."),
    ),
    SpecTool::new(
        T,
        TL,
        "dmx",
        "DMX",
        "productions:dmx-scene",
        "Save scene",
        "Save the current DMX look as a scene.",
        "light",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Intermediate,
        Contract::Gated("Needs a lighting desk to save a DMX scene."),
    ),
    SpecTool::new(
        T,
        TL,
        "dmx",
        "DMX",
        "productions:dmx-cue",
        "DMX cue",
        "Turn a saved scene into a cue with a fade.",
        "light",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Intermediate,
        Contract::Gated("Needs a lighting desk to turn a scene into a cue."),
    ),
    SpecTool::new(
        T,
        TL,
        "fixtures",
        "Fixtures",
        "productions:add-moving-head",
        "Moving head",
        "Place a moving-head fixture.",
        "light",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Intermediate,
        Contract::Gated("Needs a lighting desk to place a moving-head fixture."),
    ),
    SpecTool::new(
        T,
        TL,
        "fixtures",
        "Fixtures",
        "productions:add-led-par",
        "LED par",
        "Place an LED par fixture.",
        "light",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Novice,
        Contract::Gated("Needs a lighting desk to place an LED par."),
    ),
    SpecTool::new(
        T,
        TL,
        "fixtures",
        "Fixtures",
        "productions:add-laser",
        "Laser",
        "Place a laser fixture.",
        "light",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Expert,
        Contract::Gated("Needs a lighting desk to place a laser fixture."),
    ),
    SpecTool::new(
        T,
        TL,
        "fixtures",
        "Fixtures",
        "productions:add-strobe",
        "Strobe",
        "Place a strobe fixture.",
        "light",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Intermediate,
        Contract::Gated("Needs a lighting desk to place a strobe."),
    ),
    SpecTool::new(
        T,
        TL,
        "fixtures",
        "Fixtures",
        "productions:add-hazer",
        "Hazer",
        "Place a haze machine.",
        "light",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Intermediate,
        Contract::Gated("Needs a lighting desk to place a haze machine."),
    ),
    SpecTool::new(
        T,
        TL,
        "fixtures",
        "Fixtures",
        "productions:fixture-position",
        "Fixture position",
        "Set hang position and aim of a fixture.",
        "light",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Intermediate,
        Contract::Gated("Needs a lighting desk to set fixture hang and aim."),
    ),
];
