use super::super::row::{Contract, SpecTool};
use crate::browser::tool_proficiency::Proficiency;
use crate::tool_chest::core::intent_bus::ActionType;
use crate::tool_chest::core::tool::ToolKind;

const T: &str = "productions";
const TL: &str = "Productions";

pub(super) static ROWS: &[SpecTool] = &[
    SpecTool::new(
        T,
        TL,
        "lighting",
        "Lighting",
        "productions:colour-mix",
        "Colour mix",
        "Set fixture colour mix.",
        "light",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Novice,
        Contract::Gated("Needs a lighting desk to mix fixture colour."),
    ),
    SpecTool::new(
        T,
        TL,
        "lighting",
        "Lighting",
        "productions:beam-shape",
        "Beam shape",
        "Set zoom, focus, and iris.",
        "light",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Intermediate,
        Contract::Gated("Needs a lighting desk to set zoom, focus, and iris."),
    ),
    SpecTool::new(
        T,
        TL,
        "lighting",
        "Lighting",
        "productions:gobo-select",
        "Gobo",
        "Pick and rotate a gobo.",
        "light",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Intermediate,
        Contract::Gated("Needs a lighting desk to pick and rotate a gobo."),
    ),
    SpecTool::new(
        T,
        TL,
        "lighting",
        "Lighting",
        "productions:position-set",
        "Pan and tilt",
        "Set pan and tilt on moving fixtures.",
        "light",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Novice,
        Contract::Gated("Needs a lighting desk to set pan and tilt."),
    ),
    SpecTool::new(
        T,
        TL,
        "lighting",
        "Lighting",
        "productions:intensity-set",
        "Intensity",
        "Set fixture intensity from dark to full.",
        "light",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Novice,
        Contract::Gated("Needs a lighting desk to set fixture intensity."),
    ),
    SpecTool::new(
        T,
        TL,
        "lighting",
        "Lighting",
        "productions:effect-run",
        "Lighting effect",
        "Run a chase, wave, random, or ramp.",
        "light",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Expert,
        Contract::Gated("Needs a lighting desk to run a chase, wave, or ramp."),
    ),
    SpecTool::new(
        T,
        TL,
        "projection",
        "Projection",
        "productions:add-surface",
        "Add surface",
        "Add a flat, curved, or architectural projection surface.",
        "stage",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Novice,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "projection",
        "Projection",
        "productions:surface-map",
        "Map surface",
        "Map content onto the surface geometry.",
        "stage",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Intermediate,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "projection",
        "Projection",
        "productions:edge-blend",
        "Edge blend",
        "Blend overlapping projector edges.",
        "stage",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Expert,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "projection",
        "Projection",
        "productions:geometry-correct",
        "Geometry correct",
        "Apply keystone and warp correction.",
        "stage",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Expert,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "projection",
        "Projection",
        "productions:calibration-point",
        "Calibration point",
        "Pin a calibration point on the surface.",
        "stage",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Intermediate,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "projection",
        "Projection",
        "productions:projection-content",
        "Projection content",
        "Assign a clip or still to this surface.",
        "stage",
        ToolKind::RunAction,
        ActionType::Mutate,
        Proficiency::Novice,
        Contract::Local,
    ),
    SpecTool::new(
        T,
        TL,
        "projection",
        "Projection",
        "productions:projection-preview",
        "Preview projection",
        "Preview the mapped projection.",
        "stage",
        ToolKind::Query,
        ActionType::Query,
        Proficiency::Novice,
        Contract::Live("Render.scene"),
    ),
];
