//! Command-palette labels that place an implemented specialist container.
//!
//! Keep this routing table separate from the catalogue so palette dispatch
//! cannot silently drift back to notification-only behavior.

pub(super) fn container_for(label: &str) -> Option<(&'static str, &str)> {
    Some(match label {
        "Browse Ontology" => ("ontology", "Ontology Browser"),
        "Open Social Graph" => ("social", "Social Graph"),
        "Open Pulse Stream" => ("pulse", "Pulse Stream"),
        "Open Aura (SHACL)" => ("aura", "Aura / SHACL"),
        "Open Map (GIS)" => ("map", "Map / GIS"),
        "Open VibeScript Console" => ("code", "VibeScript Console"),
        "Open Rights & Agreements" => ("rights", "Rights & Agreements"),
        "Open Wallet" => ("wallet", "Wallet"),

        "Project Sheet" => ("project_sheet", label),
        "Work Items Kanban" => ("kanban", label),
        "Budget & Finance" => ("budget", label),
        "Cost Base & Obligation" => ("cost_base", label),
        "Deliverables & Artifacts" => ("deliverable", label),
        "Reviews & Decisions" => ("review", label),
        "Discussion" => ("discussion", label),
        "Roadmap & Phases" => ("roadmap", label),
        "Commons Publication" => ("commons", label),
        "New Agreement" | "Agreement Builder" => ("agreement_builder", "Agreement Builder"),
        "Compensation Model" => ("compensation_model", label),
        "Contribution Ledger" => ("contribution_ledger", label),
        "License Builder" => ("license_builder", label),
        "Obligation Tracker" => ("obligation_tracker", label),
        "IP Registry" => ("ip_registry", label),
        "Data Sources" => ("data_sources", label),
        "Disputes" => ("disputes", label),
        "Complaints" => ("complaints", label),
        "Corrections" => ("corrections", label),
        "Governance Meetings" => ("governance_meetings", label),
        "Conflict of Interest" => ("conflict_of_interest", label),
        "Onboarding" => ("onboarding", label),
        "Bulk Import" => ("bulk_import", label),
        "Knowledge Base" => ("knowledge_base", label),
        "Agent Console" => ("agent_console", label),
        "Dashboard" => ("dashboard", label),
        "Wiki" => ("wiki", label),
        "Governance" => ("governance", label),
        "Credentials" => ("credentials", label),
        "Token Manager" => ("token_mgr", label),
        "Awards" => ("awards", label),
        "Gantt Chart" => ("gantt", label),
        "Timeline" => ("timeline", label),
        "Calendar" => ("calendar", label),
        "Document Management" => ("doc_mgmt", label),
        "Resource Report" => ("resource_report", label),
        "Time Tracking" => ("time_tracking", label),
        "Voting" => ("voting", label),
        "Risk Register" => ("risk", label),
        "Task List" => ("task_list", label),
        "Issues" => ("issues", label),
        "Asset Manager" => ("asset_mgr", label),
        "Bounties" => ("bounties", label),
        "Automation" => ("automation", label),
        "Analytics" => ("analytics", label),
        "Events" => ("events", label),
        "News" => ("news", label),
        "Portfolio" => ("portfolio", label),
        "Integrations" => ("integrations", label),
        "Retrospective" => ("retrospective", label),

        "Evaluate Deontic Contract" => ("rights", label),
        "Jural Relations Editor" => ("rights", label),
        "Breach Log" => ("rights", label),
        "Grant Consent" => ("rights", label),
        "Send Payment" | "Receive Payment" => ("wallet", "Wallet"),
        "Tax Suite Editor" => ("finance", label),
        "Compute Cost Receipts" => ("cost_base", label),

        "Health Overview" => ("health_overview", label),
        "Clinical Calculators" => ("health_calculators", label),
        "Compound Evidence Explorer" => ("chemical_explorer", label),
        "Conditions" => ("conditions", label),
        "Clinical Reports" => ("clinical_reports", label),
        "Lab Results" => ("lab_results", label),
        "Medications" => ("medications", label),
        "Vitals" => ("vitals", label),
        "Mental Wellbeing" => ("mental_wellbeing", label),
        "Therapy Notes" => ("therapy_notes", label),
        "Sleep" => ("sleep", label),
        "Diet" => ("diet", label),
        "Physical Activity" => ("physical_activity", label),
        "Immunizations" => ("immunizations", label),
        "Procedures" => ("procedures", label),
        "Family History" => ("family_history", label),
        "Hypotheses" => ("hypotheses", label),
        "Biometrics" => ("biometrics", label),
        "Health Documents" => ("health_documents", label),
        "Welfare Support" => ("welfare_support", label),
        "Life Records" => ("life_records", label),
        "Authority Attestations" => ("authority_attestations", label),
        "Safeguards" => ("safeguards", label),
        "Disclosure Log" => ("disclosure_log", label),

        "Scene View" => ("scene_view", label),
        "Animation Timeline" => ("animation_timeline", label),
        "Desk Surface" => ("desk_surface", label),
        "Transport" => ("transport", label),
        "Routing Matrix" => ("routing_matrix", label),
        "Spatial Audio" => ("spatial_audio", label),
        "Dataset Registry" => ("dataset_registry", label),
        "Dataset Importer" => ("dataset_importer", label),
        "Presentation Editor" => ("presentation_editor", label),
        "View Canvas" => ("view_canvas", label),
        "Scene Graph" => ("scene_graph", label),
        "Material Editor" => ("material_editor", label),
        "Lighting Editor" => ("lighting_editor", label),
        "Tensor Inspector" => ("tensor_inspector", label),
        "Asset Library" => ("asset_library", label),
        "Channel Strip" => ("channel_strip", label),
        "Meter Bridge" => ("meter_bridge", label),
        "Automation Lanes" => ("automation_lanes", label),
        "Annotation Panel" => ("annotation_panel", label),
        "Lineage Graph" => ("lineage_graph", label),
        "LOD Chain" => ("lod_chain", label),
        "Shadow Settings" => ("shadow_settings", label),
        "GIS Maps" => ("gis_maps", label),
        "Ragdoll / Skin" => ("ragdoll_skin", label),
        "Animation Export" => ("animation_export", label),
        "Desk Persistence" => ("desk_persistence", label),
        "HRTF Personalization" => ("hrtf_personalization", label),
        "Manifold Transition Audio" => ("manifold_transition_audio", label),
        "Video View" => ("video_view", label),
        "Presentation Publish" => ("presentation_publish", label),
        "Super-Resolve Curation" => ("super_resolve", label),
        "CAD Curation" => ("cad_curation", label),

        "Semantic Graph Canvas" => ("ontology_graph_canvas", label),
        "Ontology Library" => ("ontology_library", label),
        "Vocabulary Mapper" => ("vocabulary_mapper", label),
        "Relation Builder" => ("relation_builder", label),
        "SHACL Shapes" => ("shacl_shapes", label),
        "N3 Editor" => ("n3_editor", label),
        "ShEx Editor" => ("shex_editor", label),
        "Ontology Compare" => ("ontology_compare", label),
        "Project Ontology Selector" => ("project_ontology_selector", label),

        "Device Manager" => ("device_manager", label),
        "Display Layout" => ("display_layout", label),
        "Workspace Sync" => ("workspace_sync", label),
        "Device Role Assigner" => ("device_role_assigner", label),
        "Remote Control" => ("remote_control", label),
        _ => return None,
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn specialist_families_have_real_container_routes() {
        for label in [
            "Project Sheet",
            "Health Overview",
            "Scene View",
            "Dataset Registry",
            "Ontology Library",
            "Device Manager",
            "Open Wallet",
        ] {
            assert!(container_for(label).is_some(), "missing route for {label}");
        }
    }
}
