#!/usr/bin/env python3
"""Generate QualiaDB's CGAL capability-coverage inventory.

This is a capability-reference workbench, not a C++ compiler or a transliteration
tool. It reads CGAL package metadata, documentation, tests, and examples (CGAL's
doc/ and test/ are CC0; its algorithm source is GPL/LGPL and is never copied),
then emits a deterministic Rust registry that serves as a completeness checklist
for the substantially different native implementation on the QualiaDB engine.
Native Rust implementation status is tracked by package-name markers in
PORTED_PACKAGES below.

Usage:
  python scripts/cgal-port/port_cgal.py --source /path/to/cgal

To obtain the pinned sparse specification checkout:
  python scripts/cgal-port/port_cgal.py --fetch
"""

from __future__ import annotations

import argparse
import dataclasses
import json
import pathlib
import re
import subprocess
import tempfile
from typing import Iterable

UPSTREAM_URL = "https://github.com/CGAL/cgal.git"
UPSTREAM_REF = "v6.2"
PORTED_PACKAGES = {"Convex_hull_2": "PortStatus::Foundation"}


@dataclasses.dataclass(frozen=True)
class Package:
    name: str
    module: str
    license: str
    description: str
    dependencies: tuple[str, ...]
    doc_files: int
    test_files: int
    example_files: int


def rust_module(name: str) -> str:
    value = re.sub(r"[^A-Za-z0-9]+", "_", name).strip("_").lower()
    if value and value[0].isdigit():
        value = f"pkg_{value}"
    return value


def read_text(path: pathlib.Path) -> str:
    try:
        return path.read_text(encoding="utf-8").strip()
    except (OSError, UnicodeDecodeError):
        return ""


def count_files(path: pathlib.Path) -> int:
    if not path.is_dir():
        return 0
    return sum(1 for candidate in path.rglob("*") if candidate.is_file())


def package_metadata_dirs(root: pathlib.Path) -> Iterable[pathlib.Path]:
    for package_info in sorted(root.glob("*/package_info")):
        for metadata in sorted(package_info.iterdir()):
            if metadata.is_dir() and (metadata / "description.txt").is_file():
                yield metadata


def scan(root: pathlib.Path) -> list[Package]:
    packages: list[Package] = []
    for metadata in package_metadata_dirs(root):
        package_root = metadata.parent.parent
        name = metadata.name
        dependencies = tuple(
            line.strip()
            for line in read_text(metadata / "dependencies").splitlines()
            if line.strip() and line.strip() != name
        )
        packages.append(
            Package(
                name=name,
                module=rust_module(name),
                license=read_text(metadata / "license.txt") or "unspecified",
                description=read_text(metadata / "description.txt"),
                dependencies=dependencies,
                doc_files=count_files(package_root / "doc"),
                test_files=count_files(package_root / "test"),
                example_files=count_files(package_root / "examples"),
            )
        )
    packages.sort(key=lambda package: package.name.casefold())
    return packages


def git_output(root: pathlib.Path, *args: str) -> str:
    completed = subprocess.run(
        ["git", "-C", str(root), *args],
        check=True,
        capture_output=True,
        text=True,
    )
    return completed.stdout.strip()


def fetch(destination: pathlib.Path) -> pathlib.Path:
    if not destination.exists():
        subprocess.run(
            [
                "git",
                "clone",
                "--depth",
                "1",
                "--filter=blob:none",
                "--no-checkout",
                "--branch",
                UPSTREAM_REF,
                UPSTREAM_URL,
                str(destination),
            ],
            check=True,
        )
        subprocess.run(
            ["git", "-C", str(destination), "sparse-checkout", "init", "--no-cone"],
            check=True,
        )
        sparse = destination / ".git" / "info" / "sparse-checkout"
        sparse.write_text(
            "\n".join(
                [
                    "/*",
                    "!/*/",
                    "/LICENSE.md",
                    "/Installation/LICENSE",
                    "/*/doc/",
                    "/*/test/",
                    "/*/examples/",
                    "/*/package_info/",
                    "/*/CMakeLists.txt",
                    "",
                ]
            ),
            encoding="utf-8",
        )
        subprocess.run(["git", "-C", str(destination), "checkout"], check=True)
    return destination


def rust_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=True)


def emit_rust(packages: list[Package], commit: str) -> str:
    lines = [
        "// @generated by scripts/cgal-port/port_cgal.py; do not hand-edit.",
        "",
        "#[derive(Debug, Clone, Copy, PartialEq, Eq)]",
        "pub enum PortStatus {",
        "    Planned,",
        "    Foundation,",
        "    Ported,",
        "}",
        "",
        "#[derive(Debug, Clone, Copy, PartialEq, Eq)]",
        "pub struct CgalPackageRecord {",
        "    pub upstream_name: &'static str,",
        "    pub rust_module: &'static str,",
        "    pub upstream_license: &'static str,",
        "    pub status: PortStatus,",
        "    pub doc_files: u32,",
        "    pub test_files: u32,",
        "}",
        "",
        f'pub const CGAL_UPSTREAM_REF: &str = "{UPSTREAM_REF}";',
        f'pub const CGAL_UPSTREAM_COMMIT: &str = "{commit}";',
        "pub const CGAL_PACKAGES: &[CgalPackageRecord] = &[",
    ]
    for package in packages:
        status = PORTED_PACKAGES.get(package.name, "PortStatus::Planned")
        lines.extend(
            [
                "    CgalPackageRecord {",
                f"        upstream_name: {rust_string(package.name)},",
                f"        rust_module: {rust_string(package.module)},",
                f"        upstream_license: {rust_string(package.license)},",
                f"        status: {status},",
                f"        doc_files: {package.doc_files},",
                f"        test_files: {package.test_files},",
                "    },",
            ]
        )
    lines.extend(["];", ""])
    return "\n".join(lines)


def emit_manifest(packages: list[Package], commit: str) -> str:
    data = {
        "schema": 1,
        "upstream": {
            "url": UPSTREAM_URL,
            "ref": UPSTREAM_REF,
            "commit": commit,
        },
        "package_count": len(packages),
        "packages": [
            {
                **dataclasses.asdict(package),
                "dependencies": list(package.dependencies),
                "status": (
                    "foundation" if package.name in PORTED_PACKAGES else "planned"
                ),
            }
            for package in packages
        ],
    }
    return json.dumps(data, indent=2, sort_keys=True) + "\n"


def main() -> int:
    script_dir = pathlib.Path(__file__).resolve().parent
    workspace = script_dir.parent.parent
    default_source = pathlib.Path(tempfile.gettempdir()) / "qualia-cgal-spec"
    parser = argparse.ArgumentParser()
    parser.add_argument("--source", type=pathlib.Path, default=default_source)
    parser.add_argument("--fetch", action="store_true")
    parser.add_argument(
        "--rust-output",
        type=pathlib.Path,
        default=workspace
        / "crates/qualia-core-db/src/specialized_libs/computational_geometry/generated/cgal_packages.rs",
    )
    parser.add_argument(
        "--manifest-output",
        type=pathlib.Path,
        default=workspace / "resources/cgal-port/cgal-6.2-packages.json",
    )
    args = parser.parse_args()

    source = fetch(args.source) if args.fetch else args.source
    if not (source / ".git").exists():
        parser.error(f"{source} is not a CGAL git checkout; pass --fetch or --source")

    packages = scan(source)
    if len(packages) < 100:
        parser.error(
            f"only found {len(packages)} packages; use the sparse patterns documented above"
        )
    commit = git_output(source, "rev-parse", "--short=12", "HEAD")

    args.rust_output.parent.mkdir(parents=True, exist_ok=True)
    args.manifest_output.parent.mkdir(parents=True, exist_ok=True)
    args.rust_output.write_text(emit_rust(packages, commit), encoding="utf-8")
    args.manifest_output.write_text(emit_manifest(packages, commit), encoding="utf-8")
    print(
        f"indexed {len(packages)} CGAL packages at {commit}; "
        f"wrote {args.rust_output} and {args.manifest_output}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

